### ISSUE TITLE
order_by(false, &["id"]) 不起作用

### ISSUE THREAD

**Issue by bernadit** [rbatis/rbatis#101]
let mut wrapper = ...;
wrapper.order_by(false, &["id"]);
... 

执行之后的结果，并不是按 id desc 来排序的

**Comment by zhuxiujia** [comment]
> let mut wrapper = ...;
> wrapper.order_by(false, &["id"]);
> ...
> 
> 执行之后的结果，并不是按 id desc 来排序的

提供下更多信息
