### ISSUE TITLE
rollback commit

### ISSUE THREAD

**Issue by chychy37** [rbatis/rbatis#102]
两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。

**Comment by zhuxiujia** [comment]
> 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。

是不是遇到行锁了

**Comment by chychy37** [comment]
> > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> 
> 是不是遇到行锁了

首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。

**Comment by chychy37** [comment]
> > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> 
> 是不是遇到行锁了

**Comment by zhuxiujia** [comment]
> > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > 
> > 
> > 是不是遇到行锁了
> 
> 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。

老铁，没毛病啊？

**Comment by chychy37** [comment]
> > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > 
> > > 
> > > 是不是遇到行锁了
> > 
> > 
> > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> 
> 老铁，没毛病啊？

就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。

**Comment by zhuxiujia** [comment]
> > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > 
> > > > 
> > > > 是不是遇到行锁了
> > > 
> > > 
> > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > 
> > 
> > 老铁，没毛病啊？
> 
> 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。

事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback

**Comment by chychy37** [comment]
> > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > 
> > > > > 
> > > > > 是不是遇到行锁了
> > > > 
> > > > 
> > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > 
> > > 
> > > 老铁，没毛病啊？
> > 
> > 
> > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> 
> 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback

也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？

**Comment by zhuxiujia** [comment]
> > > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > > 
> > > > > > 
> > > > > > 是不是遇到行锁了
> > > > > 
> > > > > 
> > > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > > 
> > > > 
> > > > 老铁，没毛病啊？
> > > 
> > > 
> > > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> > 
> > 
> > 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback
> 
> 也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？

我的意思是，全局tx manager是不会自动commit的（但是事务管理器会判断事务是否超时然后 执行回滚），你2个事务同时操作一条数据 应该是碰到了数据库行锁。除非其中一条事务取消或者提交。

**Comment by chychy37** [comment]
> > > > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > > > 
> > > > > > > 
> > > > > > > 是不是遇到行锁了
> > > > > > 
> > > > > > 
> > > > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > > > 
> > > > > 
> > > > > 老铁，没毛病啊？
> > > > 
> > > > 
> > > > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> > > 
> > > 
> > > 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback
> > 
> > 
> > 也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？
> 
> 我的意思是，全局tx manager是不会自动commit的（但是事务管理器会判断事务是否超时然后 执行回滚），你2个事务同时操作一条数据 应该是碰到了数据库行锁。除非其中一条事务取消或者提交。

我的意思是，其中一个commit，会一直卡住。

**Comment by chychy37** [comment]
> > > > > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是不是遇到行锁了
> > > > > > > 
> > > > > > > 
> > > > > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > > > > 
> > > > > > 
> > > > > > 老铁，没毛病啊？
> > > > > 
> > > > > 
> > > > > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> > > > 
> > > > 
> > > > 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback
> > > 
> > > 
> > > 也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？
> > 
> > 
> > 我的意思是，全局tx manager是不会自动commit的（但是事务管理器会判断事务是否超时然后 执行回滚），你2个事务同时操作一条数据 应该是碰到了数据库行锁。除非其中一条事务取消或者提交。
> 
> 我的意思是，其中一个commit，会一直卡住。

A 执行update语句。B执行update语句，B因为获取不到行锁也卡住。然后A commit也会一直卡住。

**Comment by zhuxiujia** [comment]
> > > > > > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 是不是遇到行锁了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > > > > > 
> > > > > > > 
> > > > > > > 老铁，没毛病啊？
> > > > > > 
> > > > > > 
> > > > > > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> > > > > 
> > > > > 
> > > > > 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback
> > > > 
> > > > 
> > > > 也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？
> > > 
> > > 
> > > 我的意思是，全局tx manager是不会自动commit的（但是事务管理器会判断事务是否超时然后 执行回滚），你2个事务同时操作一条数据 应该是碰到了数据库行锁。除非其中一条事务取消或者提交。
> > 
> > 
> > 我的意思是，其中一个commit，会一直卡住。
> 
> A 执行update语句。B执行update语句，B因为获取不到行锁也卡住。然后A commit也会一直卡住。

这个是mysql自身的问题啊，官方文档明确表示事务不支持嵌套。嵌套事务一遇到行锁会造成死锁问题，直到ORM框架判断到超时回滚了事务

**Comment by chychy37** [comment]
> > > > > > > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 是不是遇到行锁了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 老铁，没毛病啊？
> > > > > > > 
> > > > > > > 
> > > > > > > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> > > > > > 
> > > > > > 
> > > > > > 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback
> > > > > 
> > > > > 
> > > > > 也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？
> > > > 
> > > > 
> > > > 我的意思是，全局tx manager是不会自动commit的（但是事务管理器会判断事务是否超时然后 执行回滚），你2个事务同时操作一条数据 应该是碰到了数据库行锁。除非其中一条事务取消或者提交。
> > > 
> > > 
> > > 我的意思是，其中一个commit，会一直卡住。
> > 
> > 
> > A 执行update语句。B执行update语句，B因为获取不到行锁也卡住。然后A commit也会一直卡住。
> 
> 这个是mysql自身的问题啊，官方文档明确表示事务不支持嵌套。
> 
> * 一个事务执行的任何过程中都可以获得锁，但是只有事务提交或回滚的时候才释放这些锁
>   嵌套事务一遇到行锁会造成死锁问题，直到ORM框架判断到超时回滚了事务

不是事务嵌套，就是全局的db对象尝试执行sql语句时，会获取tx_manager的写锁，获得写锁后在执行对应的sql，然后sql遇到的行锁，导致tx_manager的写锁一直不能释放。导致之后任何尝试获取tx_manager的锁的操作都会堵塞住，比如查询，更新，commit等。

**Comment by zhuxiujia** [comment]
> > > > > > > > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 是不是遇到行锁了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 老铁，没毛病啊？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> > > > > > > 
> > > > > > > 
> > > > > > > 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback
> > > > > > 
> > > > > > 
> > > > > > 也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？
> > > > > 
> > > > > 
> > > > > 我的意思是，全局tx manager是不会自动commit的（但是事务管理器会判断事务是否超时然后 执行回滚），你2个事务同时操作一条数据 应该是碰到了数据库行锁。除非其中一条事务取消或者提交。
> > > > 
> > > > 
> > > > 我的意思是，其中一个commit，会一直卡住。
> > > 
> > > 
> > > A 执行update语句。B执行update语句，B因为获取不到行锁也卡住。然后A commit也会一直卡住。
> > 
> > 
> > 这个是mysql自身的问题啊，官方文档明确表示事务不支持嵌套。
> > 
> > * 一个事务执行的任何过程中都可以获得锁，但是只有事务提交或回滚的时候才释放这些锁
> >   嵌套事务一遇到行锁会造成死锁问题，直到ORM框架判断到超时回滚了事务
> 
> 不是事务嵌套，就是全局的db对象尝试执行sql语句时，会获取tx_manager的写锁，获得写锁后在执行对应的sql，然后sql遇到的行锁，导致tx_manager的写锁一直不能释放。导致之后任何尝试获取tx_manager的锁的操作都会堵塞住，比如查询，更新，commit等。
> 如果使用的是单例的db对象，就不会出现这个问题。
> 具体就是这个语句:
> let conn = self.tx_manager.get_mut(context_id).await;

了解，能否试一下我最新的提交（换用DashMap防止整个Map因为读写锁 锁死的情况），看看这个问题是否还存在？

**Comment by chychy37** [comment]
> > > > > > > > > > > > > 两个事务同时修改一行数据时，第一个commit没有及时执行，必须等到另一个lock 超时后，才会commit。
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 是不是遇到行锁了
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 首先是起了一个服务，两个请求同时进来，用的全局的db对象，管理context，两个请求同时修改一行数据，有行锁，先获得行锁的请求，没有及时commit，然后第二个请求尝试获取行锁，卡住。然后第一个请求也不commit。必须等到mysql断掉其中一个，另一个才会执行。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 老铁，没毛病啊？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 就是不会自动commit，我看了下源码。第二个请求，会先获取tx_manager的写锁，然后尝试获取mysql的行锁，一直等待，导致tx_manager的写锁不能归还。然后第一个请求的commit，因为获取tx_manager的写锁，一直等待。直到mysql自动断掉一个连接。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 事务管理器有设置超时时长，超过这个事件，事务管理器会主动rollback
> > > > > > > 
> > > > > > > 
> > > > > > > 也就是有这个问题吗？那其实在mysql上执行是不会有问题的，也就是用了全局的tx_manager出现了死锁问题吗？
> > > > > > 
> > > > > > 
> > > > > > 我的意思是，全局tx manager是不会自动commit的（但是事务管理器会判断事务是否超时然后 执行回滚），你2个事务同时操作一条数据 应该是碰到了数据库行锁。除非其中一条事务取消或者提交。
> > > > > 
> > > > > 
> > > > > 我的意思是，其中一个commit，会一直卡住。
> > > > 
> > > > 
> > > > A 执行update语句。B执行update语句，B因为获取不到行锁也卡住。然后A commit也会一直卡住。
> > > 
> > > 
> > > 这个是mysql自身的问题啊，官方文档明确表示事务不支持嵌套。
> > > 
> > > * 一个事务执行的任何过程中都可以获得锁，但是只有事务提交或回滚的时候才释放这些锁
> > >   嵌套事务一遇到行锁会造成死锁问题，直到ORM框架判断到超时回滚了事务
> > 
> > 
> > 不是事务嵌套，就是全局的db对象尝试执行sql语句时，会获取tx_manager的写锁，获得写锁后在执行对应的sql，然后sql遇到的行锁，导致tx_manager的写锁一直不能释放。导致之后任何尝试获取tx_manager的锁的操作都会堵塞住，比如查询，更新，commit等。
> > 如果使用的是单例的db对象，就不会出现这个问题。
> > 具体就是这个语句:
> > let conn = self.tx_manager.get_mut(context_id).await;
> 
> 了解，能否试一下我最新的提交（换用DashMap防止整个Map因为读写锁 锁死的情况），看看这个问题是否还存在？

应该是解决了😄

**Comment by chychy37** [comment]
1.8.88 问题复现了：
事务一：在执行sql语句时，获取tx的读锁后，遇到sql的行锁（被事务二占有），卡住。
事务二：在commit tx 时，会尝试获取tx的写锁，却因为事务一无法释放 tx 读锁，卡住。

**Comment by zhuxiujia** [comment]
> 1.8.88 问题复现了：
> 事务一：在执行sql语句时，获取tx的读锁后，遇到sql的行锁（被事务二占有），卡住。
> 事务二：在commit tx 时，会尝试获取tx的写锁，却因为事务一无法释放 tx 读锁，卡住。

确实是一个问题，新版本，rbatis会放弃使用map存储事务的方式，改为直接传递事务结构体对象。这样在性能上来说会提高很多

**Comment by zhuxiujia** [comment]
> 1.8.88 问题复现了：
> 事务一：在执行sql语句时，获取tx的读锁后，遇到sql的行锁（被事务二占有），卡住。
> 事务二：在commit tx 时，会尝试获取tx的写锁，却因为事务一无法释放 tx 读锁，卡住。

v2.0* 版本开始，移除了事务管理器模块，改用直接传递事务对象的方式。

**Comment by chychy37** [comment]
v2.0.4 使用`普通事务`和`事务守卫`都没有开启`事务`。打印的sql语句中，没有begin，commit，rollback。查询mysql `INNODB_TRX`也没有找到相关事务

**Comment by zhuxiujia** [comment]
> v2.0.4 使用`普通事务`和`事务守卫`都没有开启`事务`。打印的sql语句中，没有begin，commit，rollback。查询mysql `INNODB_TRX`也没有找到相关事务

更新到v2.0.5以上版本再试试

**Comment by chychy37** [comment]
> > v2.0.4 使用`普通事务`和`事务守卫`都没有开启`事务`。打印的sql语句中，没有begin，commit，rollback。查询mysql `INNODB_TRX`也没有找到相关事务
> 
> 更新到v2.0.5以上版本再试试

查看数据库事务，是存在了，但日志输出可能有点不全，没有了之前的begin，commit，rollback 输出，还有不同事务之间没有之前的tx_id来区分查看
事务日志格式：
```
2021-06-16T10:25:06.823387+08:00 - [rbatis] [] Fetch  ==> select * from user  where id = ?
                                                                [rbatis] [] Args   ==> [1]
2021-06-16T10:25:06.958862+08:00 - [rbatis] [] ReturnRows <== 1
```
