### ISSUE TITLE
1.8.85 Compile failure

### ISSUE THREAD

**Issue by bit-ranger** [rbatis/rbatis#104]
Compiling rbatis v1.8.85
     Running `rustc --crate-name rbatis --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-1.8.85/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="all-database"' --cfg 'feature="default"' --cfg 'feature="default_mode"' --cfg 'feature="rbatis-core"' --cfg 'feature="rbatis-macro-driver"' -C metadata=1f3c0149d7a91334 -C extra-filename=-1f3c0149d7a91334 --out-dir /data/target/debug/deps -L dependency=/data/target/debug/deps --extern async_trait=/data/target/debug/deps/libasync_trait-161180e38f64f808.so --extern chrono=/data/target/debug/deps/libchrono-f731080f23cacbe0.rmeta --extern dashmap=/data/target/debug/deps/libdashmap-76fb0d103d358413.rmeta --extern futures_core=/data/target/debug/deps/libfutures_core-bcf11669340597f2.rmeta --extern hex=/data/target/debug/deps/libhex-fd42229fd072735e.rmeta --extern lazy_static=/data/target/debug/deps/liblazy_static-8cf258078a2a9fea.rmeta --extern log=/data/target/debug/deps/liblog-44a774fb831c14f0.rmeta --extern once_cell=/data/target/debug/deps/libonce_cell-441ca5be97291913.rmeta --extern py_sql=/data/target/debug/deps/libpy_sql-ddb3be8dc295775e.rmeta --extern rand=/data/target/debug/deps/librand-fe2ef8b855c43d78.rmeta --extern rbatis_core=/data/target/debug/deps/librbatis_core-22af909e11aa3d21.rmeta --extern rbatis_macro_driver=/data/target/debug/deps/librbatis_macro_driver-da318fac58ab7e6a.so --extern rexpr=/data/target/debug/deps/librexpr-38903f675becc290.rmeta --extern serde=/data/target/debug/deps/libserde-3bde9589f11578d0.rmeta --extern serde_json=/data/target/debug/deps/libserde_json-7c294282b4fca0c6.rmeta --extern uuid=/data/target/debug/deps/libuuid-d1d5e491baf1220e.rmeta --cap-lints allow -L native=/data/target/debug/build/libsqlite3-sys-ded5c7d94cb1b32b/out -L native=/data/target/debug/build/ring-91f15c1821785a6c/out`
error[E0433]: failed to resolve: could not find `sync` in `core`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-1.8.85/src/rbatis.rs:15:18
   |
15 | use crate::core::sync::sync_map::SyncMap;
   |                  ^^^^ could not find `sync` in `core`

**Comment by bit-ranger** [comment]
the temporary solution is to fix rbatis-core version

rbatis = { version = "=1.8.85",  optional = true }
rbatis-core = {version = "=1.8.85", optional = true }

**Comment by zhuxiujia** [comment]
rbatis-core =  1.8.82

**Comment by bit-ranger** [comment]
> rbatis-core = 1.8.82

yes, it's rbatis-core = 1.8.82

**Comment by zhuxiujia** [comment]
> > rbatis-core = 1.8.82
> 
> yes, it's rbatis-core = 1.8.82

the last version fix this
