### ISSUE TITLE
not found methed “list” and “list_by_ids”

### ISSUE THREAD

**Issue by zrz4066** [rbatis/rbatis#105]
error[E0599]: no method named `list` found for struct `Rbatis` in the current scope
  --> src\main.rs:94:37
   |
94 |   let result: Vec<BizActivity> = rb.list("").await.unwrap();
   |                                     ^^^^ method not found in `Rbatis`

error[E0599]: no method named `list_by_ids` found for struct `Rbatis` in the current scope
  --> src\main.rs:98:37
   |
98 |   let result: Vec<BizActivity> = rb.list_by_ids("", &["1".to_string()]).await.unwrap();
   |                                     ^^^^^^^^^^^ method not found in `Rbatis`

error[E0061]: this function takes 4 arguments but 3 arguments were supplied
   --> src\main.rs:118:6
    |
118 |   rb.update_by_wrapper("", &mut activity, &w).await;
    |      ^^^^^^^^^^^^^^^^^ --  -------------  -- supplied 3 arguments
    |      |
    |      expected 4 arguments
    |

**Comment by zhuxiujia** [comment]
use 'fetch_list****'  Replace the  before method ‘list****’
