### ISSUE TITLE
Postgresql 的参数 $0 不存在

### ISSUE THREAD

**Issue by ferren** [rbatis/rbatis#107]
[rbatis] [] Fetch  ==> select id,company_id,name,ip,state,create_date from car_box_emulator  where name = $0
[rbatis] [] Args   ==> ["IGO_TEST"]
[rbatis] [] ReturnErr  <== error returned from database: there is no parameter $0

上面的$0 改为 $1，就能正常完成查询；查了一下相关的资料，Postgresql的这个参数，应该是从$1开始编号的，$0是一个特殊参数，不能用在这里。

**Comment by zhuxiujia** [comment]
> [rbatis] [] Fetch ==> select * from car_box_emulator where name = $0
> [rbatis] [] Args ==> ["IGO_TEST"]
> [rbatis] [] ReturnErr <== error returned from database: there is no parameter $0
> 
> 上面的$0 改为 $1，就能正常完成查询；查了一下相关的资料，Postgresql的这个参数，应该是从$1开始编号的，$0是一个特殊参数，不能用在这里。

你是用wrapper试出来的吗？

**Comment by ferren** [comment]
> > [rbatis] [] Fetch ==> select * from car_box_emulator where name = $0
> > [rbatis] [] Args ==> ["IGO_TEST"]
> > [rbatis] [] ReturnErr <== error returned from database: there is no parameter $0
> > 上面的$0 改为 $1，就能正常完成查询；查了一下相关的资料，Postgresql的这个参数，应该是从$1开始编号的，$0是一个特殊参数，不能用在这里。
> 
> 你是用wrapper试出来的吗？
> 贴一下代码

let w = RB.new_wrapper().eq("name", "IGO_TEST");
let r: Result<Option<CarBoxEmulator>, rbatis::Error> = RB.fetch_by_wrapper(&w).await;

**Comment by ferren** [comment]
[rbatis] [] Exec   ==> update car_box_emulator set  id = $0, company_id = $1, name = $2, ip = $3, state = $4, create_date = $5  where name = $6
[rbatis] [] Args   ==> [1,1,"IGO_TEST","210.152.243.200","0","2021-06-16T08:07:13.333921","IGO_TEST"]
[rbatis] [] ReturnErr  <== error returned from database: there is no parameter $0

更新记录时，也存在一样的问题。
RB.update_by_wrapper::<CarBoxEmulator>(&mut emulator, &w, false)
        .await
        .unwrap();

**Comment by ferren** [comment]
for index in 0..args.len() {
                    let mut data = String::new();
                    driver_type.stmt_convert(index, &mut data);
         ......



貌似是这里的问题吧，看到index统一都是从0开始的。

**Comment by zhuxiujia** [comment]
> pub fn eq(mut self, column: &str, obj: T) -> Self
> where
> T: Serialize,
> {
> self = self.and();
> let mut convert_column = String::new();
> self.driver_type.stmt_convert(self.args.len(),&mut convert_column);
> self.do_format_column(column, &mut convert_column);
> push_sql!(self.sql,column," = ",convert_column.as_str(),);
> self.args.push(json!(obj));
> self
> }
> 
> self.args.len() 在第一次调用eq时，应该就是0吧！在这里直接 +1 ?

你试试1.0.7版本
