### ISSUE TITLE
是否有计划支持mssql呢?

### ISSUE THREAD

**Issue by guoyucode** [rbatis/rbatis#11]
近期是否有计划支持mssql呢? 我看了一下最新版的sqlx已经支持msql了

**Comment by zhuxiujia** [comment]
我目前没有计划，不排除其他人有计划实现的话， 欢迎提交合并代码

**Comment by zhuxiujia** [comment]
> 近期是否有计划支持mssql呢? 我看了一下最新版的sqlx已经支持msql了

新版Rbatis底层已更换为sqlx，因此已支持mssql大部分类型解析（有小部分等待sqlx补完）
