### ISSUE TITLE
支持保存时忽略字段配置

### ISSUE THREAD

**Issue by gudaoxuri** [rbatis/rbatis#110]
创建/更新时间字段一般会使用数据库自身的机制生成时间戳（E.g. `update_time timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP`）

目前rbatis不支持保存时忽略这些字段，我尝试添加 `#[serde(skip_serializing)]` ，但下面代码中保存时会依赖 `table_columns` 。

https://github.com/rbatis/rbatis/blob/0b80273d1bcbc103e6b77821bd0b611a7a0ed688/src/crud.rs#L100-L135

希望可以添加类似 `#[ignore(save/update)]` 字段级保存、更新忽略宏。

**Comment by zhuxiujia** [comment]
> 创建/更新时间字段一般会使用数据库自身的机制生成时间戳（E.g. `update_time timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP`）
> 
> 目前rbatis不支持保存时忽略这些字段，我尝试添加 `#[serde(skip_serializing)]` ，但下面代码中保存时会依赖 `table_columns` 。
> 
> https://github.com/rbatis/rbatis/blob/0b80273d1bcbc103e6b77821bd0b611a7a0ed688/src/crud.rs#L100-L135
> 
> 希望可以添加类似 `#[ignore(save/update)]` 字段级保存、更新忽略宏。

目前依靠table_columns 判断哪些字段是否有用。可以用宏定义有哪些columns是有用的。
例如
```rust
#[crud_table(table_columns:"id,name,version,delete_flag")]
pub struct Test{
  id:String
}
```

**Comment by gudaoxuri** [comment]
> > 创建/更新时间字段一般会使用数据库自身的机制生成时间戳（E.g. `update_time timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP`）
> > 目前rbatis不支持保存时忽略这些字段，我尝试添加 `#[serde(skip_serializing)]` ，但下面代码中保存时会依赖 `table_columns` 。
> > https://github.com/rbatis/rbatis/blob/0b80273d1bcbc103e6b77821bd0b611a7a0ed688/src/crud.rs#L100-L135
> > 
> > 希望可以添加类似 `#[ignore(save/update)]` 字段级保存、更新忽略宏。
> 
> 目前依靠table_columns 判断哪些字段是否有用。可以用宏定义有哪些columns是有用的。
> 例如
> 
> ```rust
> #[crud_table(table_columns:"id,name")]
> pub struct Test{
>   id:String,
>   name:String,
>   age:i32
> }
> ```
> 
> 这样定义的话，只插入id和name

这会导致被过滤的字段无法查询到，从场景看我们需要插入时由数据库机制自动生成（比如创建、更新时间），然后查询时可以获取到。

**Comment by sungaoyong** [comment]
应该可以通过实现attributes来忽略，我学习https://github.com/Keats/validator这个项目看到这个实现很不错，是不是还可已集成这个实现存储前的验证。譬如定义成如下
#[derive(crud_table,attributes(crud)]
pub struct Test{
  id:String,
  name:String,
 #[crud(UpdateIgnore)]
  age:i32
}

**Comment by zhuxiujia** [comment]
> 应该可以通过实现attributes来忽略，我学习
> https://github.com/Keats/validator
> 这个项目看到这个实现很不错，是不是还可已集成这个实现存储前的验证。譬如定义成如下
> #[derive(crud_table,attributes(crud)]
> pub struct Test{
> id:String,
> name:String,
> #[crud(UpdateIgnore)]
> age:i32
> }
> 
> 这样在更新操作时就只更新id，name

新版本现已通过Skip参数获得支撑
