### ISSUE TITLE
[rbatis] make_page_sql() sql must contains 'select ' And ' from '

### ISSUE THREAD

**Issue by bit-ranger** [rbatis/rbatis#113]
fn: 
rbatis::rbatis::fetch_page

sql:
SELECT * FROM test WHERE code  = '123'

version: 
1.8.87

**Comment by zhuxiujia** [comment]
> fn:
> rbatis::rbatis::fetch_page
> 
> sql:
> SELECT * FROM test WHERE code = '123'
> 
> version:
> 1.8.87

To support uppercase SQL, RBatis is required to enable the uppercase SQL keyword
```rust
rbatis = {  features = [,"upper_case_sql_keyword"] }
```

**Comment by bin-liu** [comment]
@zhuxiujia 如果框架内部不做兼容。这里建议在错误信息里面加一个这个提示。提示增加feature中配置 upper_case_sql_keyword。
仓库的Readme还是中文文档，都没有关于uppercase SQL的描述，也建议一起补充上。
我也遇到了这个问题，跟源码调试才发现问题，希望能更直接些。
