### ISSUE TITLE
使用普通事物保存数据，提交之前引发错误，数据仍然被保存到数据库

### ISSUE THREAD

**Issue by zemelLeong** [rbatis/rbatis#116]
```rust

#[post("/", format = "json", data = "<document>")]
pub async fn create_document(
    conn: &State<Rbatis>,
    document: Json<DocumentDto>,
) -> CreatedResult<Created<Json<DocumentDto>>> {
    let document_value: Document = document.clone().into();
    let tx = conn.acquire_begin().await.unwrap();

    conn.save(&document_value).await.unwrap();
    assert_eq!("1", "2");

    tx.commit().await.unwrap();

    Ok(Created::new("/").body(document))
}

```

![image](https://user-images.githubusercontent.com/26835087/125222050-d994ac00-e2fb-11eb-9b66-0acfe8c32f57.png)

**Comment by zemelLeong** [comment]
还有数据库设置了默认值【如截图中的 object_version_number】，执行插入操作之后并没有生成，日志里是为其设置了null，可以怎样避免呢

**Comment by zemelLeong** [comment]
额，事物那个好像是我弄错了

**Comment by zhuxiujia** [comment]
> ```rust
> #[post("/", format = "json", data = "<document>")]
> pub async fn create_document(
>     conn: &State<Rbatis>,
>     document: Json<DocumentDto>,
> ) -> CreatedResult<Created<Json<DocumentDto>>> {
>     let document_value: Document = document.clone().into();
>     let tx = conn.acquire_begin().await.unwrap();
> 
>     conn.save(&document_value).await.unwrap();
>     assert_eq!("1", "2");
> 
>     tx.commit().await.unwrap();
> 
>     Ok(Created::new("/").body(document))
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/26835087/125222050-d994ac00-e2fb-11eb-9b66-0acfe8c32f57.png)


```rust
 let tx = conn.acquire_begin().await.unwrap();

    conn.save(&document_value).await.unwrap();
    assert_eq!("1", "2");

    tx.commit().await.unwrap();

```
改成
```rust
 let tx = conn.acquire_begin().await.unwrap();
    tx.save(&document_value).await.unwrap();
    assert_eq!("1", "2");
    tx.commit().await.unwrap();

```

**Comment by zhuxiujia** [comment]
> 还有数据库设置了默认值【如截图中的 object_version_number】，执行插入操作之后并没有生成，日志里是为其设置了null，可以怎样避免呢

数据库是postgres？

**Comment by zemelLeong** [comment]
> > 还有数据库设置了默认值【如截图中的 object_version_number】，执行插入操作之后并没有生成，日志里是为其设置了null，可以怎样避免呢
> 
> 数据库是postgres？

是MySQL

**Comment by zhuxiujia** [comment]
试试新版本，插入时选择跳过默认值字段column
