### ISSUE TITLE
在 web 框架 Rocket 中使用 rbatis 事务守卫报错

### ISSUE THREAD

**Issue by zemelLeong** [rbatis/rbatis#117]
如题，我想使用事务守卫需要做什么操作吗？

```
future cannot be sent between threads safely
the trait `std::marker::Send` is not implemented for `dyn FnMut(RBatisTxExecutor<'_>)`
required for the cast to the object type `dyn std::future::Future<Output = Outcome<rocket::Response<'__r>, Status, rocket::Data<'__r>>> + std::marker::Send`
```

![image](https://user-images.githubusercontent.com/26835087/125228095-bd4a3c80-e306-11eb-920b-f31d52e46d54.png)

**Comment by zhuxiujia** [comment]
使用defer_async()

**Comment by zemelLeong** [comment]
我参考 defer_async 的示例些改了，但是仍然报那个错误

![image](https://user-images.githubusercontent.com/26835087/125235776-921b1980-e315-11eb-89b5-78569573736a.png)

**Comment by zhuxiujia** [comment]
试一下更新到最新版本
