### ISSUE TITLE
事务守卫的正确使用方式是怎样的

### ISSUE THREAD

**Issue by zemelLeong** [rbatis/rbatis#119]
请问下事务守卫使用的正确方式是怎样的？根据文档我理解如果“忘记提交”应该在`defere`里执行`rollback`操作，如果没忘记提交该如何提交呢？我自己测试，图中被标记的写法似乎能更好地运作
```rust
    conn.acquire_begin().await.unwrap().defer_async(|mut tx| async {
        tx.save(&document_value, &[]).await.unwrap();
        // assert_eq!("1", "2");
        tx.save(&document_value, &[Skip::Column("create_time")]).await.unwrap();
        tx.commit().await.unwrap();
    });
```

![image](https://user-images.githubusercontent.com/26835087/125485985-766b4cfb-f58d-4547-9eec-7eeb580c3746.png)

**Comment by zhuxiujia** [comment]
> 请问下事务守卫使用的正确方式是怎样的？根据文档我理解如果“忘记提交”应该在`defere`里执行`rollback`操作，如果没忘记提交该如何提交呢？我自己测试，图中被标记的写法似乎能更好地运作
> 
> ```rust
>     conn.acquire_begin().await.unwrap().defer_async(|mut tx| async {
>         tx.save(&document_value, &[]).await.unwrap();
>         // assert_eq!("1", "2");
>         tx.save(&document_value, &[Skip::Column("create_time")]).await.unwrap();
>         tx.commit().await.unwrap();
>     });
> ```
> 
> ![image](https://user-images.githubusercontent.com/26835087/125485985-766b4cfb-f58d-4547-9eec-7eeb580c3746.png)

使用cargo update命令 更新到rbatis最新版本
可以这样判断   如果没忘记提交该如何提交。
```rust
    pub async fn forget_commit(rb: &Rbatis) -> rbatis::core::Result<()> {
        //let mut is_success = Mutex::new(Cell::new(false));
        // tx will be commit.when func end
        let mut tx = rb.acquire_begin().await?.defer_async(|tx| async {
            if !tx.is_done() {
                tx.rollback().await;
                println!("tx rollback success!");
            } else {
                println!("do success,don't need rollback!");
            }
        });
        let v = tx
            .exec("update biz_activity set name = '6' where id = 1;", &vec![])
            .await;
        return Ok(());
    }
```

当然，你也可以 使用channel 通道传送数据，或者使用锁 Mutex::new(Cell::new(Some Data));

**Comment by zemelLeong** [comment]
我测试了下，如果守卫不执行`commit`操作，在`callback`就会执行`rollback`。
![image](https://user-images.githubusercontent.com/26835087/125886339-8c1c7eff-fbb4-442d-8e40-57fae071745c.png)

![image](https://user-images.githubusercontent.com/26835087/125886562-97f9435d-a593-416b-8cca-3428b78ae3bf.png)
