### ISSUE TITLE
`serverTimezone=Asia/Shanghai` in mysql url not work

### ISSUE THREAD

**Issue by nintha** [rbatis/rbatis#12]
I connect mysql with url `mysql://root:123456@localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8`, then execute sql `select NOW()`, however the result is a time with UTC.

Does rbatis support the url option `serverTimezone=Asia/Shanghai` ?  Maybe I miss something about other way to set connection session timezone, how can I find the document about it?

Thank you.

**Comment by zhuxiujia** [comment]
> I connect mysql with url `mysql://root:123456@localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8`, then execute sql `select NOW()`, however the result is a time with UTC.
> 
> Does rbatis support the url option `serverTimezone=Asia/Shanghai` ? Maybe I miss something about other way to set connection session timezone, how can I find the document about it?
> 
> Thank you.

Does your environment use local time instead of UTC time。
I'm using navcat run 'select now()' time is local

**Comment by nintha** [comment]
I run the mysql in docker container.
The container environment
- TZ: Asia/Shanghai

my rust code
```rust
let py = r#"SELECT now()"#;
let data: serde_json::Value = rbaits.py_fetch("", py, &Value::Null).await.unwrap();
log::info!("SELECT now() > {}", data);
let py = r#"SHOW VARIABLES LIKE '%time_zone%'"#;
let data: serde_json::Value = rbaits.py_fetch("", py, &Value::Null).await.unwrap();
log::info!("SHOW VARIABLES LIKE '%time_zone%' > {}", data);
```
output log
```
2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Query ==> SELECT now()
2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Args  ==> []
2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] ReturnRows <== 1
2020-09-06 15:22:19 INFO [bbs_rs::user::handler] SELECT now() > [{"now()":"2020-09-06T07:22:18"}]
2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Query ==> SHOW VARIABLES LIKE '%time_zone%'
2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Args  ==> []
2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] ReturnRows <== 2
2020-09-06 15:22:19 INFO [bbs_rs::user::handler] SHOW VARIABLES LIKE '%time_zone%' > [{"Value":"CST","Variable_name":"system_time_zone"},{"Value":"+00:00","Variable_name":"time_zone"}]
```
The VARIABLES  `time_zone` is `+00:00`. 

I try to look up rbatis source code, and find it https://github.com/rbatis/rbatis/blob/d43b6889827f57775d44cca38e3a8a01e8e0e339/rbatis-core/src/mysql/connection.rs#L316
```
impl MySqlConnection {
    pub(super) async fn new(url: std::result::Result<Url, url::ParseError>) -> crate::Result<Self> {
        let url = url?;
        let mut stream = MySqlStream::new(&url).await?;

        establish(&mut stream, &url).await?;

        let mut self_ = Self {
            stream,
            current_row_values: Vec::with_capacity(10),
            is_ready: true,
            cache_statement: HashMap::new(),
        };

       // ..ommit comment

        self_.execute(r#"
SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE'));
SET time_zone = '+00:00';
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
        "#).await?;
```
It hardcodes the connection session timezone with `+00:00`. Does other way to set the `time_zone`?

**Comment by zhuxiujia** [comment]
> I run the mysql in docker container.
> The container environment
> 
> * TZ: Asia/Shanghai
> 
> my rust code
> 
> ```rust
> let py = r#"SELECT now()"#;
> let data: serde_json::Value = rbaits.py_fetch("", py, &Value::Null).await.unwrap();
> log::info!("SELECT now() > {}", data);
> let py = r#"SHOW VARIABLES LIKE '%time_zone%'"#;
> let data: serde_json::Value = rbaits.py_fetch("", py, &Value::Null).await.unwrap();
> log::info!("SHOW VARIABLES LIKE '%time_zone%' > {}", data);
> ```
> 
> output log
> 
> ```
> 2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Query ==> SELECT now()
> 2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Args  ==> []
> 2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] ReturnRows <== 1
> 2020-09-06 15:22:19 INFO [bbs_rs::user::handler] SELECT now() > [{"now()":"2020-09-06T07:22:18"}]
> 2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Query ==> SHOW VARIABLES LIKE '%time_zone%'
> 2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] Args  ==> []
> 2020-09-06 15:22:19 INFO [rbatis::rbatis] [rbatis] [] ReturnRows <== 2
> 2020-09-06 15:22:19 INFO [bbs_rs::user::handler] SHOW VARIABLES LIKE '%time_zone%' > [{"Value":"CST","Variable_name":"system_time_zone"},{"Value":"+00:00","Variable_name":"time_zone"}]
> ```
> 
> The VARIABLES `time_zone` is `+00:00`.
> 
> I try to look up rbatis source code, and find it
> 
> https://github.com/rbatis/rbatis/blob/d43b6889827f57775d44cca38e3a8a01e8e0e339/rbatis-core/src/mysql/connection.rs#L316
> 
> ```
> impl MySqlConnection {
>     pub(super) async fn new(url: std::result::Result<Url, url::ParseError>) -> crate::Result<Self> {
>         let url = url?;
>         let mut stream = MySqlStream::new(&url).await?;
> 
>         establish(&mut stream, &url).await?;
> 
>         let mut self_ = Self {
>             stream,
>             current_row_values: Vec::with_capacity(10),
>             is_ready: true,
>             cache_statement: HashMap::new(),
>         };
> 
>        // ..ommit comment
> 
>         self_.execute(r#"
> SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE'));
> SET time_zone = '+00:00';
> SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
>         "#).await?;
> ```
> 
> It hardcodes the connection session timezone with `+00:00`. Does other way to set the `time_zone`?

your docker config not true, you can try docker command fix  timezone when start mysql server.  for example:
```rust
docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 --name mysql -e TZ=Asia/Shanghai mysql:5.7
```

but, in rbatis use driver link change timezone not support for now.rbatis  will be use default config

**Comment by nintha** [comment]
My mysql `system_time_zone` is `CST`, container timezone is +08:00, and other mysql client can query right time with specific timezone.

Thanks for your reply, and does Rbatis has some plan to support driver link  timezone option?

**Comment by zhuxiujia** [comment]
> My mysql `system_time_zone` is `CST`, container timezone is +08:00, and other mysql client can query right time with specific timezone.
> 
> Thanks for your reply, and does Rbatis has some plan to support driver link timezone option?


now, there is no impact on query data and save data,
 but select now() return data not  right
 it will be supported in the future.

**Comment by zhuxiujia** [comment]
> My mysql `system_time_zone` is `CST`, container timezone is +08:00, and other mysql client can query right time with specific timezone.
> 
> Thanks for your reply, and does Rbatis has some plan to support driver link timezone option?


in rbatis:  version:  1.5.1
i remove the  hardcodes   for 'SET time_zone = '+00:00';'

so , if you  use this command create mysql server:
```rust 
docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 --name mysql -e TZ=Asia/Shanghai mysql:5.7
```
```rust
let data: serde_json::Value = rbaits.py_fetch("", py, &Value::Null).await.unwrap();
```
rbatis will  be return  right  data.

**Comment by nintha** [comment]
Thanks, I update Rbaits to the version 1.5.1 in dependencies. It works for me.
