### ISSUE TITLE
logic delete plugin not work

### ISSUE THREAD

**Issue by SummerVibes** [rbatis/rbatis#120]
I have enable logic delete plugin
```
lazy_static! {
    pub static ref RB: Rbatis = {
        let mut db = Rbatis::new();
        db.logic_plugin = Some(Box::new(RbatisLogicDeletePlugin::new_opt("deleted", 1, 0)));
        db
    };
}
```
The remove method worked fine.
![image](https://user-images.githubusercontent.com/32605477/125723500-00839949-44a3-4747-a62e-eb0de6245348.png)
But I got the deleted value when I fetch data.
![截屏2021-07-15 上午11 15 54](https://user-images.githubusercontent.com/32605477/125723669-a5fc79e2-d22a-452c-8447-9b09087128d9.jpg)

**Comment by zhuxiujia** [comment]
> I have enable logic delete plugin
> 
> ```
> lazy_static! {
>     pub static ref RB: Rbatis = {
>         let mut db = Rbatis::new();
>         db.logic_plugin = Some(Box::new(RbatisLogicDeletePlugin::new_opt("deleted", 1, 0)));
>         db
>     };
> }
> ```
> 
> The remove method worked fine.
> ![image](https://user-images.githubusercontent.com/32605477/125723500-00839949-44a3-4747-a62e-eb0de6245348.png)
> But I got the deleted value when I fetch data.
> ![截屏2021-07-15 上午11 15 54](https://user-images.githubusercontent.com/32605477/125723669-a5fc79e2-d22a-452c-8447-9b09087128d9.jpg)



Starting from RBatis 2.0, the logical delete plug-in is only effective in the delete method, other methods need to add their own query conditions

**Comment by SummerVibes** [comment]
Please update the doc.
