### ISSUE TITLE
tx.is_done 总是为false

### ISSUE THREAD

**Issue by wangbaolong** [rbatis/rbatis#121]
tx.is_done 总是为false
```rust
let mut tx = dao::RB.acquire_begin().await?
        .defer_async(|tx| async {
            debug!("is_done:{}", tx.is_done());
            if !tx.is_done() {
                let result = tx.rollback().await;
                info!("create user rollback result:{:?}", result);
            } else {
                let result = tx.commit().await;
                info!("create user commit result:{:?}", result);
            }
        });
let result = dao::user::create(&mut tx, user_id).await;
```

**Comment by zhuxiujia** [comment]
> tx.is_done 总是为false
> 
> ```rust
> let mut tx = dao::RB.acquire_begin().await?
>         .defer_async(|tx| async {
>             debug!("is_done:{}", tx.is_done());
>             if !tx.is_done() {
>                 let result = tx.rollback().await;
>                 info!("create user rollback result:{:?}", result);
>             } else {
>                 let result = tx.commit().await;
>                 info!("create user commit result:{:?}", result);
>             }
>         });
> let result = dao::user::create(&mut tx, user_id).await;
> ```

SQLX实现的Tx对象有问题，不管是否提交成功，都会drop销毁对象。
这边计划使用 直接执行sql commit来处理，更安全

**Comment by zhuxiujia** [comment]
2.0.18以后已修复

**Comment by zhuxiujia** [comment]
> tx.is_done 总是为false
> 
> ```rust
> let mut tx = dao::RB.acquire_begin().await?
>         .defer_async(|tx| async {
>             debug!("is_done:{}", tx.is_done());
>             if !tx.is_done() {
>                 let result = tx.rollback().await;
>                 info!("create user rollback result:{:?}", result);
>             } else {
>                 let result = tx.commit().await;
>                 info!("create user commit result:{:?}", result);
>             }
>         });
> let result = dao::user::create(&mut tx, user_id).await;
> ```

```rust
let mut tx = dao::RB.acquire_begin().await?
        .defer_async(|tx| async move {
            debug!("is_done:{}", tx.is_done());
            if !tx.is_done() {
                let result = tx.rollback().await;
                info!("create user rollback result:{:?}", result);
            }
        });
let result = dao::user::create(&mut tx, user_id).await;

//这里如果执行业务 触发panic ，仍然会执行 defer方法执行 rollback操作

let result = tx.commit().await;
info!("create user commit result:{:?}", result);
```
