### ISSUE TITLE
py_sql macro error 

### ISSUE THREAD

**Issue by ycytt-rs** [rbatis/rbatis#123]
The following code could not be compiled:
```rust
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Testings {
    pub id: String,
}

#[py_sql(RB, "SELECT id FROM testings WHERE id = #{id}")]
async fn select_testing_data_by_id_id(id: &str) -> Testings {
  todo!()
}
```
The reported error:
expected `()`, found tuple
this expression has type `()`

**Comment by zhuxiujia** [comment]
> The following code could not be compiled:
> 
> ```rust
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub struct Testings {
>     pub id: String,
> }
> 
> #[py_sql(RB, "SELECT id FROM testings WHERE id = #{id}")]
> async fn select_testing_data_by_id_id(id: &str) -> Testings {
>   todo!()
> }
> ```
> 
> The reported error:
> expected `()`, found tuple
> this expression has type `()`

did you run cargo update command？
