### ISSUE TITLE
use Cargo fmt for rbatis-related projects

### ISSUE THREAD

**Issue by ycytt-rs** [rbatis/rbatis#124]
Hi, I really enjoy the concept and the apis of this project. But when I trace the commit history. I usually found the commits related to code formatting.

I would like to suggest we use `rustfmt` to standardize the code. I would help for the PR if it is ok?

**Comment by zhuxiujia** [comment]
> Hi, I really enjoy the concept and the apis of this project. But when I trace the commit history. I usually found the commits related to code formatting.
> 
> I would like to suggest we use `rustfmt` to standardize the code. I would help for the PR if it is ok?

Perhaps this question should be referred to Clion's Rust plugin team. The format functionality they use is different from the ‘cargo fmt’
