### ISSUE TITLE
xml文件是否可以简写下

### ISSUE THREAD

**Issue by sixinyiyu** [rbatis/rbatis#126]
使用Mybatis一个比较麻烦的地方就是条件表达式要写一堆，非常繁琐。

```
<mapper>
    <select id="select_by_condition">
        select * from biz_activity where
        <if test="name != ''">
            name like #{name}
        </if>
    </select>
</mapper>
```

可以简写下
```
<mapper>
    <sql id="select_by_condition">
        select * from biz_activity where
          #[  name = :name ]
          #[ and version = :version]
    </sql >
</mapper>
```

**Comment by zhuxiujia** [comment]
> 使用Mybatis一个比较麻烦的地方就是条件表达式要写一堆，非常繁琐。
> 
> ```
> <mapper>
>     <select id="select_by_condition">
>         select * from biz_activity where
>         <if test="name != ''">
>             name like #{name}
>         </if>
>     </select>
> </mapper>
> ```
> 
> 可以简写下
> 
> ```
> <mapper>
>     <sql id="select_by_condition">
>         select * from biz_activity where
>           #[  name = :name ]
>           #[ and version = :version]
>     </sql >
> </mapper>
> ```


这样不然改成用py_sql,  使用xml的原因就是具备智能提示

**Comment by zhuxiujia** [comment]
> 使用Mybatis一个比较麻烦的地方就是条件表达式要写一堆，非常繁琐。
> 
> 
> 
> ```
> 
> <mapper>
> 
>     <select id="select_by_condition">
> 
>         select * from biz_activity where
> 
>         <if test="name != ''">
> 
>             name like #{name}
> 
>         </if>
> 
>     </select>
> 
> </mapper>
> 
> ```
> 
> 
> 
> 可以简写下
> 
> ```
> 
> <mapper>
> 
>     <sql id="select_by_condition">
> 
>         select * from biz_activity where
> 
>           #[  name = :name ]
> 
>           #[ and version = :version]
> 
>     </sql >
> 
> </mapper>
> 
> ```
> 
> 

pysql就具备你文中描述的写法
