### ISSUE TITLE
翻页提升性能的建议。

### ISSUE THREAD

**Issue by xiuno** [rbatis/rbatis#128]
在数据量大的时候，`SELECT * FROM tablename LIMIT 100000,10` 资源消耗比较大，一般优化方案如下：
`SELECT * FROM tablename WHERE id IN (SELECT id FROM tablename LIMIT 100000,10)`
看官方能否支持一下？

![image](https://user-images.githubusercontent.com/3362277/128299598-cd828532-efa1-49dc-a703-82154a34f488.png)

**Comment by xiuno** [comment]
目前还没有找到如何只查询一个字段的方法。

**Comment by zhuxiujia** [comment]
分页插件是一个插件，所以你可以impl trait自定义实现的sql。

只查询一个字段，请使用py_sql或者 html_sql 宏
