### ISSUE TITLE
[sqlite] rbatis 可以支持创建 sqlite 文件吗？

### ISSUE THREAD

**Issue by jctaoo** [rbatis/rbatis#129]

**Comment by zhuxiujia** [comment]
支持

**Comment by Athxx** [comment]
@jctaoo #149 
```rust
   let f=std::fs::File::create("test.db").unwrap();
   let rb=Rbatis::new();
   rb.link("sqlite://test.db").await?;
```

**Comment by jctaoo** [comment]
> @jctaoo #149 
> 
> ```rust
> 
>    let f=std::fs::File::create("test.db").unwrap();
> 
>    let rb=Rbatis::new();
> 
>    rb.link("sqlite://test.db").await?;
> 
> ```
> 
> 

Thank you！
