### ISSUE TITLE
逻辑删除插件，new函数里的deleted和un_deleted可能搞反了

### ISSUE THREAD

**Issue by jayy1943** [rbatis/rbatis#13]
代码如下：
````rust
  pub fn new(column: &str) -> Self {
        Self {
            column: column.to_string(),
            deleted: 0,
            un_deleted: 1,
        }
    }
`````
结合abs_admin工程里的使用示例：
````rust
let del = RbatisLogicDeletePlugin::new("del");
`````
可见通常是用诸如del作为逻辑删除的字段名，那么deleted为1，un_deleted为0，和字面意思是相符的，但代码实际上是反过来的了

**Comment by zhuxiujia** [comment]
> 代码如下：
> 
> ```rust
>   pub fn new(column: &str) -> Self {
>         Self {
>             column: column.to_string(),
>             deleted: 0,
>             un_deleted: 1,
>         }
>     }
> ```
> 
> 结合abs_admin工程里的使用示例：
> 
> ```rust
> let del = RbatisLogicDeletePlugin::new("del");
> ```
> 
> 可见通常是用诸如del作为逻辑删除的字段名，那么deleted为1，un_deleted为0，和字面意思是相符的，但代码实际上是反过来的了

new_opt(column: &str, deleted: i32, un_deleted: i32) 方法可以自定义  deleted: 0， un_deleted的。不过这里是可以按照习惯来定义

**Comment by zhuxiujia** [comment]
新版已经更正
