### ISSUE TITLE
cannot cast type integer to inet 

### ISSUE THREAD

**Issue by juzi5201314** [rbatis/rbatis#134]
数据库: `postgres`

字段: `ip inet`

结构: 
```
#[crud_table(formats_pg: "create_time:{}::timestamp, ip:{}::inet" | table_name: "users")]
#[derive(Clone, Debug)]
pub struct User {
    id: u64,
    create_time: Option<chrono::NaiveDateTime>,
    user_name: String,
    nick_name: Option<String>,
    email: String,
    tel: Option<String>,
    ip: Option<IpNetwork>,
    permissions: u16,
    description: Option<String>,
    password_hash: String,
}
```

依赖:
```
rbatis = { version = "2.0", default-features = false, features = ["tokio1", "postgres"] }
ipnetwork = "0.18.0"
```

log:
```
Aug 16 15:02:52.041  INFO rbatis::plugin::log: [rbatis] [] Exec   ==> insert into users (user_name,nick_name,email,tel,ip,permissions,description,password_hash) values ($1,$2,$3,$4,$5::inet,$6,$7,$8)
                                                                [rbatis] [] Args   ==> ["some","name","some@moeask.com","some",null,0,"i like cat","some"]    
Aug 16 15:02:52.071 ERROR rbatis::plugin::log: [rbatis] [] ReturnErr  <== error returned from database: cannot cast type integer to inet    

```

**Comment by zhuxiujia** [comment]
> 数据库: `postgres`
> 
> 字段: `ip inet`
> 
> 结构:
> 
> ```
> #[crud_table(formats_pg: "create_time:{}::timestamp, ip:{}::inet" | table_name: "users")]
> #[derive(Clone, Debug)]
> pub struct User {
>     id: u64,
>     create_time: Option<chrono::NaiveDateTime>,
>     user_name: String,
>     nick_name: Option<String>,
>     email: String,
>     tel: Option<String>,
>     ip: Option<IpNetwork>,
>     permissions: u16,
>     description: Option<String>,
>     password_hash: String,
> }
> ```
> 
> 依赖:
> 
> ```
> rbatis = { version = "2.0", default-features = false, features = ["tokio1", "postgres"] }
> ipnetwork = "0.18.0"
> ```
> 
> log:
> 
> ```
> Aug 16 15:02:52.041  INFO rbatis::plugin::log: [rbatis] [] Exec   ==> insert into users (user_name,nick_name,email,tel,ip,permissions,description,password_hash) values ($1,$2,$3,$4,$5::inet,$6,$7,$8)
>                                                                 [rbatis] [] Args   ==> ["some","name","some@moeask.com","some",null,0,"i like cat","some"]    
> Aug 16 15:02:52.071 ERROR rbatis::plugin::log: [rbatis] [] ReturnErr  <== error returned from database: cannot cast type integer to inet    
> ```

null 不可以转inet，必须是string的ip地址

**Comment by juzi5201314** [comment]
> > 数据库: `postgres`
> > 字段: `ip inet`
> > 结构:
> > ```
> > #[crud_table(formats_pg: "create_time:{}::timestamp, ip:{}::inet" | table_name: "users")]
> > #[derive(Clone, Debug)]
> > pub struct User {
> >     id: u64,
> >     create_time: Option<chrono::NaiveDateTime>,
> >     user_name: String,
> >     nick_name: Option<String>,
> >     email: String,
> >     tel: Option<String>,
> >     ip: Option<IpNetwork>,
> >     permissions: u16,
> >     description: Option<String>,
> >     password_hash: String,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 依赖:
> > ```
> > rbatis = { version = "2.0", default-features = false, features = ["tokio1", "postgres"] }
> > ipnetwork = "0.18.0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > log:
> > ```
> > Aug 16 15:02:52.041  INFO rbatis::plugin::log: [rbatis] [] Exec   ==> insert into users (user_name,nick_name,email,tel,ip,permissions,description,password_hash) values ($1,$2,$3,$4,$5::inet,$6,$7,$8)
> >                                                                 [rbatis] [] Args   ==> ["some","name","some@moeask.com","some",null,0,"i like cat","some"]    
> > Aug 16 15:02:52.071 ERROR rbatis::plugin::log: [rbatis] [] ReturnErr  <== error returned from database: cannot cast type integer to inet    
> > ```
> 
> null 不可以转inet，必须是string的ip地址

好的吧
