### ISSUE TITLE
Is there something wrong with postgres driver when excuting query include a camelCase columns?

### ISSUE THREAD

**Issue by PhoenSXar** [rbatis/rbatis#139]
code:
```
#![allow(unused_must_use)]
#![allow(non_snake_case)]
#[macro_use]
extern crate rbatis;

use actix_web::{web, App, HttpResponse, HttpServer, Responder};
// use chrono::NaiveDateTime;
use rbatis::crud::{CRUD};
use rbatis::rbatis::Rbatis;
use rbatis::core::runtime::sync::Arc;

// #[crud_table(table_name:"task" | table_columns:"id,status,sequence_id,functor_id,total,current,complete,startTime,completeTime,create_at,update_at")]
#[crud_table]
#[derive(Clone, Debug)]
pub struct Task {
    pub id: Option<String>,
    pub status: Option<String>,
    pub sequence_id: Option<String>,
    pub functor_id: Option<String>,
    pub total: Option<i32>,
    pub current: Option<i32>,
    pub complete: Option<i32>,
    pub startTime: Option<i64>,
    pub completeTime: Option<i64>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

impl Default for Task {
    fn default() -> Self {
        Task {
            id: None,
            status: None,
            sequence_id: None,
            functor_id: None,
            total: None,
            current: None,
            complete: None,
            startTime: None,
            completeTime: None,
            created_at: None,
            updated_at: None,
        }
    }
}

pub const PG_URL: &'static str = "postgresql://postgres:123456@abyssii:35432/ac";
pub const MYSQL_URL: &'static str = "mysql://root:123456@abyssii:33060/ma";

async fn postgres(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
    let v = rb.postgres.fetch_list::<Task>().await.unwrap();
    HttpResponse::Ok().json(serde_json::json!(v).to_string())
}

async fn mysql(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
    let v = rb.mysql.fetch_list::<Task>().await.unwrap();
    HttpResponse::Ok().json(serde_json::json!(v).to_string())
}

struct RbatisConnection {
    postgres: Rbatis,
    mysql: Rbatis,
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    //log
    fast_log::init_log("requests.log", 1000, log::Level::Info, None, true);
    //init rbatis . also you can use  lazy_static! { static ref RB: Rbatis = Rbatis::new(); } replace this
    log::info!("linking database...");
    let pgrb = Rbatis::new();
    pgrb.link(PG_URL).await.expect("rbatis link postgres fail");
    let myrb = Rbatis::new();
    myrb.link(MYSQL_URL).await.expect("rbatis link mysql fail");

    let rb: RbatisConnection = RbatisConnection {
        postgres: pgrb,
        mysql: myrb,
    };

    let rb = Arc::new(rb);

    log::info!("linking database successful!");
    //router
    HttpServer::new(move || {
        App::new()
            //add into actix-web data
            .data(rb.to_owned())
            .route("/pg", web::get().to(postgres))
            .route("/my", web::get().to(mysql))
    })
        .bind("0.0.0.0:8000")?
        .run()
        .await
}
```
debug_mode output:
```
............gen impl CRUDTable:
 #[derive(serde :: Serialize, serde :: Deserialize)] #[derive(Clone, Debug)]
pub struct Task
{
    pub id : Option < String >, pub status : Option < String >, pub
    sequence_id : Option < String >, pub functor_id : Option < String >, pub
    total : Option < i32 >, pub current : Option < i32 >, pub complete :
    Option < i32 >, pub startTime : Option < i64 >, pub completeTime : Option
    < i64 >, pub created_at : Option < String >, pub updated_at : Option <
    String >,
} impl rbatis :: crud :: CRUDTable for Task
{
    fn get(& self, column : & str) -> serde_json :: Value
    {
        return match column
        {
            "id" => { return serde_json :: json! (& self.id) ; } "status" =>
            { return serde_json :: json! (& self.status) ; } "sequence_id" =>
            { return serde_json :: json! (& self.sequence_id) ; } "functor_id"
            => { return serde_json :: json! (& self.functor_id) ; } "total" =>
            { return serde_json :: json! (& self.total) ; } "current" =>
            { return serde_json :: json! (& self.current) ; } "complete" =>
            { return serde_json :: json! (& self.complete) ; } "startTime" =>
            { return serde_json :: json! (& self.startTime) ; } "completeTime"
            => { return serde_json :: json! (& self.completeTime) ; }
            "created_at" =>
            { return serde_json :: json! (& self.created_at) ; } "updated_at"
            => { return serde_json :: json! (& self.updated_at) ; } _ =>
            { serde_json :: Value :: Null }
        }
    } fn table_name() -> String { "task".to_string() } fn table_columns() ->
    String
    {
        "id,status,sequence_id,functor_id,total,current,complete,startTime,completeTime,created_at,updated_at".to_string()
    } fn formats(driver_type : & rbatis :: core :: db :: DriverType) -> std ::
    collections :: HashMap < String, fn(arg : & str) -> String >
    {
        let mut m : std :: collections :: HashMap < String, fn(arg : & str) ->
        String > = std :: collections :: HashMap :: new() ; match driver_type
        {
            rbatis :: core :: db :: DriverType :: Mysql => { return m ; },
            rbatis :: core :: db :: DriverType :: Postgres => { return m ; },
            rbatis :: core :: db :: DriverType :: Sqlite => { return m ; },
            rbatis :: core :: db :: DriverType :: Mssql => { return m ; },
            rbatis :: core :: db :: DriverType :: None => { return m ; },
        }
    }
}
............gen impl CRUDTable end............
```

mysql table:
```
-- auto-generated definition
create table task
(
    id           char(36)     not null
        primary key,
    status       varchar(100) null,
    sequence_id  char(36)     null,
    functor_id   varchar(100) null,
    total        int          null,
    current      int          null,
    complete     int          null,
    startTime    bigint       null,
    completeTime bigint       null,
    created_at   timestamp    not null,
    updated_at   timestamp    not null
);
```

postgres table:
```
-- auto-generated definition
create table task
(
    id             uuid                     not null
        constraint task_pkey
            primary key,
    status         varchar(100),
    sequence_id    uuid,
    functor_id     varchar(100),
    total          integer,
    current        integer,
    complete       integer,
    "startTime"    bigint,
    "completeTime" bigint,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null
);

alter table task
    owner to postgres;
```

work with mysql, perfect!
![image](https://user-images.githubusercontent.com/28881773/132634993-cb323a09-6071-43bd-af68-6b92bf4b2ee8.png)
![image](https://user-images.githubusercontent.com/28881773/132635151-17b6e154-7858-4bba-9416-9f4f1a7fa3a1.png)

work with postgres:
![image](https://user-images.githubusercontent.com/28881773/132635214-98e6ab77-cff0-4a90-b770-96889a455daa.png)
![image](https://user-images.githubusercontent.com/28881773/132635296-d205e3c2-f652-4be6-a079-0ca5fb07a858.png)
postgres log:
![image](https://user-images.githubusercontent.com/28881773/132635342-8614b4fb-d3c8-4630-b822-7e9044955168.png)

**Comment by zhuxiujia** [comment]
> code:
> 
> ```
> #![allow(unused_must_use)]
> #![allow(non_snake_case)]
> #[macro_use]
> extern crate rbatis;
> 
> use actix_web::{web, App, HttpResponse, HttpServer, Responder};
> // use chrono::NaiveDateTime;
> use rbatis::crud::{CRUD};
> use rbatis::rbatis::Rbatis;
> use rbatis::core::runtime::sync::Arc;
> 
> // #[crud_table(table_name:"task" | table_columns:"id,status,sequence_id,functor_id,total,current,complete,startTime,completeTime,create_at,update_at")]
> #[crud_table]
> #[derive(Clone, Debug)]
> pub struct Task {
>     pub id: Option<String>,
>     pub status: Option<String>,
>     pub sequence_id: Option<String>,
>     pub functor_id: Option<String>,
>     pub total: Option<i32>,
>     pub current: Option<i32>,
>     pub complete: Option<i32>,
>     pub startTime: Option<i64>,
>     pub completeTime: Option<i64>,
>     pub created_at: Option<String>,
>     pub updated_at: Option<String>,
> }
> 
> impl Default for Task {
>     fn default() -> Self {
>         Task {
>             id: None,
>             status: None,
>             sequence_id: None,
>             functor_id: None,
>             total: None,
>             current: None,
>             complete: None,
>             startTime: None,
>             completeTime: None,
>             created_at: None,
>             updated_at: None,
>         }
>     }
> }
> 
> pub const PG_URL: &'static str = "postgresql://postgres:123456@abyssii:35432/ac";
> pub const MYSQL_URL: &'static str = "mysql://root:123456@abyssii:33060/ma";
> 
> async fn postgres(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
>     let v = rb.postgres.fetch_list::<Task>().await.unwrap();
>     HttpResponse::Ok().json(serde_json::json!(v).to_string())
> }
> 
> async fn mysql(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
>     let v = rb.mysql.fetch_list::<Task>().await.unwrap();
>     HttpResponse::Ok().json(serde_json::json!(v).to_string())
> }
> 
> struct RbatisConnection {
>     postgres: Rbatis,
>     mysql: Rbatis,
> }
> 
> #[actix_web::main]
> async fn main() -> std::io::Result<()> {
>     //log
>     fast_log::init_log("requests.log", 1000, log::Level::Info, None, true);
>     //init rbatis . also you can use  lazy_static! { static ref RB: Rbatis = Rbatis::new(); } replace this
>     log::info!("linking database...");
>     let pgrb = Rbatis::new();
>     pgrb.link(PG_URL).await.expect("rbatis link postgres fail");
>     let myrb = Rbatis::new();
>     myrb.link(MYSQL_URL).await.expect("rbatis link mysql fail");
> 
>     let rb: RbatisConnection = RbatisConnection {
>         postgres: pgrb,
>         mysql: myrb,
>     };
> 
>     let rb = Arc::new(rb);
> 
>     log::info!("linking database successful!");
>     //router
>     HttpServer::new(move || {
>         App::new()
>             //add into actix-web data
>             .data(rb.to_owned())
>             .route("/pg", web::get().to(postgres))
>             .route("/my", web::get().to(mysql))
>     })
>         .bind("0.0.0.0:8000")?
>         .run()
>         .await
> }
> ```
> 
> debug_mode output:
> 
> ```
> ............gen impl CRUDTable:
>  #[derive(serde :: Serialize, serde :: Deserialize)] #[derive(Clone, Debug)]
> pub struct Task
> {
>     pub id : Option < String >, pub status : Option < String >, pub
>     sequence_id : Option < String >, pub functor_id : Option < String >, pub
>     total : Option < i32 >, pub current : Option < i32 >, pub complete :
>     Option < i32 >, pub startTime : Option < i64 >, pub completeTime : Option
>     < i64 >, pub created_at : Option < String >, pub updated_at : Option <
>     String >,
> } impl rbatis :: crud :: CRUDTable for Task
> {
>     fn get(& self, column : & str) -> serde_json :: Value
>     {
>         return match column
>         {
>             "id" => { return serde_json :: json! (& self.id) ; } "status" =>
>             { return serde_json :: json! (& self.status) ; } "sequence_id" =>
>             { return serde_json :: json! (& self.sequence_id) ; } "functor_id"
>             => { return serde_json :: json! (& self.functor_id) ; } "total" =>
>             { return serde_json :: json! (& self.total) ; } "current" =>
>             { return serde_json :: json! (& self.current) ; } "complete" =>
>             { return serde_json :: json! (& self.complete) ; } "startTime" =>
>             { return serde_json :: json! (& self.startTime) ; } "completeTime"
>             => { return serde_json :: json! (& self.completeTime) ; }
>             "created_at" =>
>             { return serde_json :: json! (& self.created_at) ; } "updated_at"
>             => { return serde_json :: json! (& self.updated_at) ; } _ =>
>             { serde_json :: Value :: Null }
>         }
>     } fn table_name() -> String { "task".to_string() } fn table_columns() ->
>     String
>     {
>         "id,status,sequence_id,functor_id,total,current,complete,startTime,completeTime,created_at,updated_at".to_string()
>     } fn formats(driver_type : & rbatis :: core :: db :: DriverType) -> std ::
>     collections :: HashMap < String, fn(arg : & str) -> String >
>     {
>         let mut m : std :: collections :: HashMap < String, fn(arg : & str) ->
>         String > = std :: collections :: HashMap :: new() ; match driver_type
>         {
>             rbatis :: core :: db :: DriverType :: Mysql => { return m ; },
>             rbatis :: core :: db :: DriverType :: Postgres => { return m ; },
>             rbatis :: core :: db :: DriverType :: Sqlite => { return m ; },
>             rbatis :: core :: db :: DriverType :: Mssql => { return m ; },
>             rbatis :: core :: db :: DriverType :: None => { return m ; },
>         }
>     }
> }
> ............gen impl CRUDTable end............
> ```
> 
> mysql table:
> 
> ```
> -- auto-generated definition
> create table task
> (
>     id           char(36)     not null
>         primary key,
>     status       varchar(100) null,
>     sequence_id  char(36)     null,
>     functor_id   varchar(100) null,
>     total        int          null,
>     current      int          null,
>     complete     int          null,
>     startTime    bigint       null,
>     completeTime bigint       null,
>     created_at   timestamp    not null,
>     updated_at   timestamp    not null
> );
> ```
> 
> postgres table:
> 
> ```
> -- auto-generated definition
> create table task
> (
>     id             uuid                     not null
>         constraint task_pkey
>             primary key,
>     status         varchar(100),
>     sequence_id    uuid,
>     functor_id     varchar(100),
>     total          integer,
>     current        integer,
>     complete       integer,
>     "startTime"    bigint,
>     "completeTime" bigint,
>     created_at     timestamp with time zone not null,
>     updated_at     timestamp with time zone not null
> );
> 
> alter table task
>     owner to postgres;
> ```
> 
> work with mysql, perfect!
> ![image](https://user-images.githubusercontent.com/28881773/132634993-cb323a09-6071-43bd-af68-6b92bf4b2ee8.png)
> ![image](https://user-images.githubusercontent.com/28881773/132635151-17b6e154-7858-4bba-9416-9f4f1a7fa3a1.png)
> 
> work with postgres:
> ![image](https://user-images.githubusercontent.com/28881773/132635214-98e6ab77-cff0-4a90-b770-96889a455daa.png)
> ![image](https://user-images.githubusercontent.com/28881773/132635296-d205e3c2-f652-4be6-a079-0ca5fb07a858.png)
> postgres log:
> ![image](https://user-images.githubusercontent.com/28881773/132635342-8614b4fb-d3c8-4630-b822-7e9044955168.png)

add  type convert   for  pg   of    ```startTime::bigint```  , more detail you can read doc  of  https://rbatis.github.io/rbatis.io/#/en/?id=crudtable

**Comment by PhoenSXar** [comment]
> > code:
> > ```
> > #![allow(unused_must_use)]
> > #![allow(non_snake_case)]
> > #[macro_use]
> > extern crate rbatis;
> > 
> > use actix_web::{web, App, HttpResponse, HttpServer, Responder};
> > // use chrono::NaiveDateTime;
> > use rbatis::crud::{CRUD};
> > use rbatis::rbatis::Rbatis;
> > use rbatis::core::runtime::sync::Arc;
> > 
> > // #[crud_table(table_name:"task" | table_columns:"id,status,sequence_id,functor_id,total,current,complete,startTime,completeTime,create_at,update_at")]
> > #[crud_table]
> > #[derive(Clone, Debug)]
> > pub struct Task {
> >     pub id: Option<String>,
> >     pub status: Option<String>,
> >     pub sequence_id: Option<String>,
> >     pub functor_id: Option<String>,
> >     pub total: Option<i32>,
> >     pub current: Option<i32>,
> >     pub complete: Option<i32>,
> >     pub startTime: Option<i64>,
> >     pub completeTime: Option<i64>,
> >     pub created_at: Option<String>,
> >     pub updated_at: Option<String>,
> > }
> > 
> > impl Default for Task {
> >     fn default() -> Self {
> >         Task {
> >             id: None,
> >             status: None,
> >             sequence_id: None,
> >             functor_id: None,
> >             total: None,
> >             current: None,
> >             complete: None,
> >             startTime: None,
> >             completeTime: None,
> >             created_at: None,
> >             updated_at: None,
> >         }
> >     }
> > }
> > 
> > pub const PG_URL: &'static str = "postgresql://postgres:123456@abyssii:35432/ac";
> > pub const MYSQL_URL: &'static str = "mysql://root:123456@abyssii:33060/ma";
> > 
> > async fn postgres(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
> >     let v = rb.postgres.fetch_list::<Task>().await.unwrap();
> >     HttpResponse::Ok().json(serde_json::json!(v).to_string())
> > }
> > 
> > async fn mysql(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
> >     let v = rb.mysql.fetch_list::<Task>().await.unwrap();
> >     HttpResponse::Ok().json(serde_json::json!(v).to_string())
> > }
> > 
> > struct RbatisConnection {
> >     postgres: Rbatis,
> >     mysql: Rbatis,
> > }
> > 
> > #[actix_web::main]
> > async fn main() -> std::io::Result<()> {
> >     //log
> >     fast_log::init_log("requests.log", 1000, log::Level::Info, None, true);
> >     //init rbatis . also you can use  lazy_static! { static ref RB: Rbatis = Rbatis::new(); } replace this
> >     log::info!("linking database...");
> >     let pgrb = Rbatis::new();
> >     pgrb.link(PG_URL).await.expect("rbatis link postgres fail");
> >     let myrb = Rbatis::new();
> >     myrb.link(MYSQL_URL).await.expect("rbatis link mysql fail");
> > 
> >     let rb: RbatisConnection = RbatisConnection {
> >         postgres: pgrb,
> >         mysql: myrb,
> >     };
> > 
> >     let rb = Arc::new(rb);
> > 
> >     log::info!("linking database successful!");
> >     //router
> >     HttpServer::new(move || {
> >         App::new()
> >             //add into actix-web data
> >             .data(rb.to_owned())
> >             .route("/pg", web::get().to(postgres))
> >             .route("/my", web::get().to(mysql))
> >     })
> >         .bind("0.0.0.0:8000")?
> >         .run()
> >         .await
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > debug_mode output:
> > ```
> > ............gen impl CRUDTable:
> >  #[derive(serde :: Serialize, serde :: Deserialize)] #[derive(Clone, Debug)]
> > pub struct Task
> > {
> >     pub id : Option < String >, pub status : Option < String >, pub
> >     sequence_id : Option < String >, pub functor_id : Option < String >, pub
> >     total : Option < i32 >, pub current : Option < i32 >, pub complete :
> >     Option < i32 >, pub startTime : Option < i64 >, pub completeTime : Option
> >     < i64 >, pub created_at : Option < String >, pub updated_at : Option <
> >     String >,
> > } impl rbatis :: crud :: CRUDTable for Task
> > {
> >     fn get(& self, column : & str) -> serde_json :: Value
> >     {
> >         return match column
> >         {
> >             "id" => { return serde_json :: json! (& self.id) ; } "status" =>
> >             { return serde_json :: json! (& self.status) ; } "sequence_id" =>
> >             { return serde_json :: json! (& self.sequence_id) ; } "functor_id"
> >             => { return serde_json :: json! (& self.functor_id) ; } "total" =>
> >             { return serde_json :: json! (& self.total) ; } "current" =>
> >             { return serde_json :: json! (& self.current) ; } "complete" =>
> >             { return serde_json :: json! (& self.complete) ; } "startTime" =>
> >             { return serde_json :: json! (& self.startTime) ; } "completeTime"
> >             => { return serde_json :: json! (& self.completeTime) ; }
> >             "created_at" =>
> >             { return serde_json :: json! (& self.created_at) ; } "updated_at"
> >             => { return serde_json :: json! (& self.updated_at) ; } _ =>
> >             { serde_json :: Value :: Null }
> >         }
> >     } fn table_name() -> String { "task".to_string() } fn table_columns() ->
> >     String
> >     {
> >         "id,status,sequence_id,functor_id,total,current,complete,startTime,completeTime,created_at,updated_at".to_string()
> >     } fn formats(driver_type : & rbatis :: core :: db :: DriverType) -> std ::
> >     collections :: HashMap < String, fn(arg : & str) -> String >
> >     {
> >         let mut m : std :: collections :: HashMap < String, fn(arg : & str) ->
> >         String > = std :: collections :: HashMap :: new() ; match driver_type
> >         {
> >             rbatis :: core :: db :: DriverType :: Mysql => { return m ; },
> >             rbatis :: core :: db :: DriverType :: Postgres => { return m ; },
> >             rbatis :: core :: db :: DriverType :: Sqlite => { return m ; },
> >             rbatis :: core :: db :: DriverType :: Mssql => { return m ; },
> >             rbatis :: core :: db :: DriverType :: None => { return m ; },
> >         }
> >     }
> > }
> > ............gen impl CRUDTable end............
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mysql table:
> > ```
> > -- auto-generated definition
> > create table task
> > (
> >     id           char(36)     not null
> >         primary key,
> >     status       varchar(100) null,
> >     sequence_id  char(36)     null,
> >     functor_id   varchar(100) null,
> >     total        int          null,
> >     current      int          null,
> >     complete     int          null,
> >     startTime    bigint       null,
> >     completeTime bigint       null,
> >     created_at   timestamp    not null,
> >     updated_at   timestamp    not null
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > postgres table:
> > ```
> > -- auto-generated definition
> > create table task
> > (
> >     id             uuid                     not null
> >         constraint task_pkey
> >             primary key,
> >     status         varchar(100),
> >     sequence_id    uuid,
> >     functor_id     varchar(100),
> >     total          integer,
> >     current        integer,
> >     complete       integer,
> >     "startTime"    bigint,
> >     "completeTime" bigint,
> >     created_at     timestamp with time zone not null,
> >     updated_at     timestamp with time zone not null
> > );
> > 
> > alter table task
> >     owner to postgres;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > work with mysql, perfect!
> > ![image](https://user-images.githubusercontent.com/28881773/132634993-cb323a09-6071-43bd-af68-6b92bf4b2ee8.png)
> > ![image](https://user-images.githubusercontent.com/28881773/132635151-17b6e154-7858-4bba-9416-9f4f1a7fa3a1.png)
> > work with postgres:
> > ![image](https://user-images.githubusercontent.com/28881773/132635214-98e6ab77-cff0-4a90-b770-96889a455daa.png)
> > ![image](https://user-images.githubusercontent.com/28881773/132635296-d205e3c2-f652-4be6-a079-0ca5fb07a858.png)
> > postgres log:
> > ![image](https://user-images.githubusercontent.com/28881773/132635342-8614b4fb-d3c8-4630-b822-7e9044955168.png)
> 
> add type convert for pg of `startTime::bigint` , more detail you can read doc of https://rbatis.github.io/rbatis.io/#/en/?id=crudtable

thanks for your kind reply and advice!

I have added type convert like this
```
#[crud_table( formats_pg: formats_pg:"startTime:{}::bigint" | formats_pg:"completeTime:{}::bigint" )]
```
Then still get the same error.
That error tell us 
```
column \"starttime\" does not exist"
```
So I think the problem may be the driver send a wrong column name 'starttime' which should be 'startTime'.

**Comment by PhoenSXar** [comment]
I created a pair of new table that just use varchar for test.

```
#![allow(unused_must_use)]
#![allow(non_snake_case)]
#[macro_use]
extern crate rbatis;

use actix_web::{web, App, HttpResponse, HttpServer, Responder};
// use chrono::NaiveDateTime;
use rbatis::crud::{CRUD};
use rbatis::rbatis::Rbatis;
use rbatis::core::runtime::sync::Arc;

#[crud_table]
#[derive(Clone, Debug)]
struct StrangeTable {
    camelCase: Option<String>,
    snake_case: Option<String>,
}

impl Default for StrangeTable {
    fn default() -> Self {
        StrangeTable { camelCase: None, snake_case: None }
    }
}

pub const PG_URL: &'static str = "postgresql://postgres:123456@abyssii:35432/ac";
pub const MYSQL_URL: &'static str = "mysql://root:123456@abyssii:33060/ma";

async fn postgres(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
    let v = rb.postgres.fetch_list::<StrangeTable>().await.unwrap();
    HttpResponse::Ok().json(serde_json::json!(v).to_string())
}

async fn mysql(rb: web::Data<Arc<RbatisConnection>>) -> impl Responder {
    let v = rb.mysql.fetch_list::<StrangeTable>().await.unwrap();
    HttpResponse::Ok().json(serde_json::json!(v).to_string())
}

struct RbatisConnection {
    postgres: Rbatis,
    mysql: Rbatis,
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    //log
    fast_log::init_log("requests.log", 1000, log::Level::Info, None, true);
    //init rbatis . also you can use  lazy_static! { static ref RB: Rbatis = Rbatis::new(); } replace this
    log::info!("linking database...");
    let pgrb = Rbatis::new();
    pgrb.link(PG_URL).await.expect("rbatis link postgres fail");
    let myrb = Rbatis::new();
    myrb.link(MYSQL_URL).await.expect("rbatis link mysql fail");

    let rb: RbatisConnection = RbatisConnection {
        postgres: pgrb,
        mysql: myrb,
    };

    let rb = Arc::new(rb);

    log::info!("linking database successful!");
    //router
    HttpServer::new(move || {
        App::new()
            //add into actix-web data
            .data(rb.to_owned())
            .route("/pg", web::get().to(postgres))
            .route("/my", web::get().to(mysql))
    })
        .bind("0.0.0.0:8000")?
        .run()
        .await
}
```
mysql
```
CREATE TABLE `strange_table` (
  `camelCase` varchar(100) DEFAULT NULL,
  `snake_case` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```
postgres
```
create table strange_table
(
	"camelCase" varchar(100),
	snake_case varchar(100)
);

alter table strange_table owner to postgres;
```
and get a similar error
![image](https://user-images.githubusercontent.com/28881773/132643297-005d1230-09cb-4068-85b7-b94855764843.png)

**Comment by zhuxiujia** [comment]
I see an error in writing and should use the following definition
```  
#[crud_table( formats_pg:"startTime:{}::bigint,completeTime:{}::bigint" )]
```

**Comment by PhoenSXar** [comment]
> I see an error in writing and should use the following definition
> 
> ```
> #[crud_table( formats_pg:"startTime:{}::bigint,completeTime:{}::bigint" )]
> ```

my bad >_<, thanks.

I try it but still get the same error.

**Comment by zhuxiujia** [comment]
> > I see an error in writing and should use the following definition
> > ```
> > #[crud_table( formats_pg:"startTime:{}::bigint,completeTime:{}::bigint" )]
> > ```
> 
> my bad >_<, thanks.
> 
> I try it but still get the same error.

How do you prove that other tools support Postgres hump naming?

**Comment by PhoenSXar** [comment]
> > > I see an error in writing and should use the following definition
> > > ```
> > > #[crud_table( formats_pg:"startTime:{}::bigint,completeTime:{}::bigint" )]
> > > ```
> > 
> > 
> > my bad >_<, thanks.
> > I try it but still get the same error.
> 
> How do you prove that other tools support Postgres hump naming?

I'm using Datagrip to manage that strange "Task" table above. Datagrip use org.postgresql.Driver as postgres driver.

But it may be not totally fair, it depends on what is the defination of 'tools' in 'other tools', and rbatis is an ORM.

I don't know can it be a convincing evidence, but I will provide a gist later, try to show that another ORM [http://sequelize.org/](sequelize) support Postgres hump naming, which built a web service with that string "Task" table.

I am also curious about can Mybatis support Postgres hump naming too, I will do some experiment with Mybatis too.

**Comment by PhoenSXar** [comment]
Hello there, here is a little repository show that another ORM tools support Postgres hump naming
[https://github.com/PhoenSXar/sequelize-hump-naming-test/tree/master](url)

```
const { Sequelize, Model, DataTypes } = require('sequelize');

async function test() {
	const sequelize = new Sequelize({
		dialect: 'postgres',
		username: 'yourUsername',
		password: 'yourPassword',
		database: 'ac',
		host: 'yourHost',
		port: 'yourPort'
	});
	
	const attributes = {
		id: {
			type: DataTypes.INTEGER,
			primaryKey: true,
		},
		camelCase: {
			type: DataTypes.STRING(100),
			field: 'camelCase',
		},
		snake_case: {
			type: DataTypes.STRING(100),
			field: 'snake_case',
		},
	};
	
	const options = {
		tableName: 'strange_table',
		createdAt: false,
		updatedAt: false,
	}
	
	const Strange = sequelize.define('strangeTable', attributes, options);

	// await sequelize.sync(); // uncomment this if you want to create table autometic

	const result = (await Strange.findAll()).map(item => item.toJSON());

	console.log(result);
	process.exit();
}

test()
```

![image](https://user-images.githubusercontent.com/28881773/132734231-9dcef567-1d0f-4d3e-b7b8-e6bc14043a62.png)

**Comment by zhuxiujia** [comment]
Maybe SQLX-core doesn't support humps

**Comment by zhuxiujia** [comment]
fixed in v4
