### ISSUE TITLE
无法更新字段

### ISSUE THREAD

**Issue by awol2010ex** [rbatis/rbatis#140]
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SysUser {

#[serde(rename(serialize = "userId"))]
pub id: Option<String>,
#[serde(rename(serialize = "loginUserName"))]
pub login_user_name: Option<String>,
#[serde(rename(serialize = "loginPassword"))]
pub login_password: Option<String>,
#[serde(rename(serialize = "nickName"))]
pub nick_name: Option<String>,
#[serde(rename(serialize = "locked"))]
pub locked: Option<i32>,
}

let save_result =tx.update_by_column::<SysUser>(&"id".to_owned(),&sys_user).await;

INFO rbatis::plugin::log: [rbatis] [] Exec ==> update sys_user set locked = ? where id = ?
[rbatis] [] Args ==> [0,"1"]

只能更新 最后一个字段

**Comment by zhuxiujia** [comment]
> #[derive(Serialize, Deserialize, Clone, Debug)]
> pub struct SysUser {
> 
> #[serde(rename(serialize = "userId"))]
> pub id: Option,
> #[serde(rename(serialize = "loginUserName"))]
> pub login_user_name: Option,
> #[serde(rename(serialize = "loginPassword"))]
> pub login_password: Option,
> #[serde(rename(serialize = "nickName"))]
> pub nick_name: Option,
> #[serde(rename(serialize = "locked"))]
> pub locked: Option,
> }
> 
> let save_result =tx.update_by_column::(&"id".to_owned(),&sys_user).await;
> 
> INFO rbatis::plugin::log: [rbatis] [] Exec ==> update sys_user set locked = ? where id = ?
> [rbatis] [] Args ==> [0,"1"]
> 
> 只能更新 最后一个字段

暂不支持 serde(rename 宏。 因为过程宏是 读取 field 值 例如  上面的 login_user_name

**Comment by awol2010ex** [comment]
日志是 
sys_user=SysUser { id: Some("1"), login_user_name: Some("admin"), login_password: Some("e10adc3949ba59abbe56e057f20f883e"), nick_name: Some("十三"), locked: Some(0) }
Sep 16 13:20:29.233  INFO rbatis::plugin::log: [rbatis] [] Exec   ==> update sys_user set  locked = ?  where id = ?
                                                                [rbatis] [] Args   ==> [0,"1"]
Sep 16 13:20:29.240  INFO rbatis::plugin::log: [rbatis] [] RowsAffected <== 1

代码如下

//修改别名
#[fn_handler]
pub async fn edit_name(req: &mut Request, depot: &mut Depot, res: &mut Response) {
    
   let claims = depot.take::<TokenData<Claims>>(&"user_token_decode_data".to_owned()).claims;

   let user_id = claims.sub ;

   //begin
   let mut tx = RB.acquire_begin().await.unwrap();

   let result = tx.fetch_by_column::<SysUser,String>(&"user_id".to_owned(),&user_id).await;

   match result {
       Ok(mut sys_user) => {
             let putBody = req.read::<PutSysUser>().await.unwrap();
         
             //println!("putBody={:?}",&putBody);

             


             sys_user.login_user_name =Some(putBody.loginUserName.unwrap().clone());
             sys_user.nick_name =Some(putBody.nickName.unwrap().clone());
             
             println!("sys_user={:?}",&sys_user);

             let save_result =tx.update_by_column::<SysUser>(&"user_id".to_owned(),&sys_user).await;
             match save_result {
                 Ok(_) =>{
                    res.render_json(&response::success_result("修改成功".to_owned()));
                 }
                 Err(serr) => {
                    tx.rollback().await.unwrap();
                    res.render_json(&response::fail_result(serr.to_string()));
                 }
             }
       }
       Err(err) => {
        tx.rollback().await.unwrap();
        res.render_json(&response::fail_result(err.to_string()));
       }
   }
    
   //commit or rollback
   tx.commit().await.unwrap();
}
