### ISSUE TITLE
html_sql编译不通过

### ISSUE THREAD

**Issue by awol2010ex** [rbatis/rbatis#142]
代码:
use crate::extends::db::RB;
use rbatis::rbatis::Rbatis;
use rbatis::executor::{RbatisExecutor,RBatisTxExecutor};
use std::collections::HashMap;

#[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
pub async fn findGoodsCategoryList(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option<HashMap<String,String>> {}

#[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
pub async fn getTotalGoodsCategories(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option<i32> {}

cargo run 报错

error[E0061]: this function takes 2 arguments but 1 argument was supplied
 --> src/domain/categories/service.rs:7:14
  |
6 | #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
  | -------------------------------------------------------------- supplied 1 argument
7 | pub async fn findGoodsCategoryList(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option<HashMap<String,String>> {}
  |              ^^^^^^^^^^^^^^^^^^^^^ expected 2 arguments
  |
note: function defined here
 --> src/domain/categories/service.rs:7:14
  |
6 | / #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
7 | | pub async fn findGoodsCategoryList(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option<HashMap<String,String>> {}
  | |______________^^^^^^^^^^^^^^^^^^^^^_-------------------------------_-

error[E0308]: mismatched types
 --> src/domain/categories/service.rs:6:1
  |
6 | #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected opaque type, found tuple
  |
  = note: expected opaque type `impl Future`
                   found tuple `(_, _)`
  = note: this error originates in the attribute macro `html_sql` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0061]: this function takes 2 arguments but 1 argument was supplied
  --> src/domain/categories/service.rs:10:14

**Comment by zhuxiujia** [comment]
> 代码:
> use crate::extends::db::RB;
> use rbatis::rbatis::Rbatis;
> use rbatis::executor::{RbatisExecutor,RBatisTxExecutor};
> use std::collections::HashMap;
> 
> #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
> pub async fn findGoodsCategoryList(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option<HashMap<String,String>> {}
> 
> #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
> pub async fn getTotalGoodsCategories(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option {}
> 
> cargo run 报错
> 
> error[E0061]: this function takes 2 arguments but 1 argument was supplied
> --> src/domain/categories/service.rs:7:14
> |
> 6 | #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
> | -------------------------------------------------------------- supplied 1 argument
> 7 | pub async fn findGoodsCategoryList(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option<HashMap<String,String>> {} | ^^^^^^^^^^^^^^^^^^^^^ expected 2 arguments | note: function defined here --> src/domain/categories/service.rs:7:14 | 6 | / #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")] 7 | | pub async fn findGoodsCategoryList(rb : &mut RBatisTxExecutor<'_> , params: &HashMap<String,String>) -> Option<HashMap<String,String>> {}
> | |______________^^^^^^^^^^^^^^^^^^^^^_-------------------------------_-
> 
> error[E0308]: mismatched types
> --> src/domain/categories/service.rs:6:1
> |
> 6 | #[html_sql(rb, "mybatis/categories/GoodsCategoryMapper.html")]
> | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected opaque type, found tuple
> |
> = note: expected opaque type `impl Future`
> found tuple `(_, _)`
> = note: this error originates in the attribute macro `html_sql` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error[E0061]: this function takes 2 arguments but 1 argument was supplied
> --> src/domain/categories/service.rs:10:14

是不是rbatis 最新的版本？
另外看下html 里面的内容 贴上来

**Comment by awol2010ex** [comment]
GoodsCategoryMapper.html:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "https://github.com/rbatis/rbatis_sql/raw/main/mybatis-3-mapper.dtd">
<mapper>
    <select id="findGoodsCategoryList" >
        select
        category_id, category_level, parent_id, category_name, category_rank, is_deleted, 
    create_time, create_user, update_time, update_user
        from tb_newbee_mall_goods_category
        <where>
            <if test="params.categoryLevel!=null and params.categoryLevel!=''">
                and category_level = #{params.categoryLevel}
            </if>
            <if test="parentId!=null and parentId!=''">
                and parent_id = #{params.parentId}
            </if>
            and is_deleted = 0
        </where>
        order by category_rank desc
        <if test="params.start!=null and params.limit!=null">
            limit #{params.start},#{params.limit}
        </if>
    </select>
    <select id="getTotalGoodsCategories">
        select count(*) from tb_newbee_mall_goods_category
        <where>
            <if test="params.categoryLevel!=null and params.categoryLevel!=''">
                and category_level = #{params.categoryLevel}
            </if>
            <if test="params.parentId!=null and params.parentId!=''">
                and parent_id = #{params.parentId}
            </if>
            and is_deleted = 0
        </where>
    </select>
</mapper>

Cargo.toml:

[package]
name = "back-end"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = { version = "0.12", features = ["full"] }
salvo_core = "0.12.1"
tokio = { version = "1.5", features = ["full"] }


tracing = "0.1"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"

# add this library,and cargo install

# json (required)
serde = { version = "1" }
serde_json = "1"
serde_derive = "1"

# Date time (required)
chrono = { version = "0.4.19"}

# logging lib(required)
log = "0.4"
fast_log="1.3"

# BigDecimal lib(optional)
bigdecimal = "0.2"

# rbatis lib(required)
rbatis =  { version = "=2.0.30" }

lazy_static ="1.4.0"

jsonwebtoken = "7"

toml = "0.5.6"
datetime = "0.4.7"
async-trait = "*"
[profile.release]
lto = true
opt-level = 'z'

**Comment by zhuxiujia** [comment]
```html
<select id="findGoodsCategoryList">
        select
        category_id, category_level, parent_id, category_name, category_rank, is_deleted,
        create_time, create_user, update_time, update_user
        from tb_newbee_mall_goods_categoryƒ
        <where>
            <if test="params.categoryLevel!=null && params.categoryLevel!=''">
                and category_level = #{params.categoryLevel}
            </if>
            <if test="parentId!=null && parentId!=''">
                and parent_id = #{params.parentId}
            </if>
            and is_deleted = 0
        </where>
        order by category_rank desc
        <if test="params.start!=null && params.limit!=null">
            limit #{params.start},#{params.limit}
        </if>
    </select>
```
注意看，```params.categoryLevel!=null && params.categoryLevel!='' ``` 而不是 ``` and ```
你从mybatis的xml搬过来的时候，要把mybatis 的  and 符合 改成 && 符号

**Comment by zhuxiujia** [comment]
另外一点就是，阅读rust的编译错误应该自上而下读，而不是自下而上读（会迷惑）

如果你是自上而下读错误的话，会看到
```rust
error: custom attribute panicked
  --> example/src/html_sql_test.rs:13:5
   |
13 |     #[html_sql(rb, "example/example.html")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: [rexpr]syn::parse_str: params.categoryLevel!=null and params.categoryLevel!="" fail for: unexpected token
   = note: this error originates in the attribute macro `html_sql` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by awol2010ex** [comment]
发现另外一个问题，如果sql如下
'''
 <select id="findGoodsCategoryList" >
        
        select
		
        category_id, category_level, parent_id, category_name, category_rank, is_deleted, 
    create_time, create_user, update_time, update_user
	
        from tb_newbee_mall_goods_category
        <where>
            <if test="params.categoryLevel!=null && params.categoryLevel!=''">
                and category_level = #{params.categoryLevel}
            </if>
            <if test="parentId!=null && parentId!=''">
                and parent_id = #{params.parentId}
            </if>
            and is_deleted = 0
        </where>
            order by category_rank desc
        <if test="params.start!=null && params.limit!=null">
            limit #{params.start},#{params.limit}
        </if>
    </select>
'''
生成的sql如下

Sep 18 15:34:20.208  INFO rbatis::plugin::log: [rbatis] [] ReturnRows <== 1
Sep 18 15:34:20.460  INFO rbatis::plugin::log: [rbatis] [] Fetch  ==> select

        category_id, category_level, parent_id, category_name, category_rank, is_deleted,
    create_time, create_user, update_time, update_user

        from tb_newbee_mall_goods_category where is_deleted = 0order by category_rank desc
                                                                [rbatis] [] Args   ==> []
Sep 18 15:34:20.466 ERROR rbatis::plugin::log: [rbatis] [] ReturnErr  <== error returned from database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'by category_rank desc' at line 2


where部分 没有参数就会消除中间的所有空格导致  “ from tb_newbee_mall_goods_category where is_deleted = 0order by category_rank desc” 这样的情况

**Comment by zhuxiujia** [comment]
> 发现另外一个问题，如果sql如下
> 
> ```
>  <select id="findGoodsCategoryList" >
>         
>         select
> 		
>         category_id, category_level, parent_id, category_name, category_rank, is_deleted, 
>     create_time, create_user, update_time, update_user
> 	
>         from tb_newbee_mall_goods_category
>         <where>
>             <if test="params.categoryLevel!=null && params.categoryLevel!=''">
>                 and category_level = #{params.categoryLevel}
>             </if>
>             <if test="parentId!=null && parentId!=''">
>                 and parent_id = #{params.parentId}
>             </if>
>             and is_deleted = 0
>         </where>
>             order by category_rank desc
>         <if test="params.start!=null && params.limit!=null">
>             limit #{params.start},#{params.limit}
>         </if>
>     </select>
> ```
> 
> 生成的sql如下
> 
> Sep 18 15:34:20.208 INFO rbatis::plugin::log: [rbatis] [] ReturnRows <== 1
> Sep 18 15:34:20.460 INFO rbatis::plugin::log: [rbatis] [] Fetch ==> select
> 
> ```
>     category_id, category_level, parent_id, category_name, category_rank, is_deleted,
> create_time, create_user, update_time, update_user
> 
>     from tb_newbee_mall_goods_category where is_deleted = 0order by category_rank desc
>                                                             [rbatis] [] Args   ==> []
> ```
> 
> Sep 18 15:34:20.466 ERROR rbatis::plugin::log: [rbatis] [] ReturnErr <== error returned from database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'by category_rank desc' at line 2
> 
> where部分 没有参数就会消除中间的所有空格导致 “ from tb_newbee_mall_goods_category where is_deleted = 0order by category_rank desc” 这样的情况

html特性导致的。html会删除收尾空格，你可以使用${" "} 插入空格

**Comment by awol2010ex** [comment]
好的ok
