### ISSUE TITLE
ORM是否有防止SQL注入😀?

### ISSUE THREAD

**Issue by swdcgghxa** [rbatis/rbatis#147]
ORM是否有防止SQL注入😀?

我是否需要担心Sql注入的问题？

还有什么我应该注意而文档没有提到的事项？ 我想吧这个项目拿来当做我小项目的async orm

**Comment by zhuxiujia** [comment]
CRUD方法 不存在注入。因为使用Stmt 数据库内置的sql预编译。
py_sql/html_sql 使用#{} 标记变量也没用注入。除非使用${}替换命令则有可能注入（变量是字符串。数值类型不存在注入）
因此，只要注意细节，放心用

**Comment by swdcgghxa** [comment]
我可以粗略的理解为，我避免使用${} 就可以安全的在rbatis 使用ORM 并同时防止Sql 注入吗？

比较复杂的查询可以用py_sql然后py_sql语法也有防止Sql注入。

**Comment by zhuxiujia** [comment]
> 我可以粗略的理解为，我避免使用${} 就可以安全的在rbatis 使用ORM 并同时防止Sql 注入吗？
> 
> 比较复杂的查询可以用py_sql然后py_sql语法也有防止Sql注入。

非常正确

**Comment by swdcgghxa** [comment]
谢谢你喔，在Rust 还有异步的ORM可用。
😀😀😀
