### ISSUE TITLE
How to create database for sqlite?

### ISSUE THREAD

**Issue by conanchen** [rbatis/rbatis#149]
does rbatis has similari functions as sqlx?

``` 
      if !Db::database_exists(DB_URL).await.unwrap_or(false) {
        Db::create_database(DB_URL).await?;
      }
```

**Comment by zhuxiujia** [comment]
let f=std::fs::File::create("test.db").unwrap();
    let pool = Rbatis::new("sqlite://test.db").await?;
    let mut conn = pool.acquire().await?;  
    conn.exec("create table xxx").await;....

**Comment by Zerounary** [comment]
you can use the db url like this , `sqlite:./test.db?mode=rwc`，without anyother codes.
