### ISSUE TITLE
Sqlite 报错 ColumnNotFound("0")

### ISSUE THREAD

**Issue by ggggxiaolong** [rbatis/rbatis#15]
```rust
panicked at 'called `Result::unwrap()` on an `Err` value: ColumnNotFound("0")', /home/mrtan/.cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-core-1.5.2/src/sqlite/cursor.rs:78:83
```
#### 下面是debug的跟踪数据， 应该是row的key不能直接是"0,1,2.."

![image](https://user-images.githubusercontent.com/10071089/93299949-827f9100-f828-11ea-9071-b4bf94a460e2.png)

![image](https://user-images.githubusercontent.com/10071089/93300891-37ff1400-f82a-11ea-8605-75a2cf49c9e9.png)

![image](https://user-images.githubusercontent.com/10071089/93300678-d343b980-f829-11ea-8a85-023879e862e0.png)

![image](https://user-images.githubusercontent.com/10071089/93300418-4d277300-f829-11ea-9136-37fc12ac3f41.png)

![image](https://user-images.githubusercontent.com/10071089/93300513-819b2f00-f829-11ea-9248-74249d2c8ba0.png)

**Comment by zhuxiujia** [comment]
> row的key

row的数据里面似乎只有values 也就是 usize.估计搞错了，不知道它的column数据在哪...

**Comment by ggggxiaolong** [comment]
我有一个大胆的想法
![image](https://user-images.githubusercontent.com/10071089/93306829-f32bab00-f832-11ea-8b43-f5533f65b630.png)

**Comment by ggggxiaolong** [comment]
或者 我看row 里面 statement 里面有一个方法 column_name
![image](https://user-images.githubusercontent.com/10071089/93307066-2cfcb180-f833-11ea-9b99-aa4688fc14f5.png)

**Comment by zhuxiujia** [comment]
> 或者 我看row 里面 statement 里面有一个方法 column_name
> ![image](https://user-images.githubusercontent.com/10071089/93307066-2cfcb180-f833-11ea-9b99-aa4688fc14f5.png)

估计就是这个，先拿到vlaues的usize大小，然后for循环逐个通过这个方法获取 column name，然后应该就可以取value了

**Comment by ggggxiaolong** [comment]
还有一个问题:  数据库貌似没有正常关闭，跑完单元测试数据库的生成的两个文件没有删

![image](https://user-images.githubusercontent.com/10071089/93315612-d3e64b00-f83d-11ea-9669-4f67acd2db60.png)

**Comment by zhuxiujia** [comment]
> 还有一个问题: 数据库貌似没有正常关闭，跑完单元测试数据库的生成的两个文件没有删
> 
> ![image](https://user-images.githubusercontent.com/10071089/93315612-d3e64b00-f83d-11ea-9669-4f67acd2db60.png)

这2个文件不删有问题吗？
