### ISSUE TITLE
How to use postgresl jsonb type

### ISSUE THREAD

**Issue by foxzool** [rbatis/rbatis#152]
db design
```
CREATE TABLE IF NOT EXISTS categories
(
    id              UUID      DEFAULT uuid_generate_v4(),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uuid            VARCHAR NOT NULL UNIQUE,
    name            VARCHAR NOT NULL,
    default_setting jsonb   NOT NULL,
    PRIMARY KEY (id)
);
```

model
```
#[crud_table(table_name:categories| formats_pg: "id:{}::uuid,created_at:{}::timestamp,updated_at:{}::timestamp,default_setting:{}::jsonb")]
#[derive(Debug, Default, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Category {
    pub id: Option<Uuid>,
    pub created_at: Option<DateTimeNative>,
    pub updated_at: Option<DateTimeNative>,
    pub uuid: String,
    pub name: String,
    pub default_setting: Option<String>,
}
```
run save 

```
 let category = Category {
            uuid: input.uuid,
            name: input.name,
            default_setting: Some(input.default_setting.to_string()),
            ..Default::default()
        };
        DB.save(
            &category,
            &[
                Skip::Column("id"),
                Skip::Column("created_at"),
                Skip::Column("updated_at"),
            ],
        )
        .await?;
```

and got
```
2021-11-03 12:19:47.140014700 UTC    INFO rbatis::plugin::log - [rbatis] [] Exec   ==> insert into categories (uuid,name,default_setting) values ($1,$2,$3::jsonb)
                                                                [rbatis] [] Args   ==> ["234", "34636", null]

2021-11-03 12:19:47.155176800 UTC    ERROR rbatis::plugin::log - [rbatis] [] ReturnErr  <== error returned from database: 无法把类型 integer 转换为 jsonb  (D:\rustup\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rbatis-3.0.1\src\plugin\log.rs:43)
```

**Comment by zhuxiujia** [comment]
for  rbatis version 3.0
use  rbatis：Json<*>  and  rbatis：：DateTimeNative   replace  this

**Comment by foxzool** [comment]
> for rbatis version 3.0 use rbatis：：Json<*> and rbatis：：DateTimeNative replace this。
> 
> so you dont need use format pg sql

had change type for rbatis::Json
```
 pub default_setting: Option<Json<serde_json::Value>>,
```

but not work , same error

**Comment by zhuxiujia** [comment]
* code
```rust
 #[tokio::test]
    pub async fn test_save() {
        fast_log::init_log("requests.log", 1000, log::Level::Info, None, true);
        let rb = Rbatis::new();
        rb.link("postgres://postgres:123456@localhost:5432/postgres").await.unwrap();
        #[crud_table]
        #[derive(Clone, Debug)]
        pub struct BizActivity {
            pub id: Option<rbatis::Uuid>,
            pub name: Option<String>,
            pub create_time: Option<DateTimeNative>,
            pub js: Option<rbatis::Json<i32>>,
        }
        rb.save(&BizActivity{
            id: Some(rbatis::Uuid::new()),
            name: Some("what".to_string()),
            create_time: Some(DateTimeNative::now()),
            js: Some(rbatis::Json::from(serde_json::json!(1)))
        },&[]).await.unwrap();
    }

```
* result log
```log
2021-11-03 13:48:41.777306 UTC       INFO rbatis::plugin::log - [rbatis] [] Exec   ==> insert into biz_activity (id,name,create_time,js) values ($1,$2,$3,$4)
                                                                [rbatis] [] Args   ==> [Binary(0x4, ZmYxZWNjNTQtZGRlNi00NDFjLWIyZGEtNjY4ZTU1MzFhNzJh), "what", DateTime("2021-11-03 05:48:41.774 UTC"), Binary(0x90, MQ==)]
2021-11-03 13:48:41.783940 UTC       INFO rbatis::plugin::log - [rbatis] [] RowsAffected <== 1
```

**Comment by foxzool** [comment]
> did you delete `#[crud_table( formats_pg:"*****" )]` ?
> 
> this is my success code
> 
> * table
> 
> ```sql
> create table biz_activity
> (
>     id   uuid not null constraint biz_activity_pk primary key,
>     name        varchar,
>     create_time timestamp,
>     js          jsonb
> );
> ```
> 
> * code
> 
> ```rust
>  #[tokio::test]
>     pub async fn test_save() {
>         fast_log::init_log("requests.log", 1000, log::Level::Info, None, true);
>         let rb = Rbatis::new();
>         rb.link("postgres://postgres:123456@localhost:5432/postgres").await.unwrap();
>         #[crud_table]
>         #[derive(Clone, Debug)]
>         pub struct BizActivity {
>             pub id: Option<rbatis::Uuid>,
>             pub name: Option<String>,
>             pub create_time: Option<DateTimeNative>,
>             pub js: Option<rbatis::Json<i32>>,
>         }
>         rb.save(&BizActivity{
>             id: Some(rbatis::Uuid::new()),
>             name: Some("what".to_string()),
>             create_time: Some(DateTimeNative::now()),
>             js: Some(rbatis::Json::from(serde_json::json!(1)))
>         },&[]).await.unwrap();
>     }
> ```
> 
> * result log
> 
> ```
> 2021-11-03 13:48:41.777306 UTC       INFO rbatis::plugin::log - [rbatis] [] Exec   ==> insert into biz_activity (id,name,create_time,js) values ($1,$2,$3,$4)
>                                                                 [rbatis] [] Args   ==> [Binary(0x4, ZmYxZWNjNTQtZGRlNi00NDFjLWIyZGEtNjY4ZTU1MzFhNzJh), "what", DateTime("2021-11-03 05:48:41.774 UTC"), Binary(0x90, MQ==)]
> 2021-11-03 13:48:41.783940 UTC       INFO rbatis::plugin::log - [rbatis] [] RowsAffected <== 1
> ```

yes, i had removed formats_pg

my purpose to store complex js object  to column,    so my column type is Option<rbatis::Json<serde_json::value>>, but it fails when save

**Comment by zhuxiujia** [comment]
> > did you delete `#[crud_table( formats_pg:"*****" )]` ?
> > this is my success code
> > 
> > * table
> > 
> > ```sql
> > create table biz_activity
> > (
> >     id   uuid not null constraint biz_activity_pk primary key,
> >     name        varchar,
> >     create_time timestamp,
> >     js          jsonb
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * code
> > 
> > ```rust
> >  #[tokio::test]
> >     pub async fn test_save() {
> >         fast_log::init_log("requests.log", 1000, log::Level::Info, None, true);
> >         let rb = Rbatis::new();
> >         rb.link("postgres://postgres:123456@localhost:5432/postgres").await.unwrap();
> >         #[crud_table]
> >         #[derive(Clone, Debug)]
> >         pub struct BizActivity {
> >             pub id: Option<rbatis::Uuid>,
> >             pub name: Option<String>,
> >             pub create_time: Option<DateTimeNative>,
> >             pub js: Option<rbatis::Json<i32>>,
> >         }
> >         rb.save(&BizActivity{
> >             id: Some(rbatis::Uuid::new()),
> >             name: Some("what".to_string()),
> >             create_time: Some(DateTimeNative::now()),
> >             js: Some(rbatis::Json::from(serde_json::json!(1)))
> >         },&[]).await.unwrap();
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * result log
> > 
> > ```
> > 2021-11-03 13:48:41.777306 UTC       INFO rbatis::plugin::log - [rbatis] [] Exec   ==> insert into biz_activity (id,name,create_time,js) values ($1,$2,$3,$4)
> >                                                                 [rbatis] [] Args   ==> [Binary(0x4, ZmYxZWNjNTQtZGRlNi00NDFjLWIyZGEtNjY4ZTU1MzFhNzJh), "what", DateTime("2021-11-03 05:48:41.774 UTC"), Binary(0x90, MQ==)]
> > 2021-11-03 13:48:41.783940 UTC       INFO rbatis::plugin::log - [rbatis] [] RowsAffected <== 1
> > ```
> 
> yes, i had removed formats_pg
> 
> my purpose to store complex js object to column, so my column type is Option<rbatis::Json<serde_json::value>>, but it fails when save

whait error?

**Comment by foxzool** [comment]
This code works well
```
#[tokio::test]
    pub async fn test_save() {
        fast_log::init_log("../../tmp/requests.log", 1000, log::Level::Info, None, true).unwrap();
        let rb = Rbatis::new();
        rb.link("postgres://postgres:postgres@localhost:5432/postgres")
            .await
            .unwrap();
        #[crud_table(table_name:biz_activity)]
        #[derive(Clone, Debug)]
        pub struct BizActivity {
            pub id: Option<rbatis::Uuid>,
            pub name: Option<String>,
            pub create_time: Option<DateTimeNative>,
            pub js: Option<rbatis::Json<serde_json::Value>>,
        }

        #[derive(Serialize, Deserialize, Debug)]
        pub struct JsObject {
            pub name: String,
        }

        let js_obj = serde_json::to_value(JsObject {
            name: "js".to_string(),
        })
        .unwrap();

        rb.save(
            &BizActivity {
                id: Some(rbatis::Uuid::new()),
                name: Some("what".to_string()),
                create_time: Some(DateTimeNative::now()),
                js: Some(rbatis::Json::from(js_obj)),
            },
            &[],
        )
        .await
        .unwrap();
    }
```

but when i add serde setting `rename_all `
```
  #[crud_table(table_name:biz_activity)]
        #[derive(Clone, Debug)]
        #[serde(rename_all = "camelCase")]
        pub struct BizActivity {
        pub id: Option<rbatis::Uuid>,
        pub name: Option<String>,
        pub create_time: Option<DateTimeNative>,
        pub js: Option<rbatis::Json<serde_json::Value>>,
        }
```
test fails 
```
2021-11-03 17:04:54.967209100 UTC    INFO rbatis::plugin::log - [rbatis] [] Exec   ==> insert into biz_activity (id,name,create_time,js) values ($1,$2,$3,$4)
                                                                [rbatis] [] Args   ==> [Binary(0x4, NjUxMDU4MzUtYThlZS00NjA0LWFlODctZWE3MjYxMWYxNDll), "what", null, Binary(0x90, eyJuYW1lIjoianMifQ==)]
2021-11-03 17:04:54.982814100 UTC    ERROR rbatis::plugin::log - [rbatis] [] ReturnErr  <== error returned from database: 字段 "create_time" 的类型为 timestamp without time zone, 但表达式的类型为 integer  (D:\rustup\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rbatis-3.0.2\src\plugin\log.rs:43)
```

**Comment by foxzool** [comment]
> rename_all？ delete this code

I use this struct as async-graphql object  and want to return json key as  camelCase

**Comment by zhuxiujia** [comment]
> > rename_all？ delete this code
> 
> I use this struct as async-graphql object and want to return json key as camelCase

in rbatis , call save method will also call      crate::as_bson!(arg) to make an  Value Map.
if  macro  be    camelCase, the  value will  get an  Null Value!
so ,  My suggestion is that you use the new structure in your code and add camelCase
