### ISSUE TITLE
embedded enum field was not persisted on version 3.0 , but on version 2.1.8

### ISSUE THREAD

**Issue by conanchen** [rbatis/rbatis#155]
1. below X123.data field can be persisted on version 2.1.8 , but failed to persisted on version 3.0, looks like version 3.0 bson cause the problem. 
2. found the insert  log "Err(E("unsupported type!"))"
3. which config or derive I should use on version 3.0? 
```
#[rbatis::crud_table(table_name:"table_123")]
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct X123{
  pub id: String,
  pub data: Abc,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum Abc {
  A(AData),
  B(BData),
  C(CData),
}
```

**Comment by zhuxiujia** [comment]
> 1. below X123.data field can be persisted on version 2.1.8 , but failed to persisted on version 3.0, looks like version 3.0 bson cause the problem.
> 2. found the insert  log "Err(E("unsupported type!"))"
> 3. which config or derive I should use on version 3.0?
> 
> ```
> #[rbatis::crud_table(table_name:"table_123")]
> #[derive(Serialize, Deserialize, Clone, Debug)]
> pub struct X123{
>   pub id: String,
>   pub data: Abc,
> }
> 
> #[derive(Serialize, Deserialize, Clone, Debug)]
> pub enum Abc {
>   A(AData),
>   B(BData),
>   C(CData),
> }
> ```

Perhaps you could try rewriting the serialization interface and serializing to bson's string structure
