### ISSUE TITLE
crate `rbatis_macro_driver` is private

### ISSUE THREAD

**Issue by xiayulu** [rbatis/rbatis#156]
When I am trying to use `crud_table` like tihs:

```rust
use rbatis::crud::{CRUDMut, CRUD};
use rbatis::rbatis::Rbatis;
use rbatis::rbatis_macro_driver::crud_table;

#[crud_table]
#[derive(Clone, Debug)]
pub struct Users {
    pub user_id: Option<i32>,
    pub nickname: Option<String>,
    pub vavtar: Option<String>,
    pub reputation: Option<i32>,
}
```

I get the error : crate `rbatis_macro_driver` is private.

Can rabatis export macro as public?

Thanks for your Reply.

**Comment by zhuxiujia** [comment]
> ```rust
> use rbatis::rbatis_macro_driver::crud_table;
> ```

don't need ``` use rbatis::rbatis_macro_driver::crud_table; ```

just need ```  
#[macro_use]
extern crate rbatis;
 ```

**Comment by xiayulu** [comment]
It worked! 3Q
