### ISSUE TITLE
Postgres Timestamp Column format error

### ISSUE THREAD

**Issue by qinzhenren** [rbatis/rbatis#159]
struct里这样设置
    pub sign_up_at:Option<rbatis::Timestamp>
数据库里字段类型为Timestamp
查询时报错
expected character ` `, found `T`")',
换成rbatis::DateTimeNative可以正常取出，但是没有毫秒值。

**Comment by qinzhenren** [comment]
刚才试了下mysql也是同样的问题

**Comment by zhuxiujia** [comment]
timestamp 就是没有毫秒值的。

**Comment by qinzhenren** [comment]
@zhuxiujia 有没有其他办法取出表里的毫秒值。

**Comment by zhuxiujia** [comment]
> @zhuxiujia 有没有其他办法取出表里的毫秒值。

表里使用其他的类型，例如DateTime

**Comment by qinzhenren** [comment]
postgres里面没有datetime类型

**Comment by zhuxiujia** [comment]
用rbatis::DateTimeNative
