### ISSUE TITLE
如何只修改某个字段对应的表字段

### ISSUE THREAD

**Issue by songxuexian** [rbatis/rbatis#160]
```
#[derive(Clone, Debug,Deserialize,Serialize)]
struct User{
    id:Option<i32>,
    user_name:Option<String>,
    password:Option<String>,
    user_type:Option<String>,
}
```
由于type是保留字段，这里改成user_type，但是数据库表中的这一列是type，有办法解决？
thks

**Comment by zhuxiujia** [comment]
> ```
> #[derive(Clone, Debug,Deserialize,Serialize)]
> struct User{
>     id:Option<i32>,
>     user_name:Option<String>,
>     password:Option<String>,
>     user_type:Option<String>,
> }
> ```
> 
> 由于type是保留字段，这里改成user_type，但是数据库表中的这一列是type，有办法解决？ thks

改成 r#type:Option<String>
