### ISSUE TITLE
How do I return a Uuid based id after inserting (PostgreSQL)?

### ISSUE THREAD

**Issue by c9d5e1** [rbatis/rbatis#163]
How do I return a Uuid based id after using the save method on Rbatis?

**Comment by zhuxiujia** [comment]
> 

The save method does not support pg to return id, you need to query again, or use Py_SQL/html_SQL

**Comment by zhuxiujia** [comment]
see https://github.com/rbatis/rbatis/blob/master/example/src/crud.rs

save_by_wrapper
