### ISSUE TITLE
是否能兼容 sql 语句的大小写

### ISSUE THREAD

**Issue by nicky-cage** [rbatis/rbatis#168]
```rust
rb.fetch_page::<User>("select * from users", args_null, &pr).await
```

这个地方的 select 和 from 等关键字 ,必须用小写啊, 大写会提示出错: 
"[rbatis] make_page_sql() sql must contains 'select ' And ' from '",

**Comment by zhuxiujia** [comment]
> ```rust
> rb.fetch_page::<User>("select * from users", args_null, &pr).await
> ```
> 
> 这个地方的 select 和 from 等关键字 ,必须用小写啊, 大写会提示出错: "[rbatis] make_page_sql() sql must contains 'select ' And ' from '",

默认小写，启用upper_case_sql_keyword 特性即为大写
