### ISSUE TITLE
load_xml里的if xx != null应该兼容none

### ISSUE THREAD

**Issue by Silentdoer** [rbatis/rbatis#17]
毕竟在rust里没有null而是none，即if xx != none 也是可以的

**Comment by zhuxiujia** [comment]
在Rbatis的表达式引擎中结构体最终会映射为serde_json支持的json结构，因此在内部处理是按null处理的。但是考虑到外部会传None或者在表达式写None的话，引擎默认会把表达式 None 替换为 null
