### ISSUE TITLE
支持order by  fielda asc, fieldb desc 混合升降序

### ISSUE THREAD

**Issue by conanchen** [rbatis/rbatis#170]
如何写支持asc、desc混合排序?

    rb.fetch_list_by_wrapper(wrapper.order_by(false, &["filelda"]).order_by(true, &["fileldb"]))
生成的sql不对：

order by filelda desc order by fileldb asc

**Comment by zhuxiujia** [comment]
> 如何写支持asc、desc混合排序?
> 
> ```
> rb.fetch_list_by_wrapper(wrapper.order_by(false, &["filelda"]).order_by(true, &["fileldb"]))
> ```
> 
> 生成的sql不对：
> 
> order by filelda desc order by fileldb asc

 这确是是一个问题，下个版本优化

**Comment by zhuxiujia** [comment]
> 如何写支持asc、desc混合排序?
> 
> ```
> rb.fetch_list_by_wrapper(wrapper.order_by(false, &["filelda"]).order_by(true, &["fileldb"]))
> ```
> 
> 生成的sql不对：
> 
> order by filelda desc order by fileldb asc

更新最新版本后，可以使用 ``` order_bys```方法
