### ISSUE TITLE
error[E0463]: can't find crate for `rbatis_macro_driver`

### ISSUE THREAD

**Issue by Ilqjx** [rbatis/rbatis#174]
I got this error when compiling.

Cargo.toml
rbatis = { version = "3.0", default-features = false, futures = ["postgres", "runtime-tokio-rustls"] }

```
error[E0463]: can't find crate for `rbatis_macro_driver`
 --> /Users/guozhenwei/.cargo/registry/src/crates-mirror.qianxin-inc.cn-204ae133821e0d2d/rbatis-3.0.30/src/lib.rs:9:1
  |
9 | extern crate rbatis_macro_driver;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by zhuxiujia** [comment]
> I got this error when compiling.
> 
> Cargo.toml rbatis = { version = "3.0", default-features = false, futures = ["postgres", "runtime-tokio-rustls"] }
> 
> ```
> error[E0463]: can't find crate for `rbatis_macro_driver`
>  --> /Users/guozhenwei/.cargo/registry/src/crates-mirror.qianxin-inc.cn-204ae133821e0d2d/rbatis-3.0.30/src/lib.rs:9:1
>   |
> 9 | extern crate rbatis_macro_driver;
>   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
> ```

add  toml
```
rbatis = { version = "3.0", default-features = false, futures = ["postgres", "runtime-tokio-rustls","rbatis-macro-driver"] }
```

**Comment by Ilqjx** [comment]
Thank you very much for your reply.

**Comment by Ilqjx** [comment]
Sorry, this still fails.
```
error[E0463]: can't find crate for `rbatis_macro_driver`
 --> /Users/guozhenwei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/rbatis-3.0.30/src/lib.rs:9:1
  |
9 | extern crate rbatis_macro_driver;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `rbatis` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```
