### ISSUE TITLE
怎样才能真正的动态表名

### ISSUE THREAD

**Issue by simon-fu** [rbatis/rbatis#182]
例子里的动态表名不是真的动态，表名是常量。
这样写的动态表名编译不通过，请教怎么写才能通过呢

let mut w = rb.new_wrapper();
let table_name = "table_001";
let f = |s: &str| table_name.to_string();
w.formats.insert("table_name".to_string(), f);

**Comment by zhuxiujia** [comment]
> 例子里的动态表名不是真的动态，表名是常量。 这样写的动态表名编译不通过，请教怎么写才能通过呢
> 
> let mut w = rb.new_wrapper(); let table_name = "table_001"; let f = |s: &str| table_name.to_string(); w.formats.insert("table_name".to_string(), f);

是的，只有函数才能做到动态

**Comment by zhuxiujia** [comment]
v3.1版本支持 传入 string了
```rust
w.formats.insert("table_name".to_string(), “table_{}”.to_string());
```
或者
```
w.formats.insert("table_name".to_string(), “xxxx”.to_string());
```
