### ISSUE TITLE
DateTimeNative 类型序列化输出自定义格式

### ISSUE THREAD

**Issue by strive1216** [rbatis/rbatis#183]
``` 
pub struct AppInfo {
         created_at: Option<rbatis::DateTimeNative>,
}
```
需要把字段序列化:日期时间格式为 rfc339格式(%Y-%m-%dT%H:%M:%S%z), 
chrono::NaiveDateTime::parse_from_str()

**Comment by zhuxiujia** [comment]
> ```
> pub struct AppInfo {
>          created_at: Option<rbatis::DateTimeNative>,
> }
> ```
> 
> 需要把字段序列化:日期时间格式为 rfc339格式(%Y-%m-%dT%H:%M:%S%z), chrono::NaiveDateTime::parse_from_str()

目前推荐数据表结构体和返回给前端的结构体 独立开来，并使用Form接口转换。转换过程你可以使用各种格式化
