### ISSUE TITLE
formats_pg 和 formats_postgres 宏存在严重bug 写入了两次 方法名

### ISSUE THREAD

**Issue by zsl99a** [rbatis/rbatis#184]
影响版本 3.x
错误示例
values ($1,$2,$3,$4,$5,$6,{}::timestampz::timestampz)

**Comment by zhuxiujia** [comment]
> 影响版本 3.x 错误示例 values ($1,$2,$3,$4,$5,$6,{}::timestampz::timestampz)

嗯，下个版本将修复
