### ISSUE TITLE
Using the trim tag does not remove redundant commas

### ISSUE THREAD

**Issue by wangwencheng2020** [rbatis/rbatis#193]
When I used the trim tag to generate dynamic SQL scripts, I found that the generated SQL scripts did not execute properly.
This is the test SQL script.
```
  <insert id="insert_test">
    insert into biz_activity(
      <trim suffixOverrides=",">
        <if test="activity.id != None">id,</if>
        <if test="activity.name != None">name,</if>
        <if test="activity.status != None">status,</if>
      </trim>
    )values(
      <trim suffixOverrides=",">
        <if test="activity.id != None">#{activity.id},</if>
        <if test="activity.name != None">#{activity.name},</if>
        <if test="activity.status != None">#{activity.status},</if>
      </trim>
    )
  </insert>
```
This is a dynamically generated SQL script.
```
[rbatis] Fetch  ==> insert into biz_activity( id,  name, )values( $1,  $2, )
  
[rbatis] Args   ==> ["44554646", "activity002"]
```
This is an error message.
```
ERROR rbatis::plugin::log - [rbatis]  ReturnErr  <== error returned from database: syntax error at or near ")"
ERROR common::result - error returned from database: syntax error at or near ")"
```
Rbatis version is 3.1.6.
The trim tag is used to save or update only fields whose values are not None so that database-defined defaults can be used.
Of course, this feature could be added to the CRUD function, even better.

**Comment by wangwencheng2020** [comment]
rbatis version 3.1.6

**Comment by zhuxiujia** [comment]
> When I used the trim tag to generate dynamic SQL scripts, I found that the generated SQL scripts did not execute properly. This is the test SQL script.
> 
> ```
>   <insert id="insert_test">
>     insert into biz_activity(
>       <trim suffixOverrides=",">
>         <if test="activity.id != None">id,</if>
>         <if test="activity.name != None">name,</if>
>         <if test="activity.status != None">status,</if>
>       </trim>
>     )values(
>       <trim suffixOverrides=",">
>         <if test="activity.id != None">#{activity.id},</if>
>         <if test="activity.name != None">#{activity.name},</if>
>         <if test="activity.status != None">#{activity.status},</if>
>       </trim>
>     )
>   </insert>
> ```
> 
> This is a dynamically generated SQL script.
> 
> ```
> [rbatis] Fetch  ==> insert into biz_activity( id,  name, )values( $1,  $2, )
>   
> [rbatis] Args   ==> ["44554646", "activity002"]
> ```
> 
> This is an error message.
> 
> ```
> ERROR rbatis::plugin::log - [rbatis]  ReturnErr  <== error returned from database: syntax error at or near ")"
> ERROR common::result - error returned from database: syntax error at or near ")"
> ```
> 
> Rbatis version is 3.1.6. The trim tag is used to save or update only fields whose values are not None so that database-defined defaults can be used. Of course, this feature could be added to the CRUD function, even better.

you can run command ``` cargo update ```
up dep crates version to fix this bug.
