### ISSUE TITLE
compile_error

### ISSUE THREAD

**Issue by ptechen** [rbatis/rbatis#194]
compile_error!(
"only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
 'runtime-tokio-rustls'] can be enabled"
);

**Comment by zhuxiujia** [comment]
> compile_error!( "only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] can be enabled" );

Only one runtime can be enabled
