### ISSUE TITLE
Mssql/Sqlserver - sqlx-core does not support TLS

### ISSUE THREAD

**Issue by colathro** [rbatis/rbatis#198]
https://github.com/launchbadge/sqlx/issues/414

This should be documented in the readme next to "50%". All of the Mssql/Sqlserver cloud solutions require this even when traffic doesn't cross into any unsecured networking boundary.

**Comment by zhuxiujia** [comment]
> [launchbadge/sqlx#414](https://github.com/launchbadge/sqlx/issues/414)
> 
> This should be documented in the readme next to "50%". All of the Mssql/Sqlserver cloud solutions require this even when traffic doesn't cross into any unsecured networking boundary.


Details have been added to the readme file
