### ISSUE TITLE
不需要在 Mutex 里放 RefCell

### ISSUE THREAD

**Issue by Austaras** [rbatis/rbatis#2]
参见 trpl 第16章第3节

**Comment by zhuxiujia** [comment]
> 参见 trpl 第16章第3节

试了一下，是可以。感谢提醒

**Comment by Austaras** [comment]
看了新的[commit](https://github.com/rbatis/rbatis/blob/c0446f801b5c41bd0f1aa92b099c5a0ee82cb324/rbatis-core/src/sync_map.rs#L42), 也不需要再 borrow_mut
