### ISSUE TITLE
是否可以考虑支持通过宏生成类似Mybatis的@Query("select* ....)

### ISSUE THREAD

**Issue by Silentdoer** [rbatis/rbatis#20]
比如:
#[query(sql="select* from xxx where name = $1")]
Option<Vec<Xxx>> selectXxxByName(name: String) {None}

然后宏会改造这个函数为类似：
Option<Vec<Xxx>> selectXxxByName(name:String, pool:Rbatis) {
Some(pool.select(....))
}

**Comment by zhuxiujia** [comment]
> 比如:
> #[query(sql="select* from xxx where name = $1")]
> Option<Vec> selectXxxByName(name: String) {None}
> 
> 然后宏会改造这个函数为类似：
> Option<Vec> selectXxxByName(name:String, pool:Rbatis) {
> Some(pool.select(....))
> }

好主意，理论上是可以的，估计需要指定Rbatis地址，例如#[query(sql="select* from xxx where name = $1"，rbatis=RB)]

**Comment by zhuxiujia** [comment]
1.5.6版本，现已支持

**Comment by Silentdoer** [comment]
看了下实现，会自动封装返回值为Result，那如果查询单条数据没有找到的话是返回Err吗？Err里是否有获取数据失败的详情呢？还有就是目前的是要求显式给出RB的当前可用路径（对象路径），也就是限制死了一个mapper方法只能是针对一个pool，但是有这样的情况，有的时候一个mapper可能打到a库，有的时候打到b库去操作（比如读写分离），是不是应该提供一个不需要显示提供RB，然后需要参数里提供的宏？

**Comment by zhuxiujia** [comment]
> 看了下实现，会自动封装返回值为Result，那如果查询单条数据没有找到的话是返回Err吗？Err里是否有获取数据失败的详情呢？还有就是目前的是要求显式给出RB的当前可用路径（对象路径），也就是限制死了一个mapper方法只能是针对一个pool，但是有这样的情况，有的时候一个mapper可能打到a库，有的时候打到b库去操作（比如读写分离），是不是应该提供一个不需要显示提供RB，然后需要参数里提供的宏？

首先必须返回Error，比如数据库长连接断线，数据库sql执行异常。至于返回None数据你可以定义返回结构为 Option<Model>这样的类型。返回的结果只有满足能被serde_json序列化 几乎所有数据都可以返回。

**Comment by zhuxiujia** [comment]
> 看了下实现，会自动封装返回值为Result，那如果查询单条数据没有找到的话是返回Err吗？Err里是否有获取数据失败的详情呢？还有就是目前的是要求显式给出RB的当前可用路径（对象路径），也就是限制死了一个mapper方法只能是针对一个pool，但是有这样的情况，有的时候一个mapper可能打到a库，有的时候打到b库去操作（比如读写分离），是不是应该提供一个不需要显示提供RB，然后需要参数里提供的宏？

读写分离的问题，为什么不写一个代理RB的方法，在代理方法内实现路由选择数据库的逻辑呢？

**Comment by zhuxiujia** [comment]
1.5.7 新增了py_sql() 宏，可以在sql表达式内部加入 if  for_each等等动态sql判断
```rust
    #[py_sql(RB, "select * from biz_activity where id = #{name}
                  if name != '':
                    and name=#{name}")]
    fn py_select(name: &str) -> Option<BizActivity> {}
```

**Comment by Silentdoer** [comment]
那比如有这种情况，我一个服务需要定时同步其他库的数据到自己库里，所以一个select语句需要能支持两个数据源，这种用目前的方式就不好弄吧，除非一个SQL方法些两次，而且actix里支持将局部的pool放到app_data里，不需要弄成全局的lazy_static

**Comment by zhuxiujia** [comment]
> 那比如有这种情况，我一个服务需要定时同步其他库的数据到自己库里，所以一个select语句需要能支持两个数据源，这种用目前的方式就不好弄吧，除非一个SQL方法些两次，而且actix里支持将局部的pool放到app_data里，不需要弄成全局的lazy_static

上个示例的代码看看

**Comment by zhuxiujia** [comment]
> 那比如有这种情况，我一个服务需要定时同步其他库的数据到自己库里，所以一个select语句需要能支持两个数据源，这种用目前的方式就不好弄吧，除非一个SQL方法些两次，而且actix里支持将局部的pool放到app_data里，不需要弄成全局的lazy_static

actix的pool 看起来和全局的pool没什么区别吧，它是用Arc来克隆访问原始对象的，估计也用到了锁之类的，和全局访问链接池没区别。
而且 r2d2连接池还是同步链接的，没有用到async await异步的形式。
Rbatis内部已经解决了 多线程竞争问题，内部的Context为DashMap类型(内部是读写锁实现 读多写少)

**Comment by zhuxiujia** [comment]
> 那比如有这种情况，我一个服务需要定时同步其他库的数据到自己库里，所以一个select语句需要能支持两个数据源，这种用目前的方式就不好弄吧，除非一个SQL方法些两次，而且actix里支持将局部的pool放到app_data里，不需要弄成全局的lazy_static


新版即将实现 传入Rbatis全局引用和Rbatis参数引用（应该能满足你的读写分离要求，分库分表（sql拦截器））
例如:
```rust
   /// 使用参数变量例子(rbatis 名称必须和参数里的rbatis名称一样)
    #[py_sql(rbatis, "select * from biz_activity where id = #{name}
                  if name != '':
                    and name=#{name}")]
    fn py_select(rbatis: &Rbatis, name: &str) -> Option<BizActivity> {}
```

**Comment by Silentdoer** [comment]
好的，多谢。

**Comment by Silentdoer** [comment]
问下只有py_sql能传参数吗？普通sql可以传吗？

**Comment by zhuxiujia** [comment]
> 问下只有py_sql能传参数吗？普通sql可以传吗？

普通sql可以，但是普通sql参数数量要和sql里面用到的？符号数量相等对齐（除&Rbatis引用 tx_id:&str 外）。
相对来说 py_sql 简单多的多，不需要使用？，而是使用#{} 或者${}对应即可，和mybatis用法类似

**Comment by Silentdoer** [comment]
不好意思我没表述清楚，我是指sql这个宏的方法是否也支持rbatis: &Rbatis外部传pool进去呢？

**Comment by zhuxiujia** [comment]
> 不好意思我没表述清楚，我是指sql这个宏的方法是否也支持rbatis: &Rbatis外部传pool进去呢？

你看我贴的代码，是的，能传Rbatis的引用，和事务id号tx_id

**Comment by Silentdoer** [comment]
好的，谢谢，框架很完美了😂

**Comment by zhuxiujia** [comment]
> 好的，谢谢，框架很完美了😂

我制作了rbatis专用的文档网站
https://rbatis.github.io/rbatis.io/#/

细节部分的语法表格大部分都列举了，希望能帮到你
