### ISSUE TITLE
print a lot of logs like comment:<select on build

### ISSUE THREAD

**Issue by liyunde** [rbatis/rbatis#202]
print a lot of logs like comment:<select on build message when use example.html and has comment
disturb view build information
rbatis:3.1.8,3.1.9
rust:1.58

example like:
Compiling rbatis v3.1.9
comment:<sql id="select_self">(id,name,age,tag)</sql>
comment:<select id="test_include">
comment:<include refid="select_self"></include>
comment:<include refid="page_sql?file=example/example_include.html"></include>
comment:</select>

**Comment by zhuxiujia** [comment]
fix in v3.1.10
