### ISSUE TITLE
html_sql 执行自定义脚本解析出错

### ISSUE THREAD

**Issue by wangwencheng2020** [rbatis/rbatis#203]
在使用html_sql执行自定义sql脚本的时候生成的脚本有问题
sql脚本：
```
<select id="html_sql_page">
    select * from biz_activity 
    <where>
      <if test="activity.id != None ">
        and id = #{activity.id}
      </if>
      <if test="activity.name != None ">
        and name like concat('%',#{activity.name},'%')
      </if>
    </where>
    order by create_time desc
</select>
```

报错信息：
[rbatis] Fetch  ==> select count(1) from  biz_activity where id = $1 and name like concat('%',$2,'%')order by create_time desc
[rbatis] Args   ==> ["12345", "activity001"]
[rbatis] ReturnErr  <== error returned from database: column "biz_activity.create_time" must appear in the GROUP BY clause or be used in an aggregate function

rbatis版本：
rbatis = {version = "3.1.10", default-features = false, features = ["runtime-tokio-rustls", "postgres", "debug_mode"]}

另外，项目中在查询数据的时候经常会出现根据参数是否有值来拼接where条件，但是rbatis::crud里面没有找到可以直接使用的函数。现在的做法是在html_sql 中 使用<where>+<if>标签的方式来实现的。所以希望可以在fetch_by_wrapper()中使用Skip来实现动态拼接where条件。

**Comment by zhuxiujia** [comment]
> 

#{activity.id} 是否应该改成 #{id}
另外   <if test="activity.name != None "> 改成    <if test="name != None ">
呢？

**Comment by wangwencheng2020** [comment]
这样报错是因为我加了分页，不加分页是正常的
```
#[html_sql("src/mapper/activity_mapper.html")]
pub async fn html_sql_page(
    rb: &mut RbatisExecutor<'_, '_>,
    page_req: &PageRequest,
    activity: &BizActivity,
) -> Page<BizActivity> { impled!() }
```
