### ISSUE TITLE
使用f32对表中的Decimal字段进行映射时出错

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#207]
提示错误信息：
ReturnErr  <== invalid type: string "0.00", expected f32 

如何可以进行处理？

**Comment by zhuxiujia** [comment]
> 提示错误信息： ReturnErr <== invalid type: string "0.00", expected f32
> 
> 如何可以进行处理？

是什么数据库？

**Comment by longzou** [comment]
这个是MySQL数据库。
1. 表的这个字段类型是Numeric的，验证后，表示必须使用rbatis::Decimal来进行映射。
2. 另外，Rbatis连接数据库有没有进行池化？我感觉是没有的，因为我的一个应该在测试的过程中，就出现了连接不够用了的问题。而且，我也不太清楚这个有没有进行有效关闭处理？

**Comment by MacJayLee** [comment]
> 



> 这个是MySQL数据库。
> 
> 1. 表的这个字段类型是Numeric的，验证后，表示必须使用rbatis::Decimal来进行映射。
> 
> 谢谢大大的回答。

但是这样处理的话 返回到前端就是字符串了 有没有办法直接返回小数类型的？
