### ISSUE TITLE
Update功能增强需求

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#208]
目前的Update操作都是根据表映射中的所有的字段来进行的，能否给出一个或多个方法来让可以有选择的更新某些列，而不是每次都全部更新，类似于MyBatis 的客户端代码 updateSeletive和 insertSeletive这样的功能。
这在许多场景还是有很有用处的。

**Comment by easykoala** [comment]
使用mapper xml或者pysql应该都可以的

**Comment by zhuxiujia** [comment]
> 目前的Update操作都是根据表映射中的所有的字段来进行的，能否给出一个或多个方法来让可以有选择的更新某些列，而不是每次都全部更新，类似于MyBatis 的客户端代码 updateSeletive和 insertSeletive这样的功能。 这在许多场景还是有很有用处的。

update可以使用参数 Skip::Value(Bson::Null) 跳过 空字段，或者指定的字段

**Comment by longzou** [comment]
Ok, thx, found it.
