### ISSUE TITLE
Rbatis连接数据库有没有进行池化？如何正确的关闭连接？

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#210]
Rbatis连接数据库有没有进行池化？
我感觉是没有的，因为我的一个应该在测试的过程中，就出现了连接不够用了的问题。而且，我也不太清楚这个有没有进行有效关闭处理？
今天，杀掉应用 后连接降下来了。但一重开，几分钟后，连接数又上去了，目前已经用掉了500个连接了。

另外，实际的应用中，你是或者你推荐怎么进行连接池化的？

**Comment by zhuxiujia** [comment]
> Rbatis连接数据库有没有进行池化？ 我感觉是没有的，因为我的一个应该在测试的过程中，就出现了连接不够用了的问题。而且，我也不太清楚这个有没有进行有效关闭处理？ 今天，杀掉应用 后连接降下来了。但一重开，几分钟后，连接数又上去了，目前已经用掉了500个连接了。
> 
> 另外，实际的应用中，你是或者你推荐怎么进行连接池化的？

rbatis实例 需要保持单例，因为内置了连接池。可以检查一下是否有重复new rbatis

**Comment by longzou** [comment]
Thx
