### ISSUE TITLE
MySQL 中 INFORMATION_SCHEMA.COLUMNS 表中的DATA_TYPE字段的值不能被正确解析

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#216]
INFORMATION_SCHEMA.COLUMNS中的DATA_TYPE字段类型为longtext，通过查询INFORMATION_SCHEMA.COLUMNS返回出来DATA_TYPE的数据不能被正确解释，BSON显示为 Binary<0x0, ZEssdk3>。

通过客户端查询，或者JDBC查询是可以取得一致的值的。

**Comment by zhuxiujia** [comment]
> INFORMATION_SCHEMA.COLUMNS中的DATA_TYPE字段类型为longtext，通过查询INFORMATION_SCHEMA.COLUMNS返回出来DATA_TYPE的数据不能被正确解释，BSON显示为 Binary<0x0, ZEssdk3>。
> 
> 通过客户端查询，或者JDBC查询是可以取得一致的值的。

longtext 在sqlx中对应的bytes，因此你应该使用Bytes接受数据
