### ISSUE TITLE
MySQL表的字段名，而struct中是小写的，会造成数据无法映射

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#222]
MySQL表的字段名，而struct中是小写的，会造成数据无法映射，struct如下：

#[crud_table(table_name:"MORINKHUUR_USER"|table_columns:"ID,USERNAME,NICK_NAME,PASSWORD,API_PASSWORD,STATUS,ROLE,UPDATE_TIME,CREATE_TIME")]
#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct MorinkhuurUser {
    pub id: Option<i64>,
    pub username: Option<String>,
    pub nick_name: Option<String>,
    pub password: Option<String>,
    pub api_password: Option<String>,
    pub status: Option<i32>,
    pub role: Option<i32>,
    pub update_time: Option<rbatis::DateTimeNative>,
    pub create_time: Option<rbatis::DateTimeNative>,
}

表 MORINKHUUR_USER中的字段都是大写，数据库设为区分大小写。

执行查询后，返回的数据中没有被正确映射。全为null值了。
{"id":null,"username":null,"nick_name":null,"password":null,"api_password":null,"status":null,"role":null,"update_time":null,"create_time":null}

这个应该怎么弄啊。

**Comment by pymongo** [comment]
rbatis 应该有类似 serde(rename="uppercase") 的 API
