### ISSUE TITLE
Value::ObjectId(d)  variant or associated item not found in `Bson`

### ISSUE THREAD

**Issue by donga-gao** [rbatis/rbatis#224]
Bson发布的新的2.0.4版本之后好像去掉了Value::ObjectId，导致现在报错：
Value::ObjectId(d) => {
    |                    ^^^^^^^^ variant or associated item not found in `Bson`

**Comment by zhuxiujia** [comment]
> Bson发布的新的2.0.4版本之后好像去掉了Value::ObjectId，导致现在报错： Value::ObjectId(d) => { | ^^^^^^^^ variant or associated item not found in `Bson`

更新到最新版本即可解决

**Comment by zhuxiujia** [comment]
> Bson发布的新的2.0.4版本之后好像去掉了Value::ObjectId，导致现在报错： Value::ObjectId(d) => { | ^^^^^^^^ variant or associated item not found in `Bson`

更新到最新版本即可解决

**Comment by donga-gao** [comment]
就是升到最新版3.1.14才导致的问题。最新版好像默认依赖的是rbatis_sql="3.0.23"一直报错，手动指定rbatis_sql="3.0.25"之后才编译成功

**Comment by zhuxiujia** [comment]
> 就是升到最新版3.1.14才导致的问题。最新版好像默认依赖的是rbatis_sql="3.0.23"一直报错，手动指定rbatis_sql="3.0.25"之后才编译成功

那是因为你没有删除Cargo.lock，它在的情况下会锁定老版本

**Comment by donga-gao** [comment]
哦，感谢
