### ISSUE TITLE
Invalid byte sequence for encoding "UTF8": 0x00 - PostgreSQL

### ISSUE THREAD

**Issue by abdulrahman1s** [rbatis/rbatis#226]
This error happen so **often** on my local machine at tests and always on github action for unknown reason. [runner log](https://github.com/itchatapp/api/runs/7140338008?check_suite_focus=true)

### Log:
```
[INFO  rbatis::plugin::log] [rbatis] [385611330780008448] Exec   ==> INSERT INTO channels (id,type,name,recipients,overwrites,server_id,parent_id,owner_id,topic,permissions) VALUES ($1::bigint,$2,$3,$4::bigint[],$5::jsonb,$6::bigint,$7::bigint,$8::bigint,$9,$10::bigint)
 [rbatis]                      Args   ==> ["198256797126103040", 2, "Fake group", ["198256787873468417"], Binary(0x90, W10=), null, null, "198256787873468417", null, "62"]
[ERROR rbatis::plugin::log] [rbatis] [385611330754842624] ReturnErr  <== error returned from database: invalid byte sequence for encoding "UTF8": 0x00
```

### `Cargo.toml` [full](https://github.com/itchatapp/api/blob/fix-tests/Cargo.toml)
```toml
tokio = { version = "1.19.2", features = ["full"] }
rbatis = { version = "3.1.14", default-features = false, features = ["postgres", "runtime-tokio-rustls", "upper_case_sql_keyword"] }
rbson = "2.0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.81"
serde_repr = "0.1.8"
serde_with = { version = "1.14.0", features = ["json"] }
log = "0.4.17"
```

### Ways I tried and failed

1. Catching this null value by doing:
```rust
async fn save(&self) { // self implements `CRUDTable` 

     // The error always occurs only with `Channel` struct so I added his properties
        for column in ["id", "name", "overwrites", "type", "r#type", "recipients", "server_id", "parent_id", "owner_id", "permissions"] {
            let value = self.get(column).to_string();
            
            if value.contains(char::from(0)) {
                panic!("has zero byte: {}", column);
            }
        }
        
        db.save::<Self>(self, &[])
            .await
            .expect("Couldn't save this target");
    }
```

2. Updating rbatis to latest version. the old was `v3.1.11` with rbson `v2.0.3`

3. Update `Cargo.lock`

**Comment by zhuxiujia** [comment]
> This error happen so **often** on my local machine at tests and always on github action for unknown reason. [runner log](https://github.com/itchatapp/api/runs/7140338008?check_suite_focus=true)
> 
> ### Log:
> ```
> [INFO  rbatis::plugin::log] [rbatis] [385611330780008448] Exec   ==> INSERT INTO channels (id,type,name,recipients,overwrites,server_id,parent_id,owner_id,topic,permissions) VALUES ($1::bigint,$2,$3,$4::bigint[],$5::jsonb,$6::bigint,$7::bigint,$8::bigint,$9,$10::bigint)
>  [rbatis]                      Args   ==> ["198256797126103040", 2, "Fake group", ["198256787873468417"], Binary(0x90, W10=), null, null, "198256787873468417", null, "62"]
> [ERROR rbatis::plugin::log] [rbatis] [385611330754842624] ReturnErr  <== error returned from database: invalid byte sequence for encoding "UTF8": 0x00
> ```
> 
> ### `Cargo.toml` [full](https://github.com/itchatapp/api/blob/fix-tests/Cargo.toml)
> ```toml
> tokio = { version = "1.19.2", features = ["full"] }
> rbatis = { version = "3.1.14", default-features = false, features = ["postgres", "runtime-tokio-rustls", "upper_case_sql_keyword"] }
> rbson = "2.0.4"
> serde = { version = "1", features = ["derive"] }
> serde_json = "1.0.81"
> serde_repr = "0.1.8"
> serde_with = { version = "1.14.0", features = ["json"] }
> log = "0.4.17"
> ```
> 
> ### Ways I tried and failed
> 1. Catching this null value by doing:
> 
> ```rust
> async fn save(&self) { // self implements `CRUDTable` 
> 
>      // The error always occurs only with `Channel` struct so I added his properties
>         for column in ["id", "name", "overwrites", "type", "r#type", "recipients", "server_id", "parent_id", "owner_id", "permissions"] {
>             let value = self.get(column).to_string();
>             
>             if value.contains(char::from(0)) {
>                 panic!("has zero byte: {}", column);
>             }
>         }
>         
>         db.save::<Self>(self, &[])
>             .await
>             .expect("Couldn't save this target");
>     }
> ```
> 
> 2. Updating rbatis to latest version. the old was `v3.1.11` with rbson `v2.0.3`
> 3. Update `Cargo.lock`

Please change to the last version of ```rbatis = "3.1.15"```?

**Comment by abdulrahman1s** [comment]
It fixed the problem but causes others as well.
These errors happens randomly. once appear within 3-5 tries of `cargo test`.

### 1.
```
[INFO  rbatis::plugin::log] [rbatis] [387822702557270016] Exec   ==> INSERT INTO channels (id,type,name,recipients,overwrites,server_id,parent_id,owner_id,topic,permissions) VALUES ($1::bigint,$2,$3,$4::bigint[],$5::jsonb,$6::bigint,$7::bigint,$8::bigint,$9,$10::bigint)
                                                             [rbatis]                      Args   ==> ["200468174607618048", 4, "Test", null, Binary(0x90, W10=), "200468166898487296", null, null, null, null]
[ERROR rbatis::plugin::log] [rbatis] [387822702557270016] ReturnErr  <== error returned from database: incorrect binary data format in bind parameter 6
```

### 2.
```
[INFO  rbatis::plugin::log] [rbatis] [387823217840099328] Exec   ==> INSERT INTO channels (id,type,name,recipients,overwrites,server_id,parent_id,owner_id,topic,permissions) VALUES ($1::bigint,$2,$3,$4::bigint[],$5::jsonb,$6::bigint,$7::bigint,$8::bigint,$9,$10::bigint)
                                                             [rbatis]                      Args   ==> ["200468690335043584", 1, null, ["200468677806657537", "200468677806657538"], null, null, null, null, null, null]
                                                             
[ERROR rbatis::plugin::log] [rbatis] [387823217840099328] ReturnErr  <== error returned from database: binary data has array element type 25 (text) instead of expected 20 (bigint)                                                             
```

**Comment by zhuxiujia** [comment]
Maybe V4.0 will fix your problem?
