### ISSUE TITLE
是否支持全文检索啊

### ISSUE THREAD

**Issue by jiangxiaoqiang** [rbatis/rbatis#229]
请问下是否支持PostgreSQL全文检索啊，没有找到相关的文档和介绍。类似于这样的语法

`SELECT * FROM article a  WHERE to_tsvector('english', title) @@ to_tsquery('english','Rate|Limiting')
`

**Comment by zhuxiujia** [comment]
> 请问下是否支持PostgreSQL全文检索啊，没有找到相关的文档和介绍。类似于这样的语法
> 
> `SELECT * FROM article a WHERE to_tsvector('english', title) @@ to_tsquery('english','Rate|Limiting') `

可以使用 [html_sql](https://rbatis.github.io/rbatis.io/#/?id=htmlsql%e8%af%ad%e6%b3%95%e5%85%bc%e5%ae%b9mybatis) 来自定义查询
