### ISSUE TITLE
当Struct中使用#[serde(deserialize_with="i64_from_str")]来解释相应的返回结果时会出现异常

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#233]
在使用最新版的rbatis时，会出现这个问题，而之前版本3.1.11是没有问题的。

例如：
struct test_info {
    pub normal_point: Option<rbatis::Decimal>,
    #[serde(default)]
    #[serde(deserialize_with="i64_from_str")]    
    pub point_id: Option<i64>,
}

查询返回时会出现异常：
 data did not match any variant of untagged enum StrOrI64

i64_from_str 实现如下：（它是为了兼容JSON中被引号包起来的数字的情况：如 { "point_id": "10" }）
#[derive(Deserialize)]
#[serde(untagged)] // 枚举类型的无标签方式
enum StrOrI64 {
    String(String),
    I64(i64),
    U64(u64),
}

#[allow(dead_code)]
pub fn i64_from_str<'de, D>(deserializer: D) -> Result<Option<i64>, D::Error>
where
    D: Deserializer<'de>,
{
    Ok(match StrOrI64::deserialize(deserializer)? {
        StrOrI64::String(v) => match v.parse::<i64>() {
            Ok(st) => {
                Some(st)
            }
            Err(_) => {
                None
            }
        },
        StrOrI64::U64(v) => Some(v as i64),
        StrOrI64::I64(v) => Some(v),
    })
}

**Comment by zhuxiujia** [comment]
试一下v4.0. 新版本不再使用包裹的方式了
