### ISSUE TITLE
read Mysql timestamp error

### ISSUE THREAD

**Issue by jackielihf** [rbatis/rbatis#234]
1、 DDL
CREATE TABLE `position` (
  `account_id` varchar(64) NOT NULL,
  `instrument_id` varchar(32) NOT NULL,
  `market_type` varchar(32) DEFAULT NULL,
  `amount` decimal(20,2) DEFAULT NULL,
  `enable` decimal(20,2) DEFAULT NULL,
  `frozen` decimal(20,2) DEFAULT NULL,
  `create_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`account_id`,`instrument_id`),
  UNIQUE KEY `idx_position_key` (`instrument_id`,`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

2、use DateTime<Utc> of  chrono

use chrono::prelude::*;

#[crud_table(table_name:position)]
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Position{
    pub account_id: Option<String>,
    pub instrument_id: Option<String>,
    pub market_type: Option<String>,
    pub amount: Option<Decimal>,
    pub enable: Option<Decimal>,
    pub frozen: Option<Decimal>,
    pub create_at: Option<DateTime<Utc>>,
    pub update_at: Option<DateTime<Utc>>,
}

3、error info:

premature end of input

**Comment by zhuxiujia** [comment]
this fix on rbatis -v4.0
