### ISSUE TITLE
Pull request for Postgis point support added

### ISSUE THREAD

**Issue by insanebaba** [rbatis/rbatis#24]
Hi There,
Kindly review the pull request https://github.com/rbatis/rbatis/pull/23 for postgis point. I have tested reading columns with postgres and it works, but writing is not yet tested. let me know if you can merge it. I'll update further when I find time about writing point type to database. 

kindly check the serialization and deserialization in point.rs file , as it might not be optimal, and can be improved(currently using format macro)

**Comment by zhuxiujia** [comment]
> Hi There,
> Kindly review the pull request #23 for postgis point. I have tested reading columns with postgres and it works, but writing is not yet tested. let me know if you can merge it. I'll update further when I find time about writing point type to database.
> 
> kindly check the serialization and deserialization in point.rs file , as it might not be optimal, and can be improved(currently using format macro)

hi: have you merge the last rbatis version? please check it

**Comment by insanebaba** [comment]
Follow the conversation on the pull request #23
