### ISSUE TITLE
Rbatis v4 crud!() 报错

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#245]
一直报如下错误：

141 | crud!(ChimesPermissionInfo{},"chimes_permission");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: [rbatis] parse py_sql fail!: E("[rbatis] express trim value must be string value, for example:  trim 'value',error express: \\',\\'")
    = note: this error originates in the macro `$crate::impl_insert` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0425]: cannot find function `insert_batch` in this scope
   --> src\permission.rs:141:1
error[E0425]: cannot find function `update_by_column` in this scope
   --> src\permission.rs:141:1
error[E0425]: cannot find function `delete_by_column_batch` in this scope
   --> src\permission.rs:141:1

代码非常简单：

#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct ChimesPermissionInfo {
    pub id: Option<i64>,
    pub alias: Option<String>,
    pub create_time: Option<rbatis::rbdc::datetime::DateTime>,
    pub name: Option<String>,
    pub pid: Option<i64>,
    pub api_pattern: Option<String>,
    pub service_id: Option<String>,
    pub api_method: Option<String>,
    pub api_bypass: Option<String>,
}

crud!(ChimesPermissionInfo{});

不知道这是什么问题产生的？？

**Comment by longzou** [comment]
照文档的例子做了一个极简单的，也是报这相同的错误。
代码如下：


#[macro_use]
extern crate rbatis;
extern crate rbdc;

use rbatis::Rbatis;
use rbatis::rbdc::datetime::FastDateTime;
use serde::{Deserialize, Serialize};
use rbdc_mysql::driver::MysqlDriver;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BizActivity {
    pub id: Option<String>,
    pub name: Option<String>,
    pub pc_link: Option<String>,
    pub h5_link: Option<String>,
    pub pc_banner_img: Option<String>,
    pub h5_banner_img: Option<String>,
    pub sort: Option<String>,
    pub status: Option<i32>,
    pub remark: Option<String>,
    pub create_time: Option<FastDateTime>,
    pub version: Option<i64>,
    pub delete_flag: Option<i32>,
}

crud!(BizActivity{});


编译时报如下错误：


D:\gitspaces\longzou\test>cargo b
   Compiling rbatis-codegen v4.0.17
   Compiling rbatis-macro-driver v4.0.11
   Compiling rbatis v4.0.35
   Compiling test v0.2.0 (D:\gitspaces\longzou\test)
error: custom attribute panicked
  --> src\main.rs:27:1
   |
27 | crud!(BizActivity{});
   | ^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: [rbatis] parse py_sql fail!: E("[rbatis] express trim value must be string value, for example:  trim 'value',error express: \\',\\'")
   = note: this error originates in the macro `$crate::impl_insert` (in Nightly builds, run with -Z macro-backtrace for more info)

error: custom attribute panicked
  --> src\main.rs:27:1
   |
27 | crud!(BizActivity{});
   | ^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: [rbatis] parse py_sql fail!: E("[rbatis] express trim value must be string value, for example:  trim 'value',error express: \\',\\'")
   = note: this error originates in the macro `$crate::impl_update` (in Nightly builds, run with -Z macro-backtrace for more info)

error: custom attribute panicked
  --> src\main.rs:27:1
   |
27 | crud!(BizActivity{});
   | ^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: [rbatis] parse py_sql fail!: E("[rbatis] express trim value must be string value, for example:  trim 'value',error express: \\',\\'")
   = note: this error originates in the macro `$crate::impl_delete` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find function `insert_batch` in this scope
  --> src\main.rs:27:1
   |
27 | crud!(BizActivity{});
   | ^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in the macro `$crate::impl_insert` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find function `update_by_column` in this scope
  --> src\main.rs:27:1
   |
27 | crud!(BizActivity{});
   | ^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in the macro `$crate::impl_update` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find function `delete_by_column_batch` in this scope
  --> src\main.rs:27:1
   |
27 | crud!(BizActivity{});
   | ^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in the macro `$crate::impl_delete` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated associated function `rbatis::Rbatis::link`
  --> src\main.rs:37:8
   |
37 |     rb.link(
   |        ^^^^
   |
   = note: `#[warn(deprecated)]` on by default

For more information about this error, try `rustc --explain E0425`.
warning: `test` (bin "test") generated 1 warning
error: could not compile `test` due to 6 previous errors; 1 warning emitted.

**Comment by zhuxiujia** [comment]
是否跑过 cargo update  更新到最新？

**Comment by longzou** [comment]
> 是否跑过 cargo update 更新到最新？

跑过了，，到了 v4.0.35了。

不过，我之前使用的是 rust 1.61 版，，执行了rustup之后，升级到rust 1.63，就可以了。。

**Comment by zhuxiujia** [comment]
> > 是否跑过 cargo update 更新到最新？
> 
> 跑过了，，到了 v4.0.35了。
> 
> 不过，我之前使用的是 rust 1.61 版，，执行了rustup之后，升级到rust 1.63，就可以了。。

了解
