### ISSUE TITLE
sqlite数据库 INT8 的 id 类型，读取错误的值到 i64 中

### ISSUE THREAD

**Issue by Zerounary** [rbatis/rbatis#249]
场景：sqlite数据库使用 `rbatis::plugin::snowflake::new_snowflake_id()` 插入数据，然后查出到 UserBO 中
```rust
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct UserBO {
    pub id: i64,
    pub username: String,
}
```

数据库正确：
![image](https://user-images.githubusercontent.com/31512287/189477264-0d7c63a5-ece4-4179-b3af-06c2e932bf53.png)

![image](https://user-images.githubusercontent.com/31512287/189477358-d2b3e086-c4f3-4f17-935b-9ed4c24aaa2d.png)

py_sql 查出的 decode 结果不正确

![image](https://user-images.githubusercontent.com/31512287/189477364-06cca6fe-3013-47ab-a5eb-c08f03659edf.png)

**Comment by zhuxiujia** [comment]
```
   println!("{}",u8::MAX);
   println!("{}",i8::MAX);
255
127
```
