### ISSUE TITLE
这个可以自定义插件吗？

### ISSUE THREAD

**Issue by Silentdoer** [rbatis/rbatis#25]
比如我自定义一个拦截器，在生成SQL之前修改SQL，并且最好能分类比如只拦截update或select等

**Comment by zhuxiujia** [comment]
> 比如我自定义一个拦截器，在生成SQL之前修改SQL，并且最好能分类比如只拦截update或select等

生成之前修改SQL?这样有什么用呢？

**Comment by Silentdoer** [comment]
比如我可以根据不同ID来分表查询

**Comment by zhuxiujia** [comment]
> 比如我可以根据不同ID来分表查询

了解，下个版本可以支持

**Comment by zhuxiujia** [comment]
> 比如我自定义一个拦截器，在生成SQL之前修改SQL，并且最好能分类比如只拦截update或select等

最新版本已支持插件SqlIntercept，实现这个trait即可
