### ISSUE TITLE
Inserting point type column in postgres is not working

### ISSUE THREAD

**Issue by insanebaba** [rbatis/rbatis#26]
Encoding method is currently inserting **point** type as text in **pgbuffer** which throws error, I don't know what's the correct way to encode. 

**db** : postgres
**query log:**
```
 [2020-09-25T08:02:07Z INFO  rbatis::rbatis] [rbatis] [] Exec ==> INSERT INTO demo (coordinates,id) VALUES ( $1 , $2 )
[2020-09-25T08:02:07Z INFO  rbatis::rbatis] [rbatis] [] Args ==> [{"x":12.1,"y":2.12},2]
[2020-09-25T08:02:09Z INFO  rbatis::rbatis] [rbatis] [] RowsAffected <== 0
```
**error message** : {"Err":"column \"coordinates\" is of type point but expression is of type text"}

If anyone knows how to encode to pgbuffer, let me know, I'll fix it

**Comment by zhuxiujia** [comment]
> type as text in

How does SQLX work? Maybe we can find it in it？

**Comment by zhuxiujia** [comment]
> Encoding method is currently inserting **point** type as text in **pgbuffer** which throws error, I don't know what's the correct way to encode.
> 
> **db** : postgres
> **query log:**
> 
> ```
>  [2020-09-25T08:02:07Z INFO  rbatis::rbatis] [rbatis] [] Exec ==> INSERT INTO demo (coordinates,id) VALUES ( $1 , $2 )
> [2020-09-25T08:02:07Z INFO  rbatis::rbatis] [rbatis] [] Args ==> [{"x":12.1,"y":2.12},2]
> [2020-09-25T08:02:09Z INFO  rbatis::rbatis] [rbatis] [] RowsAffected <== 0
> ```
> 
> **error message** : {"Err":"column "coordinates" is of type point but expression is of type text"}
> 
> If anyone knows how to encode to pgbuffer, let me know, I'll fix it

in Rbatis, coming data also is json args you can  'rbatis_core/db.rs'
Rbatis only deal with json's number,null,string.  
than  The data is then bound using SQLX macros。
so  I wonder if you need to change the type here

**Comment by zhuxiujia** [comment]
> Encoding method is currently inserting **point** type as text in **pgbuffer** which throws error, I don't know what's the correct way to encode.
> 
> **db** : postgres
> **query log:**
> 
> ```
>  [2020-09-25T08:02:07Z INFO  rbatis::rbatis] [rbatis] [] Exec ==> INSERT INTO demo (coordinates,id) VALUES ( $1 , $2 )
> [2020-09-25T08:02:07Z INFO  rbatis::rbatis] [rbatis] [] Args ==> [{"x":12.1,"y":2.12},2]
> [2020-09-25T08:02:09Z INFO  rbatis::rbatis] [rbatis] [] RowsAffected <== 0
> ```
> 
> **error message** : {"Err":"column "coordinates" is of type point but expression is of type text"}
> 
> If anyone knows how to encode to pgbuffer, let me know, I'll fix it


My idea is whether json can pass a type tag and query.bind can identify the correct type based on the parameters
in  method  bind_value()

**Comment by insanebaba** [comment]
I'm going to check rust-postgis library on how they did it. They use similar buffer writing method

**Comment by insanebaba** [comment]
I'm sorry, but I cannot continue working on this project anymore, as I am working on building my API for now. I raised an issue on rust user forum for failure of my contribution as well https://users.rust-lang.org/t/failed-to-contribute-due-to-difficulty-in-understanding-rust/49148

Here are some things I found
1. RBatis is the most promising ORM for rust, more than sqlx, diesel or arysn
2. It's difficult to extend this library to add more types as there are lots of them like postgis and similar on mysql
3. I think Rust is not ready for web development which is shame. I'd try again in 2 years if this project can include important types. For Now, I'm moving to golang gorm.

You can close the issue as I am not going to work on this.

**Comment by zhuxiujia** [comment]
> I'm sorry, but I cannot continue working on this project anymore, as I am working on building my API for now. I raised an issue on rust user forum for failure of my contribution as well https://users.rust-lang.org/t/failed-to-contribute-due-to-difficulty-in-understanding-rust/49148
> 
> Here are some things I found
> 
> 1. RBatis is the most promising ORM for rust, more than sqlx, diesel or arysn
> 2. It's difficult to extend this library to add more types as there are lots of them like postgis and similar on mysql
> 3. I think Rust is not ready for web development which is shame. I'd try again in 2 years if this project can include important types. For Now, I'm moving to golang gorm.
> 
> You can close the issue as I am not going to work on this.

Yes, I'm currently focused on trying to solve the type problem, which stems from JSON and the overall structure. If I succeed, welcome back
