### ISSUE TITLE
postgresql serialization error  fail to insert :{"Err":"column \"chefid\" of relation \"offer\" does not exist"}

### ISSUE THREAD

**Issue by insanebaba** [rbatis/rbatis#28]
fail to insert on postgres 

**DB Schema**
 ordinal_position |  column_name   | data_type | character_maximum_length | modifier | notnull | hasdefault
------------------+----------------+-----------+--------------------------+----------+---------+------------
                1 | id             | uuid      |                       16 |       -1 | t       | t
                2 | create_date    | timestamp |                        8 |       -1 | t       | t
                3 | update_date    | timestamp |                        8 |       -1 | t       | t
                4 | version        | int4      |                        4 |       -1 | t       | f
                5 | is_active      | bool      |                        1 |       -1 | t       | t
                6 | dateOfDelivery | timestamp |                        8 |       -1 | t       | f
                7 | tokenValue     | int4      |                        4 |       -1 | t       | t
                8 | maxQuantity    | int4      |                        4 |       -1 | t       | t
                9 | status         | varchar   |                       -1 |       54 | t       | t
               10 | coordinates    | point     |                       16 |       -1 | f       | f
               11 | chefId         | uuid      |                       16 |       -1 | f       | f
               12 | dishId         | uuid      |                       16 |       -1 | t       | f
(12 rows)

RUST CODE 

```RUST
let off = Offer {
        id: Some(Uuid::new_v4()),
        create_date: Some(Utc::now().naive_local()),
        update_date: Some(Utc::now().naive_local()),
        version: Some(1),
        is_active: Some(true),
        date_of_delivery: Some(Utc::now().naive_local()),
        token_value: Some(2),
        max_quantity: Some(2),
        status: Some("OUT_OF_DELIVERY".to_string()),
        // coordinates: None,
        chefId: Some(Uuid::parse_str("ebb787b4-d90c-4b0f-9bbe-7324f3d90efe").unwrap()),
        dishId: Some(Uuid::parse_str("85357370-8aef-4262-bf68-f6d38522cf6b").unwrap()),
    };
    Json(RB.save_batch("", &vec![off]).await)
```

**log**
```
[2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] Exec ==> INSERT INTO Offer (chefId,create_date,date_of_delivery,dishId,id,is_active,max_quantity,status,token_value,update_date,version) VALUES ( $1 ,cast( $2  as timestamp),cast( $3  as timestamp), $4 , $5 , $6 , $7 , $8 , $9 ,cast( $10  as timestamp), $11 )
[2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] Args ==> ["ebb787b4-d90c-4b0f-9bbe-7324f3d90efe","2020-09-26T12:22:06.537112100","2020-09-26T12:22:06.537112100","85357370-8aef-4262-bf68-f6d38522cf6b","3d30b1fa-4d41-4b54-88e4-9e9065904b9f",true,2,"OUT_OF_DELIVERY",2,"2020-09-26T12:22:06.537112100",1]
[2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] RowsAffected <== 0
```

**Comment by zhuxiujia** [comment]
> fail to insert on postgres
> 
> **DB Schema**
> ordinal_position | column_name | data_type | character_maximum_length | modifier | notnull | hasdefault
> ------------------+----------------+-----------+--------------------------+----------+---------+------------
> 1 | id | uuid | 16 | -1 | t | t
> 2 | create_date | timestamp | 8 | -1 | t | t
> 3 | update_date | timestamp | 8 | -1 | t | t
> 4 | version | int4 | 4 | -1 | t | f
> 5 | is_active | bool | 1 | -1 | t | t
> 6 | dateOfDelivery | timestamp | 8 | -1 | t | f
> 7 | tokenValue | int4 | 4 | -1 | t | t
> 8 | maxQuantity | int4 | 4 | -1 | t | t
> 9 | status | varchar | -1 | 54 | t | t
> 10 | coordinates | point | 16 | -1 | f | f
> 11 | chefId | uuid | 16 | -1 | f | f
> 12 | dishId | uuid | 16 | -1 | t | f
> (12 rows)
> 
> RUST CODE
> 
> ```rust
> let off = Offer {
>         id: Some(Uuid::new_v4()),
>         create_date: Some(Utc::now().naive_local()),
>         update_date: Some(Utc::now().naive_local()),
>         version: Some(1),
>         is_active: Some(true),
>         date_of_delivery: Some(Utc::now().naive_local()),
>         token_value: Some(2),
>         max_quantity: Some(2),
>         status: Some("OUT_OF_DELIVERY".to_string()),
>         // coordinates: None,
>         chefId: Some(Uuid::parse_str("ebb787b4-d90c-4b0f-9bbe-7324f3d90efe").unwrap()),
>         dishId: Some(Uuid::parse_str("85357370-8aef-4262-bf68-f6d38522cf6b").unwrap()),
>     };
>     Json(RB.save_batch("", &vec![off]).await)
> ```
> 
> **log**
> 
> ```
> [2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] Exec ==> INSERT INTO Offer (chefId,create_date,date_of_delivery,dishId,id,is_active,max_quantity,status,token_value,update_date,version) VALUES ( $1 ,cast( $2  as timestamp),cast( $3  as timestamp), $4 , $5 , $6 , $7 , $8 , $9 ,cast( $10  as timestamp), $11 )
> [2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] Args ==> ["ebb787b4-d90c-4b0f-9bbe-7324f3d90efe","2020-09-26T12:22:06.537112100","2020-09-26T12:22:06.537112100","85357370-8aef-4262-bf68-f6d38522cf6b","3d30b1fa-4d41-4b54-88e4-9e9065904b9f",true,2,"OUT_OF_DELIVERY",2,"2020-09-26T12:22:06.537112100",1]
> [2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] RowsAffected <== 0
> ```

Pg database fields must be lowercase, which is the reason for the database

**Comment by zhuxiujia** [comment]
> point

Using the point structure of PG, whether the insert statement needs function conversion, my suggestion is that you can use native SQL to insert, such as：
```rust
 lazy_static! {
     static ref RB:Rbatis=Rbatis::new();
   }
    #[py_sql(RB, "INSERT INTO Offer (chefId,create_date,date_of_delivery,dishId,id,is_active,max_quantity,status,token_value,update_date,version) VALUES ('#{chefId}')]
    fn insert_data(chefId: &str) -> Option<BizActivity> {}

```

**Comment by insanebaba** [comment]
Thank you for suggestion. But I'm not using point type in this operation, in saving normal crud struct in db

**Comment by insanebaba** [comment]
> > fail to insert on postgres
> > **DB Schema**
> > ordinal_position | column_name | data_type | character_maximum_length | modifier | notnull | hasdefault
> > ------------------+----------------+-----------+--------------------------+----------+---------+------------
> > 1 | id | uuid | 16 | -1 | t | t
> > 2 | create_date | timestamp | 8 | -1 | t | t
> > 3 | update_date | timestamp | 8 | -1 | t | t
> > 4 | version | int4 | 4 | -1 | t | f
> > 5 | is_active | bool | 1 | -1 | t | t
> > 6 | dateOfDelivery | timestamp | 8 | -1 | t | f
> > 7 | tokenValue | int4 | 4 | -1 | t | t
> > 8 | maxQuantity | int4 | 4 | -1 | t | t
> > 9 | status | varchar | -1 | 54 | t | t
> > 10 | coordinates | point | 16 | -1 | f | f
> > 11 | chefId | uuid | 16 | -1 | f | f
> > 12 | dishId | uuid | 16 | -1 | t | f
> > (12 rows)
> > RUST CODE
> > ```rust
> > let off = Offer {
> >         id: Some(Uuid::new_v4()),
> >         create_date: Some(Utc::now().naive_local()),
> >         update_date: Some(Utc::now().naive_local()),
> >         version: Some(1),
> >         is_active: Some(true),
> >         date_of_delivery: Some(Utc::now().naive_local()),
> >         token_value: Some(2),
> >         max_quantity: Some(2),
> >         status: Some("OUT_OF_DELIVERY".to_string()),
> >         // coordinates: None,
> >         chefId: Some(Uuid::parse_str("ebb787b4-d90c-4b0f-9bbe-7324f3d90efe").unwrap()),
> >         dishId: Some(Uuid::parse_str("85357370-8aef-4262-bf68-f6d38522cf6b").unwrap()),
> >     };
> >     Json(RB.save_batch("", &vec![off]).await)
> > ```
> > 
> > 
> > **log**
> > ```
> > [2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] Exec ==> INSERT INTO Offer (chefId,create_date,date_of_delivery,dishId,id,is_active,max_quantity,status,token_value,update_date,version) VALUES ( $1 ,cast( $2  as timestamp),cast( $3  as timestamp), $4 , $5 , $6 , $7 , $8 , $9 ,cast( $10  as timestamp), $11 )
> > [2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] Args ==> ["ebb787b4-d90c-4b0f-9bbe-7324f3d90efe","2020-09-26T12:22:06.537112100","2020-09-26T12:22:06.537112100","85357370-8aef-4262-bf68-f6d38522cf6b","3d30b1fa-4d41-4b54-88e4-9e9065904b9f",true,2,"OUT_OF_DELIVERY",2,"2020-09-26T12:22:06.537112100",1]
> > [2020-09-26T12:22:06Z INFO  rbatis::rbatis] [rbatis] [] RowsAffected <== 0
> > ```
> 
> Pg database fields must be lowercase, which is the reason for the database。
> for example: i see your DB Schema column: 'maxQuantity' ,but in log is 'max_quantity'

I have implemented CRUDEnable too. I was under the impression I can map struct fields to column field in this way

```Rust
impl CRUDEnable for Offer {
    type IdType = Uuid;
    fn table_name() -> String {
        "Offer".to_string()
    }
    fn table_fields() -> String {
        "id,create_date,update_date,version,is_active,dateOfDelivery,tokenValue,maxQuantity,status,chefId,dishId"
            .to_string()
    }
}
```

**Comment by insanebaba** [comment]
I'm now renaming columns in database and testing

**Comment by insanebaba** [comment]
I've fixed the column mapping issue , by renaming all the column field from **camelCase** to **snake_case** . But I found another issue in inserting uuid values. 
```
{"Err":"column \"chef_id\" is of type uuid but expression is of type text"}
```
```RUST
        chef_id: Some(Uuid::parse_str("ebb787b4-d90c-4b0f-9bbe-7324f3d90efe").unwrap()),

```

**Comment by zhuxiujia** [comment]
> I've fixed the column mapping issue , by renaming all the column field from **camelCase** to **snake_case** . But I found another issue in inserting uuid values.
> 
> ```
> {"Err":"column \"chef_id\" is of type uuid but expression is of type text"}
> ```
> 
> ```rust
>         chef_id: Some(Uuid::parse_str("ebb787b4-d90c-4b0f-9bbe-7324f3d90efe").unwrap()),
> ```

uuid in sql  will be string, so , you need convert . for example :        #{chef_id}::uuid

**Comment by zhuxiujia** [comment]
> I've fixed the column mapping issue , by renaming all the column field from **camelCase** to **snake_case** . But I found another issue in inserting uuid values.
> 
> ```
> {"Err":"column \"chef_id\" is of type uuid but expression is of type text"}
> ```
> 
> ```rust
>         chef_id: Some(Uuid::parse_str("ebb787b4-d90c-4b0f-9bbe-7324f3d90efe").unwrap()),
> ```

in  PG,  have type Always need conversion， so , I'm trying to get the user to customize the converter。

**Comment by insanebaba** [comment]
I got it working with https://github.com/rbatis/rbatis/issues/28#issuecomment-699509421 . I faced the issue with bool values also, so I implemented same for bool. Final query for future reference.
Closing this issue for now, 
```RUST 

#[py_sql(RB, "INSERT INTO offer_copy (chef_id,create_date,date_of_delivery,dish_id,is_active,max_quantity,status,token_value,update_date,ver) VALUES ( #{offer.chef_id}::uuid ,cast( #{offer.create_date}  as timestamp),cast( #{offer.date_of_delivery}  as timestamp),  #{offer.dish_id}::uuid , #{offer.is_active}::bool ,#{offer.max_quantity} , #{offer.status} , #{offer.token_value} , cast( #{offer.update_date}  as timestamp), #{offer.ver} )")]
pub fn insert_offer(offer: &Offer) -> u64 {
} 

```

For someone from future looking at this issue I did below to solve the issue
1. use py_sql macro for writing raw sql
2. map uuid using #{some_value}::uuid
3. map bool also using #{some_value}::bool

**Comment by zhuxiujia** [comment]
> I got it working with [#28 (comment)](https://github.com/rbatis/rbatis/issues/28#issuecomment-699509421) . I faced the issue with bool values also, so I implemented same for bool. Final query for future reference.
> Closing this issue for now,
> 
> ```rust
> #[py_sql(RB, "INSERT INTO offer_copy (chef_id,create_date,date_of_delivery,dish_id,is_active,max_quantity,status,token_value,update_date,ver) VALUES ( #{offer.chef_id}::uuid ,cast( #{offer.create_date}  as timestamp),cast( #{offer.date_of_delivery}  as timestamp),  #{offer.dish_id}::uuid , #{offer.is_active}::bool ,#{offer.max_quantity} , #{offer.status} , #{offer.token_value} , cast( #{offer.update_date}  as timestamp), #{offer.ver} )")]
> pub fn insert_offer(offer: &Offer) -> u64 {
> } 
> ```
> 
> For someone from future looking at this issue I did below to solve the issue
> 
> 1. use py_sql macro for writing raw sql
> 2. Use **snake_case** only for column names
> 3. map uuid using #{some_value}::uuid
> 4. map bool also using #{some_value}::bool


'py_sql' macro  use '#{}' or '${}' replace arg .  it  can use   'trim :', 'if  :'  ,'for in  :' ,'choose  :','bind  :','set  :' and more opt in sql.
'sql'  macro  use the raw  sql   and use '?' or '$1' replace arg.
this will be  Solve your problem completely

**Comment by insanebaba** [comment]
Is there any difference in performance between these 2 macro approaches ??

**Comment by zhuxiujia** [comment]
> Is there any difference in performance between these 2 macro approaches ??

The difference between static SQL and dynamic SQL, dynamic SQL means that SQL content will be dynamically modified during operation

**Comment by zhuxiujia** [comment]
> Is there any difference in performance between these 2 macro approaches ??

in Rbatis version: v1.6.0
we add trait  
```rust
ColumnFormat{
    fn need_format(&self, driver_type: &DriverType, column: &str) -> bool;
    fn do_format(&self, driver_type: &DriverType, sql: &str, value: &serde_json::Value) -> rbatis_core::Result<(String, Value)>;
}
```
* this trait  do_format() method  can format  json value for pg, for example:
```rust
 //befor format sql
select * from biz_activity where  date = $1
 //after format  date
select * from biz_activity where  date = $1::timestamp
``` 
*  this format is define on CRUDEnable trait. so  you can Override it to customize the values that require format
```rust
    fn format_chain() -> Vec<Box<dyn ColumnFormat>> {
        let mut chain: Vec<Box<dyn ColumnFormat>> = vec![Box::new(DateFormat {})];
        return chain;
    }
```
