### ISSUE TITLE
分页插件的count统计有问题

### ISSUE THREAD

**Issue by RisingStar20** [rbatis/rbatis#29]
在统计分页（count）的时候，加入limit了，当页数大于0的时候，是统计不了总数。
`rbatis::rbatis-242]: [rbatis] [] Query ==> SELECT count(1) FROM t_test WHERE del = 0 LIMIT 2,10`

具体在：在RbatisPagePlugin类的create_page_sql的方法里面创建count_sql有问题。
希望作者修复一下。谢谢了。

**Comment by zhuxiujia** [comment]
> 在统计分页（count）的时候，加入limit了，当页数大于0的时候，是统计不了总数。
> `rbatis::rbatis-242]: [rbatis] [] Query ==> SELECT count(1) FROM t_test WHERE del = 0 LIMIT 2,10`
> 
> 具体在：在RbatisPagePlugin类的create_page_sql的方法里面创建count_sql有问题。
> 希望作者修复一下。谢谢了。

已修复，等待发布

**Comment by zhuxiujia** [comment]
已发布1.5.9 试试看
