### ISSUE TITLE
静态定义一个Rabtis实例，执行第一个sql没问题，第二个就卡主了

### ISSUE THREAD

**Issue by adminSxs** [rbatis/rbatis#3]
lazy_static!{
  pub static ref Rb: Rbatis<'static>={
    let rb = Rbatis::new();
    async_std::task::block_on(async{
     rb.link(&CONFIG.database.url).await;
    });
    return rb;
  };
}

Rb.fetch_by_wrapper()===>success

Rb.remove_by_wrapper() ===>卡主一直不会动

==============================
我改成
pub async fn connect()->Rbatis<'static>{
   let rb = Rbatis::new();
    rb.link(&CONFIG.database.url).await;
    return rb;
}

connecti().await.fetch_by_wrapper()===>success
connecti().await.remove_by_wrapper()===>success
这个就正常了。请问这个是什么原因

**Comment by zhuxiujia** [comment]
> lazy_static!{
> pub static ref Rb: Rbatis<'static>={
> let rb = Rbatis::new();
> async_std::task::block_on(async{
> rb.link(&CONFIG.database.url).await;
> });
> return rb;
> };
> }
> 
> Rb.fetch_by_wrapper()===>success
> 
> Rb.remove_by_wrapper() ===>卡主一直不会动
> 
> ==============================
> 我改成
> pub async fn connect()->Rbatis<'static>{
> let rb = Rbatis::new();
> rb.link(&CONFIG.database.url).await;
> return rb;
> }
> 
> connecti().await.fetch_by_wrapper()===>success
> connecti().await.remove_by_wrapper()===>success
> 这个就正常了。请问这个是什么原因

我本地试过不会出现。你的具体代码看看，你是不是哪里加锁了。

**Comment by adminSxs** [comment]
> > lazy_static!{
> > pub static ref Rb: Rbatis<'static>={
> > let rb = Rbatis::new();
> > async_std::task::block_on(async{
> > rb.link(&CONFIG.database.url).await;
> > });
> > return rb;
> > };
> > }
> > Rb.fetch_by_wrapper()===>success
> > Rb.remove_by_wrapper() ===>卡主一直不会动
> > ==============================
> > 我改成
> > pub async fn connect()->Rbatis<'static>{
> > let rb = Rbatis::new();
> > rb.link(&CONFIG.database.url).await;
> > return rb;
> > }
> > connecti().await.fetch_by_wrapper()===>success
> > connecti().await.remove_by_wrapper()===>success
> > 这个就正常了。请问这个是什么原因
> 
> 我本地试过不会出现。你的具体代码看看，你是不是哪里加锁了。

我没有加锁。我提供一下代码吧
```rust
lazy_static!{
  pub static ref Rb: Rbatis<'static>={
    let rb = Rbatis::new();
    async_std::task::block_on(async{
     rb.link(&CONFIG.database.url).await;
    });
    return rb;
  };
}

pub async fn find_by_email(email: String)->Result<User>{
    let rb = &super::Rb;
    let w = Wrapper::new(&rb.driver_type().unwrap())
        .eq("email",email)
        .check()
        .unwrap();
    let r: Result<User>=rb.fetch_by_wrapper("",&w).await;
    r
}
pub async fn delete_by_id(id: Option<u64>){
     let rb = &super::Rb;
    let w = Wrapper::new(&rb.driver_type().unwrap())
        .eq("id",id)
        .check()
        .unwrap();
    let r=rb.remove_by_wrapper::<User>("",&w).await;
    if(r.is_err()){
        println!("delete user fail");
    }else{
        println!("delete user success!,count={}",r.unwrap());
    }
}


```

![image](https://user-images.githubusercontent.com/15902505/87430277-8f5cea00-c617-11ea-92c1-cb74d8f5b402.png)
一直卡到现在

**Comment by zhuxiujia** [comment]
> > > # lazy_static!{
> > > pub static ref Rb: Rbatis<'static>={
> > > let rb = Rbatis::new();
> > > async_std::task::block_on(async{
> > > rb.link(&CONFIG.database.url).await;
> > > });
> > > return rb;
> > > };
> > > }
> > > Rb.fetch_by_wrapper()===>success
> > > Rb.remove_by_wrapper() ===>卡主一直不会动
> > > 我改成
> > > pub async fn connect()->Rbatis<'static>{
> > > let rb = Rbatis::new();
> > > rb.link(&CONFIG.database.url).await;
> > > return rb;
> > > }
> > > connecti().await.fetch_by_wrapper()===>success
> > > connecti().await.remove_by_wrapper()===>success
> > > 这个就正常了。请问这个是什么原因
> > 
> > 
> > 我本地试过不会出现。你的具体代码看看，你是不是哪里加锁了。
> 
> 我没有加锁。我提供一下代码吧
> 
> ```rust
> lazy_static!{
>   pub static ref Rb: Rbatis<'static>={
>     let rb = Rbatis::new();
>     async_std::task::block_on(async{
>      rb.link(&CONFIG.database.url).await;
>     });
>     return rb;
>   };
> }
> 
> pub async fn find_by_email(email: String)->Result<User>{
>     let rb = &super::Rb;
>     let w = Wrapper::new(&rb.driver_type().unwrap())
>         .eq("email",email)
>         .check()
>         .unwrap();
>     let r: Result<User>=rb.fetch_by_wrapper("",&w).await;
>     r
> }
> pub async fn delete_by_id(id: Option<u64>){
>      let rb = &super::Rb;
>     let w = Wrapper::new(&rb.driver_type().unwrap())
>         .eq("id",id)
>         .check()
>         .unwrap();
>     let r=rb.remove_by_wrapper::<User>("",&w).await;
>     if(r.is_err()){
>         println!("delete user fail");
>     }else{
>         println!("delete user success!,count={}",r.unwrap());
>     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/15902505/87430277-8f5cea00-c617-11ea-92c1-cb74d8f5b402.png)
> 一直卡到现在

&super::Rb 这里指向了哪里，
调用方的代码 也贴上来

**Comment by adminSxs** [comment]
![image](https://user-images.githubusercontent.com/15902505/87431362-178fbf00-c619-11ea-83c4-c4a64467e89f.png)
没有执行完成

**Comment by adminSxs** [comment]
![image](https://user-images.githubusercontent.com/15902505/87431434-355d2400-c619-11ea-8e9a-102b27058562.png)
```rust

//通过这种方式获取的rb，执行都没问题
let rb=connect().await;

//在lazy_static中获取的rb就会卡在第二个sql

```

**Comment by zhuxiujia** [comment]
> ![image](https://user-images.githubusercontent.com/15902505/87431434-355d2400-c619-11ea-8e9a-102b27058562.png)
> 
> ```rust
> //通过这种方式获取的rb，执行都没问题
> let rb=connect().await;
> 
> //在lazy_static中获取的rb就会卡在第二个sql
> ```

能否debug进去呢？我这样目测很难测到。  debug 进去定位到 卡主那句代码

**Comment by adminSxs** [comment]
> > ![image](https://user-images.githubusercontent.com/15902505/87431434-355d2400-c619-11ea-8e9a-102b27058562.png)
> > ```rust
> > //通过这种方式获取的rb，执行都没问题
> > let rb=connect().await;
> > 
> > //在lazy_static中获取的rb就会卡在第二个sql
> > ```
> 
> 能否debug进去呢？我这样目测很难测到。 debug 进去定位到 卡主那句代码

我是msvc 安装的，clion不支持debugo(╯□╰)o

**Comment by adminSxs** [comment]
> > > ![image](https://user-images.githubusercontent.com/15902505/87431434-355d2400-c619-11ea-8e9a-102b27058562.png)
> > > ```rust
> > > //通过这种方式获取的rb，执行都没问题
> > > let rb=connect().await;
> > > 
> > > //在lazy_static中获取的rb就会卡在第二个sql
> > > ```
> > 
> > 
> > 能否debug进去呢？我这样目测很难测到。 debug 进去定位到 卡主那句代码
> 
> 我是msvc 安装的，clion不支持debugo(╯□╰)o

有微信群或者qq群之类的吗

**Comment by zhuxiujia** [comment]
> > > > ![image](https://user-images.githubusercontent.com/15902505/87431434-355d2400-c619-11ea-8e9a-102b27058562.png)
> > > > ```rust
> > > > //通过这种方式获取的rb，执行都没问题
> > > > let rb=connect().await;
> > > > 
> > > > //在lazy_static中获取的rb就会卡在第二个sql
> > > > ```
> > > 
> > > 
> > > 能否debug进去呢？我这样目测很难测到。 debug 进去定位到 卡主那句代码
> > 
> > 
> > 我是msvc 安装的，clion不支持debugo(╯□╰)o
> 
> 有微信群或者qq群之类的吗

微信 zxj347284221

**Comment by zhuxiujia** [comment]
> > > > ![image](https://user-images.githubusercontent.com/15902505/87431434-355d2400-c619-11ea-8e9a-102b27058562.png)
> > > > ```rust
> > > > //通过这种方式获取的rb，执行都没问题
> > > > let rb=connect().await;
> > > > 
> > > > //在lazy_static中获取的rb就会卡在第二个sql
> > > > ```
> > > 
> > > 
> > > 能否debug进去呢？我这样目测很难测到。 debug 进去定位到 卡主那句代码
> > 
> > 
> > 我是msvc 安装的，clion不支持debugo(╯□╰)o
> 
> 有微信群或者qq群之类的吗

windows的话，用GNU 不要MSVC,GNU可以debug的。是msvc还没有支持clion debug
