### ISSUE TITLE
or()和like()有问题

### ISSUE THREAD

**Issue by RisingStar20** [rbatis/rbatis#30]
1.  使用like 的时候, 生成的语句在?的左右会有空格，导致找不到数据。
`SELECT count(1) FROM t_test WHERE del = 0 AND TITLE LIKE '% ? %' ORDER BY create_time DESC`
2. or 是怎么用的？ 会无端端多了一个or，其他的用了and.
`RB.new_wrapper()
                        .eq("1","1")
                        .or()
                        .like("TITLE",&str)
                        .or()
                        .like("ORIGINAL_NAME",&str)`
生成的语句：
`SELECT count(1) FROM t_test WHERE del = 0 AND 1 =  ?  OR  OR TITLE LIKE '% ? %' OR  OR ORIGINAL_NAME LIKE '% ? %'`

**Comment by zhuxiujia** [comment]
> 1. 使用like 的时候, 生成的语句在?的左右会有空格，导致找不到数据。
>    `SELECT count(1) FROM t_test WHERE del = 0 AND TITLE LIKE '% ? %' ORDER BY create_time DESC`
> 2. or 是怎么用的？ 会无端端多了一个or，其他的用了and.
>    `RB.new_wrapper() .eq("1","1") .or() .like("TITLE",&str) .or() .like("ORIGINAL_NAME",&str)`
>    生成的语句：
>    `SELECT count(1) FROM t_test WHERE del = 0 AND 1 =  ?  OR  OR TITLE LIKE '% ? %' OR  OR ORIGINAL_NAME LIKE '% ? %'`

这个问题已修复，待发布

**Comment by zhuxiujia** [comment]
1.5.9 可以试试

**Comment by RisingStar20** [comment]
还有部分问题。
代码：
` let mut wrapper = wrapper = RB.new_wrapper()
                        .or()
                        .like("ORIGINAL_NAME",&str)
                        .or()
                        .like("TITLE",&str)
                        .order_by(false,&["create_time"]).check()?;`

生成的错误sql：
`SELECT count(1) FROM t_test WHERE del = 0 AND ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' ORDER BY create_time DESC`

问题： 
 期待生成的sql是
SELECT count(1) FROM t_test WHERE del = 0 and ( ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' ) 。

是我用错or方法，还是说，生成sql有问题？

**Comment by zhuxiujia** [comment]
> 已升级到1.6.0 ，但是还有问题。
> 代码：
> ` let mut wrapper = wrapper = RB.new_wrapper() .or() .like("ORIGINAL_NAME",&str) .or() .like("TITLE",&str) .order_by(false,&["create_time"]).check()?;`
> 
> 生成的错误sql：
> `SELECT count(1) FROM t_test WHERE del = 0 AND ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' ORDER BY create_time DESC`
> 
> 问题：
> 
> 1. sql的不对。2. 如果统计总数，不需要加上order by 吧。
>    期待生成的sql是
>    SELECT count(1) FROM t_test WHERE del = 0 and ( ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' )
> 
> 是我用错or方法，还是说，生成sql有问题？

如果要加括号的话，你可以直接 往 Wrapper里面的sql 加括号

**Comment by RisingStar20** [comment]
升级到1.6.2后， 使用下面的代码，还是不可以。生成的sql是没问题的，但是count的数据，都是为0. 下图是我跟踪到的代码
`let mut w= RB.new_wrapper()
.push_sql(" (ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' )  ")
.check()?;

w.args.push(json!("1"));
w.args.push(json!("1"));`



<img width="837" alt="image" src="https://user-images.githubusercontent.com/49504621/95555716-c8550100-0a44-11eb-81f0-757aaaf9c94e.png">

**Comment by zhuxiujia** [comment]
完整日志打印下

**Comment by RisingStar20** [comment]
日志
`2020-10-09T16:02:10.223826+08:00-[INFO]-[actix-rt:worker:0:123145358544896]-[rbatis::rbatis-268]: [rbatis] [] Query ==> SELECT count(1) FROM t_test WHERE del = 0 AND (ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' )  ORDER BY create_time DESC
2020-10-09T16:02:10.224026+08:00-[INFO]-[actix-rt:worker:0:123145358544896]-[rbatis::rbatis-269]: [rbatis] [] Args  ==> ["un"]
2020-10-09T16:02:10.232397+08:00-[INFO]-[actix-rt:worker:0:123145358544896]-[rbatis::rbatis-291]: [rbatis] [] ReturnRows <== 1
2020-10-09T16:02:10.232673+08:00-[INFO]-[actix-rt:worker:0:123145358544896]-[test_controller-24]: vo=Ok(Page { records: [], total: 0, pages: 0, size: 2, current: 1, serch_count: true })`

**Comment by zhuxiujia** [comment]
```rust
SELECT count(1) FROM t_test WHERE del = 0 AND (ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' ) ORDER BY create_time DESC
```
这个sql 查了0条数据了吧？ 应该是sql 写的有问题吧？到navcat或者mysqlworkbench  执行下sql看看

**Comment by RisingStar20** [comment]
navcat查的，有3条数据。
<img width="648" alt="image" src="https://user-images.githubusercontent.com/49504621/95560345-bd519f00-0a4b-11eb-8a0f-d56f22de4b45.png">

**Comment by zhuxiujia** [comment]
完整代码贴上来，看看

**Comment by RisingStar20** [comment]
`
let req = PageRequest::new(arg.page.unwrap_or(1), arg.size.unwrap_or(20));//分页请求，页码，条数
 let wrapper = RB.new_wrapper()
                        .push_sql(" (ORIGINAL_NAME LIKE '%?%' OR TITLE LIKE '%?%' ) ")
                        .order_by(false,&["create_time"]).check()?;
                    wrapper.args.push(json!("un"))

        let mut result: Page<Test> = RB.fetch_page_by_wrapper("", &wrapper, &req).await?;
`

**Comment by zhuxiujia** [comment]
好像是有这个问题，
* 一个问题是，好像预编译模式下，这样的百分号不起作用，需要改成concat('%',?,'%')
* 还有一个问题则是Rbatis 取统计数写的有bug，应该取返回的count(1)对应的值，而不是直接解析为 Result<u64>

**Comment by zhuxiujia** [comment]
原因大概是Mysql预编译的话，执行的时候会把？的值 替换为 '?' .
所以你 '%?%'就变成了  '%’un‘%'这样.
建议 使用concat('%',?,'%'),或者你用Wrapper.like。
还有wrapper 有push_arg()方法，不需要写w.args.push
