### ISSUE TITLE
数据写入时(insert or update)值里有mysql函数包装不能识别?

### ISSUE THREAD

**Issue by lijunfeng** [rbatis/rbatis#304]
类似这样的如何写入？
`Some(format!("UNDEX(0x{})", ip))`
读取的时候我用select hex(ip)读出来，有没有可以直接读取二进制的方法呢？

**Comment by zhuxiujia** [comment]
> 类似这样的如何写入？ `Some(format!("UNDEX(0x{})", ip))` 读取的时候我用select hex(ip)读出来，有没有可以直接读取二进制的方法呢？

读取的时候反序列化类型使用rbatis::rbdc::types::Bytes类型

**Comment by lijunfeng** [comment]
这个试过了，是空的，所以我才hex转成字符串，但是写的时候unhex不能转了，定义成string后写入是字符串了。我用拦截器把字符串转成binary后无效的，还是按字符串处理的，是否可以增加源字符处理机制？这样可能不安全，也和数据库关系比较密切了。

**Comment by zhuxiujia** [comment]
> 这个试过了，是空的，所以我才hex转成字符串，但是写的时候unhex不能转了，定义成string后写入是字符串了。我用拦截器把字符串转成binary后无效的，还是按字符串处理的，是否可以增加源字符处理机制？这样可能不安全，也和数据库关系比较密切了。

展示一下代码看看？

**Comment by lijunfeng** [comment]
我读的库是wordpress的
`/// wp_wfblockediplog 内容主要信息
// #[crud_table(table_name:"wp_wfblockediplog" | formats_pg:"id:{}::uuid,create_time:{}::timestamp")]
// #[py_sql(formats_mysql:"IP:UNHEX({})")]
#[allow(non_snake_case)]
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WpWfblockediplog {
    // pub IP: Option<Vec<char>>,
    // pub IP: Option<rbatis::rbdc::bytes::Bytes>,
    // pub IP: Option<serde_bytes::ByteBuf>,
    // pub IP: Option<rbs::Value>,
    // pub IP: Option<Vec<u8>>,
    // pub IP: Option<rbatis::rbdc::bytes::Bytes>,
    pub IP: Option<String>,
    pub countryCode: Option<String>,
    pub blockCount: Option<usize>,
    pub unixday: Option<usize>,
    pub blockType: Option<String>,
}`

IP如果不用hex转换的话用注释掉的读取出来的都是空的。
数据库IP类型是binary(16)的。

**Comment by zhuxiujia** [comment]
> ```rust
> UNHEX
> ```

我尝试了binary(16)的类型，mysql在插入时会吧字符串类型 转bytes，查询时会吧byte转字符串，因此 ip用Option<String>就行了
