### ISSUE TITLE
where 不加条件，仅使用order_by ，sql会自动加上一个 AND

### ISSUE THREAD

**Issue by RisingStar20** [rbatis/rbatis#31]
配置：
`let mut rbatis = Rbatis::new();
     //logic plugin 设置逻辑删除插件
     rbatis.logic_plugin = Some(Box::new(RbatisLogicDeletePlugin::new_opt("del",1,0)));`

wrapper
`let mut wrapper = RB.new_wrapper().order_by(false,&["create_time"]).check()?;`
生成的错误语句：
`SELECT count(1) FROM t_test WHERE del = 0 AND  ORDER BY create_time DESC`

现在临时的办法是：
`        let mut wrapper = RB.new_wrapper().eq("1","1").order_by(false,&["create_time"]).check()?;
`

**Comment by zhuxiujia** [comment]
> 配置：
> `let mut rbatis = Rbatis::new(); //logic plugin 设置逻辑删除插件 rbatis.logic_plugin = Some(Box::new(RbatisLogicDeletePlugin::new_opt("del",1,0)));`
> 
> wrapper
> `let mut wrapper = RB.new_wrapper().order_by(false,&["create_time"]).check()?;`
> 生成的错误语句：
> `SELECT count(1) FROM t_test WHERE del = 0 AND ORDER BY create_time DESC`
> 
> 现在临时的办法是：
> ` let mut wrapper = RB.new_wrapper().eq("1","1").order_by(false,&["create_time"]).check()?;`

#30 导致的问题，已修复，待发布

**Comment by zhuxiujia** [comment]
v1.5.9 可以试试

**Comment by RisingStar20** [comment]
升级后，还是不行。

**Comment by zhuxiujia** [comment]
> 升级后，还是不行。

具体代码贴上来看看

**Comment by zhuxiujia** [comment]
> 升级后，还是不行。

查到了，应该是分页插件导致的bug，分页插件直接拼接sql 没有做判断。升级到1.6.0版本你在试试

**Comment by RisingStar20** [comment]
1.6.0，可以解决
