### ISSUE TITLE
mysql IN clause not working with vector

### ISSUE THREAD

**Issue by sysmat** [rbatis/rbatis#315]
- my struct:

```rust
impl_select!(User{select_by_user_role(user:String, roles: Vec<String>) -> Option => "`where user = #{user} and role IN (#{roles}) limit 1`"});
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct User {
    pub username: String,
}
```
- log:
```
[rbatis] [428143780235972608] ==> select * from user where user = ? and role IN (?) limit 1
[rbatis]               Args   ==> ["test",["service_admin"]]
```
- I would expect generated query to be: `select * from upis_role_ejb_realm net_id where net_id = "test" and role IN ("service_admin");`

**Comment by zhuxiujia** [comment]
> 

you must use 'for'
```rust
     and id in (
     trim ',': for item in ids:
       #{item},
    )
```

**Comment by zhuxiujia** [comment]
> * my struct:
> 
> ```rust
> impl_select!(User{select_by_user_role(user:String, roles: Vec<String>) -> Option => "`where user = #{user} and role IN (#{roles}) limit 1`"});
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub struct User {
>     pub username: String,
> }
> ```
> 
> * log:
> 
> ```
> [rbatis] [428143780235972608] ==> select * from user where user = ? and role IN (?) limit 1
> [rbatis]               Args   ==> ["test",["service_admin"]]
> ```
> 
> * I would expect generated query to be: `select * from upis_role_ejb_realm net_id where net_id = "test" and role IN ("service_admin");`

you must use 'for'
```rust
     and id in (
     trim ',': for item in ids:
       #{item},
    )
```

**Comment by zhuxiujia** [comment]
> > * my struct:
> > 
> > ```rust
> > impl_select!(User{select_by_user_role(user:String, roles: Vec<String>) -> Option => "`where user = #{user} and role IN (#{roles}) limit 1`"});
> > #[derive(Clone, Debug, Serialize, Deserialize)]
> > pub struct User {
> >     pub username: String,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * log:
> > 
> > ```
> > [rbatis] [428143780235972608] ==> select * from user where user = ? and role IN (?) limit 1
> > [rbatis]               Args   ==> ["test",["service_admin"]]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * I would expect generated query to be: `select * from upis_role_ejb_realm net_id where net_id = "test" and role IN ("service_admin");`
> 
> you must use 'for'
> 
> ```rust
>      and id in (
>      trim ',': for item in ids:
>        #{item},
>      )
> ```

I will add simplified keywords in future releases

**Comment by sysmat** [comment]
- when I use this:

```rust
impl_select!(User{select_by_user_role(user:String, roles: Vec<String>) -> Option => "`where user = #{user} and role IN (trim ',': for item in roles: #{item},) limit 1`"});
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct User {
    pub username: String,
}
```
- I got mysql error

`E("1064 (42000): 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax 
to use near '',': for role in roles: ?,) limit 1' at line 1")'`

**Comment by sysmat** [comment]
- error still persist in rbatis = "4.0.41"

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '',': for role in roles: ?,) limit 1'
`

**Comment by zhuxiujia** [comment]
> * error still persist in rbatis = "4.0.41"
> 
> `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '',': for role in roles: ?,) limit 1' `

You must pay attention to line breaks and formatting alignment。
just like 

```rust
"`insert into ${table_name} (`
                    trim ',':
                      for k,v in tables[0]:
                         if k == 'id' && v== null:
                           continue:
                        ${k},
                    `) VALUES `
                    trim ',':
                     for _,table in tables:
                      (
                      trim ',':
                       for k,v in table:
                         if k == 'id' && v== null:
                            continue:
                         #{v},
                      ),
                    "
```

**Comment by sysmat** [comment]
- if I remove **backtick**  in source
```rust
"where net_id = #{net_id} and role IN (
        trim ',':
            for role in roles:
                #{role}
                ,
        ) limit 1"
```
- rbatis generate sql:

```
'`select * from upis_role_ejb_realm `where net_id = ? and role IN (?) limit 1'
```
- so first char is backtick and then near where is another backtick and this is not supported in SQL

**Comment by sysmat** [comment]
- rbatis = "4.0.46"
- code:

```rust
use rbatis::sql::IntoSql;

impl_select!(UpisRoleEjbRealm{select_by_net_id_role(net_id:String, roles: Vec<String>) -> Option =>
            "`where net_id = #{net_id} and role IN ${roles.sql()} limit 1`"});

```

- it solve the problem

**Comment by zhuxiujia** [comment]
> 

also. you can use ```ValueMap``` to Replaces rbatis- version=3.0 ‘s Wrapper struct. It can assemble arbitrary sql statements

**Comment by sysmat** [comment]
@zhuxiujia thx for tip
