### ISSUE TITLE
rbdc-mysql 与 lazy_static 冲突

### ISSUE THREAD

**Issue by jiashiwen** [rbatis/rbatis#318]
hi
我的lazy_static 代码 在引入 rbdc-mysql 时出现如下错误

lazy_static 代码
```
lazy_static::lazy_static! {
    static ref GLOBALE_CASBIN_ENFORCER: AsyncOnce<RwLock<CasbinEnforcer>> = AsyncOnce::new(async {
        let ce=CasbinEnforcer::default().await;
        RwLock::new(ce)
    });
}
```

Cargo.yml
```
rbdc-mysql = "0.1.17"
```

错误输出

```
`*const futures_locks::RwLock<CasbinEnforcer>` cannot be sent between threads safely
the trait `std::marker::Send` is not implemented for `*const futures_locks::RwLock<CasbinEnforcer>`
the trait `std::marker::Send` is implemented for `futures_locks::RwLock<T>`
required because of the requirements on the impl of `std::marker::Send` for `Cell<*const futures_locks::RwLock<CasbinEnforcer>>`
required because of the requirements on the impl of `Sync` for `spin::once::Once<AsyncOnce<futures_locks::RwLock<CasbinEnforcer>>>`
shared static variables must have a type that implements `Sync`

```

```

`(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)` cannot be sent between threads safely
the trait `std::marker::Send` is not implemented for `(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)`
required because of the requirements on the impl of `std::marker::Send` for `Unique<(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)>`
required because of the requirements on the impl of `std::marker::Send` for `std::sync::Mutex<std::result::Result<futures_locks::RwLock<CasbinEnforcer>, Pin<Box<(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)>>>>`
required because of the requirements on the impl of `Sync` for `spin::once::Once<AsyncOnce<futures_locks::RwLock<CasbinEnforcer>>>`
shared static variables must have a type that implements `Sync`
```

引入 rbdc-sqlite、rbdc-pg、rbdc-oracle 则没有相关问题 。
我试着在我项目的Cargo.yml 中阴影 rbdc-mysql的依赖包，发现 rsa = { version = "0.7.0" }  会引起这个问题

**Comment by zhuxiujia** [comment]
> 

maybe you should use this code
```
pub static RB: once_cell::sync::Lazy<ServiceContext> = once_cell::sync::Lazy::new(|| Rbatis::new());
```

**Comment by zhuxiujia** [comment]
> hi 我的lazy_static 代码 在引入 rbdc-mysql 时出现如下错误
> 
> lazy_static 代码
> 
> ```
> lazy_static::lazy_static! {
>     static ref GLOBALE_CASBIN_ENFORCER: AsyncOnce<RwLock<CasbinEnforcer>> = AsyncOnce::new(async {
>         let ce=CasbinEnforcer::default().await;
>         RwLock::new(ce)
>     });
> }
> ```
> 
> Cargo.yml
> 
> ```
> rbdc-mysql = "0.1.17"
> ```
> 
> 错误输出
> 
> ```
> `*const futures_locks::RwLock<CasbinEnforcer>` cannot be sent between threads safely
> the trait `std::marker::Send` is not implemented for `*const futures_locks::RwLock<CasbinEnforcer>`
> the trait `std::marker::Send` is implemented for `futures_locks::RwLock<T>`
> required because of the requirements on the impl of `std::marker::Send` for `Cell<*const futures_locks::RwLock<CasbinEnforcer>>`
> required because of the requirements on the impl of `Sync` for `spin::once::Once<AsyncOnce<futures_locks::RwLock<CasbinEnforcer>>>`
> shared static variables must have a type that implements `Sync`
> ```
> 
> ```
> 
> `(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)` cannot be sent between threads safely
> the trait `std::marker::Send` is not implemented for `(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)`
> required because of the requirements on the impl of `std::marker::Send` for `Unique<(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)>`
> required because of the requirements on the impl of `std::marker::Send` for `std::sync::Mutex<std::result::Result<futures_locks::RwLock<CasbinEnforcer>, Pin<Box<(dyn futures::Future<Output = futures_locks::RwLock<CasbinEnforcer>> + 'static)>>>>`
> required because of the requirements on the impl of `Sync` for `spin::once::Once<AsyncOnce<futures_locks::RwLock<CasbinEnforcer>>>`
> shared static variables must have a type that implements `Sync`
> ```
> 
> 引入 rbdc-sqlite、rbdc-pg、rbdc-oracle 则没有相关问题 。 我试着在我项目的Cargo.yml 中阴影 rbdc-mysql的依赖包，发现 rsa = { version = "0.7.0" } 会引起这个问题

可以参考[abs_admin](https://github.com/rbatis/abs_admin) 项目中链接mysql的使用场景

**Comment by jiashiwen** [comment]
thx
