### ISSUE TITLE
数据库名问题

### ISSUE THREAD

**Issue by Vjze** [rbatis/rbatis#320]
新人刚接触rust，有个疑问。数据库名字如果是大写加上下划线，会报数据库对象名无效，数据库名字也会被自动修改。本身数据库名字：crud!(QA_snRelation{});  结果输出：2022-11-09 10:02:05.2500148 ERROR tiberius::tds::stream::token - 对象名 'q_a_sn_relation' 无效。 code=208 ，纯小写的就不会报问题，大写的开头都会这样，不知道是不是我的问题。

**Comment by zhuxiujia** [comment]
> 新人刚接触rust，有个疑问。数据库名字如果是大写加上下划线，会报数据库对象名无效，数据库名字也会被自动修改。本身数据库名字：crud!(QA_snRelation{}); 结果输出：2022-11-09 10:02:05.2500148 ERROR tiberius::tds::stream::token - 对象名 'q_a_sn_relation' 无效。 code=208 ，纯小写的就不会报问题，大写的开头都会这样，不知道是不是我的问题。


你可以自定义表名称  例如  crud!(Table{},"QA_snRelation") 或者 impl_select!(Table{ method.....},"QA_snRelation")

**Comment by Vjze** [comment]
> > 新人刚接触rust，有个疑问。数据库名字如果是大写加上下划线，会报数据库对象名无效，数据库名字也会被自动修改。本身数据库名字：crud！（QA_snRelation{}）;结果输出：2022-11-09 10：02：05.2500148 错误 提比略：：tds：：流：：令牌 - 对象名 'q_a_sn_relation' 无效。code=208 ，纯小写的就不会报问题，大写的开头都会这样，不知道是不是我的问题。
> 
> 你可以自定义表名称 例如 crud！（Table{}，“QA_snRelation”） 或者 impl_select！（Table{ method.....}，“QA_snRelation”）

感谢大佬，怪我没仔细看官网文档介绍，刚发现文档里面是有说明的.....
