### ISSUE TITLE
日志过滤级别设置未生效

### ISSUE THREAD

**Issue by LayneYy** [rbatis/rbatis#326]
已经将日志过滤级别设置成了 `LevelFilter::Error`,但是info级别的sql却打印了出来,`LevelFilter::Off`是可以生效的
```rust
async fn init() -> Result<Rbatis> {
    let c = &get_config().await.mysql;
    let mut rb = Rbatis::new();
    let opt = MySqlConnectOptions::new()
        .host(&c.host)
        .port(c.port)
        .username(&c.username)
        .password(&c.password)
        .database(&c.database);
    rb.init_opt(MysqlDriver {}, opt)?;
    let log_opts = RbatisLogPlugin ::default();
    log_opts.set_level_filter(LevelFilter::Error);
    rb.set_log_plugin(log_opts);
    Ok(rb)
}

2022-12-05T19:25:16.149156Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] Fetch  ==> select * from bank_card_issue where card_bin = left(?, card_bin_length) order by card_bin_length desc limit 1
                                                      [rbatis]                      Args   ==> ["6259691600759410"]    
2022-12-05T19:25:16.171894Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] ReturnRows <== 1  
```

另外,怎么设置连接池的参数,比如最小链接数,最大连接数,链接存活时间之类的

**Comment by LayneYy** [comment]
> > 已经将日志过滤级别设置成了 `LevelFilter::Error`,但是info级别的sql却打印了出来,`LevelFilter::Off`是可以生效的
> > ```rust
> > async fn init() -> Result<Rbatis> {
> >     let c = &get_config().await.mysql;
> >     let mut rb = Rbatis::new();
> >     let opt = MySqlConnectOptions::new()
> >         .host(&c.host)
> >         .port(c.port)
> >         .username(&c.username)
> >         .password(&c.password)
> >         .database(&c.database);
> >     rb.init_opt(MysqlDriver {}, opt)?;
> >     let log_opts = RbatisLogPlugin ::default();
> >     log_opts.set_level_filter(LevelFilter::Error);
> >     rb.set_log_plugin(log_opts);
> >     Ok(rb)
> > }
> > 
> > 2022-12-05T19:25:16.149156Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] Fetch  ==> select * from bank_card_issue where card_bin = left(?, card_bin_length) order by card_bin_length desc limit 1
> >                                                       [rbatis]                      Args   ==> ["6259691600759410"]    
> > 2022-12-05T19:25:16.171894Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] ReturnRows <== 1  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外,怎么设置连接池的参数,比如最小链接数,最大连接数,链接存活时间之类的
> 
> rb.get_pool().unwrap().resize(10)

这是就是设置连接池大小,其他的一些连接池属性目前还没有支持吧

**Comment by zhuxiujia** [comment]
> > > 已经将日志过滤级别设置成了 `LevelFilter::Error`,但是info级别的sql却打印了出来,`LevelFilter::Off`是可以生效的
> > > ```rust
> > > async fn init() -> Result<Rbatis> {
> > >     let c = &get_config().await.mysql;
> > >     let mut rb = Rbatis::new();
> > >     let opt = MySqlConnectOptions::new()
> > >         .host(&c.host)
> > >         .port(c.port)
> > >         .username(&c.username)
> > >         .password(&c.password)
> > >         .database(&c.database);
> > >     rb.init_opt(MysqlDriver {}, opt)?;
> > >     let log_opts = RbatisLogPlugin ::default();
> > >     log_opts.set_level_filter(LevelFilter::Error);
> > >     rb.set_log_plugin(log_opts);
> > >     Ok(rb)
> > > }
> > > 
> > > 2022-12-05T19:25:16.149156Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] Fetch  ==> select * from bank_card_issue where card_bin = left(?, card_bin_length) order by card_bin_length desc limit 1
> > >                                                       [rbatis]                      Args   ==> ["6259691600759410"]    
> > > 2022-12-05T19:25:16.171894Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] ReturnRows <== 1  
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 另外,怎么设置连接池的参数,比如最小链接数,最大连接数,链接存活时间之类的
> > 
> > 
> > rb.get_pool().unwrap().resize(10)
> 
> 这是就是设置连接池大小,其他的一些连接池属性目前还没有支持吧

目前支持动态设置最大连接数，其他属性暂不支持，以后应该会优化这块内容

**Comment by LayneYy** [comment]
> > > > 已经将日志过滤级别设置成了 `LevelFilter::Error`,但是info级别的sql却打印了出来,`LevelFilter::Off`是可以生效的
> > > > ```rust
> > > > async fn init() -> Result<Rbatis> {
> > > >     let c = &get_config().await.mysql;
> > > >     let mut rb = Rbatis::new();
> > > >     let opt = MySqlConnectOptions::new()
> > > >         .host(&c.host)
> > > >         .port(c.port)
> > > >         .username(&c.username)
> > > >         .password(&c.password)
> > > >         .database(&c.database);
> > > >     rb.init_opt(MysqlDriver {}, opt)?;
> > > >     let log_opts = RbatisLogPlugin ::default();
> > > >     log_opts.set_level_filter(LevelFilter::Error);
> > > >     rb.set_log_plugin(log_opts);
> > > >     Ok(rb)
> > > > }
> > > > 
> > > > 2022-12-05T19:25:16.149156Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] Fetch  ==> select * from bank_card_issue where card_bin = left(?, card_bin_length) order by card_bin_length desc limit 1
> > > >                                                       [rbatis]                      Args   ==> ["6259691600759410"]    
> > > > 2022-12-05T19:25:16.171894Z  INFO rbatis::plugin::log: [rbatis] [442406445615550464] ReturnRows <== 1  
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 另外,怎么设置连接池的参数,比如最小链接数,最大连接数,链接存活时间之类的
> > > 
> > > 
> > > rb.get_pool().unwrap().resize(10)
> > 
> > 
> > 这是就是设置连接池大小,其他的一些连接池属性目前还没有支持吧
> 
> 目前支持动态设置最大连接数，其他属性暂不支持，以后应该会优化这块内容

感谢大佬耐心解答,java coder,刚接触rust不久.看到这个库太亲切了
