### ISSUE TITLE
Add example for join tables and relationship in readme

### ISSUE THREAD

**Issue by insanebaba** [rbatis/rbatis#33]
Can you add a join example in readme? Using wrapper and macro ?
1. One to many ? 
     For example **  Author -> vec(Books)  **
2. Many to Many ? With join table 
     For example **dish - dish_allergy - allergy**

**Comment by zhuxiujia** [comment]
> Can you add a join example in readme? Using wrapper and macro ?
> 
> 1. One to many ?
>    For example **  Author -> vec(Books)  **
> 2. Many to Many ? With join table
>    For example **dish - dish_allergy - allergy**

i add test on example/src/crud_test.rs

```rust
#[py_sql(rbatis, "SELECT a1.name as name,a2.create_time as create_time FROM test.biz_activity a1,biz_activity a2 where a1.id=a2.id and a1.name=#{name}")]
    fn join_select(rbatis: &Rbatis, name: &str) -> Option<Vec<BizActivity>> {}
    #[async_std::test]
    pub async fn test_join() {
        fast_log::log::init_log("requests.log", &RuntimeType::Std);
        RB.link("mysql://root:123456@localhost:3306/test").await.unwrap();
        let results=join_select(&RB,"test").await.unwrap();
        println!("data: {:?}",results);
    }
```
