### ISSUE TITLE
如何实in,notin之类的查询？

### ISSUE THREAD

**Issue by male110** [rbatis/rbatis#334]

**Comment by zhuxiujia** [comment]
> _No description provided._

可以使用impl_select!

**Comment by male110** [comment]
impl_select!(User{select_by_ids(table_column:&str,ids:Vec<u64>)=>
     "`where id in #{ids}"});


2022-12-16 08:08:54.1987024 INFO rbatis::plugin::log - [rbatis] [446222499097743360] Fetch  ==> `select id,username from user where id in ?
                                                      [rbatis]                      Args   ==> [[10000,10001]]
thread 'actix-rt|system:0|arbiter:2' panicked at 'called `Result::unwrap()` on an `Err` value: MyError { code: 400, err_msg: "1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`select id,username from user where id in ?' at line 1" }', src\controller\test_controller.rs:21:2022-12-16 08:08:54.1989699 ERROR G:\Users\whm\.cargo\registry\src\github.com-1ecc6299db9ec823\rbatis-4.0.43\src\plugin\log.rs:36 [rbatis] [446222499097743360] ReturnError  <== 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`select id,username from user where id in ?' at line 1
26

**Comment by male110** [comment]
`impl_select!(User{select_by_ids(table_column:&str,ids:Vec<u64>)=>
     " ` where id in (`
          trim ',': for _,item in ids:
             #{item},
          `)`"});`
