### ISSUE TITLE
Sqlite collation不起作用

### ISSUE THREAD

**Issue by t1000ln** [rbatis/rbatis#342]
我使用Rbatis连接Sqlite文件数据库，希望设置排序规则，但是没生效，请大神帮忙看看怎么回事？
初始化数据库连接：
```rust
pub static R_BATIS: Lazy<Rbatis> = Lazy::new(|| Rbatis::new());

pub fn connect_db(data_path: &str) {
    let db_file_path = PathBuf::from(data_path).join(SQLITE_FILE_NAME);
    let db_path = format!("sqlite://{}", db_file_path.to_str().expect("无法处理数据库文件路径！"));
    let db_path = db_path.as_str();

    debug!("数据库文件路径为：{}", db_path);

    // R_BATIS.init(SqliteDriver {}, db_path).unwrap();
    let mut opts = SqliteConnectOptions::new().create_if_missing(true)
        .collation("pinyin", |s1, s2| chinese_str_to_ascii(s1).cmp(&chinese_str_to_ascii(s2)));
    opts.set_uri(db_path).unwrap();

    R_BATIS.init_opt(SqliteDriver {}, opts).unwrap();
}

pub fn get_db() -> &'static Rbatis {
    R_BATIS.deref()
}
```
执行测试:
```rust
#[tokio::test]
pub async fn test_get_users() {
        fast_log::init(fast_log::Config::new().console()).expect("rbatis init fail");
        let _ = connect_db("cache");
        let mut rb = get_db();
        let resp = rb.fetch("select count(1) as count from v_app_users  order by u_name collate pinyin", vec![]).await.unwrap();
        println!("查询到的结果为：{:?}", resp);
        assert!(true)
}
```
测试结果：
```
2022-12-29 23:28:17.062108248 INFO rbatis::plugin::log - [rbatis] [451044115216470016] Fetch  ==> select count(1) as count from v_app_users  order by u_name collate pinyin
                                                      [rbatis]                      Args   ==> []

called `Result::unwrap()` on an `Err` value: E("no such collation sequence: pinyin")
```

**Comment by t1000ln** [comment]
补充一下，用`rusqlite`是可以正常使用自定义的`pinyin`排序规则的：
```rust
    let db = Connection::open(db_file_path).unwrap();
    db.create_collation("pinyin", |s1, s2| {
         chinese_str_to_ascii(s1).cmp(&chinese_str_to_ascii(s2))
    });
    
    let mut ps = db.prepare("select u_name from v_app_users order by u_name collate pinyin").unwrap();
    let rows = ps.query_map([], |row| {
         row.get(0)
    }).unwrap();
    let mut names: Vec<String> = Vec::new();
    for row in rows {
         names.push(row.unwrap());
    }
    println!("names: {:?}", names);
```

**Comment by zhuxiujia** [comment]
> 我使用Rbatis连接Sqlite文件数据库，希望设置排序规则，但是没生效，请大神帮忙看看怎么回事？ 初始化数据库连接：
> 
> ```rust
> pub static R_BATIS: Lazy<Rbatis> = Lazy::new(|| Rbatis::new());
> 
> pub fn connect_db(data_path: &str) {
>     let db_file_path = PathBuf::from(data_path).join(SQLITE_FILE_NAME);
>     let db_path = format!("sqlite://{}", db_file_path.to_str().expect("无法处理数据库文件路径！"));
>     let db_path = db_path.as_str();
> 
>     debug!("数据库文件路径为：{}", db_path);
> 
>     // R_BATIS.init(SqliteDriver {}, db_path).unwrap();
>     let mut opts = SqliteConnectOptions::new().create_if_missing(true)
>         .collation("pinyin", |s1, s2| chinese_str_to_ascii(s1).cmp(&chinese_str_to_ascii(s2)));
>     opts.set_uri(db_path).unwrap();
> 
>     R_BATIS.init_opt(SqliteDriver {}, opts).unwrap();
> }
> 
> pub fn get_db() -> &'static Rbatis {
>     R_BATIS.deref()
> }
> ```
> 
> 执行测试:
> 
> ```rust
> #[tokio::test]
> pub async fn test_get_users() {
>         fast_log::init(fast_log::Config::new().console()).expect("rbatis init fail");
>         let _ = connect_db("cache");
>         let mut rb = get_db();
>         let resp = rb.fetch("select count(1) as count from v_app_users  order by u_name collate pinyin", vec![]).await.unwrap();
>         println!("查询到的结果为：{:?}", resp);
>         assert!(true)
> }
> ```
> 
> 测试结果：
> 
> ```
> 2022-12-29 23:28:17.062108248 INFO rbatis::plugin::log - [rbatis] [451044115216470016] Fetch  ==> select count(1) as count from v_app_users  order by u_name collate pinyin
>                                                       [rbatis]                      Args   ==> []
> 
> called `Result::unwrap()` on an `Err` value: E("no such collation sequence: pinyin")
> ```



> 

```rust
pub static R_BATIS: Lazy<Rbatis> = Lazy::new(|| Rbatis::new());

pub fn connect_db(data_path: &str) {
    let db_file_path = PathBuf::from(data_path).join(SQLITE_FILE_NAME);
    let db_path = format!("sqlite://{}", db_file_path.to_str().expect("无法处理数据库文件路径！"));
    let db_path = db_path.as_str();

    debug!("数据库文件路径为：{}", db_path);

    // R_BATIS.init(SqliteDriver {}, db_path).unwrap();
    let mut opts = SqliteConnectOptions::new().create_if_missing(true);
    opts.set_uri(db_path).unwrap();
    opts=opts.collation("pinyin", |s1, s2| chinese_str_to_ascii(s1).cmp(&chinese_str_to_ascii(s2)));

    R_BATIS.init_opt(SqliteDriver {}, opts).unwrap();
}

pub fn get_db() -> &'static Rbatis {
    R_BATIS.deref()
}
```

**Comment by t1000ln** [comment]
换过设置顺序了，不行。我昨天粗略跟了一下源码，好像连接池初始化的时候根本就没有调用`collation`相关的逻辑，如果不是连接池，单独调用`SqliteConnectOptions`的`connect`方法，倒是会执行`create_collation`的逻辑过程。

**Comment by t1000ln** [comment]
@zhuxiujia 多谢回复，我试了调整设置顺序，还是不行。

直接调用`SqliteConnectOptions.connect()`方法，在`SqliteConnectOptions`中定义的`collation`生效了，但这样不能使用连接池和宏了，这是否BUG？
```rust
let rb: &Rbatis = get_db();
let pool = rb.get_pool().unwrap();
let mut conn = pool.manager.option.connect().await?;
let result = conn.get_values("select u_name from v_app_users order by u_name collate pinyin", vec![]).await?;
```

**Comment by t1000ln** [comment]
@zhuxiujia 多谢回复，我试了调整设置顺序，还是不行。

直接调用`SqliteConnectOptions.connect()`方法，在`SqliteConnectOptions`中定义的`collation`生效了，但这样不能使用连接池和宏了，这是否BUG？
```rust
let rb: &Rbatis = get_db();
let pool = rb.get_pool().unwrap();
let mut conn = pool.manager.option.connect().await?;
let result = conn.get_values("select u_name from v_app_users order by u_name collate pinyin", vec![]).await?;
```

**Comment by zhuxiujia** [comment]
> @zhuxiujia 多谢回复，我试了调整设置顺序，还是不行。
> 
> 直接调用`SqliteConnectOptions.connect()`方法，在`SqliteConnectOptions`中定义的`collation`生效了，但这样不能使用连接池和宏了，这是否BUG？
> 
> ```rust
> let rb: &Rbatis = get_db();
> let pool = rb.get_pool().unwrap();
> let mut conn = pool.manager.option.connect().await?;
> let result = conn.get_values("select u_name from v_app_users order by u_name collate pinyin", vec![]).await?;
> ```

执行一下 cargo update 可以解决这个问题
