### ISSUE TITLE
为什么 ` 字符没有在生成代码中去除掉？

### ISSUE THREAD

**Issue by artorias1024** [rbatis/rbatis#348]
if { (&arg["do_count"]).op_eq(&true) }.to_owned().into() {
            sql.push_str(" count(1) from ( ");
            sql.push_str(
                " SELECT `\n        ` '${rate_label}' as rate_label, "
                    .replacen("${rate_label}", &{ &arg["rate_label"] }.as_sql(), 1)
                    .as_str(),
            );
            for (index, val) in { &arg["cid"] } {
                sql.push_str("${val} as cid".replacen("${val}", &{ val }.as_sql(), 1).as_str());
            }

===== 
以前的版本中没有出现这个问题，今天更新版本后生产环境全面报错。。。

**Comment by artorias1024** [comment]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/82564604/210966462-4c926186-6c60-44cd-abb9-dcfaeadedc2f.png">

**Comment by artorias1024** [comment]
已知在4.0.39版本中未出现上述问题

**Comment by zhuxiujia** [comment]
> 已知在4.0.39版本中未出现上述问题

cargo update 更新后即可修复
