### ISSUE TITLE
fetch 执行sql似乎有问题

### ISSUE THREAD

**Issue by 1926752325** [rbatis/rbatis#351]
```rust
use rbatis::Rbatis;
use rbdc_sqlite::driver::SqliteDriver;
use rbs::to_value;

#[tokio::main]
async fn main() -> Result<(), rbatis::Error> {
    fast_log::init(fast_log::Config::new().console()).expect("rbatis init fail");
    let rb = Rbatis::new();
    let mut db_path = std::env::var("DATABASE_URL");
    if db_path.is_err() {
        db_path = Ok("sqlite://ve.sqlite?mode=rwc".to_string());
    }
    rb.init(SqliteDriver {}, db_path.unwrap().as_str()).unwrap();

    let table_name = "user";
    let value = rb.clone().fetch("select * from ? ", vec![to_value!(table_name)]).await.unwrap();
    let x = value.as_array().unwrap();
    dbg!(&x);

    Ok(())
}
```
执行结果
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("near \"?\": syntax error")', examples\example1.rs:16:89
stack backtrace:
2023-01-10 14:58:42.206149 INFO rbatis::plugin::log - [rbatis] [455264529362849792] Fetch  ==> select * from ? 
                                                      [rbatis]                      Args   ==> ["user"]
2023-01-10 14:58:42.2064139 ERROR C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\rbatis-4.0.44\src\plugin\log.rs:39 [rbatis] [455264529362849792] ReturnError  <== near "?": syntax error
   0: std::panicking::begin_panic_handler
             at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\core\src\panicking.rs:64
   2: core::result::unwrap_failed
             at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\core\src\result.rs:1790
   3: enum2$<core::result::Result<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> > >::unwrap<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> >
             at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc\library\core\src\result.rs:1112
   4: example1::main::async_block$0
             at .\examples\example1.rs:16
   5: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<example1::main::async_block_env$0> >
             at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\park.rs:283
   6: tokio::runtime::coop::with_budget
             at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\coop.rs:102
   7: tokio::runtime::coop::budget
             at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\coop.rs:68
   8: tokio::runtime::park::CachedParkThread::block_on<enum2$<example1::main::async_block_env$0> >
             at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\park.rs:283
   9: tokio::runtime::context::BlockingRegionGuard::block_on<enum2$<example1::main::async_block_env$0> >
             at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\context.rs:295
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<example1::main::async_block_env$0> >
             at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\scheduler\multi_thread\mod.rs:66
  11: tokio::runtime::runtime::Runtime::block_on<enum2$<example1::main::async_block_env$0> >
             at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\runtime.rs:284
  12: example1::main
             at .\examples\example1.rs:20
  13: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<rbdc::error::Error> > > (*)(),tuple$<> >
             at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc\library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\example1.exe` (exit code: 101)
```
sql行改成这样就可以了
```rust
let value = rb.clone().fetch(format!("select * from {} ", table_name).as_str(), vec![]).await.unwrap();
```
结果
```
2023-01-10 15:01:46.6659421 INFO rbatis::plugin::log - [rbatis] [455265303039971328] Fetch  ==> select * from user 
                                                      [rbatis]                      Args   ==> []
[examples\example1.rs:18] 2023-01-10 15:01:46.6665601 INFO rbatis::plugin::log - [rbatis] [455265303039971328] ReturnRows <== 1
&x = [
    Map(
        {
            String(
                "balance",
            ): F64(
                100.0,
            ),
            String(
                "username",
            ): String(
                "test",
            ),
            String(
                "id",
            ): I64(
                1,
            ),
        },
    ),
]
```

**Comment by zhuxiujia** [comment]
> ```rust
> use rbatis::Rbatis;
> use rbdc_sqlite::driver::SqliteDriver;
> use rbs::to_value;
> 
> #[tokio::main]
> async fn main() -> Result<(), rbatis::Error> {
>     fast_log::init(fast_log::Config::new().console()).expect("rbatis init fail");
>     let rb = Rbatis::new();
>     let mut db_path = std::env::var("DATABASE_URL");
>     if db_path.is_err() {
>         db_path = Ok("sqlite://ve.sqlite?mode=rwc".to_string());
>     }
>     rb.init(SqliteDriver {}, db_path.unwrap().as_str()).unwrap();
> 
>     let table_name = "user";
>     let value = rb.clone().fetch("select * from ? ", vec![to_value!(table_name)]).await.unwrap();
>     let x = value.as_array().unwrap();
>     dbg!(&x);
> 
>     Ok(())
> }
> ```
> 
> 执行结果
> 
> ```
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("near \"?\": syntax error")', examples\example1.rs:16:89
> stack backtrace:
> 2023-01-10 14:58:42.206149 INFO rbatis::plugin::log - [rbatis] [455264529362849792] Fetch  ==> select * from ? 
>                                                       [rbatis]                      Args   ==> ["user"]
> 2023-01-10 14:58:42.2064139 ERROR C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\rbatis-4.0.44\src\plugin\log.rs:39 [rbatis] [455264529362849792] ReturnError  <== near "?": syntax error
>    0: std::panicking::begin_panic_handler
>              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\std\src\panicking.rs:575
>    1: core::panicking::panic_fmt
>              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\core\src\panicking.rs:64
>    2: core::result::unwrap_failed
>              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\core\src\result.rs:1790
>    3: enum2$<core::result::Result<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> > >::unwrap<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> >
>              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc\library\core\src\result.rs:1112
>    4: example1::main::async_block$0
>              at .\examples\example1.rs:16
>    5: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<example1::main::async_block_env$0> >
>              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\park.rs:283
>    6: tokio::runtime::coop::with_budget
>              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\coop.rs:102
>    7: tokio::runtime::coop::budget
>              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\coop.rs:68
>    8: tokio::runtime::park::CachedParkThread::block_on<enum2$<example1::main::async_block_env$0> >
>              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\park.rs:283
>    9: tokio::runtime::context::BlockingRegionGuard::block_on<enum2$<example1::main::async_block_env$0> >
>              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\context.rs:295
>   10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<example1::main::async_block_env$0> >
>              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\scheduler\multi_thread\mod.rs:66
>   11: tokio::runtime::runtime::Runtime::block_on<enum2$<example1::main::async_block_env$0> >
>              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\runtime.rs:284
>   12: example1::main
>              at .\examples\example1.rs:20
>   13: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<rbdc::error::Error> > > (*)(),tuple$<> >
>              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc\library\core\src\ops\function.rs:507
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> error: process didn't exit successfully: `target\debug\examples\example1.exe` (exit code: 101)
> ```
> 
> sql行改成这样就可以了
> 
> ```rust
> let value = rb.clone().fetch(format!("select * from {} ", table_name).as_str(), vec![]).await.unwrap();
> ```
> 
> 结果
> 
> ```
> 2023-01-10 15:01:46.6659421 INFO rbatis::plugin::log - [rbatis] [455265303039971328] Fetch  ==> select * from user 
>                                                       [rbatis]                      Args   ==> []
> [examples\example1.rs:18] 2023-01-10 15:01:46.6665601 INFO rbatis::plugin::log - [rbatis] [455265303039971328] ReturnRows <== 1
> &x = [
>     Map(
>         {
>             String(
>                 "balance",
>             ): F64(
>                 100.0,
>             ),
>             String(
>                 "username",
>             ): String(
>                 "test",
>             ),
>             String(
>                 "id",
>             ): I64(
>                 1,
>             ),
>         },
>     ),
> ]
> ```

sqlite不支持 表名 使用 ？ 占位符，这是数据库的差异，和orm无关

**Comment by 1926752325** [comment]
> > ```rust
> > use rbatis::Rbatis;
> > use rbdc_sqlite::driver::SqliteDriver;
> > use rbs::to_value;
> > 
> > #[tokio::main]
> > async fn main() -> Result<(), rbatis::Error> {
> >     fast_log::init(fast_log::Config::new().console()).expect("rbatis init fail");
> >     let rb = Rbatis::new();
> >     let mut db_path = std::env::var("DATABASE_URL");
> >     if db_path.is_err() {
> >         db_path = Ok("sqlite://ve.sqlite?mode=rwc".to_string());
> >     }
> >     rb.init(SqliteDriver {}, db_path.unwrap().as_str()).unwrap();
> > 
> >     let table_name = "user";
> >     let value = rb.clone().fetch("select * from ? ", vec![to_value!(table_name)]).await.unwrap();
> >     let x = value.as_array().unwrap();
> >     dbg!(&x);
> > 
> >     Ok(())
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 执行结果
> > ```
> > thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("near \"?\": syntax error")', examples\example1.rs:16:89
> > stack backtrace:
> > 2023-01-10 14:58:42.206149 INFO rbatis::plugin::log - [rbatis] [455264529362849792] Fetch  ==> select * from ? 
> >                                                       [rbatis]                      Args   ==> ["user"]
> > 2023-01-10 14:58:42.2064139 ERROR C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\rbatis-4.0.44\src\plugin\log.rs:39 [rbatis] [455264529362849792] ReturnError  <== near "?": syntax error
> >    0: std::panicking::begin_panic_handler
> >              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\std\src\panicking.rs:575
> >    1: core::panicking::panic_fmt
> >              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\core\src\panicking.rs:64
> >    2: core::result::unwrap_failed
> >              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc/library\core\src\result.rs:1790
> >    3: enum2$<core::result::Result<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> > >::unwrap<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> >
> >              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc\library\core\src\result.rs:1112
> >    4: example1::main::async_block$0
> >              at .\examples\example1.rs:16
> >    5: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<example1::main::async_block_env$0> >
> >              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\park.rs:283
> >    6: tokio::runtime::coop::with_budget
> >              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\coop.rs:102
> >    7: tokio::runtime::coop::budget
> >              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\coop.rs:68
> >    8: tokio::runtime::park::CachedParkThread::block_on<enum2$<example1::main::async_block_env$0> >
> >              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\park.rs:283
> >    9: tokio::runtime::context::BlockingRegionGuard::block_on<enum2$<example1::main::async_block_env$0> >
> >              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\context.rs:295
> >   10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<example1::main::async_block_env$0> >
> >              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\scheduler\multi_thread\mod.rs:66
> >   11: tokio::runtime::runtime::Runtime::block_on<enum2$<example1::main::async_block_env$0> >
> >              at C:\Users\name\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.23.0\src\runtime\runtime.rs:284
> >   12: example1::main
> >              at .\examples\example1.rs:20
> >   13: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<rbdc::error::Error> > > (*)(),tuple$<> >
> >              at /rustc/0468a00ae3fd6ef1a6a0f9eaf637d7aa9e604acc\library\core\src\ops\function.rs:507
> > note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> > error: process didn't exit successfully: `target\debug\examples\example1.exe` (exit code: 101)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sql行改成这样就可以了
> > ```rust
> > let value = rb.clone().fetch(format!("select * from {} ", table_name).as_str(), vec![]).await.unwrap();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 结果
> > ```
> > 2023-01-10 15:01:46.6659421 INFO rbatis::plugin::log - [rbatis] [455265303039971328] Fetch  ==> select * from user 
> >                                                       [rbatis]                      Args   ==> []
> > [examples\example1.rs:18] 2023-01-10 15:01:46.6665601 INFO rbatis::plugin::log - [rbatis] [455265303039971328] ReturnRows <== 1
> > &x = [
> >     Map(
> >         {
> >             String(
> >                 "balance",
> >             ): F64(
> >                 100.0,
> >             ),
> >             String(
> >                 "username",
> >             ): String(
> >                 "test",
> >             ),
> >             String(
> >                 "id",
> >             ): I64(
> >                 1,
> >             ),
> >         },
> >     ),
> > ]
> > ```
> 
> sqlite不支持 表名 使用 ？ 占位符，这是数据库的差异，和orm无关

可以帮我删掉这个issue吗,用错帐号了,这个账号会泄露我的隐私
