### ISSUE TITLE
事务疑问

### ISSUE THREAD

**Issue by male110** [rbatis/rbatis#353]
比如我在事务中有5次操作。每次操作后我都要判断是否成功，不成功提交吗？
let op1=操作数据库；
if op1.is_err(){
  回滚
}
let op2=操作数据库；
if op2.is_err(){
  回滚
}
let op3=操作数据库；
if op3.is_err(){
  回滚
}
let op4=操作数据库；
if op4.is_err(){
  回滚
}
let op5=操作数据库；
if op5.is_err(){
  回滚
}
提交事务
这样写是不是很啰嗦？

**Comment by zhuxiujia** [comment]
可以使用defer_async()函数处理这个业务

**Comment by male110** [comment]
具体怎么用？

**Comment by zhuxiujia** [comment]
> 具体怎么用？

[example](https://github.com/rbatis/rbatis/blob/master/example/src/transaction.rs)
