### ISSUE TITLE
使用RB.fetch_page的后，如果model属性的名字和数据库的字段名【大小写】不一致，会转换不了。

### ISSUE THREAD

**Issue by RisingStar20** [rbatis/rbatis#36]

**Comment by zhuxiujia** [comment]
> _No description provided._

是的，Rust的命名规范是蛇形的下划线小写，和表字段应该是一模一样的。  理论上 字段应该和表字段严格一样，比较严谨一些

**Comment by RisingStar20** [comment]
虽然说执行严格标准是好事，但是易用性、平民化好一点吧，在转换称model的时候，忽略大小写就好了。
而在使用RB.fetch_page_by_wrapper的就没这个问题。
