### ISSUE TITLE
can't distinguish Raw identifiers when use in fileds.

### ISSUE THREAD

**Issue by umaYnit** [rbatis/rbatis#38]
eg:
``` rust
#[derive(CRUDEnable, Debug, Clone, Serialize, Deserialize)]
pub struct SomeThing {
    pub id: String,
    pub r#type: String,
}
```
it will generate sql like `SELECT id,r#type FROM SomeThing ` .

by the way,  would i customize the table name while using the macro `CRUDEnable` ?

**Comment by zhuxiujia** [comment]
> eg:
> 
> ```rust
> #[derive(CRUDEnable, Debug, Clone, Serialize, Deserialize)]
> pub struct SomeThing {
>     pub id: String,
>     pub r#type: String,
> }
> ```
> 
> it will generate sql like `SELECT id,r#type FROM SomeThing ` .
> 
> by the way, would i customize the table name while using the macro `CRUDEnable` ?


it will be   sql like `SELECT id,r#type FROM some_thing ` .

**Comment by zhuxiujia** [comment]
> eg:
> 
> ```rust
> #[derive(CRUDEnable, Debug, Clone, Serialize, Deserialize)]
> pub struct SomeThing {
>     pub id: String,
>     pub r#type: String,
> }
> ```
> 
> it will generate sql like `SELECT id,r#type FROM SomeThing ` .
> 
> by the way, would i customize the table name while using the macro `CRUDEnable` ?

also,you can   customize the table name  using impl CRUDEnable trait replace #[derive(CRUDEnable)]

**Comment by umaYnit** [comment]
I expect the field `r#type` can be recognized as `type` in sql, because the field in the database is `type`.

**Comment by zhuxiujia** [comment]
> I expect the field `r#type` can be recognized as `type` in sql, because the field in the database is `type`.

you need impl CRUDEnable and rewrite  CRUDEnable's method fn table_columns()

**Comment by umaYnit** [comment]
But the `r#` is the **Raw identifiers** and should not parsing in sql.  
[Raw identifiers](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/raw-identifiers.html)

**Comment by zhuxiujia** [comment]
> But i think the `r#` is the **Raw identifiers** and should not parsing in sql.
> [Raw identifiers](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/raw-identifiers.html)

Parse sql column the dependency macro or ImpL Trait, if you choose ImpL Trait then any fields can be customized

**Comment by zhuxiujia** [comment]
i will close this issue, If you have any questions, I will reply in time
