### ISSUE TITLE
If the last character of the string is the letter T, an error will occur.

### ISSUE THREAD

**Issue by gb24800** [rbatis/rbatis#388]
pub struct Test {
    pub id: Option<u64>,
    pub str_field: Option<String>,
    //...
}

let test = Test {
    id: Some(100),
    str_field: "111111111111111T",
};

Test::update_by_column(&mut rb, &test, "id").await?;

error like:
panicked at 'called `Result::unwrap()` on an `Err` value: E("TooShort")', path/to/rbdc-mysql-4.2.2/src/types/value.rs:163:71
panicked at 'called `Result::unwrap()` on an `Err` value: E("OutOfRangeHour")', path/to/rbdc-mysql-4.2.2/src/types/value.rs:163:71

value.rs:163
"Time" => Time::from(fastdate::Time::from_str(&v).unwrap()).encode(buf),

**Comment by zhuxiujia** [comment]
> pub struct Test { pub id: Option, pub str_field: Option, //... }
> 
> let test = Test { id: Some(100), str_field: "111111111111111T", };
> 
> Test::update_by_column(&mut rb, &test, "id").await?;
> 
> error like: panicked at 'called `Result::unwrap()` on an `Err` value: E("TooShort")', path/to/rbdc-mysql-4.2.2/src/types/value.rs:163:71 panicked at 'called `Result::unwrap()` on an `Err` value: E("OutOfRangeHour")', path/to/rbdc-mysql-4.2.2/src/types/value.rs:163:71
> 
> value.rs:163 "Time" => Time::from(fastdate::Time::from_str(&v).unwrap()).encode(buf),

use rbatis="4.3"  will be fix this
