### ISSUE TITLE
orm-crud will not add ` to tablename like order

### ISSUE THREAD

**Issue by Evanpatchouli** [rbatis/rbatis#389]
if I define a struct named Order and impl crud for it, when I do select actions, it will show 'ReturnError  <== near "order": syntax error'

**Comment by Evanpatchouli** [comment]
> 

yes, i have already had a order table, i use like this `Order::insert(&mut rb, &order).await`: 
[rbatis] [486550222370115584] Exec   ==> into order (oid,bname,bphone,baddress,money,otype,lease,uid,stime,etime,cid) VALUES (?,??,?,?,?,?,?,?)
Error: [rbatis] [486550222370115584] Return
<== near "order": syntax error

i have to write raw sql to avoid this

**Comment by Evanpatchouli** [comment]
> > if I define a struct named Order and impl crud for it, when I do select actions, it will show 'ReturnError <== near "order": syntax error'
> 
> did you create table 'order' ?

yes, i have already had a order table, i use like this Order::insert(&mut rb, &order).await:
[rbatis] [486550222370115584] Exec ==> into order (oid,bname,bphone,baddress,money,otype,lease,uid,stime,etime,cid) VALUES (?,??,?,?,?,?,?,?)
Error: [rbatis] [486550222370115584] Return
<== near "order": syntax error

i have to write raw sql to avoid this

**Comment by Evanpatchouli** [comment]
> > > if I define a struct named Order and impl crud for it, when I do select actions, it will show 'ReturnError <== near "order": syntax error'
> > 
> > 
> > did you create table 'order' ?
> 
> yes, i have already had a order table, i use like this Order::insert(&mut rb, &order).await: [rbatis] [486550222370115584] Exec ==> into order (oid,bname,bphone,baddress,money,otype,lease,uid,stime,etime,cid) VALUES (?,??,?,?,?,?,?,?) Error: [rbatis] [486550222370115584] Return <== near "order": syntax error
> 
> i have to write raw sql to avoid this

Although "crud!(Order{}, "`order`");" will be OK, i think it is better that user has no need to do this.

**Comment by zhuxiujia** [comment]
> into order (oid,bname,bphone,baddress,money,otype,lease,uid,stime,etime,cid) VALUES (?,??,?,?,?,?,?,?)

Did you miss the keyword `insert into order (oid,bname,bphone,baddress,money,otype,lease,uid,stime,etime,cid) VALUES (?,??,?,?,?,?,?,?)` instead of `into order (oid,bname,bphone,baddress,money,otype,lease,uid,stime,etime,cid) VALUES (?,??,?,?,?,?,?,?)`
