### ISSUE TITLE
问下in_为啥后面要加下划线？

### ISSUE THREAD

**Issue by Silentdoer** [rbatis/rbatis#40]
rt

**Comment by zhuxiujia** [comment]
> rt

in 原本是rust的关键字，所以Rbatis的Wrapper 用了 in_array() 如果用r#in()的话太丑，所以同时可以调用in_和in_array

**Comment by Silentdoer** [comment]
好吧😂，不过感觉r#in也还OK，ide能够直接识别in然后自动完成填写
