### ISSUE TITLE
通过group by 查询的 sum(amount) as amount 无法使用 数字类型接收,只能使用String接收

### ISSUE THREAD

**Issue by Caisin** [rbatis/rbatis#400]
例如:
let sql="select uid,sum(amount) amount from user_order group by uid";
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StatOrder {
    pub uid: u32,
    pub amount: u64,
}

let ret=rb.query_decode::<Vec<StatOrder>>().await?;
将会出现下面的错误
Error: error while decoding value: invalid type: string "2", expected u64

**Comment by zhuxiujia** [comment]
sum(amount)  will be return  String data。This is to prevent loss of precision

**Comment by Caisin** [comment]
我的是整数列的时候,不用关心精度丢失问题,我可以选择让它返回数字,方便后续处理,不然还要把字符串转一下数字,处理起来就很麻烦了

**Comment by Caisin** [comment]
如果是小数列统计,可以选择用String作为接收参数
