### ISSUE TITLE
MySQL datetime query loses millisecond precision

### ISSUE THREAD

**Issue by gy0801151351** [rbatis/rbatis#404]
MySQL的datetime类型是支持 毫秒精度的, 只需要将字段类型设置为 datetime(3) 就能支持毫秒精度, 但是 rbdc-mysql驱动在读取datetime数据时, 把毫秒丢掉了. 

代码位置
rbdc-mysql-4.3.1 的 src/types/decode.rs 第143行~148行

`
pub(crate) fn decode_time_buf(_: u8, mut buf: &[u8]) -> Result<String, Error> {

    let hour = buf.get_u8();

    let minute = buf.get_u8();

    let seconds = buf.get_u8();

    Ok(format!("{:0>2}:{:0>2}:{:0>2}", hour, minute, seconds))

}
`

**Comment by zhuxiujia** [comment]
fix on rbdc-mysql="4.3.2"

**Comment by zhuxiujia** [comment]
this is support   `datetime(6)` and `datetime(3)`

**Comment by gy0801151351** [comment]
Thanks for replying so quickly.
