### ISSUE TITLE
Each Rbatis version update is not compatible with the original api

### ISSUE THREAD

**Issue by artorias1024** [rbatis/rbatis#408]
Why do we have to do a destructive iterative update every time
？？？？？？

**Comment by zhuxiujia** [comment]
> 

Small scale updates, mostly compatible with older versions

**Comment by artorias1024** [comment]
<img width="1322" alt="image" src="https://github.com/rbatis/rbatis/assets/82564604/3a52df93-7ef4-48f8-a68d-401da9eb9a84">

**Comment by zhuxiujia** [comment]
> <img alt="image" width="1322" src="https://user-images.githubusercontent.com/82564604/243952580-3a52df93-7ef4-48f8-a68d-401da9eb9a84.png">

This is an upgraded version of the dependent rust version. You only need to upgrade the Trust update to 1.70+

**Comment by artorias1024** [comment]
<img width="1695" alt="image" src="https://github.com/rbatis/rbatis/assets/82564604/a00b43ca-28a1-4cc4-8986-1e309ff63cb1">
ok,As a library, I don't think such an update would result in a good user experience

**Comment by zhuxiujia** [comment]
> <img alt="image" width="1695" src="https://user-images.githubusercontent.com/82564604/243956360-a00b43ca-28a1-4cc4-8986-1e309ff63cb1.png"> ok,As a library, I don't think such an update would result in a good user experience

new version renamed to  `RBatis`, Because older versions of names will prompt syntax warnings

**Comment by artorias1024** [comment]
I am really on the verge of collapse. I use rbatis as a core library and now I have to modify a lot of code to be compatible with the original business logic.

**Comment by zhuxiujia** [comment]
> I am really on the verge of collapse. I use rbatis as a core library and now I have to modify a lot of code to be compatible with the original business logic.

There are bound to be feature changes in the latest version, even minor changes to the api. If you want to fix a version, you should use Cargo.lock to lock the version of each dependent library

**Comment by zhuxiujia** [comment]
We should not be afraid to break change，It's about understanding what does that change bring

**Comment by artorias1024** [comment]
> We should not be afraid to break change，It's about understanding what does that change bring
