### ISSUE TITLE
use of unstable library feature 'once_cell'

### ISSUE THREAD

**Issue by liyan-ah** [rbatis/rbatis#409]
```
error[E0658]: use of unstable library feature 'once_cell'
 -->rbatis-4.3.6/src/plugin/object_id.rs:4:5
  |
4 | use std::sync::OnceLock;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information

```

here is part of  `Cargo.toml`:
```
[package]
edition = "2021"

[dependencies]
rbatis = {version="4.3", features=["debug_mode"]}
rbdc = "4.3"
rbdc-mysql = "4.3"
rbs = "4.3"
```

It's a bug? or what version works okay?

**Comment by zhuxiujia** [comment]
> ```
> error[E0658]: use of unstable library feature 'once_cell'
>  -->rbatis-4.3.6/src/plugin/object_id.rs:4:5
>   |
> 4 | use std::sync::OnceLock;
>   |     ^^^^^^^^^^^^^^^^^^^
>   |
>   = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
> ```
> 
> here is part of `Cargo.toml`:
> 
> ```
> [package]
> edition = "2021"
> 
> [dependencies]
> rbatis = {version="4.3", features=["debug_mode"]}
> rbdc = "4.3"
> rbdc-mysql = "4.3"
> rbs = "4.3"
> ```
> 
> It's a bug? or what version works okay?

it‘s stable feature. you should run `rustup update` to up rust compiler

**Comment by DarrenHou1993** [comment]
Have the some error . Can't to compile after update rust .

**Comment by zhuxiujia** [comment]
> run `rustup update` to up rust compiler

you need run `rustup update` to up rust compiler to v1.70+

**Comment by DarrenHou1993** [comment]
Thanks for your answer. But not work for me . 

## my info
```
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0 (90c541806 2023-05-31)
```
## the error
```
error[E0658]: use of unstable library feature 'once_cell'
  --> /Users/liang/.cargo/registry/src/github.com-1ecc6299db9ec823/rbdc-4.3.10/src/rt.rs:19:9
   |
19 |     use std::sync::OnceLock;
```
![image](https://github.com/rbatis/rbatis/assets/9291785/26699e2f-df32-4722-a6ca-1e5b291ec953)

**Comment by zhuxiujia** [comment]
> Thanks for your answer. But not work for me .
> 
> ## my info
> ```
> rustup 1.26.0 (5af9b9484 2023-04-05)
> info: This is the version for the rustup toolchain manager, not the rustc compiler.
> info: The currently active `rustc` version is `rustc 1.70.0 (90c541806 2023-05-31)
> ```
> 
> ## the error
> ```
> error[E0658]: use of unstable library feature 'once_cell'
>   --> /Users/liang/.cargo/registry/src/github.com-1ecc6299db9ec823/rbdc-4.3.10/src/rt.rs:19:9
>    |
> 19 |     use std::sync::OnceLock;
> ```
> 
> ![image](https://user-images.githubusercontent.com/9291785/251371124-26699e2f-df32-4722-a6ca-1e5b291ec953.png)

```
#[stable(feature = "once_cell", since = "1.70.0")]
pub struct OnceLock<T> {
    once: Once,
    // Whether or not the value is initialized is tracked by `once.is_completed()`.
    value: UnsafeCell<MaybeUninit<T>>,
    /// `PhantomData` to make sure dropck understands we're dropping T in our Drop impl.
    ///
    /// ```compile_fail,E0597
    /// use std::sync::OnceLock;
    ///
    /// struct A<'a>(&'a str);
    ///
    /// impl<'a> Drop for A<'a> {
    ///     fn drop(&mut self) {}
    /// }
    ///
    /// let cell = OnceLock::new();
    /// {
    ///     let s = String::new();
    ///     let _ = cell.set(A(&s));
    /// }
    /// ```
    _marker: PhantomData<T>,
}
```

**Comment by zhuxiujia** [comment]
did you run 
print
```
rustc --version
rustc 1.70.0
```
?

**Comment by DarrenHou1993** [comment]
Oh!!
```
➜  ~ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0 (90c541806 2023-05-31)`
➜  ~ rustc --version
rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball)
```
The rustc version was lower (installed by brew).  so i uninstall it . It's ok for now .   Thank you so much.
