### ISSUE TITLE
是否考虑用feature宏来条件编译

### ISSUE THREAD

**Issue by Silentdoer** [rbatis/rbatis#42]
现在好像是即便用了runtime-tokio也是会编译async-std

**Comment by zhuxiujia** [comment]
> 现在好像是即便用了runtime-tokio也是会编译async-std

你的配置是什么样的

**Comment by Silentdoer** [comment]
就只加了rbatis，然后default-feature是false，features用了runtime-tokio

**Comment by zhuxiujia** [comment]
> 就只加了rbatis，然后default-feature是false，features用了runtime-tokio

新版本会得到修复，并且我会给出详细 切换运行时的配置

**Comment by zhuxiujia** [comment]
> 就只加了rbatis，然后default-feature是false，features用了runtime-tokio

目前默认选择async_std主要是因为目前async_std1.6以上版本默认运行时为smol

smol是一个轻量而高效的异步runtime。它采用了对标准库进行扩展的方式，整个runtime只有大约1500行代码。作者stjepang大神是大名鼎鼎crossbeam的作者。而他之前参与tokio和async-std的开发的经验和思考，产生出了从头开始构建的smol这个库。实际上在达到和tokio以及async-std相似的性能的前提下，smol代码短线精悍，完全没有依赖mio库，API更加简单，并且没有unsafe代码！

而且smol 同时支持tokio和async_std 运行时切换，不会割裂运行时生态
[dependencies]smol = { version = "0.1", features = ["tokio02"] }

Rbatis也有计划 切换到 到默认的smol运行时，维护会更加简单

**Comment by zhuxiujia** [comment]
在1.7.23版本中，切换运行时应该是
```rust
async-std = { version = "1.6", features = ["attributes","tokio02"] }
```
