### ISSUE TITLE
failed to resolve: could not find `core_reexport` in `futures_core`

### ISSUE THREAD

**Issue by pauljohn21** [rbatis/rbatis#44]
error[E0433]: failed to resolve: could not find `core_reexport` in `futures_core`
 --> /Users/__/.cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-1.7.24/src/wrapper.rs:3:19
  |
3 | use futures_core::core_reexport::any::Any;
  |                   ^^^^^^^^^^^^^ could not find `core_reexport` in `futures_core`

futures 0.3.7出现的问题，无法启动

**Comment by zhuxiujia** [comment]
> error[E0433]: failed to resolve: could not find `core_reexport` in `futures_core`
> --> /Users/__/.cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-1.7.24/src/wrapper.rs:3:19
> |
> 3 | use futures_core::core_reexport::any::Any;
> | ^^^^^^^^^^^^^ could not find `core_reexport` in `futures_core`
> 
> futures 0.3.7出现的问题，无法启动

已修复在 版本 1.7.25
