### ISSUE TITLE
New feature suggestion: Enhancement of pagination functionality for the py_sql macro.

### ISSUE THREAD

**Issue by FoldingFan** [rbatis/rbatis#445]
I’ve noticed that the htmlsql_select_page macro supports pagination, which is a fantastic feature. However, it seems that the py_sql macro currently doesn’t have this capability. It would be wonderful if this functionality could be incorporated, allowing for syntax like the following:
```rust
#[py_sql_page(
    "`select `

    if do_count == true:
        ` count(*) from biz_activity `
    if do_count == false:
        ` * from biz_activity `

    ` where delete_flag = 0 `

    if name != '':
      ` and name=#{name}` 
      
    if do_count == false:
        ` limit #{page_no},#{page_size}`

    "
)]
pub async fn py_sql(
    rb: &RBatis,
    page_req: &PageRequest,
    name: &str,
) -> Page<BizActivity> {
    impled!()
}

```

**Comment by zhuxiujia** [comment]
> I’ve noticed that the htmlsql_select_page macro supports pagination, which is a fantastic feature. However, it seems that the py_sql macro currently doesn’t have this capability. It would be wonderful if this functionality could be incorporated, allowing for syntax like the following:
> 
> ```rust
> #[py_sql_page(
>     "`select `
> 
>     if do_count == true:
>         ` count(*) from biz_activity `
>     if do_count == false:
>         ` * from biz_activity `
> 
>     ` where delete_flag = 0 `
> 
>     if name != '':
>       ` and name=#{name}` 
>       
>     if do_count == false:
>         ` limit #{page_no},#{page_size}`
> 
>     "
> )]
> pub async fn py_sql(
>     rb: &RBatis,
>     page_req: &PageRequest,
>     name: &str,
> ) -> Page<BizActivity> {
>     impled!()
> }
> ```

this is you want?
```rust
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Activity {
    pub id: Option<String>,
    pub name: Option<String>,
    pub pc_link: Option<String>,
    pub h5_link: Option<String>,
    pub pc_banner_img: Option<String>,
    pub h5_banner_img: Option<String>,
    pub sort: Option<String>,
    pub status: Option<i32>,
    pub remark: Option<String>,
    pub create_time: Option<DateTime>,
    pub version: Option<i64>,
    pub delete_flag: Option<i32>,
}

impl_select_page!(Activity{select_page() =>"
     if !sql.contains('count(1)'):
       `order by create_time desc`"});
impl_select_page!(Activity{select_page_by_name(name:&str) =>"
     if name != null && name != '':
       `where name != #{name}`
     if name == '':
       `where name != ''`"});

impl_select_page!(Activity{select_page_by_limit(name:&str,limit_sql:&str) => "`where name != #{name}`"});

```
[see this code](https://github.com/rbatis/example/blob/main/src/crud_select_page.rs)

**Comment by FoldingFan** [comment]
Thank you for your reply.  The impl_select_page macro is very useful, but it does not support queries on multiple tables.I hope that pagination can support queries on multiple tables, similar to this.  I am not sure if I am clear in my explanation.
```rust
#[py_sql_page(
    "`select `

    if do_count == true:
        ` count(*) from biz_activity left join xxx`
    if do_count == false:
        ` xxx.id,biz_activity.id from biz_activity  left join xxx`

    ` where delete_flag = 0 `

    if name != '':
      ` and name=#{name}` 
      
    if do_count == false:
        ` limit #{page_no},#{page_size}`

    "
)]
pub async fn py_sql(
    rb: &RBatis,
    page_req: &PageRequest,
    name: &str,
) -> Page<BizActivity> {
    impled!()
}

```

**Comment by zhuxiujia** [comment]
> Thank you for your reply. The impl_select_page macro is very useful, but it does not support queries on multiple tables.I hope that pagination can support queries on multiple tables, similar to this. I am not sure if I am clear in my explanation.
> 
> ```rust
> #[py_sql_page(
>     "`select `
> 
>     if do_count == true:
>         ` count(*) from biz_activity left join xxx`
>     if do_count == false:
>         ` xxx.id,biz_activity.id from biz_activity  left join xxx`
> 
>     ` where delete_flag = 0 `
> 
>     if name != '':
>       ` and name=#{name}` 
>       
>     if do_count == false:
>         ` limit #{page_no},#{page_size}`
> 
>     "
> )]
> pub async fn py_sql(
>     rb: &RBatis,
>     page_req: &PageRequest,
>     name: &str,
> ) -> Page<BizActivity> {
>     impled!()
> }
> ```

fine ,
I understand

**Comment by zhuxiujia** [comment]
support
```rust
use rbatis::sql::IntoSql;
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct BizActivity{}
rbatis::pysql_select_page!(select_page_data(name: &str) -> BizActivity =>
r#"`select * from activity where delete_flag = 0` 
                  if name != '': 
                    ` and name=#{name}` 
                  if !ids.is_empty(): 
                    ` and id in ` 
                    ${ids.sql()}"#);
```
