### ISSUE TITLE
What happened to table_sync::SqliteTableSync and table_sync::TableSync?

### ISSUE THREAD

**Issue by ptdecker** [rbatis/rbatis#448]
Hello!

When I just moved from 4.4.14 to 4.4.17 I have encountered a breaking change in the test code I have in place to create an in-memory SQLite database for testing purposes.  It appears that rbatis::table_sync::SqliteTableSync and rbatis::table_sync::TableSync are no longer available?

Looks like here is the commit that removed it:

https://github.com/rbatis/rbatis/commit/19c4444c891bb4bf794ed49dcceeee127dc614b4

Since this is a breaking change, shouldn't we have gone to 4.5.x instead of from 4.4.14 to 4.4.17?

What should be used instead?

Thank you for your help

P. Todd

Here is a partial amount of my code which worked prior to 4.4.17:

```rust
use rbatis::{
    table_sync::{SqliteTableSync, TableSync},
    RBatis,
};

// REDACTED

pub(crate) async fn rbatis_sqlite_in_memory_db_setup() -> DbEngine {
    let rb = RBatis::new();
    rb.link(SqliteDriver {}, "sqlite::memory:").await.unwrap();
    let s = SqliteTableSync::default();

    // Customer table
    s.sync(
        rb.acquire().await.unwrap(),
        rbs::to_value!(Customer {
           // REDACTED
        }),
        "customers",
    )
    .await
    .unwrap();
    
    // REDACTED

    DbEngine::Sqlite(rb)
}
```

**Comment by zhuxiujia** [comment]
yes table sync have some changed
see https://github.com/rbatis/rbatis/releases/

**Comment by ptdecker** [comment]
Okay, since it was a breaking change, do you agree that the crate version should have changed to 4.5?   Changes to the 'z' version should not be breaking changes.

**Comment by ptdecker** [comment]
Thank you.

Okay, I have switched my code over to your new approach.  See below.  But, the temp tables are not being created so all our tests are failing.  Can you see something obvious that I'm doing?

```rustuse rbatis::{
    table_sync::{sync, SqliteTableMapper},
    RBatis,
};
use rbdc_sqlite::driver::SqliteDriver;
use rbs::to_value;

// REDACTED

/// Creates an in-memory SQLite database with a partial schema
///

pub(crate) async fn rbatis_sqlite_in_memory_db_setup() -> DbEngine {
    let rb = RBatis::new();
    rb.link(SqliteDriver {}, "sqlite::memory:").await.unwrap();
    let conn = rb.acquire().await.unwrap();

    // Customer table
    let table = Customer {
        // [REDACTED]
    };
    sync(&conn, &SqliteTableMapper {}, to_value!(table), "customers");

    // [[REDACTED]] 

    DbEngine::Sqlite(rb)
}
```

**Comment by zhuxiujia** [comment]
> Thank you.
> 
> 
> 
> Okay, I have switched my code over to your new approach.  See below.  But, the temp tables are not being created so all our tests are failing.  Can you see something obvious that I'm doing?
> 
> 
> 
> ```rust
> 
> use rbatis::{
> 
>     table_sync::{sync, SqliteTableMapper},
> 
>     RBatis,
> 
> };
> 
> use rbdc_sqlite::driver::SqliteDriver;
> 
> use rbs::to_value;
> 
> 
> 
> // REDACTED
> 
> 
> 
> /// Creates an in-memory SQLite database with a partial schema
> 
> ///
> 
> 
> 
> pub(crate) async fn rbatis_sqlite_in_memory_db_setup() -> DbEngine {
> 
>     let rb = RBatis::new();
> 
>     rb.link(SqliteDriver {}, "sqlite::memory:").await.unwrap();
> 
>     let conn = rb.acquire().await.unwrap();
> 
> 
> 
>     // Customer table
> 
>     let table = Customer {
> 
>         // [REDACTED]
> 
>     };
> 
>     sync(&conn, &SqliteTableMapper {}, to_value!(table), "customers");
> 
> 
> 
>     // [[REDACTED]] 
> 
> 
> 
>     DbEngine::Sqlite(rb)
> 
> }
> 
> ```

miss 
    .await on sync（）.await

**Comment by ptdecker** [comment]
Perfect.  That was it.  Thank you.   And I appreciate you honoring the semver going forward.  We really like the rbatis project.

**Comment by zhuxiujia** [comment]
> Perfect.  That was it.  Thank you.   And I appreciate you honoring the semver going forward.  We really like the rbatis project.

 Thanks for your like .

**Comment by ptdecker** [comment]
Closing this as resolved. Thank you

**Comment by ptdecker** [comment]
Closing this as resolved. Thank you
