### ISSUE TITLE
Error caused by enumeration in table definition

### ISSUE THREAD

**Issue by FoldingFan** [rbatis/rbatis#450]
数据库：MySQL8.0
rbatis版本：4.4.19

```rust

#[derive(Debug, Serialize, Deserialize)]
pub struct SysUserPageDTO {
    /// 主键
    pub id: Option<u64>,
    /// 登录账户
    pub account: Option<String>,
    /// 姓名
    pub real_name: Option<String>,
    /// 用户状态
    pub status: Option<StatusEnum>,
    /// 最后登录时间
    pub last_login_time: Option<DateTime>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StatusEnum {
    /// 正常
    #[serde(rename = "Normal")]
    Normal,
    /// 禁用
    #[serde(rename = "Disable")]
    Disable,
}


// 分页查询
pysql_select_page!(page_query(page_search:&UserPageSearch)-> SysUserPageDTO =>"
    `select `
    
    // 查询的列
    if do_count==true:
        ` count(1) as count `
    if do_count==false:
        ` su.id ,`
        ` su.account ,`
        ` su.real_name,`
        ` su.status ,`
        ` su.last_login_time `


    ` from sys_user su where 1=1 `


    if page_search.account != '' :
        ` and account like #{'%' + page_search.account + '%'}`

    // 分页
    if do_count==false:
        ` limit ${page_no},${page_size}`
");

```
发生报错 
`error while decoding value: invalid type: byte array, expected array, map or int`

StatusEnum 在数据库中的类型是 varchar(10)

大佬可以告诉我 关于表定义里面的枚举 应该用什么姿势写吗？

**Comment by zhuxiujia** [comment]
> 数据库：MySQL8.0
> 
> rbatis版本：4.4.19
> 
> 
> 
> ```rust
> 
> 
> 
> #[derive(Debug, Serialize, Deserialize)]
> 
> pub struct SysUserPageDTO {
> 
>     /// 主键
> 
>     pub id: Option<u64>,
> 
>     /// 登录账户
> 
>     pub account: Option<String>,
> 
>     /// 姓名
> 
>     pub real_name: Option<String>,
> 
>     /// 用户状态
> 
>     pub status: Option<StatusEnum>,
> 
>     /// 最后登录时间
> 
>     pub last_login_time: Option<DateTime>,
> 
> }
> 
> 
> 
> #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
> 
> pub enum StatusEnum {
> 
>     /// 正常
> 
>     #[serde(rename = "Normal")]
> 
>     Normal,
> 
>     /// 禁用
> 
>     #[serde(rename = "Disable")]
> 
>     Disable,
> 
> }
> 
> 
> 
> 
> 
> // 分页查询
> 
> pysql_select_page!(page_query(page_search:&UserPageSearch)-> SysUserPageDTO =>"
> 
>     `select `
> 
>     
> 
>     // 查询的列
> 
>     if do_count==true:
> 
>         ` count(1) as count `
> 
>     if do_count==false:
> 
>         ` su.id ,`
> 
>         ` su.account ,`
> 
>         ` su.real_name,`
> 
>         ` su.status ,`
> 
>         ` su.last_login_time `
> 
> 
> 
> 
> 
>     ` from sys_user su where 1=1 `
> 
> 
> 
> 
> 
>     if page_search.account != '' :
> 
>         ` and account like #{'%' + page_search.account + '%'}`
> 
> 
> 
>     // 分页
> 
>     if do_count==false:
> 
>         ` limit ${page_no},${page_size}`
> 
> ");
> 
> 
> 
> ```
> 
> 发生报错 
> 
> `error while decoding value: invalid type: byte array, expected array, map or int`
> 
> 
> 
> StatusEnum 在数据库中的类型是 varchar(10)
> 
> 
> 
> 大佬可以告诉我 关于表定义里面的枚举 应该用什么姿势写吗？

先暂时用String   替代  枚举目前被序列化数组了，后期要改改

**Comment by zhuxiujia** [comment]
执行`cargo update` 即可支持这个
