### ISSUE TITLE
about use htmlsql

### ISSUE THREAD

**Issue by moom-en** [rbatis/rbatis#453]
The error file does not exist when starting with  htmlsql! or #[htmlsql], the file is in the same level directory

**Comment by zhuxiujia** [comment]
did you check your file path?

**Comment by moom-en** [comment]
![image](https://github.com/rbatis/rbatis/assets/35919845/b093990c-3bf4-4fa6-a27e-9c7fb2139312)
this is biz.rs content:
rbatis::htmlsql!(get_user(rb: &dyn Executor, account: &str, wechat_id: &str) -> rbatis::Result<User> => "user.html");

**Comment by zhuxiujia** [comment]
> ![image](https://user-images.githubusercontent.com/35919845/280880290-b093990c-3bf4-4fa6-a27e-9c7fb2139312.png) this is biz.rs content: rbatis::htmlsql!(get_user(rb: &dyn Executor, account: &str, wechat_id: &str) -> rbatis::Result => "user.html");

you can use full path or 'api/src/user.html'

**Comment by moom-en** [comment]
> > ![image](https://user-images.githubusercontent.com/35919845/280880290-b093990c-3bf4-4fa6-a27e-9c7fb2139312.png) this is biz.rs content: rbatis::htmlsql!(get_user(rb: &dyn Executor, account: &str, wechat_id: &str) -> rbatis::Result => "user.html");
> 
> you can use full path or 'api/src/user.html'

我都用了不得行，依然报这个错

**Comment by zhuxiujia** [comment]
> > > ![image](https://user-images.githubusercontent.com/35919845/280880290-b093990c-3bf4-4fa6-a27e-9c7fb2139312.png) this is biz.rs content: rbatis::htmlsql!(get_user(rb: &dyn Executor, account: &str, wechat_id: &str) -> rbatis::Result => "user.html");
> > 
> > 
> > you can use full path or 'api/src/user.html'
> 
> 我都用了不得行，依然报这个错

放到项目根目录试试？

**Comment by moom-en** [comment]
> > > > ![image](https://user-images.githubusercontent.com/35919845/280880290-b093990c-3bf4-4fa6-a27e-9c7fb2139312.png) this is biz.rs content: rbatis::htmlsql!(get_user(rb: &dyn Executor, account: &str, wechat_id: &str) -> rbatis::Result => "user.html");
> > > 
> > > 
> > > you can use full path or 'api/src/user.html'
> > 
> > 
> > 我都用了不得行，依然报这个错
> 
> 放到项目根目录试试？ 也可以写绝对路径

后边我再试下吧

**Comment by zhuxiujia** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/35919845/280880290-b093990c-3bf4-4fa6-a27e-9c7fb2139312.png) this is biz.rs content: rbatis::htmlsql!(get_user(rb: &dyn Executor, account: &str, wechat_id: &str) -> rbatis::Result => "user.html");
> > > > 
> > > > 
> > > > you can use full path or 'api/src/user.html'
> > > 
> > > 
> > > 我都用了不得行，依然报这个错
> > 
> > 
> > 放到项目根目录试试？ 也可以写绝对路径
> 
> 后边我再试下吧

你看我的
![image](https://github.com/rbatis/rbatis/assets/3481148/453702e7-0720-4031-b613-28420c4e991e)

**Comment by moom-en** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/35919845/280880290-b093990c-3bf4-4fa6-a27e-9c7fb2139312.png) this is biz.rs content: rbatis::htmlsql!(get_user(rb: &dyn Executor, account: &str, wechat_id: &str) -> rbatis::Result => "user.html");
> > > > > 
> > > > > 
> > > > > you can use full path or 'api/src/user.html'
> > > > 
> > > > 
> > > > 我都用了不得行，依然报这个错
> > > 
> > > 
> > > 放到项目根目录试试？ 也可以写绝对路径
> > 
> > 
> > 后边我再试下吧
> 
> 你看我的截图，可以正常编译通过执行 ![image](https://user-images.githubusercontent.com/3481148/282646110-453702e7-0720-4031-b613-28420c4e991e.png)

好的，谢谢
