### ISSUE TITLE
Query results Boolean type support

### ISSUE THREAD

**Issue by FoldingFan** [rbatis/rbatis#455]
数据库：mysql8
rbatis：

数据库类型为 `bit(1) ` 查询到rust的类型是 `Option<bool>` 
结果报错， ```integer `0`, expected a boolean```

**Comment by zhuxiujia** [comment]
> 数据库：mysql8 rbatis：
> 
> 数据库类型为 `bit(1) ` 查询到rust的类型是 `Option<bool>` 结果报错， `` integer `0`, expected a boolean ``

mysql不支持bool，只支持Tiny（i8）

**Comment by FoldingFan** [comment]
好吧，我提的问题有点唐突了
