### ISSUE TITLE
partial CRUDEnable implementation

### ISSUE THREAD

**Issue by aCLr** [rbatis/rbatis#46]
Greetings!

First of all thanks for your great tool. It works like a charm :)

My problem is that I can't override CRUDEnable implementation if derive clause used. Example:
```
#[derive(CRUDEnable, Serialize, Deserialize, Clone, Debug)]
pub struct Source {
    pub id: u32,
    pub name: String,
    pub origin: String,
}
``` 

I want to use table_name = "sources" but currently there are two options:
1. not to use `#[derive(CRUDEnable)]` and implement all trait methods
2. use `#[derive(CRUDEnable)]` and accept library logic. So in that case I have to rename database table from `sources` to `source`.

It would be great if I can use some kind of macro for that.

**Comment by zhuxiujia** [comment]
> Greetings!
> 
> First of all thanks for your great tool. It works like a charm :)
> 
> My problem is that I can't override CRUDEnable implementation if derive clause used. Example:
> 
> ```
> #[derive(CRUDEnable, Serialize, Deserialize, Clone, Debug)]
> pub struct Source {
>     pub id: u32,
>     pub name: String,
>     pub origin: String,
> }
> ```
> 
> I want to use table_name = "sources" but currently there are two options:
> 
> 1. not to use `#[derive(CRUDEnable)]` and implement all trait methods
> 2. use `#[derive(CRUDEnable)]` and accept library logic. So in that case I have to rename database table from `sources` to `source`.
> 
> It would be great if I can use some kind of macro for that.

you can  impl  CRUDEnable  trait for  this struct.

for example:

```rust
impl CRUDEnable  for Source{
      type IdType = u32;
     fn table_name() -> String{
           "sources".to_string()
      }
}
```

**Comment by aCLr** [comment]
Are you sure?
```
use rbatis::crud::CRUDEnable;
use serde::{Deserialize, Serialize};

#[derive(CRUDEnable, Serialize, Deserialize, Clone, Debug)]
pub struct Source {
    pub id: u32,
    pub name: String,
    pub origin: String,
}
impl CRUDEnable for Source {
    type IdType = u32;
    fn table_name() -> String {
        "sources".to_string()
    }
}
```

```
error[E0119]: conflicting implementations of trait `rbatis::crud::CRUDEnable` for type `db::models::Source`:
  --> src/db/models.rs:4:10
   |
4  | #[derive(CRUDEnable, Serialize, Deserialize, Clone, Debug)]
   |          ^^^^^^^^^^ conflicting implementation for `db::models::Source`
...
10 | impl CRUDEnable for Source {
   | -------------------------- first implementation here
   |

```

**Comment by zhuxiujia** [comment]
> Are you sure?
> 
> ```
> 
> use rbatis::crud::CRUDEnable;
> 
> use serde::{Deserialize, Serialize};
> 
> 
> 
> #[derive(CRUDEnable, Serialize, Deserialize, Clone, Debug)]
> 
> pub struct Source {
> 
>     pub id: u32,
> 
>     pub name: String,
> 
>     pub origin: String,
> 
> }
> 
> impl CRUDEnable for Source {
> 
>     type IdType = u32;
> 
>     fn table_name() -> String {
> 
>         "sources".to_string()
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> ```
> 
> error[E0119]: conflicting implementations of trait `rbatis::crud::CRUDEnable` for type `db::models::Source`:
> 
>   --> src/db/models.rs:4:10
> 
>    |
> 
> 4  | #[derive(CRUDEnable, Serialize, Deserialize, Clone, Debug)]
> 
>    |          ^^^^^^^^^^ conflicting implementation for `db::models::Source`
> 
> ...
> 
> 10 | impl CRUDEnable for Source {
> 
>    | -------------------------- first implementation here
> 
>    |
> 
> 
> 
> ```

if you impl CRUDEnable trait already
you Need remove the[derive(CRUDEnable）］

**Comment by aCLr** [comment]
Oh, I see now: there is default implementation. Thanks.
