### ISSUE TITLE
can't use array as query parameters

### ISSUE THREAD

**Issue by aCLr** [rbatis/rbatis#47]
Hi!
I can't find a way to use an array in queries. Here is an example:
```
#[tokio::main]
async fn main() {
    db::RB
        .link("postgres://user:password@0.0.0.0:5432/db")
        .await
        .expect("can't initialize pool");
    let guids = vec!["1", "2", "3"];  // absolutely the same result with `let guids = ("1", "2", "3")`
    let exists: Vec<String> = db::RB
        .fetch_prepare(
            "",
            r#"
        SELECT guid 
        FROM records
        WHERE guid = ANY($1)
        AND source_id = $2"#,
            &vec![json!(&guids), json!(&1)],
        )
        .await
        .unwrap();
}
```

Logs:
```
[2020-11-04T11:45:51Z INFO  rbatis::plugin::log] [rbatis] [] Query ==> 
            SELECT guid 
            FROM records
            WHERE guid = ANY($1)
            AND source_id = $2
[2020-11-04T11:45:51Z INFO  rbatis::plugin::log] [rbatis] [] Args  ==> [["1","2","3"],1]
[2020-11-04T11:45:51Z INFO  sqlx::query] /* SQLx ping */; rows: 0, elapsed: 614.743µs
[2020-11-04T11:45:51Z INFO  sqlx::query] SELECT guid FROM records …; rows: 0, elapsed: 1.014ms
    
    SELECT
      guid
    FROM
      records
    WHERE
      guid = ANY($1)
      AND source_id = $2
    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("error returned from database: op ANY/ALL (array) requires array on right side")', src/main.rs:48:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zhuxiujia** [comment]
> Hi!
> I can't find a way to use an array in queries. Here is an example:
> 
> ```
> #[tokio::main]
> async fn main() {
>     db::RB
>         .link("postgres://user:password@0.0.0.0:5432/db")
>         .await
>         .expect("can't initialize pool");
>     let guids = vec!["1", "2", "3"];  // absolutely the same result with `let guids = ("1", "2", "3")`
>     let exists: Vec<String> = db::RB
>         .fetch_prepare(
>             "",
>             r#"
>         SELECT guid 
>         FROM records
>         WHERE guid = ANY($1)
>         AND source_id = $2"#,
>             &vec![json!(&guids), json!(&1)],
>         )
>         .await
>         .unwrap();
> }
> ```
> 
> Logs:
> 
> ```
> [2020-11-04T11:45:51Z INFO  rbatis::plugin::log] [rbatis] [] Query ==> 
>             SELECT guid 
>             FROM records
>             WHERE guid = ANY($1)
>             AND source_id = $2
> [2020-11-04T11:45:51Z INFO  rbatis::plugin::log] [rbatis] [] Args  ==> [["1","2","3"],1]
> [2020-11-04T11:45:51Z INFO  sqlx::query] /* SQLx ping */; rows: 0, elapsed: 614.743µs
> [2020-11-04T11:45:51Z INFO  sqlx::query] SELECT guid FROM records …; rows: 0, elapsed: 1.014ms
>     
>     SELECT
>       guid
>     FROM
>       records
>     WHERE
>       guid = ANY($1)
>       AND source_id = $2
>     
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("error returned from database: op ANY/ALL (array) requires array on right side")', src/main.rs:48:10
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

You should read  doc website   https://rbatis.github.io/rbatis.io/#/README_EN?id=wrapper

Here is how to use wrapper

**Comment by aCLr** [comment]
I think that I can't use wrapper because result data type is Vec<String>:
```
let wrapper = db::RB
        .new_wrapper()
        .r#in("guid", &guids)
        .eq("source_id", 1)
        .check()
        .unwrap();
    let exists: Vec<String> = db::RB.fetch_by_wrapper("", &wrapper).await.unwrap();
    println!("{:?}", exists);
```


```
error[E0277]: the trait bound `std::string::String: rbatis::crud::CRUDEnable` is not satisfied
  --> src/main.rs:41:41
   |
41 |     let exists: Option<String> = db::RB.fetch_by_wrapper("", &wrapper).await.unwrap();
   |                                         ^^^^^^^^^^^^^^^^ the trait `rbatis::crud::CRUDEnable` is not implemented for `std::string::String`
   |
```

**Comment by zhuxiujia** [comment]
> I think that I can't use wrapper because result data type is Vec:
> 
> ```
> let wrapper = db::RB
>         .new_wrapper()
>         .r#in("guid", &guids)
>         .eq("source_id", 1)
>         .check()
>         .unwrap();
>     let exists: Vec<String> = db::RB.fetch_by_wrapper("", &wrapper).await.unwrap();
>     println!("{:?}", exists);
> ```
> 
> ```
> error[E0277]: the trait bound `std::string::String: rbatis::crud::CRUDEnable` is not satisfied
>   --> src/main.rs:41:41
>    |
> 41 |     let exists: Option<String> = db::RB.fetch_by_wrapper("", &wrapper).await.unwrap();
>    |                                         ^^^^^^^^^^^^^^^^ the trait `rbatis::crud::CRUDEnable` is not implemented for `std::string::String`
>    |
> ```

try use macro
```rust
   #[py_sql(RB, "select * from biz_activity where delete_flag = 0
                  AND id in
                  for item in ids:
                      #{item}")]
    fn py_select_vec(ids: &Vec<String>) -> Vec<String> {
    }


    #[async_std::test]
    pub async fn test_vec() {
        fast_log::init_log("requests.log", 1000, log::Level::Info, true);
        //use static ref
        RB.link("mysql://root:123456@localhost:3306/test").await.unwrap();
        let a = py_select_vec(&vec!["1".to_string(), "2".to_string()]).await.unwrap();
        println!("{:?}", a);
    }
```

**Comment by zhuxiujia** [comment]
Finally, you can use fast_log to disable logs from SQLX。
for example:

```rust
use fast_log::fast_log::LogAppender;
use fast_log::plugin::file::FileAppender;
use fast_log::plugin::console::ConsoleAppender;
use fast_log::filter::ModuleFilter;

pub fn init_log() {
    //自定义日志追加器
    let mut appenders: Vec<Box<dyn LogAppender>> = vec![
        Box::new(FileAppender::new("requests.log"))
    ];
    if true {
        appenders.push(Box::new(ConsoleAppender {}));
    }
    //自定义日志过滤
    fast_log::init_custom_log(appenders, 1000, log::Level::Info, Box::new(
        //NoFilter{}//无过滤

        //按模块过滤
        ModuleFilter {
            //contains
            contains: None,
            //exclude_contains
            exclude_contains: Some(vec![
                "sqlx".to_string()
            ]),
        }
    ));
}
```

**Comment by aCLr** [comment]
So now I see that arrays as parameters not supported.

**Comment by zhuxiujia** [comment]
> So now I see that arrays as parameters not supported.

array param not support in prepare method。

maybe we need add fetch_prepare_wrapper method。
for now you can use rbatis-macro fix this
