### ISSUE TITLE
Transactton Token error: 'Incorrect syntax near 'begin'.' on server

### ISSUE THREAD

**Issue by xingsongs** [rbatis/rbatis#473]
database：sql server 2016.
```
Call to start transaction：
 let mut txn = CONTEXT.rb.acquire_begin().await?;

Execute transaction error：
  Token error: 'Incorrect syntax near 'begin'.' on server WIN-B9A9 executing  on line 1 (code: 102, state: 1, class: 15)  
```

Sql server does not support 'begin'.

```
Added the following method：

pub async fn acquire_begin_transaction(&self) -> Result<RBatisTxExecutor, Error> {
        let pool = self.rb.get_pool()?;
        let mut conn = pool.get().await?;

        conn.exec("BEGIN TRAN", vec![]).await?;

        Ok(RBatisTxExecutor {
            tx_id: new_snowflake_id(),
            conn: Mutex::new(Box::new(conn)),
            rb: self.rb.clone(),
            done: false,
        })
    }


Execute  error：
Token error: 'Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.' on server WIN-B9A9 executing  on line 0 (code: 266, state: 2, class: 16)

```
Please give me some advice?

**Comment by zhuxiujia** [comment]
> database：sql server 2016.
> 
> ```
> Call to start transaction：
>  let mut txn = CONTEXT.rb.acquire_begin().await?;
> 
> Execute transaction error：
>   Token error: 'Incorrect syntax near 'begin'.' on server WIN-B9A9 executing  on line 1 (code: 102, state: 1, class: 15)  
> ```
> 
> Sql server does not support 'begin'.
> 
> ```
> Added the following method：
> 
> pub async fn acquire_begin_transaction(&self) -> Result<RBatisTxExecutor, Error> {
>         let pool = self.rb.get_pool()?;
>         let mut conn = pool.get().await?;
> 
>         conn.exec("BEGIN TRAN", vec![]).await?;
> 
>         Ok(RBatisTxExecutor {
>             tx_id: new_snowflake_id(),
>             conn: Mutex::new(Box::new(conn)),
>             rb: self.rb.clone(),
>             done: false,
>         })
>     }
> 
> 
> Execute  error：
> Token error: 'Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.' on server WIN-B9A9 executing  on line 0 (code: 266, state: 2, class: 16)
> ```
> 
> Please give me some advice?

SQL Server 2016 supports starting a transaction using `BEGIN TRANSACTION`, which is used to explicitly start a transaction in SQL Server. Through BEGIN TRANSACT, you can start a new transaction and then end or roll back the transaction in either COMMIT TRANSACT or Rollback TRANSACT.

**Comment by xingsongs** [comment]
> > database：sql server 2016.
> > ```
> > Call to start transaction：
> >  let mut txn = CONTEXT.rb.acquire_begin().await?;
> > 
> > Execute transaction error：
> >   Token error: 'Incorrect syntax near 'begin'.' on server WIN-B9A9 executing  on line 1 (code: 102, state: 1, class: 15)  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sql server does not support 'begin'.
> > ```
> > Added the following method：
> > 
> > pub async fn acquire_begin_transaction(&self) -> Result<RBatisTxExecutor, Error> {
> >         let pool = self.rb.get_pool()?;
> >         let mut conn = pool.get().await?;
> > 
> >         conn.exec("BEGIN TRAN", vec![]).await?;
> > 
> >         Ok(RBatisTxExecutor {
> >             tx_id: new_snowflake_id(),
> >             conn: Mutex::new(Box::new(conn)),
> >             rb: self.rb.clone(),
> >             done: false,
> >         })
> >     }
> > 
> > 
> > Execute  error：
> > Token error: 'Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.' on server WIN-B9A9 executing  on line 0 (code: 266, state: 2, class: 16)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please give me some advice?
> 
> SQL Server 2016 supports starting a transaction using `BEGIN TRANSACTION`, which is used to explicitly start a transaction in SQL Server. Through BEGIN TRANSACT, you can start a new transaction and then end or roll back the transaction in either COMMIT TRANSACT or Rollback TRANSACT.
> 
> I suggest you use an interceptor to modify the transaction statement start to `BEGIN TRANSACTION`
> 
> ```rust
> #[derive(Debug)]
> pub struct TxIntercept {}
> 
> #[async_trait]
> impl Intercept for TxIntercept {
>     async fn before(
>         &self,
>         _task_id: i64,
>         _rb: &dyn Executor,
>         sql: &mut String,
>         _args: &mut Vec<Value>,
>         _result: ResultType<&mut Result<ExecResult, Error>, &mut Result<Vec<Value>, Error>>,
>     ) -> Result<bool, Error> {
>         if sql.contains("begin") {
>           *sql = sql.replace("begin","BEGIN TRANSACTION").to_string();
>         } else if sql.contains("commit") {
>             *sql = sql.replace("commit","COMMIT TRANSACTION").to_string();
>         } else if sql.contains("rollback") {
>             *sql = sql.replace("rollback","ROLLBACK TRANSACTION").to_string();
>         }
>         Ok(true)
>     }
> }
> #[tokio::main]
> pub async fn main() {
>     fast_log::init(fast_log::Config::new().console()).expect("rbatis init fail");
>     defer!(|| log::logger().flush());
>     let rb = RBatis::new();
>     rb.intercepts.push(Arc::new(TxIntercept {}));
> }
> ```

Thank you very much that the interceptor has taken effect.
`But it still prompts this error：Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.`

**Comment by zhuxiujia** [comment]
> Thank you very much that the interceptor has taken effect.
> `But it still prompts this error：Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.`

did you call commit method or  rollback ?

**Comment by xingsongs** [comment]
> > Thank you very much that the interceptor has taken effect.
> > `But it still prompts this error：Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.`
> 
> did you call commit method or rollback ?
<img width="1044" alt="image" src="https://github.com/rbatis/rbatis/assets/6611189/d8366352-dd9a-42ee-a25b-0405d2c92850">
call CONTEXT.rb.try_acquire_begin().await?  report error

**Comment by xingsongs** [comment]
#488  Already solved
