### ISSUE TITLE
type of Mysql isn't support.

### ISSUE THREAD

**Issue by dopeter** [rbatis/rbatis#48]
Error : un support database type for:"BIT"!

ddl of sql :

    removed      bit       default b'0'              null comment 'is soft deleted',
    creator      bigint    default -1                null,
    create_at    timestamp default CURRENT_TIMESTAMP null,
    updater      bigint    default -1                null,
    update_at    timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP

**Comment by zhuxiujia** [comment]
> Error : un support database type for:"BIT"!
> 
> ddl of sql :
> 
> ```
> removed      bit       default b'0'              null comment 'is soft deleted',
> creator      bigint    default -1                null,
> create_at    timestamp default CURRENT_TIMESTAMP null,
> updater      bigint    default -1                null,
> update_at    timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP
> ```

fine , i will check this try add this decode

**Comment by zhuxiujia** [comment]
now ,the new version rbatis is fix this.please check this
