### ISSUE TITLE
The json field of the database is returned as an escaped string

### ISSUE THREAD

**Issue by yishiyuntuan** [rbatis/rbatis#494]
数据库
依赖版本
```toml
[dependencies]
actix-web = "4.4"
actix-cors= "0.7.0"

#sea-orm = { version = "0.12.12", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "debug-print", "macros"] }
rbs = { version = "4.5"}
rbatis = { version = "4.5"}
rbdc-sqlite = { version = "4.5" }

serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive"] }
futures = "0.3"

env_logger = "0.8"
log = "0.4"
fast_log = "1.6"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
```

数据库表
```sql
CREATE TABLE alarm (
    id VARCHAR NOT NULL PRIMARY KEY, 
    path VARCHAR, 
    start JSON, 
    end JSON, 
    extra JSON, 
    branch VARCHAR, 
    repo VARCHAR, 
    handler VARCHAR, 
    reason VARCHAR, 
    check_id VARCHAR
)
```

结构
```rust
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Alarm {
    pub id: Option<String>,
    pub path: Option<String>,
    pub start: Option<Value>,
    pub end: Option<Value>,
    pub extra: Option<Value>,
    pub branch: Option<String>,
    pub repo: Option<String>,
    pub check_id: Option<String>,
    pub handler: Option<String>,
    pub reason: Option<String>,
}
rbatis::crud!(Alarm {});
```
actix-web
```rust
async fn get_alarm_list(path: web::Path<String>, req_body: Json<Value>) -> actix_web::Result<impl Responder> {
    let x = req_body.as_array().unwrap();
    let vec: Vec<Alarm> = Vec::new();
    if x.len() <= 0 {
        return Ok(Json(vec));
    }
    let ids: Vec<_> = x.iter().map(|item| {
        item.as_str().unwrap_or_default()
    }).collect();

    let product = path.into_inner();
    let url = format!("sqlite://db/{}.sqlite", product);

    let rb = RBatis::new();
    rb.link(SqliteDriver {}, &url).await.unwrap();
    let result: Vec<Alarm> = Alarm::select_in_column(&rb, "id", &ids).await.unwrap_or(vec);
    Ok(Json(result))
}
```
返回的数据
```json
{
	"id": "4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0",
	"path": "test-cases/main.go",
	"start": "{\"col\":1,\"line\":3,\"offset\":14}",
	"end": "{\"col\":13,\"line\":3,\"offset\":26}",
	"extra": "{\"engine_kind\":\"OSS\",\"fingerprint\":\"4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0\",\"is_ignored\":true,\"lines\":\"import \"log\"\",\"message\":\"G.PKG.05 导入包时避免使用别名\",\"metadata\":{},\"metavars\":{\"$1\":{\"abstract_content\":\"import \"log\"\",\"end\":{\"col\":13,\"line\":3,\"offset\":26},\"start\":{\"col\":1,\"line\":3,\"offset\":14}}},\"severity\":\"ERROR\",\"validation_state\":\"NO_VALIDATOR\"}",
	"branch": "test",
	"repo": "123.git",
	"check_id": "semgrep.go.ccn-ps.no-package-alias",
	"handler": "[]",
	"reason": ""
}
```
期望返回的数据
```json
	{
		"id": "4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0",
		"path": "test-cases/main.go",
		"start": {
			"col": 1,
			"line": 3,
			"offset": 14
		},
		"end": {
			"col": 13,
			"line": 3,
			"offset": 26
		},
		"extra": {
			"engine_kind": "OSS",
			"fingerprint": "4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0",
			"is_ignored": true,
			"lines": "import \"log\"",
			"message": "G.PKG.05 导入包时避免使用别名",
			"metadata": {},
			"metavars": {
				"$1": {
					"abstract_content": "import \"log\"",
					"end": {
						"col": 13,
						"line": 3,
						"offset": 26
					},
					"start": {
						"col": 1,
						"line": 3,
						"offset": 14
					}
				}
			},
			"severity": "ERROR",
			"validation_state": "NO_VALIDATOR"
		},
		"branch": "test",
		"repo": "123.git",
		"check_id": "semgrep.go.ccn-ps.no-package-alias",
		"handler": [],
		"reason": ""
	}
```

日志
```bash
[2024-02-28T03:22:20Z INFO  rbatis::plugin::intercept_log] [rbatis] [605240366127127637] query => `select * from alarm  where id in (?)` ["4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be6
0fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0"]
[2024-02-28T03:22:20Z INFO  rbatis::plugin::intercept_log] [rbatis] [605240366127127637] query <= len=1,rows=[{"check_id":"semgrep.go.ccn-ps.no-package-alias","reason":"","handler":"[]","repo":"123.gi
t","branch":"test","extra":"{"engine_kind":"OSS","fingerprint":"4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0","is_
ignored":true,"lines":"import "log"","message":"G.PKG.05 导入包时避免使用别名","metadata":{},"metavars":{"$1":{"abstract_content":"import "log"","end":{"col":13,"line":3,"offset":26},"start":{"col":1,
"line":3,"offset":14}}},"severity":"ERROR","validation_state":"NO_VALIDATOR"}","end":"{"col":13,"line":3,"offset":26}","start":"{"col":1,"line":3,"offset":14}","path":"test-cases/main.go","id":"4142c6
4ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0"}]
[2024-02-28T03:22:20Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /alarm/list/test HTTP/1.1" 200 896 "-" "PostmanRuntime-ApipostRuntime/1.1.0" 0.007776
```

**Comment by zhuxiujia** [comment]
> 数据库 依赖版本
> 
> ```toml
> [dependencies]
> actix-web = "4.4"
> actix-cors= "0.7.0"
> 
> #sea-orm = { version = "0.12.12", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "debug-print", "macros"] }
> rbs = { version = "4.5"}
> rbatis = { version = "4.5"}
> rbdc-sqlite = { version = "4.5" }
> 
> serde_json = "1.0.113"
> serde = { version = "1.0.196", features = ["derive"] }
> futures = "0.3"
> 
> env_logger = "0.8"
> log = "0.4"
> fast_log = "1.6"
> tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
> ```
> 
> 数据库表
> 
> ```sql
> CREATE TABLE alarm (
>     id VARCHAR NOT NULL PRIMARY KEY, 
>     path VARCHAR, 
>     start JSON, 
>     end JSON, 
>     extra JSON, 
>     branch VARCHAR, 
>     repo VARCHAR, 
>     handler VARCHAR, 
>     reason VARCHAR, 
>     check_id VARCHAR
> )
> ```
> 
> 结构
> 
> ```rust
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub struct Alarm {
>     pub id: Option<String>,
>     pub path: Option<String>,
>     pub start: Option<Value>,
>     pub end: Option<Value>,
>     pub extra: Option<Value>,
>     pub branch: Option<String>,
>     pub repo: Option<String>,
>     pub check_id: Option<String>,
>     pub handler: Option<String>,
>     pub reason: Option<String>,
> }
> rbatis::crud!(Alarm {});
> ```
> 
> actix-web
> 
> ```rust
> async fn get_alarm_list(path: web::Path<String>, req_body: Json<Value>) -> actix_web::Result<impl Responder> {
>     let x = req_body.as_array().unwrap();
>     let vec: Vec<Alarm> = Vec::new();
>     if x.len() <= 0 {
>         return Ok(Json(vec));
>     }
>     let ids: Vec<_> = x.iter().map(|item| {
>         item.as_str().unwrap_or_default()
>     }).collect();
> 
>     let product = path.into_inner();
>     let url = format!("sqlite://db/{}.sqlite", product);
> 
>     let rb = RBatis::new();
>     rb.link(SqliteDriver {}, &url).await.unwrap();
>     let result: Vec<Alarm> = Alarm::select_in_column(&rb, "id", &ids).await.unwrap_or(vec);
>     Ok(Json(result))
> }
> ```
> 
> 返回的数据
> 
> ```json
> {
> 	"id": "4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0",
> 	"path": "test-cases/main.go",
> 	"start": "{\"col\":1,\"line\":3,\"offset\":14}",
> 	"end": "{\"col\":13,\"line\":3,\"offset\":26}",
> 	"extra": "{\"engine_kind\":\"OSS\",\"fingerprint\":\"4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0\",\"is_ignored\":true,\"lines\":\"import \"log\"\",\"message\":\"G.PKG.05 导入包时避免使用别名\",\"metadata\":{},\"metavars\":{\"$1\":{\"abstract_content\":\"import \"log\"\",\"end\":{\"col\":13,\"line\":3,\"offset\":26},\"start\":{\"col\":1,\"line\":3,\"offset\":14}}},\"severity\":\"ERROR\",\"validation_state\":\"NO_VALIDATOR\"}",
> 	"branch": "test",
> 	"repo": "123.git",
> 	"check_id": "semgrep.go.ccn-ps.no-package-alias",
> 	"handler": "[]",
> 	"reason": ""
> }
> ```
> 
> 期望返回的数据
> 
> ```json
> 	{
> 		"id": "4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0",
> 		"path": "test-cases/main.go",
> 		"start": {
> 			"col": 1,
> 			"line": 3,
> 			"offset": 14
> 		},
> 		"end": {
> 			"col": 13,
> 			"line": 3,
> 			"offset": 26
> 		},
> 		"extra": {
> 			"engine_kind": "OSS",
> 			"fingerprint": "4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0",
> 			"is_ignored": true,
> 			"lines": "import \"log\"",
> 			"message": "G.PKG.05 导入包时避免使用别名",
> 			"metadata": {},
> 			"metavars": {
> 				"$1": {
> 					"abstract_content": "import \"log\"",
> 					"end": {
> 						"col": 13,
> 						"line": 3,
> 						"offset": 26
> 					},
> 					"start": {
> 						"col": 1,
> 						"line": 3,
> 						"offset": 14
> 					}
> 				}
> 			},
> 			"severity": "ERROR",
> 			"validation_state": "NO_VALIDATOR"
> 		},
> 		"branch": "test",
> 		"repo": "123.git",
> 		"check_id": "semgrep.go.ccn-ps.no-package-alias",
> 		"handler": [],
> 		"reason": ""
> 	}
> ```
> 
> 日志
> 
> ```shell
> [2024-02-28T03:22:20Z INFO  rbatis::plugin::intercept_log] [rbatis] [605240366127127637] query => `select * from alarm  where id in (?)` ["4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be6
> 0fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0"]
> [2024-02-28T03:22:20Z INFO  rbatis::plugin::intercept_log] [rbatis] [605240366127127637] query <= len=1,rows=[{"check_id":"semgrep.go.ccn-ps.no-package-alias","reason":"","handler":"[]","repo":"123.gi
> t","branch":"test","extra":"{"engine_kind":"OSS","fingerprint":"4142c64ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0","is_
> ignored":true,"lines":"import "log"","message":"G.PKG.05 导入包时避免使用别名","metadata":{},"metavars":{"$1":{"abstract_content":"import "log"","end":{"col":13,"line":3,"offset":26},"start":{"col":1,
> "line":3,"offset":14}}},"severity":"ERROR","validation_state":"NO_VALIDATOR"}","end":"{"col":13,"line":3,"offset":26}","start":"{"col":1,"line":3,"offset":14}","path":"test-cases/main.go","id":"4142c6
> 4ad77a1c4daaccbd401dd3d63ccab595bfcae8a6fb3bdde0b459be60fde73eebe744bfab9b2edca7971a3129f476830c7fc09c7a8052eacfeeb9506411_0"}]
> [2024-02-28T03:22:20Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /alarm/list/test HTTP/1.1" 200 896 "-" "PostmanRuntime-ApipostRuntime/1.1.0" 0.007776
> ```

see  https://github.com/rbatis/example/blob/main/src/crud_json.rs

**Comment by zhuxiujia** [comment]
see https://github.com/rbatis/example/blob/main/src/crud_json.rs

**Comment by zhuxiujia** [comment]
sqlite driver return json objcet/array/null is supported
