### ISSUE TITLE
快不快？

### ISSUE THREAD

**Issue by pickfire** [rbatis/rbatis#5]
有数据吗？比如比较 drogon getFastDbClient、diesel、sqlx 和其它的性能。

**Comment by zhuxiujia** [comment]
> 有数据吗？比如比较 drogon getFastDbClient、diesel、sqlx 和其它的性能。


因为是根据sqlx的驱动修改而来，可以直接参考sqlx。
其他核心部分消耗性能的也就是serde__json了，这个也很快，不需要测

**Comment by pickfire** [comment]
啊，那就是不快了吧。或者 getFastDbClient 太变态了。

**Comment by zhuxiujia** [comment]
> 啊，那就是不快了吧。或者 getFastDbClient 太变态了。

你说的快是指低延迟，还是高并发。按照大多数需求，web服务端应用都趋向于高并发，基于future的设计，已经满足这点了。
而且最终的性能取决于数据库最大连接数，和你的数据库性能配置。一般来说框架不是瓶颈，捂捂钱包在考虑性能
