### ISSUE TITLE
i128 or u128 is un support 

### ISSUE THREAD

**Issue by dopeter** [rbatis/rbatis#50]
3ks.
I will test #48 later on my project.

I had found a new problem that I can't ensure that is whether in Rbatis.
Doc of serde said that i128 or u128 can implement by macro , but I never found the place or medium to get this.

**Comment by dopeter** [comment]
The field type of Mysql is BIGINT(20).

**Comment by zhuxiujia** [comment]
> Mysql的字段类型为BIGINT（20）。

1.8.7版本中我试了BIGINT（20） 用i64可以解析，i128也可以解析

**Comment by zhuxiujia** [comment]
> 3ks.
> I will test #48 later on my project.
> 
> I had found a new problem that I can't ensure that is whether in Rbatis.
> Doc of serde said that i128 or u128 can implement by macro , but I never found the place or medium to get this.

Many languages don't even support I128 or U128, so you might consider using BigDecimal
