### ISSUE TITLE
提交一个小bug

### ISSUE THREAD

**Issue by templar721** [rbatis/rbatis#51]
db_adapter.rs中第252行，

> return Ok(DBPoolConn {
                    driver_type: **DriverType::Mssql,**
                    mysql: None,
                    postgres: None,
                    sqlite: None,
                    mssql: Some(conn.unwrap()),
                });

应该是这样的把。好像是拷贝的时候，把sqllite的驱动类型名称拷贝过来了 @zhuxiujia

**Comment by zhuxiujia** [comment]
是的，是个bug
