### ISSUE TITLE
Variable `recordsValue` should have snake_case name, e.g. `records_value`

### ISSUE THREAD

**Issue by liniu** [rbatis/rbatis#510]
![image](https://github.com/rbatis/rbatis/assets/11866304/32f0d4c6-673f-48a7-a800-0b9e08a40f30)

**Comment by liniu** [comment]
![image](https://github.com/rbatis/rbatis/assets/11866304/660f4ee4-e20b-4066-8c82-06128c25bf3b)

totalValue 也是

**Comment by zhuxiujia** [comment]
你执行cargo update更新依赖库版本了吗

**Comment by liniu** [comment]
> 你执行cargo update更新依赖库版本了吗

sorry，我的错，版本非最新的，谢谢您
