### ISSUE TITLE
How to dynamically specify schema

### ISSUE THREAD

**Issue by dianond** [rbatis/rbatis#514]
I have read the documentation of V4 and found no explanation about schema.
I now encounter the same table structure under different schema in the same database.
How can I switch between different schema?

This is how I use crud macros:
crud!(BizActivity{}, "schema_a.biz_activity");
But it can no longer be used
crud!(BizActivity{}, "schema_b.biz_activity");
Compilation will fail

**Comment by zhuxiujia** [comment]
`crud!(BizActivity{}, "schema_b.biz_activity");` Compilation  will be ok,did you run `cargo update` to update ?

**Comment by dianond** [comment]
I use the following code
    let value = vec![];
    let change_schema = format!("SET search_path TO {}", db_schema_a);
    rb.exec(&change_schema, value).await.unwrap();
    BizActivity::select_all(&rb).await;
This output can retrieve table data under the specified schema.

But continuing to use the code to set schema_b still returns the data in schema_a
    let value = vec![];
    let change_schema = format!("SET search_path TO {}", db_schema_b);
    rb.exec(&change_schema, value).await.unwrap();
    BizActivity::select_all(&rb).await;

Using database tools to execute sentence by sentence is not a problem
    SET search_path TO schema_a;
    select * from biz_activity;
    SET search_path TO schema_b;
    select * from biz_activity;

I don't understand why it works the first time, but it doesn't work afterwards
    SET search_path TO schema_a  ok
    SET search_path TO schema_b  fail

**Comment by dianond** [comment]
I found that there was confusing behavior during execution

```
    let value = vec![];
    let change_schema = format!("SET search_path TO {}", db_schema_b);
    rb.exec(&change_schema, value).await.unwrap();
    BizActivity::select_all(&rb).await;

    let value = vec![];
    let change_schema = format!("SET search_path TO {}", db_schema_a);
    rb.exec(&change_schema, value).await.unwrap();
    BizActivity::select_all(&rb).await;

    let value = vec![];
    let change_schema = format!("SET search_path TO {}", db_schema_b);
    rb.exec(&change_schema, value).await.unwrap();
    BizActivity::select_all(&rb).await;
```
The code retrieves schema_b data for the first time, schema_a data for the second time, and schema_b data for the third time.
The result returns schema_b data for the first time, schema_b data for the second time, and schema_a data for the third time.
The code is **bab**, but the result is **bba** 

Multiple executions with consistent results

**Comment by dianond** [comment]
Add the fourth time
The code is **baba**, but the result is **bbab**

**Comment by dianond** [comment]
testing environment
Docker postgres:alpine

Add schema_a and schema_b to the database postgres.
```
CREATE TABLE schema_a.table_test (
	name_test varchar NULL
);
INSERT INTO schema_a.table_test
(name_test)
VALUES('aaa');
```
```
CREATE TABLE schema_b.table_test (
	name_test varchar NULL
);
INSERT INTO schema_b.table_test
(name_test)
VALUES('bbb');
```

rust code
```
use std::time::Duration;
use log::{Level, log};
use rbatis::RBatis;
use rbdc_pg::PgDriver;
use serde::{Deserialize, Serialize};
use urlencoding::encode;

pub async fn run() {
    // enable log crate to show sql logs
    fast_log::init(fast_log::Config::new().console()).expect("rbatis init fail");
    let rb = RBatis::new();
    let db_host = "localhost";
    let db_user = "postgres";
    let db_pwd = "1234567";
    let db_pwd = encode(db_pwd);
    let db_name = "postgres";
    let db_url = format!("postgresql://{}:{}@{}:5432/{}", db_user, db_pwd, db_host, db_name);
    log!(Level::Info, "db_url:{}", &db_url);

    rb.init(PgDriver {}, &db_url).unwrap();

    let run_param = vec!["schema_a", "schema_b", "schema_a", "schema_b"];

    for &schema in run_param.iter() {
        let value = vec![];
        let change_schema = format!("SET search_path TO {};", schema);
        rb.exec(&change_schema, value).await.unwrap();
        let data = TableTest::select_all(&rb).await.unwrap();
        tokio::time::sleep(Duration::from_millis(500)).await;
        println!("select_all = {:?}", data);
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TableTest {
    pub name_test: Option<String>,
}

crud!(TableTest{}, "table_test");
```

output
```
2024-04-11 15:38:59.1250587 [INFO] [rbatis] [620885921234948097] => `SET search_path TO schema_a;` []
2024-04-11 15:38:59.1255732 [INFO] [rbatis] [620885921234948097] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 15:38:59.2113914 [INFO] [rbatis] [620885921595658243] => `select * from table_test ` []
2024-04-11 15:38:59.2126179 [INFO] [rbatis] [620885921595658243] <= len=1
select_all = [TableTest { name_test: Some("aaa") }]
2024-04-11 15:39:00.003406  [INFO] [rbatis] [620885924917547013] => `SET search_path TO schema_b;` []
2024-04-11 15:39:00.0039098 [INFO] [rbatis] [620885924917547013] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 15:39:00.0888497 [INFO] [rbatis] [620885925274062855] => `select * from table_test ` []
2024-04-11 15:39:00.0894934 [INFO] [rbatis] [620885925274062855] <= len=1
select_all = [TableTest { name_test: Some("aaa") }]
2024-04-11 15:39:00.890744  [INFO] [rbatis] [620885928637894665] => `SET search_path TO schema_a;` []
2024-04-11 15:39:00.8912879 [INFO] [rbatis] [620885928637894665] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 15:39:00.9775975 [INFO] [rbatis] [620885929002799115] => `select * from table_test ` []
2024-04-11 15:39:00.978781  [INFO] [rbatis] [620885929002799115] <= len=1
select_all = [TableTest { name_test: Some("bbb") }]
2024-04-11 15:39:01.7782843 [INFO] [rbatis] [620885932362436621] => `SET search_path TO schema_b;` []
2024-04-11 15:39:01.778854  [INFO] [rbatis] [620885932362436621] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 15:39:01.8637564 [INFO] [rbatis] [620885932718952463] => `select * from table_test ` []
2024-04-11 15:39:01.8643993 [INFO] [rbatis] [620885932718952463] <= len=1
select_all = [TableTest { name_test: Some("aaa") }]
```

**Comment by zhuxiujia** [comment]
did you try ?
```rust
crud!(TableTestA{}, "schema_a.table_test");
```

```rust
crud!(TableTestB{}, "schema_b.table_test");
```

**Comment by dianond** [comment]
The schema name is dynamic and may include schema_a, schema_b, schema_c, schema_d, or even more.

So I can't fix it with a string.

**Comment by dianond** [comment]
```
let db_url = format!("postgresql://{}:{}@{}:5432/{}?options=-c%20search_path%3D{}", db_user, db_pwd, db_host, db_name, db_schema);
rb.init(PgDriver {}, &db_url).unwrap();
let data = TableTest::select_all(&rb).await.unwrap();
```

By using this method, there is no problem with the result, but it cannot reuse the database connection.
So, I still want to use 'SET search_path TO schema_a'.

There is another issue, after I execute the setup code twice in a row, the query code shows a panic.
 ```
let value = vec![];
let change_schema = format!("SET search_path TO {};", schema);
rb.exec(&change_schema, value).await.unwrap();
let value = vec![];
rb.exec(&change_schema, value).await.unwrap();
let data = TableTest::select_all(&rb).await.unwrap();
```
The error is that the table cannot be found. I guess the schema has been set to public.

So you can troubleshoot the issue from here. Setting the schema multiple times within the same session does not cause any issues with SQL tools, but the rbatis framework seems to be different.

**Comment by zhuxiujia** [comment]
> ```
> let db_url = format!("postgresql://{}:{}@{}:5432/{}?options=-c%20search_path%3D{}", db_user, db_pwd, db_host, db_name, db_schema);
> rb.init(PgDriver {}, &db_url).unwrap();
> let data = TableTest::select_all(&rb).await.unwrap();
> ```
> 
> By using this method, there is no problem with the result, but it cannot reuse the database connection. So, I still want to use 'SET search_path TO schema_a'.
> 
> There is another issue, after I execute the setup code twice in a row, the query code shows a panic.
> 
> ```
> let value = vec![];
> let change_schema = format!("SET search_path TO {};", schema);
> rb.exec(&change_schema, value).await.unwrap();
> let value = vec![];
> rb.exec(&change_schema, value).await.unwrap();
> let data = TableTest::select_all(&rb).await.unwrap();
> ```
> 
> The error is that the table cannot be found. I guess the schema has been set to public.
> 
> So you can troubleshoot the issue from here. Setting the schema multiple times within the same session does not cause any issues with SQL tools, but the rbatis framework seems to be different.

You should not randomly execute connections from the connection pool. A connection should be taken from the connection pool to execute the statement
for example:
```rust
let conn = rb.acquire().await;
conn .exec(&change_schema, value).await.unwrap();
let data = TableTest::select_all(&conn ).await.unwrap();
```

**Comment by dianond** [comment]
Thank you very much. I tried it and the problem was resolved

```
let conn = rb.acquire().await.unwrap();
let change_schema = format!("SET search_path TO {}", schema);
conn.exec(&change_schema, vec![]).await.unwrap();
let data = TableTest::select_all(&conn).await.unwrap();
```

**Comment by zhuxiujia** [comment]
> Thank you very much. I tried it and the problem was resolved
> 
> ```
> let conn = rb.acquire().await.unwrap();
> let change_schema = format!("SET search_path TO {}", schema);
> conn.exec(&change_schema, vec![]).await.unwrap();
> let data = TableTest::select_all(&conn).await.unwrap();
> ```

i try code
```rust
 let result = rb
        .exec(&format!("SET search_path TO a"), vec![])
        .await
        .unwrap();
    println!(">>>>> exec={}", result);
    let result = rb
        .exec(&format!("SET search_path TO b"), vec![])
        .await
        .unwrap();
    println!(">>>>> exec={}", result);
    let result = rb
        .exec(&format!("SET search_path TO a"), vec![])
        .await
        .unwrap();
    println!(">>>>> exec={}", result);
    let result = rb
        .exec(&format!("SET search_path TO b"), vec![])
        .await
        .unwrap();
    println!(">>>>> exec={}", result);
```

```log
>>>>> exec={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 22:42:03.2439634 [INFO] [rbatis] [620992389942611969] => `SET search_path TO a` []
2024-04-11 22:42:03.2444637 [INFO] [rbatis] [620992389942611969] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 22:42:03.3185276 [INFO] [rbatis] [620992390257184771] => `SET search_path TO b` []
>>>>> exec={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 22:42:03.3189867 [INFO] [rbatis] [620992390257184771] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 22:42:03.3934686 [INFO] [rbatis] [620992390571757573] => `SET search_path TO a` []
>>>>> exec={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 22:42:03.3939305 [INFO] [rbatis] [620992390571757573] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 22:42:03.4687854 [INFO] [rbatis] [620992390886330375] => `SET search_path TO b` []
>>>>> exec={"rows_affected": 0, "last_insert_id": Null}
2024-04-11 22:42:03.4692542 [INFO] [rbatis] [620992390886330375] <= rows_affected={"rows_affected": 0, "last_insert_id": Null}

```

this is ok.

**Comment by dianond** [comment]
It's just a problem with the connection pool. Using rb to only do `SET search_path TO b` won't cause any problems, but when doing queries, it may not be the same session. Therefore, after using `rb.equire()` to obtain this session (which I understand myself), there will be no problems in the same session.
