### ISSUE TITLE
field value with json string, return invalid type: map, expected String error

### ISSUE THREAD

**Issue by mifly** [rbatis/rbatis#517]
rbatis version is 4.5  
sqlite database  
when I define a struct with a field type `Some<String> `   
and add a record, the field value set to a object json string, something like `{"id":"01HVZGMB3"}`  
when invoke impl_select! query, I expect it return OK, but it will error: invalid type: map, expected String...  

By the way, Thinks your work

**Comment by zhuxiujia** [comment]
> rbatis version is 4.5 sqlite database when I define a struct with a field type `Some<String> ` and add a record, the field value set to a object json string, something like `{"id":"01HVZGMB3"}` when invoke impl_select! query, I expect it return OK, but it will error: invalid type: map, expected String...
> 
> By the way, Thinks your work

did you run `cargo update` and  see example: https://github.com/rbatis/rbatis/blob/master/example/src/crud_json.rs

**Comment by mifly** [comment]
Thinks, OK now
