### ISSUE TITLE
Setting the maximum connection pool doesn't work well

### ISSUE THREAD

**Issue by wl416195** [rbatis/rbatis#518]
Hello, I set the maximum number of connection pools, but it's not working.
![image](https://github.com/rbatis/rbatis/assets/141891244/3d133c15-41b9-43f5-91a6-80fd0b2ed0c5)
![image](https://github.com/rbatis/rbatis/assets/141891244/a24b9cb8-97a5-462b-ad19-8b82b2e46f11)

One more question Can you help me implement the set_max_idle_conns method and set_conn_max_lifetime Thanks!

![image](https://github.com/rbatis/rbatis/assets/141891244/0d8c7f80-2c8d-470d-8aa7-d76a2f743d87)

**Comment by zhuxiujia** [comment]
> Hello, I set the maximum number of connection pools, but it's not working. ![image](https://private-user-images.githubusercontent.com/141891244/325528029-3d133c15-41b9-43f5-91a6-80fd0b2ed0c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzgxMzMsIm5iZiI6MTcxNDAzNzgzMywicGF0aCI6Ii8xNDE4OTEyNDQvMzI1NTI4MDI5LTNkMTMzYzE1LTQxYjktNDNmNS05MWE2LTgwZmQwYjJlZDBjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwOTM3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjAzMGMzZGRiNDE2NjRiMmVlOTY0MmNhMWRlMzE0YTc5YWY5NDI3NDQ3MzJhOGJkMzM4NjBmMmVjY2IzMWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9aaEJCPR1gbEFgB8R58Ic9cNSZrObqw3UyQbSIRvTtg) ![image](https://private-user-images.githubusercontent.com/141891244/325528449-a24b9cb8-97a5-462b-ad19-8b82b2e46f11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzgxMzMsIm5iZiI6MTcxNDAzNzgzMywicGF0aCI6Ii8xNDE4OTEyNDQvMzI1NTI4NDQ5LWEyNGI5Y2I4LTk3YTUtNDYyYi1hZDE5LThiODJiMmU0NmYxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwOTM3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDdkODlkN2ExZTFlZmQ3Yzk2Nzk5M2JjMDk0Njc1ZmQ3MzYxYmIyZmVkYzcxMDFlMDQ2ZTBhYzc0ODY0M2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uzJZuDWGXoBEsFtSXROJSGRP8BJufasLJjdqehjO-0g)
> 
> One more question Can you help me implement the set_max_idle_conns method and set_conn_max_lifetime Thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/141891244/325528701-0d8c7f80-2c8d-470d-8aa7-d76a2f743d87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzgxMzMsIm5iZiI6MTcxNDAzNzgzMywicGF0aCI6Ii8xNDE4OTEyNDQvMzI1NTI4NzAxLTBkOGM3ZjgwLTJjOGQtNDcwZC04YWE3LWQ3NmEyZjc0M2Q4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwOTM3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzc4M2I5OTg0YzI4Njg4Yzg0ZWNkZjI2YzhiYWMzYTNhOTA3M2U4MGU3NDdjZDgzZjIzMDFiZTlmZTAxZmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8qJPR-2I_8i__Gou4XNAT9KzVIJTqFhsCvKngtpDzf4)

FastPool unsupport `set_max_idle_conns`  but .
FastPool support `set_max_open_conns`.
did you run `cargo update` command?

**Comment by wl416195** [comment]
No, I'll try to run it.

**Comment by wl416195** [comment]
Great
