### ISSUE TITLE
openssl-sys v0.9.58错误

### ISSUE THREAD

**Issue by gqinghua** [rbatis/rbatis#52]
error: failed to run custom build command for `openssl-sys v0.9.58` 
此错误会导致
cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset

 $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.58
把rbatis依赖去除，则构建成功，具体原因未知

**Comment by gqinghua** [comment]
记录原因,防止踩坑

**Comment by zhuxiujia** [comment]
> error: failed to run custom build command for `openssl-sys v0.9.58`
> 此错误会导致
> cargo:rustc-cfg=const_fn
> cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
> X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
> 
> $HOST = x86_64-unknown-linux-gnu
> $TARGET = x86_64-unknown-linux-gnu
> openssl-sys = 0.9.58
> 把rbatis依赖去除，则构建成功，具体原因未知

Cargo.lock 看出，是tls库依赖openssl 。  定位到 是sqlx-rt  依赖了tls(async_std feature 启用的情况下)

**Comment by rustyang** [comment]
怎么解决的，巨佬

**Comment by rustyang** [comment]
> 问题已解决,是因为openssl库升级原因导致编译失败
要怎么做

**Comment by zhuxiujia** [comment]
> > 问题已解决,是因为openssl库升级原因导致编译失败
> > 要怎么做

最新版本的rbatis 默认使用 rustls（是兼容的,老版本使用native tls（依赖系统openssl））,   
 你们所说的不兼容情况我也碰到了，
在centos下，跑rbatis/example 是正常的，
但是如果你使用了类似rewest之类的库的话，是依赖tokio-openssl-依赖native ssl

**Comment by zhuxiujia** [comment]
> error: failed to run custom build command for `openssl-sys v0.9.58`
> 此错误会导致
> cargo:rustc-cfg=const_fn
> cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
> X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
> 
> $HOST = x86_64-unknown-linux-gnu
> $TARGET = x86_64-unknown-linux-gnu
> openssl-sys = 0.9.58
> 把rbatis依赖去除，则构建成功，具体原因未知

使用最新版 rbatis 解决，新版使用了rustls

**Comment by rustyang** [comment]
谢巨佬
