### ISSUE TITLE
Does the latest version not support Option single result?

### ISSUE THREAD

**Issue by LiangYaoHuo** [rbatis/rbatis#521]
![image](https://github.com/rbatis/rbatis/assets/65275012/7a708835-9430-41b4-b8d8-95884b9010af)
提示异常：Some("系统异常:invalid type: map, expected a string")

**Comment by zhuxiujia** [comment]
你执行过cargo update 更新依赖了吗？

```rust
/// doc you can see https://rbatis.github.io/rbatis.io
#[sql("select max(id) from activity")]
async fn raw_sql(rb: &RBatis, delete_flag: &i32) -> String {
    impled!()
}
```
```log
2024-05-06 22:24:36.0922484 [INFO] [rbatis] [630047694512984079] => `select max(id) from activity` [0]
"3"
2024-05-06 22:24:36.092448  [INFO] [rbatis] [630047694512984079] <= len=1,rows=[{"max(id)":"3"}]

```

**Comment by LiangYaoHuo** [comment]
之前是4.5.11版本，cargo update更新了4.22版本后就不可以了，我看了更改记录，发现是4.20版本后decode.rs那里更改了导致的，然后就不支持解码Option<T>这种类型了
![1715010694225](https://github.com/rbatis/rbatis/assets/65275012/d9aa6e3f-9fd5-4a8a-9907-32f09ed3a5ed)

**Comment by zhuxiujia** [comment]
> 之前是4.5.11版本，cargo update更新了4.22版本后就不可以了，我看了更改记录，发现是4.20版本后decode.rs那里更改了导致的，然后就不支持解码Option这种类型了 ![1715010694225](https://private-user-images.githubusercontent.com/65275012/328238506-d9aa6e3f-9fd5-4a8a-9907-32f09ed3a5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTU2MTgsIm5iZiI6MTcxNTA5NTMxOCwicGF0aCI6Ii82NTI3NTAxMi8zMjgyMzg1MDYtZDlhYTZlM2YtOWZkNS00YThhLTk5MDctMzJmMDllZDNhNWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE1MjE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTUyN2M5MjU2M2QzZjU3Y2RhNjg4MGUwMTg1MDE3MmJjZGNkNjM3ZDI5MWU2ZDVmZjAxMjYzZjJlNGUzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7BV4X3nFr7GCkC7oK_1gJsCrArGvfz3fYIMVg8_Hgl4)

嗯，已添加补丁代码，等下次新版本发布
