### ISSUE TITLE
How to use rbatis to implement dynamic structure like Java return value map < string, Object >

### ISSUE THREAD

**Issue by wcpsoft** [rbatis/rbatis#523]
How to use rbatis to implement dynamic structure like Java return value map < string, Object > , I want to write a dynamic SQL DBIO for general DBIO DBIO. HTML manipulates the database, and the surface and field names and conditions are dynamically parsed by SQL, similar to MYBATIS3's tag parsing.

**Comment by wcpsoft** [comment]
#[html_sql("src/mapper/dbio/dbio.html")]
async fn select_test<T>(rb: & dyn Executor) -> Vec<T> {
    impled!()
}
Similar writing does not work

**Comment by zhuxiujia** [comment]
not support , must be 
```
[ {"column":"value"}  ,   {"column":"value"}]

```

**Comment by wcpsoft** [comment]
Is there a plan to support it? This is important for low code development

**Comment by wcpsoft** [comment]
hi,I want to ask again how this return value works？
`
#[html_sql("src/mapper/dbio/dbio.html")]
async fn select_test(rb: & dyn Executor) -> Vec<HashMap<String, String>> {
    impled!()
}

#[tokio::main]
async fn main() {
    log::init_logging();
    route::load_route_config();
    let mut app = Router::new()
        .route("/", get(root))
        .route("/dbio", get(test_log))
        .route("/health", get(health));

    let rb = RBatis::new();
    rb.link(PgDriver {},"postgres://root:rxzhang@pgsql_root2024@192.168.3.116:5432/helloweb").await.unwrap();
    let result: Vec<HashMap<String, String>> = select_test(&rb).await.unwrap_or_else(|err| {
        vec![]
    });
    info!("select_test:{:?}", result);
    let count = count_test(&rb).await.unwrap_or_else(|err| {
        0
    });
    info!("count_test:{:?}", count);
    let addr = "0.0.0.0:3000";
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app.into_make_service())
        .await
        .unwrap();
}

    <select id="select_test">
        `select * from test`
    </select>

`

**Comment by wcpsoft** [comment]
INFO 2024-05-30 09:56:13 +08:00 [main] pid:46341 tid:1988709 - [rbatis] [638556668002570242] => `select * from test` []
INFO 2024-05-30 09:56:13 +08:00 [main] pid:46341 tid:1988709 - [rbatis] [638556668002570242] <= len=2
INFO 2024-05-30 09:56:13 +08:00 [main] pid:46341 tid:1988709 - select_test:[]
INFO 2024-05-30 09:56:13 +08:00 [main] pid:46341 tid:1988709 - [rbatis] [638556668522663940] => `select count(1) from test` []
INFO 2024-05-30 09:56:13 +08:00 [main] pid:46341 tid:1988709 - [rbatis] [638556668522663940] <= len=1
INFO 2024-05-30 09:56:13 +08:00 [main] pid:46341 tid:1988709 - count_test:2

test data: {id:1 test:234}, {id:1 test:test}

**Comment by wcpsoft** [comment]
Resolved, using serde: : Value to help get the transformation of the Value, basically accomplishing the purpose of OBJEC.   
 let result: Vec<HashMap<String, serde_json::Value>> = select_test(&rb).await.unwrap_or_else(|err| {
        vec![]
    });
    info!("select_test:{:?}", result);
    //遍历result
    for item in result.iter() {
        for (key, value) in item.iter() {
            // 判定value类型,然后输出
            if value.is_string() {
                info!("key:{},value:{}", key, value.as_str().unwrap());
            } else if value.is_number() {
                info!("key:{},value:{}", key, value.as_u64().unwrap());
            }
        }
    }
