### ISSUE TITLE
rbatis::crud!(Book {},"t_book");    No effect

### ISSUE THREAD

**Issue by lontten** [rbatis/rbatis#524]
win11 
rustc 1.78.0
pg
serde = { version = "1", features = ["derive"] }

rbs = { version = "4.5" }
rbatis = { version = "4.5" }
rbdc-pg = { version = "4.5" }
```rust
rbatis::crud!(Book {},"t_book"); // this way custom table name
impl_select!(Book{select_one() -> Option => "`limit 1`"});
``` 

sql
select * from book limit 1

**Comment by zhuxiujia** [comment]
> win11 rustc 1.78.0 pg serde = { version = "1", features = ["derive"] }
> 
> rbs = { version = "4.5" } rbatis = { version = "4.5" } rbdc-pg = { version = "4.5" }
> 
> ```rust
> rbatis::crud!(Book {},"t_book"); // this way custom table name
> impl_select!(Book{select_one() -> Option => "`limit 1`"});
> ```
> 
> sql select * from book limit 1

```rust
impl_select!(Book{select_one() -> Option => "`limit 1`","t_book"});
```
