### ISSUE TITLE
Do not use AtomicU64 !!!

### ISSUE THREAD

**Issue by asemor** [rbatis/rbatis#527]
Some platforms do not  support AtomicU64, please use AtomicUsize instead.

**Comment by zhuxiujia** [comment]
did you use `cargo build --target i686-pc-windows-gnu` and `cargo build --target i686-unknown-linux-gnu` ????

**Comment by asemor** [comment]
I used cargo build --target=armv5te-unknown-linux-musleabi

**Comment by asemor** [comment]
The armv5te-unknown-linux-musleabi target need armv5l gcc. You can download it from https://musl.cc/armv5l-linux-musleabi-cross.tgz
