### ISSUE TITLE
增加数据库的feature，只编译特定的数据库，对移设备友好

### ISSUE THREAD

**Issue by Peacess** [rbatis/rbatis#53]

**Comment by zhuxiujia** [comment]
最新版本已支持

**Comment by Peacess** [comment]
feature增加了特定数据库的，
但是为什么编译出来文件大小，还是那么大呢，是不是所有数据库相关的代码都编译进去了

**Comment by zhuxiujia** [comment]
> feature增加了特定数据库的，
> 但是为什么编译出来文件大小，还是那么大呢，是不是所有数据库相关的代码都编译进去了

你可以检查 Cargo.lock ，比如我只编译mysql,那你在。lock文件是找不到sqlie3-sys的依赖的。
