### ISSUE TITLE
When MySQL inserts batch into database insert_batch, if the number of None attribute columns in the collection is inconsistent, an error will be reported.

### ISSUE THREAD

**Issue by Tomao2014** [rbatis/rbatis#531]
作者您好，MySQL批量入库insert_batch时，如果集合中为None的属性列数量不一致时，将会报错。

依赖版本：
```toml
# rbatis 数据库ORM
rbs = { version = "4.5" }
rbatis = { version = "4.5" }
rbdc-mysql = { version = "4.5" }
```

```rust
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BizActivity {
    pub id: Option<String>,
    pub name: Option<String>,
    pub pc_link: Option<String>,
}

crud!(BizActivity {});

#[tokio::test]
async fn test() {
    let mut tables = vec![];
    tables.push(BizActivity {
        id: Some("1".into()),
        name: Some("rbatis".into()),
        pc_link:Some("https://github.com/rbatis/rbatis".into()),
    });
    tables.push(BizActivity {
        id: Some("2".into()),
        name: Some("MysqlDriver".into()),
        pc_link: None,
    });
    BizActivity::insert_batch(&rb, &tables, 100).await.unwrap();
}
```

最终执行的SQL 语句是
`insert into biz_activity (id,name,pc_link) VALUES (?,?,?),(?,?)`

请问这种场景下，除了将tables[1].pc_link的None属性修改成Some("".into())，以保持集合中各个属性值不为None的数量一致之外，还没有其他更好的解决方案。

**Comment by zhuxiujia** [comment]
> 作者您好，MySQL批量入库insert_batch时，如果集合中为None的属性列数量不一致时，将会报错。
> 
> 依赖版本：
> 
> ```toml
> # rbatis 数据库ORM
> rbs = { version = "4.5" }
> rbatis = { version = "4.5" }
> rbdc-mysql = { version = "4.5" }
> ```
> 
> ```rust
> use serde::{Deserialize, Serialize};
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub struct BizActivity {
>     pub id: Option<String>,
>     pub name: Option<String>,
>     pub pc_link: Option<String>,
> }
> 
> crud!(BizActivity {});
> 
> #[tokio::test]
> async fn test() {
>     let mut tables = vec![];
>     tables.push(BizActivity {
>         id: Some("1".into()),
>         name: Some("rbatis".into()),
>         pc_link:Some("https://github.com/rbatis/rbatis".into()),
>     });
>     tables.push(BizActivity {
>         id: Some("2".into()),
>         name: Some("MysqlDriver".into()),
>         pc_link: None,
>     });
>     BizActivity::insert_batch(&rb, &tables, 100).await.unwrap();
> }
> ```
> 
> 最终执行的SQL 语句是 `insert into biz_activity (id,name,pc_link) VALUES (?,?,?),(?,?)`
> 
> 请问这种场景下，除了将tables[1].pc_link的None属性修改成Some("".into())，以保持集合中各个属性值不为None的数量一致之外，还没有其他更好的解决方案。

将在下个版本 4.5.26 解决这个问题
