### ISSUE TITLE
Error found when I used rbatis to connect postgres server which has a column with type timestamptz in the table

### ISSUE THREAD

**Issue by HeroistBi** [rbatis/rbatis#535]
I created a struct including a field which uses Option<Timestamptz>, there was an error message found , the detail message is ::

called `Result::unwrap()` on an `Err` value: E("a character literal was not valid of '2024-07-26 09:03:48+00'"),

postgres server's version is : 16.3

I don't know how to fix this error, it seems like the field value that postgres returned has a wrong format, your help will be apprecicated very much.

**Comment by zhuxiujia** [comment]
fix on rbdc-pg=v4.5.8
