### ISSUE TITLE
Deadlocked on RBatis.acquire method

### ISSUE THREAD

**Issue by longzou** [rbatis/rbatis#536]
When I use the RBatis in a Pin<Box<Future>>, it will cause the acquire method deadlock.

**Comment by zhuxiujia** [comment]
> When I use the RBatis in a Pin<Box>, it will cause the acquire method deadlock.

Can you provide test code?

**Comment by longzou** [comment]
This may not a bug. But it may be a good suggestion for use RBatis. 
I used the RBatis in two difference tokio runtime that will make the deadlock occurred. 
So, don't use rb in difference tokio runtime.

**Comment by zhuxiujia** [comment]
> This may not a bug. But it may be a good suggestion for use RBatis.
> I used the RBatis in two difference tokio runtime that will make the deadlock occurred.
> So, don't use rb in difference tokio runtime.

The lock of Tokio cannot be shared across multiple runtimes, which is an issue with Tokio。 not `RBatis`
