### ISSUE TITLE
select COALESCE(max(sort) + 1, 1) , return error

### ISSUE THREAD

**Issue by RisingStar20** [rbatis/rbatis#538]
rbatis：4.5.29
数据库：pg 16
字段：sort   real 类型

```rust
   pub async fn select_max_sort(activity_id:i64)-> Result<f32,   Error>{
        pool!().query_decode(" select COALESCE(max(sort) + 1, 1) next_sort_value from activity where activity_id = ? ", vec![rbs::to_value!(activity_id)])
            .await
    }

``` 
问题： 返回有问题 。 查不到activity_id对应的数据，返回了：1.875  。正确返回默认值为： 1

**Comment by zhuxiujia** [comment]
这看起来是你自己的问题吧

**Comment by zhuxiujia** [comment]
> rbatis：4.5.29 数据库：pg 16 字段：sort real 类型
> 
> ```rust
>    pub async fn select_max_sort(activity_id:i64)-> Result<f32,   Error>{
>         pool!().query_decode(" select COALESCE(max(sort) + 1, 1) next_sort_value from activity where activity_id = ? ", vec![rbs::to_value!(activity_id)])
>             .await
>     }
> ```
> 
> 问题： 返回有问题 。 查不到activity_id对应的数据，返回了：1.875 。正确返回默认值为： 1

这是你的问题，数据类型如果是浮点型，pg 的加算法会出错。如果你表里的类型是int 类型，则能得到正确结果。
如果不用预编译参数，也能正确结果。  用了预编译，表数据是浮点型，加算法会失真（这是pg数据库的问题）

**Comment by zhuxiujia** [comment]
找到bug了，将在下个pg版本做修复

**Comment by zhuxiujia** [comment]
已发布 rbdc-pg  v4.5.10
