### ISSUE TITLE
What is this code and does it work?

### ISSUE THREAD

**Issue by zoain-it** [rbatis/rbatis#54]
https://github.com/rbatis/rbatis/blob/8a763bd80737ea16864a9b41c639f5b837f74b52/src/engine/runtime.rs#L84

**Comment by zhuxiujia** [comment]
> https://github.com/rbatis/rbatis/blob/8a763bd80737ea16864a9b41c639f5b837f74b52/src/engine/runtime.rs#L84

Determine if the string is a number,
 is much faster than  
```rust
"0".parse::<f64>()
```

**Comment by zoain-it** [comment]
But it's wrong and doesn't work properly. For example, "1.1.1.-1"

**Comment by zhuxiujia** [comment]
> But it's wrong and doesn't work properly. For example, "1.1.1.-1"

You're right, it's a bug，i will change to parse

**Comment by zoain-it** [comment]
The code quality of this library is questionable.

**Comment by zhuxiujia** [comment]
> The code quality of this library is questionable.

Don't use it if you doubt, try it if you believe
