### ISSUE TITLE
Can you add support for the chrono date and time type?

### ISSUE THREAD

**Issue by liniu** [rbatis/rbatis#542]
能否增加 chrono 日期时间类型的支持？

**Comment by zhuxiujia** [comment]
> 能否增加 chrono 日期时间类型的支持？

不能

**Comment by prehonor** [comment]
#[serde(deserialize_with = "deserialize_datetime")]
    pub time: NaiveDateTime,


fn deserialize_datetime<'de, D>(deserializer: D) -> Result<NaiveDateTime, D::Error>
where
    D: Deserializer<'de>,
{
    
    let ms = i64::deserialize(deserializer)?;
    let datetime = Utc.timestamp_millis_opt(ms).unwrap();
    let naive_datetime = datetime.naive_utc();
    let date = naive_datetime.date();
    let time = naive_datetime.time();
    Ok(NaiveDateTime::new(date, time))
}
