### ISSUE TITLE
LIKE '%?%'  can't match data

### ISSUE THREAD

**Issue by RisingStar20** [rbatis/rbatis#544]
rbs = "= 4.5.18"
rbatis = { version = "= 4.5.29"}
rbdc =  "= 4.5.33"
rbdc-pg={version="= 4.5.11" }
 database：pg 16

    pub async fn test_like(content:&str) -> Result<Vec<BizActivity>, rbdc::Error>{
        pool!().query_decode("select * from biz_activity where h5_link like '%?%' ", vec![rbs::to_value!(content)])
            .await
    }

**Comment by zhuxiujia** [comment]
> rbs = "= 4.5.18" rbatis = { version = "= 4.5.29"} rbdc = "= 4.5.33" rbdc-pg={version="= 4.5.11" } database：pg 16
> 
> ```
> pub async fn test_like(content:&str) -> Result<Vec<BizActivity>, rbdc::Error>{
>     pool!().query_decode("select * from biz_activity where h5_link like '%?%' ", vec![rbs::to_value!(content)])
>         .await
> }
> ```

```
   pub async fn test_like(pool: &RBatis,content:&str) -> Result<Vec<Activity>, Error>{
        pool.query_decode("select * from activity where name like ? ", vec![rbs::to_value!(content)])
            .await
    }
    //query
    let r=test_like(&rb,"%2%").await.unwrap();
    println!("{:?}",r);
```

If you are familiar with MySQL instead of PG database, please don't ask questions without thinking
