### ISSUE TITLE
fetch_prepare if fetch null will throw ex

### ISSUE THREAD

**Issue by dopeter** [rbatis/rbatis#55]
If the parameter didn't hit any data that stored in db.

Rbatis gave me a err.

![Uploading image.png…]()

**Comment by dopeter** [comment]
![image](https://user-images.githubusercontent.com/9638883/99509517-cfb2e700-29c0-11eb-99bf-6a881c5b0b51.png)

**Comment by dopeter** [comment]
![image](https://user-images.githubusercontent.com/9638883/99509596-ea855b80-29c0-11eb-8ba1-afb6ab6dfaf4.png)

**Comment by zhuxiujia** [comment]
> If the parameter didn't hit any data that stored in db.
> 
> Rbatis gave me a err.

can't see  any image.  may be  your  return   Struct need  change to   Option<Struct>.

**Comment by dopeter** [comment]
ye, type of return is "Option". 
"Vec<>" is ok.

Maybe it's not an issue.
