### ISSUE TITLE
mysql’s time zone is utc, and the program is deployed on a utc+8 server, which will cause time zone errors

### ISSUE THREAD

**Issue by bajie-git** [rbatis/rbatis#552]
rbaits会认为mysql返回的datetime类型为utc+8，最后转换出来的时间戳会少8个小时。我该怎么配置让rbatis知道返回的时区是utc

**Comment by zhuxiujia** [comment]
> rbaits会认为mysql返回的datetime类型为utc+8，最后转换出来的时间戳会少8个小时。我该怎么配置让rbatis知道返回的时区是utc

目前是根据当前时区的 ， mysql设置到UTC会造成区别

**Comment by bajie-git** [comment]
> > rbaits会认为mysql返回的datetime类型为utc+8，最后转换出来的时间戳会少8个小时。我该怎么配置让rbatis知道返回的时区是utc
> 
> 目前是根据当前时区的 ， mysql设置到UTC会造成区别

目前版本针对我这种场景无解对么，如果我要解决  我需要让程序所在的系统时区和mysql保持一致是么？

**Comment by zhuxiujia** [comment]
> > > rbaits会认为mysql返回的datetime类型为utc+8，最后转换出来的时间戳会少8个小时。我该怎么配置让rbatis知道返回的时区是utc
> > 
> > 
> > 目前是根据当前时区的 ， mysql设置到UTC会造成区别
> 
> 目前版本针对我这种场景无解对么，如果我要解决 我需要让程序所在的系统时区和mysql保持一致是么？

目前可以把mysql的时区设置到北京/上海，可以解决

**Comment by zhuxiujia** [comment]
> > > rbaits会认为mysql返回的datetime类型为utc+8，最后转换出来的时间戳会少8个小时。我该怎么配置让rbatis知道返回的时区是utc
> > 
> > 
> > 目前是根据当前时区的 ， mysql设置到UTC会造成区别
> 
> 目前版本针对我这种场景无解对么，如果我要解决 我需要让程序所在的系统时区和mysql保持一致是么？

如果你用了UTC时间，可以指定时区为0
例如
 ```rust
  use rbdc_mysql::options::MySqlConnectOptions;
  let options = MySqlConnectOptions::new()
     .offset_sec(fastdate::offset_sec());
```

**Comment by bajie-git** [comment]
好的，感谢

**Comment by zhuxiujia** [comment]
> 好的，感谢

看你到底用哪个时区，如果你用UTC就MySqlConnectOptions设置到0

如果你用本地时区，那就 mysql设置到上海

**Comment by bajie-git** [comment]
> > 好的，感谢
> 
> 看你到底用哪个时区，如果你用UTC就MySqlConnectOptions设置到0
> 
> 如果你用本地时区，那就 mysql设置到上海
> 
> 记得先cargo update更新依赖

嗯嗯  了解，其实我当时没有找到设置时区的位置。。。。

**Comment by bajie-git** [comment]
> > > > rbaits会认为mysql返回的datetime类型为utc+8，最后转换出来的时间戳会少8个小时。我该怎么配置让rbatis知道返回的时区是utc
> > > 
> > > 
> > > 目前是根据当前时区的 ， mysql设置到UTC会造成区别
> > 
> > 
> > 目前版本针对我这种场景无解对么，如果我要解决 我需要让程序所在的系统时区和 mysql保持一致是么？
> 
> 2种方案
> 
> 第一种办法： 如果你用了UTC时间，可以指定时区为0 例如
> 
> ```rust
> //默认情况下MysqlConnectOptions的时区设置的是本地
>  use rbdc_mysql::options::MySqlConnectOptions;
>  let options = MySqlConnectOptions::new().offset_sec(0);
> ```
> 
> 第二种办法： 一般情况下，也可以mysql设置时区到上海（而不是使用UTC时间），这样查出来也是对的。



> > > > rbaits会认为mysql返回的datetime类型为utc+8，最后转换出来的时间戳会少8个小时。我该怎么配置让rbatis知道返回的时区是utc
> > > 
> > > 
> > > 目前是根据当前时区的 ， mysql设置到UTC会造成区别
> > 
> > 
> > 目前版本针对我这种场景无解对么，如果我要解决 我需要让程序所在的系统时区和mysql保持一致是么？
> 
> 2种方案
> 
> 第一种办法： 如果你用了UTC时间，可以指定时区为0 例如
> 
> ```rust
> //默认情况下MysqlConnectOptions的时区设置的是本地
>  use rbdc_mysql::options::MySqlConnectOptions;
>  let options = MySqlConnectOptions::new().offset_sec(0);
> ```
> 
> 第二种办法： 一般情况下，也可以mysql设置时区到上海（而不是使用UTC时间），这样查出来也是对的。

最近我又开始看这个问题  我使用了你这个代码
```rust
let mut options = MySqlConnectOptions::new().offset_sec(0);
    options.set_uri("mysql://root:Xzg5Y4vM+[y-AB!@18.142.244.22:3006/longi_darkblue").unwrap();
    rb.init_option::<MysqlDriver, MySqlConnectOptions, DefaultPool>(MysqlDriver {}, options)
        .unwrap();
```
我发现她并没有效果，我查了一些资料  我发现mysql datetime字段是没有时区概念的，也就是给数据库设置社区对这个字段没有任何影响，但我数据库里面存储的日期是另一个程序写入utc时区。

使用rbatis读取出来他总是按照本地时区进行偏移。   我们能指定实体字段的时区么  类似于这种：
```rust
pub struct User {
    /// 用户 ID
    pub id: String,
    /// 邮箱
    pub email: String,
    /// 创建时间   指定接受的日期按照Utc反序列化
    pub create_time: DateTime<Utc>,
}
```

**Comment by bajie-git** [comment]
我还发现 在DateTime方法处设置断点，会进来两次，一次是正常得utc时区另一次就变成了东8时区，进入两次有点难理解，而且第一次是正确的第二次反而错了

![image](https://github.com/user-attachments/assets/02b860ff-d832-4d4b-a758-12cf65885673)

![image](https://github.com/user-attachments/assets/89ea3297-611f-4c3e-bbe3-694475aadda3)
