### ISSUE TITLE
 6/5000 Batch insert data panic

### ISSUE THREAD

**Issue by DongpoMr** [rbatis/rbatis#553]
你好批量插入数据导致 panic IndexMap: key not found

环境:

      Windows 11 和 Linux 20.04 Ubuntu
      rust： 1.80.0

依赖：

     rbs = { version = "4.5.18" }
     rbatis = { version = "4.5.29" }
     rbdc-mysql = { version = "4.5.8" }

代码：简化后的

       #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
       pub struct Test {
           pub id: u64,
          #[serde(skip_serializing_if = "Option::is_none")]
          pub url: Option<String>,
          #[serde(skip_serializing_if = "Option::is_none")]
          #[serde(with = "opt_fast_date_time_formatter", default)]
          pub create_time: Option<fastdate::DateTime>,
       }
       crud!(Test {}, "test ");
        let tmp_list = vec![Test {
            id: 0,
            url: Some("http://192.0.1.1:8585/v5/resources/data?uri=test://aaa/bbb&contentType=image/jpeg".to_owned()),
            create_time: Some(DateTime::now()),
        }, Test {
            id: 0,
            url: None,
            create_time: Some(DateTime::now()),
        }];
       Test ::insert_batch(db, &tmp_list , 350).await;

问题出在url字段上

![微信图片_20240923174037](https://github.com/user-attachments/assets/0773510c-413d-4a04-a656-2171f92000b8)
![微信图片_20240923173322](https://github.com/user-attachments/assets/a1b5e87f-cfca-4183-9898-30eeb6069ddb)
![微信图片_20240923174144](https://github.com/user-attachments/assets/92cb203d-4efd-4d3a-b824-d24ef3502f64)

**Comment by zhuxiujia** [comment]
> 你好批量插入数据导致 panic IndexMap: key not found
> 
> 环境:
> 
> ```
>   Windows 11 和 Linux 20.04 Ubuntu
>   rust： 1.80.0
> ```
> 
> 依赖：
> 
> ```
>  rbs = { version = "4.5.18" }
>  rbatis = { version = "4.5.29" }
>  rbdc-mysql = { version = "4.5.8" }
> ```
> 
> 代码：简化后的
> 
> ```
>    #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
>    pub struct Test {
>        pub id: u64,
>       #[serde(skip_serializing_if = "Option::is_none")]
>       pub url: Option<String>,
>       #[serde(skip_serializing_if = "Option::is_none")]
>       #[serde(with = "opt_fast_date_time_formatter", default)]
>       pub create_time: Option<fastdate::DateTime>,
>    }
>    crud!(Test {}, "test ");
>     let tmp_list = vec![Test {
>         id: 0,
>         url: Some("http://192.0.1.1:8585/v5/resources/data?uri=test://aaa/bbb&contentType=image/jpeg".to_owned()),
>         create_time: Some(DateTime::now()),
>     }, Test {
>         id: 0,
>         url: None,
>         create_time: Some(DateTime::now()),
>     }];
>    Test ::insert_batch(db, &tmp_list , 350).await;
> ```
> 
> 问题出在url字段上
> 
> ![微信图片_20240923174037](https://private-user-images.githubusercontent.com/15266809/369822416-0773510c-413d-4a04-a656-2171f92000b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDA4NjIsIm5iZiI6MTcyNzEwMDU2MiwicGF0aCI6Ii8xNTI2NjgwOS8zNjk4MjI0MTYtMDc3MzUxMGMtNDEzZC00YTA0LWE2NTYtMjE3MWY5MjAwMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE0MDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NGU0MjJlZWY2ZTI4NzgxMTY3ODBhN2EyY2UzMzYzM2QxNjRmM2ViMmM0MTE2ZTE3ODk2NDk3YTEwZjNmNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a-_PFIplXlICRnhPI1-RtFQMq2w6Qk5e18isN38X5Bw) ![微信图片_20240923173322](https://private-user-images.githubusercontent.com/15266809/369822490-a1b5e87f-cfca-4183-9898-30eeb6069ddb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDA4NjIsIm5iZiI6MTcyNzEwMDU2MiwicGF0aCI6Ii8xNTI2NjgwOS8zNjk4MjI0OTAtYTFiNWU4N2YtY2ZjYS00MTgzLTk4OTgtMzBlZWI2MDY5ZGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE0MDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZDZhODQ5OWFkY2E4ZjYzMTVlMjZmMWY2NDc4MWZmNmU3Njk2MDc0MGQ4YmMwNzJjNzI1ZTZmNWM4ZjQxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aueB7rG60-QxnOtuKHr7iDjJBmXu3gb4-tjrN_53JvA) ![微信图片_20240923174144](https://private-user-images.githubusercontent.com/15266809/369822852-92cb203d-4efd-4d3a-b824-d24ef3502f64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDA4NjIsIm5iZiI6MTcyNzEwMDU2MiwicGF0aCI6Ii8xNTI2NjgwOS8zNjk4MjI4NTItOTJjYjIwM2QtNGVmZC00ZDNhLWI4MjQtZDI0ZWYzNTAyZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE0MDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZDFhYWI2MzBlZWRkMzJjMjNjY2UwMDEyZmY1ZjY2Zjg5ZjZhMDY4YjExOGM2ODE0YzYxOTNhZDhlZTBjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NfNMGzTT3Aunjtyzec5SflSL_xVMlUeCVGkSNexyCFI)

已修复，但是不建议在RB使用skip_serializing 以免造成意外。因为RBatis还是蛮依赖序列化的
