### ISSUE TITLE
Trait name typo

### ISSUE THREAD

**Issue by barsdeveloper** [rbatis/rbatis#557]
Hello, is the name rbatis::plugin::table_sync::ColumMapper a typo? I see the method get_column is written correctly

**Comment by zhuxiujia** [comment]
> Hello, is the name rbatis::plugin::table_sync::ColumMapper a typo? I see the method get_column is written correctly

it's TableSync plugin for  get column type

**Comment by barsdeveloper** [comment]
I mean the name ColumMapper shouldn't be spelled ColumnMapper?

**Comment by zhuxiujia** [comment]
i will fix this
