### ISSUE TITLE
有个相关的问题。

### ISSUE THREAD

**Issue by templar721** [rbatis/rbatis#56]
既然rbatis底层使用了sqlx。那么我想问一个问题。sqlx的Pool在使用之后是不是需要close?
按理说随着生命周期的结束，连接应该是被释放了，但是既然Pool有一个close方法，似乎问题有没有那么简单。还是说close方法是关闭整个连接池呢？我英文不是太好，在sqlx中提出的Issues没人理，似乎没人看懂。。哈哈。希望大佬给与解答。

**Comment by zhuxiujia** [comment]
> 既然rbatis底层使用了sqlx。那么我想问一个问题。sqlx的Pool在使用之后是不是需要close?
> 按理说随着生命周期的结束，连接应该是被释放了，但是既然Pool有一个close方法，似乎问题有没有那么简单。还是说close方法是关闭整个连接池呢？我英文不是太好，在sqlx中提出的Issues没人理，似乎没人看懂。。哈哈。希望大佬给与解答。

你可以看sqlx pool的实现，
```rust
pub struct Pool<DB: Database>(pub(crate) Arc<SharedPool<DB>>);
```
它是一个Arc引用计数智能指针包裹的SharedPool.
首先引用计数你应该很熟悉，多线程引用计数表示 
多一个引用那么+1，删一个引用-1.
同时结构体的生命周期为'static 

再来看看sqlx连接池的close方法（可以理解sqlx是设置一个已关闭标志位，通知其他线程我要关了，然后pop掉正在执行的线程），
```rust
    pub(super) async fn close(&self) {
        self.is_closed.store(true, Ordering::Release);
        while let Ok(waker) = self.waiters.pop() {
            waker.wake();
        }

        // ensure we wait until the pool is actually closed
        while self.size() > 0 {
            let _ = self
                .idle_conns
                .pop()
                .map(|idle| Floating::from_idle(idle, self));

            // yield to avoid starving the executor
            sqlx_rt::yield_now().await;
        }
    }
```

最后可以总结为啥生命周期结束也不释放的问题。
因为如果其他线程存在应用的话，那么计数没有归零的情况下，是不会触发Drop的。除非强制调用sqlx的close方法，使用原子标志位通知其他线程我要关了。

**Comment by zhuxiujia** [comment]
> 既然rbatis底层使用了sqlx。那么我想问一个问题。sqlx的Pool在使用之后是不是需要close?
> 按理说随着生命周期的结束，连接应该是被释放了，但是既然Pool有一个close方法，似乎问题有没有那么简单。还是说close方法是关闭整个连接池呢？我英文不是太好，在sqlx中提出的Issues没人理，似乎没人看懂。。哈哈。希望大佬给与解答。


不过 我这边测试确实发现sqlx 的连接池释放有泄漏问题。已提交问题，不知他们怎么处理。
测试代码
```rust
#[cfg(test)]
mod test{
    use std::time::Duration;
    use crate::db::DriverType;
    use sqlx_core::mysql::{MySqlPool, MySqlConnectOptions};
    use std::str::FromStr;
    use sqlx_core::connection::ConnectOptions;

    #[test]
    pub  fn test_drop_pool() {
        async_std::task::block_on(async{
            loop{
                let mut opt = MySqlConnectOptions::from_str("mysql://root:123456@localhost:3306/test").unwrap();
                opt.log_slow_statements(log::LevelFilter::Off, Duration::from_secs(0));
                opt.log_statements(log::LevelFilter::Off);
                let pool = MySqlPool::connect_with(opt).await.unwrap();
                pool.close().await;
                drop(pool);
            }
        });

    }
}
```

**Comment by templar721** [comment]
谢谢。非常清晰。果然是高手。
