### ISSUE TITLE
Support for similar functionality to `sqlx::types::Json`.

### ISSUE THREAD

**Issue by PPakalns** [rbatis/rbatis#58]
About working with JSON, JSONB postgres fields.

Does this library support defining crud enabled structs with json fields that do not have type `serde_json::Value`, but has rust structure with implemented serde serialization, deserialization.

For example sqlx has syntax support for the following syntax when fetching data from database:

```
#[derive(Clone, Serialize, Deserialize, Debug)]
struct Example {
   ...
   json_field: sqlx::types::Json<MyRustType>,
   ...
}
```

Then in `sqlx::query_as!` sql you would write something like this for JSONB field to pass compile time validation. 
```
SELECT
     ...
     json_field as "json_field: sqlx::types::Json<MyRustType>",
     ...
```

This allows not to use identical intermediate rust structures with serde_json::Value type fields.

**Comment by zhuxiujia** [comment]
> About working with JSON, JSONB postgres fields.
> 
> Does this library support defining crud enabled structs with json fields that do not have type `serde_json::Value`, but has rust structure with implemented serde serialization, deserialization.
> 
> For example sqlx has syntax support for the following syntax when fetching data from database:
> 
> ```
> #[derive(Clone, Serialize, Deserialize, Debug)]
> struct Example {
>    ...
>    json_field: sqlx::types::Json<MyRustType>,
>    ...
> }
> ```
> 
> Then in sqlx sql you would write something like this for JSONB field:
> 
> ```
> SELECT
>      ...
>      json_field as "json_field: sqlx::types::Json<MyRustType>",
>      ...
> ```
> 
> This allows not to use identical intermediate rust structures with serde_json::Value type fields.

this type is supported!
for Rbatis all of  support postgres  Types, you can see rbatis-core/src/postgres/sqlx_value.rs

One premise about types that do not support SQLX is that SQLX does not implement Serialize, Deserialize

**Comment by PPakalns** [comment]
Looks like it could work, but it looks like intermediate json representation before data insertion in database could cause problems with types like `UUID`, see: #59 .

Closing this issue for now.
