### ISSUE TITLE
db conn error

### ISSUE THREAD

**Issue by roysha01** [rbatis/rbatis#60]
method: run test:
------
 #[async_std::test]
    pub async fn test_use_driver() {
env:
------
conn string:
pub const MYSQL_URL: &'static str = "mysql://root:currect@10.0.0.5:3306/test";

C:\Users\Administrator>rustup show
Default host: x86_64-pc-windows-gnu

installed toolchains
stable-x86_64-pc-windows-gnu (default)

active toolchain
stable-x86_64-pc-windows-gnu (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

hung at the sentence: 
------
let pool = DBPool::new(MYSQL_URL).await.unwrap();

err:
------
called `Result::unwrap()` on an `Err` value: E("encountered unexpected or invalid data: expected NUL in byte sequence")
thread 'test::test_use_driver' panicked at 'called `Result::unwrap()` on an `Err` value: E("encountered unexpected or invalid data: expected NUL in byte sequence")', example\src\main.rs:118:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at .\C:\Users\Administrator\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\library\core\src/result.rs:973
   4: example::test::test_use_driver::{{closure}}
             at .\example\src/main.rs:118

**Comment by zhuxiujia** [comment]
> ## method: run test:
> ## #[async_std::test]
> pub async fn test_use_driver() {
> env:
> conn string:
> pub const MYSQL_URL: &'static str = "mysql://root:currect@10.0.0.5:3306/test";
> 
> C:\Users\Administrator>rustup show
> Default host: x86_64-pc-windows-gnu
> 
> installed toolchains
> stable-x86_64-pc-windows-gnu (default)
> 
> active toolchain
> stable-x86_64-pc-windows-gnu (default)
> rustc 1.48.0 (7eac88abb 2020-11-16)
> 
> ## hung at the sentence:
> let pool = DBPool::new(MYSQL_URL).await.unwrap();
> 
> ## err:
> called `Result::unwrap()` on an `Err` value: E("encountered unexpected or invalid data: expected NUL in byte sequence")
> thread 'test::test_use_driver' panicked at 'called `Result::unwrap()` on an `Err` value: E("encountered unexpected or invalid data: expected NUL in byte sequence")', example\src\main.rs:118:49
> stack backtrace:
> 0: rust_begin_unwind
> at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library\std\src/panicking.rs:483
> 1: core::panicking::panic_fmt
> at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library\core\src/panicking.rs:85
> 2: core::option::expect_none_failed
> at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library\core\src/option.rs:1234
> 3: core::result::Result<T,E>::unwrap
> at .\C:\Users\Administrator.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\library\core\src/result.rs:973
> 4: example::test::test_use_driver::{{closure}}
> at .\example\src/main.rs:118

What is your version of mysql？

**Comment by roysha01** [comment]
win 5.5.7

**Comment by zhuxiujia** [comment]
> win 5.5.7

My  MySQL5.7 test is normal,       so you can report this bug to SQLX

**Comment by zhuxiujia** [comment]
> directly sqlx conn has the same error on version 5.5.7.
> I tried another version mysql: no any error on ver 5.6.28, both sqlx and rbatis.

SQLX uses mysql 5.6 or above protocol, 5.5 support is problematic
