### ISSUE TITLE
是否考虑默认是tokio而非async std？

### ISSUE THREAD

**Issue by Silentdoer** [rbatis/rbatis#64]
tokio已经1.0，且star是async std的数倍，生产上也很成熟，而且据说执行效率比async std其实要高一些？

**Comment by zhuxiujia** [comment]
asyncStd 并非割裂社区的运行时，它内置依赖了tokio02,tokio03,asyncio,。。。等等待加入的运行时。
我认为它在做整合而不是割裂社区生态，应该在不久之后async_std即会支持tokio1.0,到时候只需增加一条feature即可切换

**Comment by zhuxiujia** [comment]
> tokio已经1.0，且star是async std的数倍，生产上也很成熟，而且据说执行效率比async std其实要高一些？

看 https://github.com/async-rs/async-std/pull/924
这里他们已经提交代码了

**Comment by derust** [comment]
@zhuxiujia 
rbatis选择async std而不是tokio的主要原因是什么？

楼上提的性能差异，是否有相关benchmark可参考

**Comment by zhuxiujia** [comment]
> @zhuxiujia
> rbatis选择async std而不是tokio的主要原因是什么？
> 
> 楼上提的性能差异，是否有相关benchmark可参考

我的意思是，选择AsyncStd是因为它已经依赖了Tokio的依赖，这样和我们直接对Tokio做依赖没有区别，反而还增加了不必要的无用功。
因为AsyncSTD已经对tokio做了 条件编译切换了，比如你只要指定feature="tokio02",那么运行时是跑在tokio的运行时里面的

**Comment by zhuxiujia** [comment]
v4 默认tokio

**Comment by Silentdoer** [comment]
默认tokio是不会同时加载async_std是吧？
