### ISSUE TITLE
Tokio 1.0 support

### ISSUE THREAD

**Issue by akashgurava** [rbatis/rbatis#65]
Hi, Is there plan to support tokio 1.0? I am planning to use rbatis but have already setup using tokio 1.0 and hyper 0.14.2.

**Comment by zhuxiujia** [comment]
> Hi, Is there plan to support tokio 1.0? I am planning to use rbatis but have already setup using tokio 1.0 and hyper 0.14.2.

Async_std has a complete dependency on ToKIO, including TOKIO02, TOKIO03 and TOKIO1.0
async_std  is  support   tokio1.0. but  not  publish into  crate.io.(If they release a new version, then this will be updated as well)
see   async-rs/async-std#924

**Comment by zhuxiujia** [comment]
> Hi, Is there plan to support tokio 1.0? I am planning to use rbatis but have already setup using tokio 1.0 and hyper 0.14.2.

新版本已支持tokio1.0（通过async_std新版本升级获得）
