### ISSUE TITLE
the trait bound `fn() -> impl futures::Future {get_all_users}: Factory<_, _, _>` is not satisfied

### ISSUE THREAD

**Issue by FETE-CH** [rbatis/rbatis#66]
使用时编译不通过，改怎么处理？
```rust
#[get("/all")]
pub async fn get_all_users() -> Result<Page<User>, rbatis::core::Error> {
    let request = PageRequest::new(1, 20);
    let wrapper = RB.new_wrapper().check().unwrap();
    RB.fetch_page_by_wrapper("", &wrapper, &request).await
}

#[get("/{id}")]
pub async fn get_user(web::Path(id): web::Path<u32>) -> Option<User> {
    let user: Option<User> = RB.fetch_by_id("", &id).await.unwrap();
    user
}
```
编译错误
```bash
error[E0277]: the trait bound `fn() -> impl futures::Future {get_all_users}: Factory<_, _, _>` is not satisfied
  --> src/service/user.rs:24:14
   |
24 | pub async fn get_all_users() -> Result<Page<User>, rbatis::core::Error> {
   |              ^^^^^^^^^^^^^ the trait `Factory<_, _, _>` is not implemented for `fn() -> impl futures::Future {get_all_users}`

```
```bash
error[E0277]: the trait bound `fn(actix_web::web::Path<u32>) -> impl futures::Future {get_user}: Factory<_, _, _>` is not satisfied
  --> src/service/user.rs:31:14
   |
31 | pub async fn get_user(web::Path(id): web::Path<u32>) -> Option<User> {
   |              ^^^^^^^^ the trait `Factory<_, _, _>` is not implemented for `fn(actix_web::web::Path<u32>) -> impl futures::Future {get_user}`

```

我尝试去掉使用 rbatis 的查询，直接返回字符串，是没问题的，应该不是其他的错误

**Comment by zhuxiujia** [comment]
> 使用时编译不通过，改怎么处理？
> 
> ```rust
> #[get("/all")]
> pub async fn get_all_users() -> Result<Page<User>, rbatis::core::Error> {
>     let request = PageRequest::new(1, 20);
>     let wrapper = RB.new_wrapper().check().unwrap();
>     RB.fetch_page_by_wrapper("", &wrapper, &request).await
> }
> 
> #[get("/{id}")]
> pub async fn get_user(web::Path(id): web::Path<u32>) -> Option<User> {
>     let user: Option<User> = RB.fetch_by_id("", &id).await.unwrap();
>     user
> }
> ```
> 
> 编译错误
> 
> ```shell
> error[E0277]: the trait bound `fn() -> impl futures::Future {get_all_users}: Factory<_, _, _>` is not satisfied
>   --> src/service/user.rs:24:14
>    |
> 24 | pub async fn get_all_users() -> Result<Page<User>, rbatis::core::Error> {
>    |              ^^^^^^^^^^^^^ the trait `Factory<_, _, _>` is not implemented for `fn() -> impl futures::Future {get_all_users}`
> ```
> 
> ```shell
> error[E0277]: the trait bound `fn(actix_web::web::Path<u32>) -> impl futures::Future {get_user}: Factory<_, _, _>` is not satisfied
>   --> src/service/user.rs:31:14
>    |
> 31 | pub async fn get_user(web::Path(id): web::Path<u32>) -> Option<User> {
>    |              ^^^^^^^^ the trait `Factory<_, _, _>` is not implemented for `fn(actix_web::web::Path<u32>) -> impl futures::Future {get_user}`
> ```
> 
> 我尝试去掉使用 rbatis 的查询，直接返回字符串，是没问题的，应该不是其他的错误

actix-web的接口要求返回的对象 实现 impl Responder， 
String是它已经实现了的，自定义的结构体需要你自己实现impl Responder

**Comment by FETE-CH** [comment]
感谢，已成功解决
