### ISSUE TITLE
表的列与结构体的属性怎么对应？

### ISSUE THREAD

**Issue by TideDlrow** [rbatis/rbatis#67]
`player`表中有四列分别是`id,userName,password,activeUUID` ~~原先是用java所以用的是驼峰~~
然后我的结构体如下
```rust
#[derive(Clone, Debug,Deserialize,Serialize)]
struct Player{
    id:Option<i32>,
    user_name:Option<String>,
    password:Option<String>,
    active_uuid:Option<String>,
}
//同时实现了CRUDEnable
impl CRUDEnable for Player{
    type IdType = String;

    fn table_name() -> String {
        "player".to_string()
    }
    fn table_columns() -> String {
        "id,userName,password,activeUUID".to_string()
    }
}
```
最终查询出来的结果中`user_name`和`active_uuid`都为None。
如果把结构体中的属性改为和表中的列名相同就不会为None，所以请问一下有什么办法将其对应起来吗？

**Comment by zhuxiujia** [comment]
> `player`表中有四列分别是`id,userName,password,activeUUID` ~原先是用java所以用的是驼峰~
> 然后我的结构体如下
> 
> ```rust
> #[derive(Clone, Debug,Deserialize,Serialize)]
> struct Player{
>     id:Option<i32>,
>     user_name:Option<String>,
>     password:Option<String>,
>     active_uuid:Option<String>,
> }
> //同时实现了CRUDEnable
> impl CRUDEnable for Player{
>     type IdType = String;
> 
>     fn table_name() -> String {
>         "player".to_string()
>     }
>     fn table_columns() -> String {
>         "id,userName,password,activeUUID".to_string()
>     }
> }
> ```
> 
> 最终查询出来的结果中`user_name`和`active_uuid`都为None。
> 如果把结构体中的属性改为和表中的列名相同就不会为None，所以请问一下有什么办法将其对应起来吗？

对应的属性列改成userName activeUUID，添加rust的宏忽略lint 提示即可

**Comment by Silentdoer** [comment]
这个有办法做别名吗？毕竟还是希望遵循rust命名规范，但是连接的表有时候不是我们自己设计的，这种情况需要别名来连接

**Comment by Silentdoer** [comment]
或者我觉得可以做默认的转换，比如小驼峰的数据库字段自动映射为下划线的rust字段

**Comment by Silentdoer** [comment]
这个应该可以参考serde的设计，可以添加字段宏注解实现字段名映射

**Comment by zhuxiujia** [comment]
> 或者我觉得可以做默认的转换，比如小驼峰的数据库字段自动映射为下划线的rust字段

不妥，比如我表A{ a_column,aColumn  }这时候，你把aColumn 转换为 a_column会和之前的字段重合

**Comment by zhuxiujia** [comment]
> 这个应该可以参考serde的设计，可以添加字段宏注解实现字段名映射

你可以试试 serde的注解，当然理想情况下我建议还是 对方用小驼峰，你也用小驼峰，以后查数据，比对都正确。随意改别名很影响debug的
