### ISSUE TITLE
建议增加乐观锁的支持

### ISSUE THREAD

**Issue by any35** [rbatis/rbatis#69]
乐观锁是处理并发的一种手段, 甚至比逻辑删除更常用, 希望能增加对乐观锁的支持.

**Comment by zhuxiujia** [comment]
> 乐观锁是处理并发的一种手段, 甚至比逻辑删除更常用, 希望能增加对乐观锁的支持.

rbatis  版本 "1.8.66"以上  会获得 乐观锁支持

**Comment by any35** [comment]
更新后完美解决! 赞!
