### ISSUE TITLE
不知道为啥fetch_list性能很差

### ISSUE THREAD

**Issue by nyrf** [rbatis/rbatis#73]
release 模式，测试了sqlx也是一样，测试了diesel倒是可以的，这不应该啊, insert倒是很快的，这个是测试的pg，开始是用的sqlite, 也是一样

`rbatis`

```shell
❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts
Running 10s test @ http://localhost:3000/posts
  2 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.12s   461.98ms   1.98s    58.23%
    Req/Sec    26.60     15.09    69.00     64.07%
  474 requests in 10.08s, 18.64MB read
  Socket errors: connect 0, read 11, write 0, timeout 395
Requests/sec:     47.04
Transfer/sec:      1.85MB
```

`diesel`

```shell
❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts/list_diesel
Running 10s test @ http://localhost:3000/posts/list_diesel
  2 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   663.73ms  110.04ms   1.06s    92.15%
    Req/Sec   145.90     46.84   272.00     71.00%
  2919 requests in 10.05s, 114.56MB read
Requests/sec:    290.40
Transfer/sec:     11.40MB
```

最后这个是用gin和gorm试的，

```
❯ wrk -t2 -c200 -d10s  http://localhost:8080/posts
Running 10s test @ http://localhost:8080/posts
  2 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   157.52ms  184.07ms   1.99s    94.63%
    Req/Sec   211.62     44.90   330.00     75.50%
  4224 requests in 10.04s, 173.64MB read
  Socket errors: connect 0, read 0, write 0, timeout 242
Requests/sec:    420.79
Transfer/sec:     17.30MB
```

**Comment by zhuxiujia** [comment]
> 用了原生sqlx也是一样，测试了diesel倒是可以的，这不应该啊, insert倒是很快的，这个是测试的pg，开始是用的sqlite, 也是一样
> 
> `rbatis`
> 
> ```shell
> ❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts
> Running 10s test @ http://localhost:3000/posts
>   2 threads and 200 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency     1.12s   461.98ms   1.98s    58.23%
>     Req/Sec    26.60     15.09    69.00     64.07%
>   474 requests in 10.08s, 18.64MB read
>   Socket errors: connect 0, read 11, write 0, timeout 395
> Requests/sec:     47.04
> Transfer/sec:      1.85MB
> ```
> 
> `diesel`
> 
> ```shell
> ❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts/list_diesel
> Running 10s test @ http://localhost:3000/posts/list_diesel
>   2 threads and 200 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency   663.73ms  110.04ms   1.06s    92.15%
>     Req/Sec   145.90     46.84   272.00     71.00%
>   2919 requests in 10.05s, 114.56MB read
> Requests/sec:    290.40
> Transfer/sec:     11.40MB
> ```
> 
> 最后这个是用gin和gorm试的，
> 
> ```
> ❯ wrk -t2 -c200 -d10s  http://localhost:8080/posts
> Running 10s test @ http://localhost:8080/posts
>   2 threads and 200 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency   157.52ms  184.07ms   1.99s    94.63%
>     Req/Sec   211.62     44.90   330.00     75.50%
>   4224 requests in 10.04s, 173.64MB read
>   Socket errors: connect 0, read 0, write 0, timeout 242
> Requests/sec:    420.79
> Transfer/sec:     17.30MB
> ```

* 理论上Rbatis因为依赖sqlx-core的驱动，性能应该和sqlx差不多。
* 你的测试代码需要规避从数据库连接池拿连接的步骤（diesel，gorm 是否有连接池的设计？没有的话sqlx需要规避）
* 你的压测，需要关闭日志输出(或者直接用sqlx对比压测)

**Comment by nyrf** [comment]
> > 用了原生sqlx也是一样，测试了diesel倒是可以的，这不应该啊, insert倒是很快的，这个是测试的pg，开始是用的sqlite, 也是一样
> > `rbatis`
> > ```shell
> > ❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts
> > Running 10s test @ http://localhost:3000/posts
> >   2 threads and 200 connections
> >   Thread Stats   Avg      Stdev     Max   +/- Stdev
> >     Latency     1.12s   461.98ms   1.98s    58.23%
> >     Req/Sec    26.60     15.09    69.00     64.07%
> >   474 requests in 10.08s, 18.64MB read
> >   Socket errors: connect 0, read 11, write 0, timeout 395
> > Requests/sec:     47.04
> > Transfer/sec:      1.85MB
> > ```
> > 
> > 
> > `diesel`
> > ```shell
> > ❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts/list_diesel
> > Running 10s test @ http://localhost:3000/posts/list_diesel
> >   2 threads and 200 connections
> >   Thread Stats   Avg      Stdev     Max   +/- Stdev
> >     Latency   663.73ms  110.04ms   1.06s    92.15%
> >     Req/Sec   145.90     46.84   272.00     71.00%
> >   2919 requests in 10.05s, 114.56MB read
> > Requests/sec:    290.40
> > Transfer/sec:     11.40MB
> > ```
> > 
> > 
> > 最后这个是用gin和gorm试的，
> > ```
> > ❯ wrk -t2 -c200 -d10s  http://localhost:8080/posts
> > Running 10s test @ http://localhost:8080/posts
> >   2 threads and 200 connections
> >   Thread Stats   Avg      Stdev     Max   +/- Stdev
> >     Latency   157.52ms  184.07ms   1.99s    94.63%
> >     Req/Sec   211.62     44.90   330.00     75.50%
> >   4224 requests in 10.04s, 173.64MB read
> >   Socket errors: connect 0, read 0, write 0, timeout 242
> > Requests/sec:    420.79
> > Transfer/sec:     17.30MB
> > ```
> 
> * 理论上Rbatis因为依赖sqlx-core的驱动，性能应该和sqlx差不多。
> * 你的测试代码需要规避从数据库连接池拿连接的步骤（diesel，gorm 是否有连接池的设计？没有的话sqlx需要规避（即避免重复调用acqure() 方法拿连接，改成一次创建连接后一直复用这个连接））
> * 你的压测，需要关闭日志输出(或者直接用sqlx（也要关闭日志log）对比压测)

rbatis 我是按你https://github.com/rbatis/abs_admin这个项目里一样写的，写数据的速度没问题，就是这个读取不知道为啥，日志关了和没关都试过，数据差的不是太大，好像sqlx我看有人也发这么个问题，

**Comment by zhuxiujia** [comment]
> > > 用了原生sqlx也是一样，测试了diesel倒是可以的，这不应该啊, insert倒是很快的，这个是测试的pg，开始是用的sqlite, 也是一样
> > > `rbatis`
> > > ```shell
> > > ❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts
> > > Running 10s test @ http://localhost:3000/posts
> > >   2 threads and 200 connections
> > >   Thread Stats   Avg      Stdev     Max   +/- Stdev
> > >     Latency     1.12s   461.98ms   1.98s    58.23%
> > >     Req/Sec    26.60     15.09    69.00     64.07%
> > >   474 requests in 10.08s, 18.64MB read
> > >   Socket errors: connect 0, read 11, write 0, timeout 395
> > > Requests/sec:     47.04
> > > Transfer/sec:      1.85MB
> > > ```
> > > 
> > > 
> > > `diesel`
> > > ```shell
> > > ❯ wrk -t2 -c200 -d10s  http://localhost:3000/posts/list_diesel
> > > Running 10s test @ http://localhost:3000/posts/list_diesel
> > >   2 threads and 200 connections
> > >   Thread Stats   Avg      Stdev     Max   +/- Stdev
> > >     Latency   663.73ms  110.04ms   1.06s    92.15%
> > >     Req/Sec   145.90     46.84   272.00     71.00%
> > >   2919 requests in 10.05s, 114.56MB read
> > > Requests/sec:    290.40
> > > Transfer/sec:     11.40MB
> > > ```
> > > 
> > > 
> > > 最后这个是用gin和gorm试的，
> > > ```
> > > ❯ wrk -t2 -c200 -d10s  http://localhost:8080/posts
> > > Running 10s test @ http://localhost:8080/posts
> > >   2 threads and 200 connections
> > >   Thread Stats   Avg      Stdev     Max   +/- Stdev
> > >     Latency   157.52ms  184.07ms   1.99s    94.63%
> > >     Req/Sec   211.62     44.90   330.00     75.50%
> > >   4224 requests in 10.04s, 173.64MB read
> > >   Socket errors: connect 0, read 0, write 0, timeout 242
> > > Requests/sec:    420.79
> > > Transfer/sec:     17.30MB
> > > ```
> > 
> > 
> > 
> > * 理论上Rbatis因为依赖sqlx-core的驱动，性能应该和sqlx差不多。
> > * 你的测试代码需要规避从数据库连接池拿连接的步骤（diesel，gorm 是否有连接池的设计？没有的话sqlx需要规避（即避免重复调用acqure() 方法拿连接，改成一次创建连接后一直复用这个连接））
> > * 你的压测，需要关闭日志输出(或者直接用sqlx（也要关闭日志log）对比压测)
> 
> rbatis 我是按你 https://github.com/rbatis/abs_admin 这个项目里一样写的，写数据的速度没问题，就是这个读取不知道为啥，日志关了和没关都试过，数据差的不是太大，好像sqlx我看有人也发这么个问题，

diesel压根就没有连接池这个东西，何况sqlx的连接池 拿连接的时候 首先会ping一下是否是联通的，而且连接池拿连接也需要判断剩余数，公平性，这些都是有时间消耗的。
做压测需要一个绝对公平的环境。。。。。abs_admin项目开启了debug，日志打印特别多，不适合做压测

**Comment by nyrf** [comment]
我只是rbatis的使用方式用了abs_admin一样的方式，都是lazy_load的，其它没用，而且insert一点问题没有，轻松跑gorm和diesel的两倍，只有读取这块，我对rust不是太深入，只是写了很简单的demo试了下，比较疑惑

**Comment by zhuxiujia** [comment]
> 我只是rbatis的使用方式用了abs_admin一样的方式，都是lazy_load的，其它没用，而且insert一点问题没有，轻松跑gorm和diesel的两倍，只有读取这块，我对rust不是太深入，只是写了很简单的demo试了下，比较疑惑

应该哪里还有问题，我这边测试结果理论上比go自带的连接池要快

**Comment by nyrf** [comment]
> > 我只是rbatis的使用方式用了abs_admin一样的方式，都是lazy_load的，其它没用，而且insert一点问题没有，轻松跑gorm和diesel的两倍，只有读取这块，我对rust不是太深入，只是写了很简单的demo试了下，比较疑惑
> 
> 应该哪里还有问题，我这边测试结果实际上比golang std标准库自带的连接池要快
感谢，我再试下，
