### ISSUE TITLE
是否考虑支持分库分表呢?

### ISSUE THREAD

**Issue by any35** [rbatis/rbatis#74]
如题: 是否考虑支持分库分表呢?

**Comment by zhuxiujia** [comment]
> 如题: 是否考虑支持分库分表呢?

Citus是PostgreSQL的一个插件，通过citus，你可以让多个PostgreSQL机器组成一个集群，利用这个集群，你可以将一张大数据量的表自动水平分表，而无需担心分配的逻辑。具体citus可以做如下的事情：

自动分片和分布数据。你可以选择一个列，citus依据这个列将大数据表进行分片（sharding），然后将各个分片分配到各个worker节点；
可以实现数据高可用。通过设置"citus.shard_replication_factor"控制每个分片的副本数量，每个分片的副本会被分配到不同的机器，如果包含该分片副本的某个机器宕机，数据还是查询的到，除非所有包含该副本的机器全部宕机，数据才会不可用。

**Comment by zhuxiujia** [comment]
> 如题: 是否考虑支持分库分表呢?

如果希望使用分库分表，建议使用Citus+PostgreSQ。 这样业务层是无侵入的，当成一个分布式数据库来使用。
如果不希望分库分表，建议使用小强db或者tidb之类的newsql

**Comment by any35** [comment]
Citus是一个很好的方案, 但是只支持分库, 企业版的价格不透明, 毕竟在国内.

小强db或者tidb之前都用过, 公司内部部署了一个集群几十台, 真心觉得非高富帅用不起, 这东西要上阿里云, 那账单看着就心疼不已.
其实还有一个致命的问题就是对于有些企业如SasS, 无法根据tenant_id做数据的co-location. 小强db之前有类似方案, 如interleave table等, 不过后来实践证明效果并不好, 现在已经废弃了.  Google Spanner模型并不适合所有的应用场景.

最好的方式是能有类似于MyCat或者shardingsphere. 这样数据可以单独运维, 开发干预小, 不过这两个proxy性能其实并不太理想好, 需要部署很多台, 对于postgresql进程模型来说, 也是比较致命的. (当然可以加上pgBouncer, 但中间经过太多层了. )

如果rust驱动能自动生成对应的分库分表SQL, 那中间很多组件就都不需要了.

如果rbatis能有分表的功能, 加上Citus的分库, 那就非常方便了.

不知 @zhuxiujia  大牛是否有考虑加上这个功能呢? 其实只要生成SQL表名能调用自定义的函数去生成那分表的问题就解决了. 剩下的问题就可以以插件的形式解决.

**Comment by zhuxiujia** [comment]
> Citus是一个很好的方案, 但是只支持分库, 企业版的价格不透明, 毕竟在国内.
> 
> 小强db或者tidb之前都用过, 公司内部部署了一个集群几十台, 真心觉得非高富帅用不起, 这东西要上阿里云, 那账单看着就心疼不已.
> 其实还有一个致命的问题就是对于有些企业如SasS, 无法根据tenant_id做数据的co-location. 小强db之前有类似方案, 如interleave table等, 不过后来实践证明效果并不好, 现在已经废弃了. Google Spanner模型并不适合所有的应用场景.
> 
> 最好的方式是能有类似于MyCat或者shardingsphere. 这样数据可以单独运维, 开发干预小, 不过这两个proxy性能其实并不太理想好, 需要部署很多台, 对于postgresql进程模型来说, 也是比较致命的. (当然可以加上pgBouncer, 但中间经过太多层了. )
> 
> 如果rust驱动能自动生成对应的分库分表SQL, 那中间很多组件就都不需要了.
> 
> 如果rbatis能有分表的功能, 加上Citus的分库, 那就非常方便了.
> 
> 不知 @zhuxiujia 大牛是否有考虑加上这个功能呢? 其实只要生成SQL表名能调用自定义的函数去生成那分表的问题就解决了. 剩下的问题就可以以插件的形式解决.

你们用过这么多分布式数据库，应该你才是大牛才对哈哈。
*  如果要实现分表的话，目前可以在最新版本  自定义实现Rbatis的拦截器，根据传进来的context_id来路由选择走哪个表
* 类似于MyCat或者shardingsphere，都必须能解析完整的sql才行，类似sqlparser.rs 等等之类的库没到1.0版本，不知道是否能稳定解析完整sql（你可以试试看）
* 如果能完整解析sql，rust实现类似阿里分布式事务seata估计也有希望了
* Tidb之类的确实很吃配置，rocksdb读写放大还会搞坏固态硬盘
*  暂时没想到特别好的方案，我想多听听你们的看法，哈哈

**Comment by any35** [comment]
多谢回复!

1.
    刚刚发现Citus新发布的10.0把可以rebalance了, 原来这个功能只有收费的企业版里面有. 现在社区版有这个功能实在太香了.确实就不需要考虑在rbatis里实现分库分表.

2. 不过本着学习的精神, 还是尝试了非citus的方案.

sqlparser.rs试了下这个库还挺好用的, 通过这个库重写SQL也挺方便的.

现在唯一的问题是在async/await的框架下context如何传递比较方便?

这里说的context就是类似于java里面通过ThreadLocal传递的信息.

如果把context全放参数里面是不现实的.

目前我只想到两个解决方案, 但都不完美: 
1. wrap一下future, 每次poll前后把上下文重新放到thread local里. 缺点是代码入侵性强
2. 自定义executor, 第一次执行task后如果不是Ready 就把当前task和thread local的上下文包装成另外一个task(类似方案1), 后面执行就能自动恢复上下文. 非常担心性能有问题.


不知大牛有没有更好的方案呢?

**Comment by dobzhao** [comment]
新接触rust，特别欣慰看到出现rbatis这个项目，关于sharding说一点个人浅见：
R/O mapping跟sharding是两个层面的需求，应该相互解耦，做sharding是个大话题，代理服务方式和客户端方式各有适应场景，如果考虑提供客户端sharding方案，建议的方式是在驱动下层实现sharding，上层实现mapping，类似shardingsphere JDBC实现JDBC驱动接口，上层R/O mapping层比如mybatis或者hibernate都当做普通jdbc驱动去使用，并不清楚下层是否做了分库分表。

做sharing需要考虑的事情非常多，比如事务一致性保证，各种优化客户端排序，聚合的设计，个人不建议rbatis项目提供这个特性

**Comment by any35** [comment]
感谢回复. 你说的很对. 其实我们还有其他方面考虑, 欢迎指点.

1.  一般来讲高性能场合只考虑client模式, Rust目前都不太成熟, 在每个客户端实现目前不太现实. 还有一些client中间件如基于sidecard的能做还很有限.  而基于rbatis的插件SQL改写简单而且有一定的可行性. 实际上我们目前也已经是这么做了.   

2. 程序员应该清楚底层sharing的需求, 包括您提到的一致性之类的问题, 而不应该全部依赖中间件解决, 毕竟合理的拆分是一个系统工程. 

3. 另外一个层面, 我们并不希望能提供全面完整的功能. 大部分分库分表并不复杂也不会涉及多个不同的库的事务/拆分/聚合的问题.. 比如, 在SaaS系统里面租户的id需要通过改写SQL自动注入查询条件, 而不是每个SQL都写一遍这个条件(这个id一般也是作为sharing key), 可以顺带把分库分表的需求顺带做了, 避免了底层驱动二次解析SQL.   至于很复杂的需求应该另行处理优化掉, 比如业务中使用DDD, 复杂查询做异构等.

4. 还有一个需求就是中台服务的编排问题, 类似于分布式事务, 其主要还是实现多服务间的最终一致性问题. 特别是在目前云原生系统下, 各服务的编程语言都不一样, 这些也不能指望通过中间件能解决. 靠近应用的rbatis反而比较好搞定.

5. 当然, 如果需要列出来的还有不少, 这些都是我们目前工程化中遇到的实际问题, 也是从这些角度考虑考虑.

**Comment by dobzhao** [comment]
> 感谢回复. 你说的很对. 其实我们还有其他方面考虑, 欢迎指点.
> 
> 1. 一般来讲高性能场合只考虑client模式, Rust目前都不太成熟, 在每个客户端实现目前不太现实. 还有一些client中间件如基于sidecard的能做还很有限.  而基于rbatis的插件SQL改写简单而且有一定的可行性. 实际上我们目前也已经是这么做了.
> 2. 程序员应该清楚底层sharing的需求, 包括您提到的一致性之类的问题, 而不应该全部依赖中间件解决, 毕竟合理的拆分是一个系统工程.
> 3. 另外一个层面, 我们并不希望能提供全面完整的功能. 大部分分库分表并不复杂也不会涉及多个不同的库的事务/拆分/聚合的问题.. 比如, 在SaaS系统里面租户的id需要通过改写SQL自动注入查询条件, 而不是每个SQL都写一遍这个条件(这个id一般也是作为sharing key), 可以顺带把分库分表的需求顺带做了, 避免了底层驱动二次解析SQL.   至于很复杂的需求应该另行处理优化掉, 比如业务中使用DDD, 复杂查询做异构等.
> 4. 还有一个需求就是中台服务的编排问题, 类似于分布式事务, 其主要还是实现多服务间的最终一致性问题. 特别是在目前云原生系统下, 各服务的编程语言都不一样, 这些也不能指望通过中间件能解决. 靠近应用的rbatis反而比较好搞定.
> 5. 当然, 如果需要列出来的还有不少, 这些都是我们目前工程化中遇到的实际问题, 也是从这些角度考虑考虑.

就lib库来说，我个人不建议sharding和mapping有耦合，两类库应该可以独立切换，并且sharding的功能如果作为lib库提供，也需要尽可能多的考虑各种场景。
当然对于特定项目，考虑场景要求，生态现状，我相信您的项目会选择最适合的方案，我稍微有一点提醒
1. client模式有利于提升单笔交易响应时间，但应用集群节点到一定规模的时候，数据库的连接数的量可能会成为性能瓶颈
2. 进程内跨分片的事务有可能在微服务内部解决，跨进程甚至跨主机的微服务间的事务一致性单个微服务是无法解决的，如果有这方面需求，要评估应用+消息中间件还是引入全局的事务协调管理器

**Comment by any35** [comment]
非常感谢回复! 此问题可以关闭了.
