### ISSUE TITLE
Foreign keys and unique columns

### ISSUE THREAD

**Issue by omofolarin** [rbatis/rbatis#76]
Please, it's there any implementation for setting sql constraint on tables like foreign keys  and unique keys(or columns)?

**Comment by zhuxiujia** [comment]
> Please, it's there any implementation for setting sql constraint on tables like foreign keys and unique keys(or columns)?

There is no limit， Use py_sql for complex scenarios

**Comment by omofolarin** [comment]
Okay, thanks.
