### ISSUE TITLE
crud_enable macro table_name attribute

### ISSUE THREAD

**Issue by omofolarin** [rbatis/rbatis#77]
Please, the table name doesn't change from user_model to users

```
#[crud_enable((table_name:"users" | formats_pg:"id:{}::uuid"))]
/// User Model - A user in the company
#[derive(PartialEq, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct UserModel {
    pub id: Uuid,
    pub company_id: Uuid,

    ///  Title `Mr/Mrs/Dr/Master/Prince` etc
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,

    ///  User nickname in company
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,

    /// User can be archived or soft deleted
    pub is_deleted: bool,
    pub created_at: NaiveDateTime,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<NaiveDateTime>,
}

```

**Comment by zhuxiujia** [comment]
> Please, the table name doesn't change from user_model to users
> 
> ```
> #[crud_enable((table_name:"users" | formats_pg:"id:{}::uuid"))]
> /// User Model - A user in the company
> #[derive(PartialEq, Debug, Clone)]
> #[serde(rename_all = "camelCase")]
> pub struct UserModel {
>     pub id: Uuid,
>     pub company_id: Uuid,
> 
>     ///  Title `Mr/Mrs/Dr/Master/Prince` etc
>     #[serde(skip_serializing_if = "Option::is_none")]
>     pub title: Option<String>,
> 
>     ///  User nickname in company
>     #[serde(skip_serializing_if = "Option::is_none")]
>     pub nickname: Option<String>,
> 
>     /// User can be archived or soft deleted
>     pub is_deleted: bool,
>     pub created_at: NaiveDateTime,
> 
>     #[serde(skip_serializing_if = "Option::is_none")]
>     pub updated_at: Option<NaiveDateTime>,
> }
> ```

```rust
#[crud_enable(table_name: "users" | formats_pg: "id:{}::uuid")]
/// User Model - A user in the company
#[derive(PartialEq, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct UserModel {
    //....
}
```

**Comment by omofolarin** [comment]
Oh, my bad.  Thanks.
