### ISSUE TITLE
PostgreSQL 13.4反序列化错误

### ISSUE THREAD

**Issue by zuoziqi** [rbatis/rbatis#79]
Rbatis最新版本，Rust编译器nightly最新版本，连接Postgresql数据库报错：[rbatis] json_decode fail decode_type:"alloc::vec::Vec<beta_agent::database::model::Address>",serde_err:"premature end of input"，之前同样的代码连接MySQL数据库正常无报错

**Comment by zhuxiujia** [comment]
不支持nightly最新版本！
因为json解析 crate serde json没有支持

**Comment by zuoziqi** [comment]
问题似乎解决了，我的锅，数据库的一个时间字段时间类型错误导致的问题。不过似乎一切在rust nightly编译器下运行正常，编译器版本：rustc 1.52.0-nightly (4f20caa62 2021-03-01)
