### ISSUE TITLE
DOMAIN 层 简化

### ISSUE THREAD

**Issue by ace1818** [rbatis/rbatis#8]
我看到Domain层的逻辑

```
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SysUser {
    pub id: Option<String>,
    pub account: Option<String>,
    pub password: Option<String>,
    pub name: Option<String>,
    pub del: Option<i32>,
    pub create_time: Option<NaiveDateTime>,
}


impl CRUDEnable for SysUser {
    type IdType = String;
}
```

可以用宏来简洁一下

**Comment by zhuxiujia** [comment]
> 我看到Domain层的逻辑
> 
> ```
> #[derive(Serialize, Deserialize, Clone, Debug)]
> pub struct SysUser {
>     pub id: Option<String>,
>     pub account: Option<String>,
>     pub password: Option<String>,
>     pub name: Option<String>,
>     pub del: Option<i32>,
>     pub create_time: Option<NaiveDateTime>,
> }
> 
> 
> impl CRUDEnable for SysUser {
>     type IdType = String;
> }
> ```
> 
> 可以用宏来简洁一下

主意是很不错。
但是：
 1 如果使用宏的话，我们需要自定义表名称 怎么办。目前CRUDEnable 重写table_name()方法可以做到。还有其他的方法如table_fields可以重写自定义表字段（忽略某些用不得的字段）
 2 是用过程宏还是申明宏？申明宏是否支持上面说的内容。

如果这2个问题能解决，那么可以使用宏。如果有解决方法，欢迎提交代码~~

**Comment by ycvbcvfu** [comment]
```
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SysUser {
    pub id: Option<String>,
    pub account: Option<String>,
    pub password: Option<String>,
    pub name: Option<String>,
    pub del: Option<i32>,
    pub create_time: Option<NaiveDateTime>,
}


impl CRUDEnable for SysUser {
    type IdType = String;
}
```

对于上面的简化

我提供下面思路,我觉得可行:



1、简化版本，无需自定义

```
#[derive(Serialize, Deserialize, Clone, Debug, CRUDEnable)]
pub struct SysUser {
    pub id: Option<String>,
    pub account: Option<String>,
    pub password: Option<String>,
    pub name: Option<String>,
    pub del: Option<i32>,
    pub create_time: Option<NaiveDateTime>,
}
```

2、需自定义

```
#[derive(Serialize, Deserialize, Clone, Debug, CRUDEnable)]
#[rbatis(table="t_user", id="uid")]
pub struct SysUser {
    pub uid: Option<String>,
    pub account: Option<String>,
    pub password: Option<String>,
    pub name: Option<String>,
    pub del: Option<i32>,
    pub create_time: Option<NaiveDateTime>,
}
```

**Comment by zhuxiujia** [comment]
> ```
> #[derive(Serialize, Deserialize, Clone, Debug)]
> pub struct SysUser {
>     pub id: Option<String>,
>     pub account: Option<String>,
>     pub password: Option<String>,
>     pub name: Option<String>,
>     pub del: Option<i32>,
>     pub create_time: Option<NaiveDateTime>,
> }
> 
> 
> impl CRUDEnable for SysUser {
>     type IdType = String;
> }
> ```
> 
> 对于上面的简化
> 
> 我提供下面思路,我觉得可行:
> 
> 1、简化版本，无需自定义
> 
> ```
> #[derive(Serialize, Deserialize, Clone, Debug, CRUDEnable)]
> pub struct SysUser {
>     pub id: Option<String>,
>     pub account: Option<String>,
>     pub password: Option<String>,
>     pub name: Option<String>,
>     pub del: Option<i32>,
>     pub create_time: Option<NaiveDateTime>,
> }
> ```
> 
> 2、需自定义
> 
> ```
> #[derive(Serialize, Deserialize, Clone, Debug, CRUDEnable)]
> #[rbatis(table="t_user", id="uid")]
> pub struct SysUser {
>     pub uid: Option<String>,
>     pub account: Option<String>,
>     pub password: Option<String>,
>     pub name: Option<String>,
>     pub del: Option<i32>,
>     pub create_time: Option<NaiveDateTime>,
> }
> ```

1.5.0版本，现已实现 #[derive(CRUDEnable)]  功能。
上面提到的第二条，采取 手动实现 impl CRUDEnable for  SysUser { }  这种形式

**Comment by ace1818** [comment]
@ycvbcvfu  great idea
