### ISSUE TITLE
数据库连接报错，连接池超时

### ISSUE THREAD

**Issue by zuoziqi** [rbatis/rbatis#80]
如题，数据库PostgreSQL 13, Rbatis使用lazy_statics全局单例，所有数据库读写使用事务守卫，PostgreSQL设定了最大连接数1000，目前同时有四个程序在读写同一个数据库且均正常工作，后台查询PostgreSQL保持了28个连接数，但是当加入第五个程序时，第五个程序报错：pool timed out while waiting for an open connection，无法取得事务，其余四个程序依然正常工作，五个程序都共用同一个DAO工具类库。想请教一下，大概原因出在哪里。业务流量稍大，每秒平均40-50个事务请求

**Comment by zhuxiujia** [comment]
> 如题，数据库PostgreSQL 13, Rbatis使用lazy_statics全局单例，所有数据库读写使用事务守卫，PostgreSQL设定了最大连接数1000，目前同时有四个程序在读写同一个数据库且均正常工作，后台查询PostgreSQL保持了28个连接数，但是当加入第五个程序时，第五个程序报错：pool timed out while waiting for an open connection，无法取得事务，其余四个程序依然正常工作，五个程序都共用同一个DAO工具类库。想请教一下，大概原因出在哪里。业务流量稍大，每秒平均40-50个事务请求


事务会占用一条连接的，是否是事务启动过多导致 postgres的总的连接数消耗完了？

**Comment by zhuxiujia** [comment]
> 如题，数据库PostgreSQL 13, Rbatis使用lazy_statics全局单例，所有数据库读写使用事务守卫，PostgreSQL设定了最大连接数1000，目前同时有四个程序在读写同一个数据库且均正常工作，后台查询PostgreSQL保持了28个连接数，但是当加入第五个程序时，第五个程序报错：pool timed out while waiting for an open connection，无法取得事务，其余四个程序依然正常工作，五个程序都共用同一个DAO工具类库。想请教一下，大概原因出在哪里。业务流量稍大，每秒平均40-50个事务请求

请问找问题解决了吗？

**Comment by zuoziqi** [comment]
问题解决了，不是性能问题，sqlx有毒，啥都报超时，我docker-compose里一个数据库地址的变量少输了一个字母导致连接失败，但是sqlx还是会报等待超时而不是连接失败，这个问题sqlx-core的issue里有人提过
