### ISSUE TITLE
乐观锁插件生成的SQL语句结构有问题

### ISSUE THREAD

**Issue by zuoziqi** [rbatis/rbatis#81]
使用了乐观锁插件，在数据表中和模型中建立了一个BigDecimal类型的version字段，生成的SQL结构有些问题，日志如下：
```
 INFO  rbatis::plugin::log > [rbatis] [tx:d39d1fc6-e985-441d-848c-1aabd2b86826] Exec  ==> UPDATE realtime_data SET  id = $1, inflow = $2, name = $3, num = $4, outflow = $5, pressure = $6, status = $7, temperature = $8, timestamp = $9::timestamp, version = $10version = "1" WHERE entity_id = $11
[rbatis] [tx:d39d1fc6-e985-441d-848c-1aabd2b86826] Args  ==> [3,0.0,"江苏新浙铜业有限公司",4,0.0,0.0,"OK",0.0,"2021-03-06T14:28:18.388803555","2","3d75fe8a-d499-4d83-b86f-82b8ac56e146"]
```
相关代码如下：
```rust
static ref BATIS: Rbatis = {
        let mut rb = Rbatis::new();
        rb.version_lock_plugin = Some(Box::new(RbatisVersionLockPlugin::new("version")));
        rb
};
#[crud_enable(id_name:"entity_id"|id_type:"String"|table_name:"realtime_data"|formats_pg:"timestamp:{}::timestamp")]
#[derive(Debug, PartialEq, Clone)]
pub struct RealtimeData {
    pub entity_id: String,
    pub name: String,
    pub id: i32,
    pub num: i32,
    pub inflow: f64,
    pub outflow: f64,
    pub pressure: f64,
    pub temperature: f64,
    pub status: String,
    pub timestamp: NaiveDateTime,
    pub version: BigDecimal,
}
```
update调用:
```
BATIS.update_by_wrapper(tx, record, &update_wrapper, true).await?;
```

**Comment by zhuxiujia** [comment]
> 使用了乐观锁插件，在数据表中和模型中建立了一个BigDecimal类型的version字段，生成的SQL结构有些问题，日志如下：
> 
> ```
>  INFO  rbatis::plugin::log > [rbatis] [tx:d39d1fc6-e985-441d-848c-1aabd2b86826] Exec  ==> UPDATE realtime_data SET  id = $1, inflow = $2, name = $3, num = $4, outflow = $5, pressure = $6, status = $7, temperature = $8, timestamp = $9::timestamp, version = $10version = "1" WHERE entity_id = $11
> [rbatis] [tx:d39d1fc6-e985-441d-848c-1aabd2b86826] Args  ==> [3,0.0,"江苏新浙铜业有限公司",4,0.0,0.0,"OK",0.0,"2021-03-06T14:28:18.388803555","2","3d75fe8a-d499-4d83-b86f-82b8ac56e146"]
> ```
> 
> 相关代码如下：
> 
> ```rust
> static ref BATIS: Rbatis = {
>         let mut rb = Rbatis::new();
>         rb.version_lock_plugin = Some(Box::new(RbatisVersionLockPlugin::new("version")));
>         rb
> };
> #[crud_enable(id_name:"entity_id"|id_type:"String"|table_name:"realtime_data"|formats_pg:"timestamp:{}::timestamp")]
> #[derive(Debug, PartialEq, Clone)]
> pub struct RealtimeData {
>     pub entity_id: String,
>     pub name: String,
>     pub id: i32,
>     pub num: i32,
>     pub inflow: f64,
>     pub outflow: f64,
>     pub pressure: f64,
>     pub temperature: f64,
>     pub status: String,
>     pub timestamp: NaiveDateTime,
>     pub version: BigDecimal,
> }
> ```
> 
> update调用:
> 
> ```
> BATIS.update_by_wrapper(tx, record, &update_wrapper, true).await?;
> ```

version = "1.8.77" fixed this bug.
```rust
2021-03-06 23:19:18.638488 +08:00    INFO rbatis::plugin::log - [rbatis] [] Exec  ==> update biz_activity set  create_time = ?, delete_flag = ?, status = ?, version = ?  where version = "1"  and id = ?
                                                                [rbatis] [] Args  ==> ["2021-03-06T23:19:18.636223500",1,1,"2","12312"]
```

**Comment by zuoziqi** [comment]
好的，我更新一下版本再试一下
