### ISSUE TITLE
請問為什麼 update_by_id 需要mut參數

### ISSUE THREAD

**Issue by damody** [rbatis/rbatis#84]
https://docs.rs/rbatis/1.8.79/rbatis/rbatis/struct.Rbatis.html#method.update_by_id
可以看到型別是 arg: &'life2 mut T

https://rbatis.github.io/rbatis.io/#/?id=%e6%95%b0%e6%8d%ae%e5%ba%93%e5%88%97%e6%a0%bc%e5%bc%8f%e5%8c%96%e5%ae%8f
但根據您範例使用上看起來好像沒有mut的必要，請問是不是可以把update_by_id的mut拿掉？

**Comment by zhuxiujia** [comment]
因為rbatis的樂觀鎖插件 會嘗試使用樂觀的模式更新記錄，如果更新成功那麼對象的版本號增加1反之則不變 so it use “mut ”

**Comment by damody** [comment]
可能是我的應用場景沒有這個需求所以我會覺得有點奇怪，感覺要靈活還是寫sql再呼叫 exec_prepare來做事。
因為我有時只是要更新幾個值 但我不想把rust struct所有的值都改成 Option。
