### ISSUE TITLE
可否详细加几个自增主键的例子，生产级别的

### ISSUE THREAD

**Issue by JinAirsOs** [rbatis/rbatis#86]
目前biz_activity这个表不是自增主键，比较困惑，如何从model层面，比如从struct层面就指定这个id是自增主键，可否给个例子？

**Comment by zhuxiujia** [comment]
> 目前biz_activity这个表不是自增主键，比较困惑，如何从model层面，比如从struct层面就指定这个id是自增主键，可否给个例子？

表里面id设置自增即可，然后参数的话，id传null

**Comment by JinAirsOs** [comment]
> > 目前biz_activity这个表不是自增主键，比较困惑，如何从model层面，比如从struct层面就指定这个id是自增主键，可否给个例子？
> 
> 表里面id设置自增即可，然后参数的话，id传null

感谢，这个问题我已经解决了。

**Comment by banapy** [comment]
```
#[crud_table(formats_pg:"id:{}::i4")]
pub struct Test {
    id: Option<i8>,
    name: Option<String>,
    uuid:Option<Uuid>,
}
```
设置id自增后，id的类型是什么呢？上面那种方式报错了。
