### ISSUE TITLE
fetch数据的时候空数据返回Error, "json_decode fail"

### ISSUE THREAD

**Issue by mifaly** [rbatis/rbatis#87]
日志记录了好多的error, 其实只是库里面没有符合条件的数据

db > db.adapter.rs > fetch_parperd  返回前调用的json_decode

**Comment by zhuxiujia** [comment]
> 日志记录了好多的error, 其实只是库里面没有符合条件的数据
> 
> db > db.adapter.rs > fetch_parperd 返回前调用的json_decode

新版本error.rs  会区分序列化错误

**Comment by mifaly** [comment]
谢谢，辛苦了 @zhuxiujia
