### ISSUE TITLE
It shows me errors when fetching data from mysql.

### ISSUE THREAD

**Issue by luislozad** [rbatis/rbatis#90]
It works fine when saving or updating but when searching the tables, it shows the following error:

![image](https://user-images.githubusercontent.com/53956308/113258161-31e5f780-9291-11eb-9a85-609dfed4f6e3.png)

I am using actix

**Comment by zhuxiujia** [comment]
> It works fine when saving or updating but when searching the tables, it shows the following error:
> 
> ![image](https://user-images.githubusercontent.com/53956308/113258161-31e5f780-9291-11eb-9a85-609dfed4f6e3.png)
> 
> I am using actix


* can you add this code  on  Cargo.toml,   to see what result return for   Option<Vec<movieapi::Users>>
 ``` 
rbatis = {  features = ["debug_mode"] }
```

**Comment by luislozad** [comment]
Show this:
![image](https://user-images.githubusercontent.com/53956308/113448162-eb8fb600-93c0-11eb-9410-b06c779b7795.png)

**Comment by zhuxiujia** [comment]
> Show this:
> ![image](https://user-images.githubusercontent.com/53956308/113448162-eb8fb600-93c0-11eb-9410-b06c779b7795.png)

Please show me the movieapi::User  struct  define  rust code

**Comment by luislozad** [comment]
This is all the code:

![image](https://user-images.githubusercontent.com/53956308/113491025-5d383480-9493-11eb-8972-857bbed23024.png)

The following error is displayed:

![image](https://user-images.githubusercontent.com/53956308/113491031-6fb26e00-9493-11eb-90db-353d690a6dc4.png)

**Comment by zhuxiujia** [comment]
> This is all the code:
> 
> ![image](https://user-images.githubusercontent.com/53956308/113491025-5d383480-9493-11eb-8972-857bbed23024.png)
> 
> The following error is displayed:
> 
> ![image](https://user-images.githubusercontent.com/53956308/113491031-6fb26e00-9493-11eb-90db-353d690a6dc4.png)


struct NaiveDateTime  
It means date plus time。
so  serde json will be decode fail for  “2021-04-01”

you should replace NaiveDateTime   to  NaiveDate
