### ISSUE TITLE
rbatis.begin_defer(..., false) does not rollback the transaction (PostgreSQL)

### ISSUE THREAD

**Issue by Aries85** [rbatis/rbatis#95]
Hi,

I try to write a test on database and want TxManager to rollback the transaction at the end of the test. 
     
It seems, that rollback does not work.
     
Tried:
- begin_defer()
- begin_tx_defer()
- Rbatis.rollback()

Database is PostgreSQL

Can you please advise?

**Comment by zhuxiujia** [comment]
> Hi,
> 
> I try to write a test on database and want TxManager to rollback the transaction at the end of the test.
> 
> It seems, that rollback does not work.
> 
> Tried:
> 
> * begin_defer()
> * begin_tx_defer()
> * Rbatis.rollback()
> 
> Database is PostgreSQL
> 
> Can you please advise?

The defer rollback function depends on the drop function to be released and can be rolled back as soon as the transaction guard is released. You don't need to call Rbatis. Rollback ()

**Comment by Aries85** [comment]
I tried just with the transaction guard being released, however, it does not rollback. Maybe it is PostgreSQL related.

Code that does not rollback:

```
#[tokio::main]
async fn main() {
    RB.link(...).await.unwrap();

    let tx_guard = RB.begin_tx_defer(false).await.unwrap();

    let customer = Customer {
        name: String::from("Custom Er"),
        contact_email: String::from("customer@127.0.0.1")
    };
    
    let result = database::dao::customer_create(&RB, &tx_guard.tx_id, &customer).await;

    println!("{:?}", result);

}
```

**Comment by zhuxiujia** [comment]
> I tried just with the transaction guard being released, however, it does not rollback. Maybe it is PostgreSQL related.
> 
> Code that does not rollback:
> 
> ```
> #[tokio::main]
> async fn main() {
>     RB.link(...).await.unwrap();
> 
>     let tx_guard = RB.begin_tx_defer(false).await.unwrap();
> 
>     let customer = Customer {
>         name: String::from("Custom Er"),
>         contact_email: String::from("customer@127.0.0.1")
>     };
>     
>     let result = database::dao::customer_create(&RB, &tx_guard.tx_id, &customer).await;
> 
>     println!("{:?}", result);
> 
> }
> ```

you should add this code when block  exit:

```code
drop(tx_guard);
```
or, you can use other function call this for example:
```rust
pub async fn do_tx(){
  RB.link(...).await.unwrap();

    let tx_guard = RB.begin_tx_defer(false).await.unwrap();

    let customer = Customer {
        name: String::from("Custom Er"),
        contact_email: String::from("customer@127.0.0.1")
    };
    
    let result = database::dao::customer_create(&RB, &tx_guard.tx_id, &customer).await;

    println!("{:?}", result);
   //end,tx_guard will be free and call  rollback
}

#[tokio::main]
async fn main() {
  
   do_tx().await;
   
   sleep(Duration::from_sec(2));
}
```

**Comment by Aries85** [comment]
Just tried both solutions - explicit drop and separate function. The record stays in the table.

To ensure my environment is not the cause:
- with every code change, the table is cleaned and first insert passes (as the record stays there) and the following fail on duplicate key constraint, meaning there is still the record from previous run.
- running `cargo clean` before each change

Is there any debug log or code point in Rbatis that could give shed some light on why is the rollback not performed?

**Comment by zhuxiujia** [comment]
> Just tried both solutions - explicit drop and separate function. The record stays in the table.
> 
> To ensure my environment is not the cause:
> 
> * with every code change, the table is cleaned and first insert passes (as the record stays there) and the following fail on duplicate key constraint, meaning there is still the record from previous run.
> * running `cargo clean` before each change
> 
> Is there any debug log or code point in Rbatis that could give shed some light on why is the rollback not performed?

you can use  fast_log::init to see   rollback logs

**Comment by Aries85** [comment]
It seems that transaction rollback is not triggered. 

Log:
```
2021-04-25 11:20:56.424235991 +02:00 INFO rbatis::plugin::log - [rbatis] [tx:6e2742b3-0ff1-4dec-babb-0eef180c5b70] [rbatis] [tx:6e2742b3-0ff1-4dec-babb-0eef180c5b70] Begin
2021-04-25 11:20:56.424489537 +02:00 INFO rbatis::plugin::log - [rbatis] [] Exec  ==> INSERT INTO customers (name, contact_email) VALUES ($1, $2)
                                                                [rbatis] [] Args  ==> ["Custom Er","customer@127.0.0.1"]
2021-04-25 11:20:56.431226530 +02:00 INFO rbatis::plugin::log - [rbatis] [] RowsAffected <== 1

```
Code:
```
lazy_static! {
   static ref RB:Rbatis=Rbatis::new();
}

#[tokio::main]
async fn main() {
    fast_log::init_log("requests.log", 10000, log::Level::Debug, None, true);

    RB.link("...").await.unwrap();

    let tx_guard = RB.begin_tx_defer(false).await.unwrap();

    let customer = Customer {
        name: String::from("Custom Er"),
        contact_email: String::from("customer@127.0.0.1")
    };

    let result = database::dao::customer_create(&RB, &tx_guard.tx_id, &customer).await;
    println!("{:?}", result);

    drop(tx_guard);

}
```

Tried debugging it a bit.

In `tx.rs`, the `drop()` is called, and it goes through line 301 `manager.rollback(...)`, then it goes to `pub async fn rollback(&self, context_id: &str) -> Result<String, crate::core::Error>` and then I am a bit confused.

It goes to line 226 `if tx_op.is_none()`, goes to line 232 `let (tx, state): (DBTx, TxState) = tx_op.unwrap();` and then seems to end.

Not sure what is happening. Would you have an idea?

**Comment by zhuxiujia** [comment]
> It seems that transaction rollback is not triggered.
> 
> Log:
> 
> ```
> 2021-04-25 11:20:56.424235991 +02:00 INFO rbatis::plugin::log - [rbatis] [tx:6e2742b3-0ff1-4dec-babb-0eef180c5b70] [rbatis] [tx:6e2742b3-0ff1-4dec-babb-0eef180c5b70] Begin
> 2021-04-25 11:20:56.424489537 +02:00 INFO rbatis::plugin::log - [rbatis] [] Exec  ==> INSERT INTO customers (name, contact_email) VALUES ($1, $2)
>                                                                 [rbatis] [] Args  ==> ["Custom Er","customer@127.0.0.1"]
> 2021-04-25 11:20:56.431226530 +02:00 INFO rbatis::plugin::log - [rbatis] [] RowsAffected <== 1
> ```
> 
> Code:
> 
> ```
> lazy_static! {
>    static ref RB:Rbatis=Rbatis::new();
> }
> 
> #[tokio::main]
> async fn main() {
>     fast_log::init_log("requests.log", 10000, log::Level::Debug, None, true);
> 
>     RB.link("...").await.unwrap();
> 
>     let tx_guard = RB.begin_tx_defer(false).await.unwrap();
> 
>     let customer = Customer {
>         name: String::from("Custom Er"),
>         contact_email: String::from("customer@127.0.0.1")
>     };
> 
>     let result = database::dao::customer_create(&RB, &tx_guard.tx_id, &customer).await;
>     println!("{:?}", result);
> 
>     drop(tx_guard);
> 
> }
> ```
> 
> Tried debugging it a bit.
> 
> In `tx.rs`, the `drop()` is called, and it goes through line 301 `manager.rollback(...)`, then it goes to `pub async fn rollback(&self, context_id: &str) -> Result<String, crate::core::Error>` and then I am a bit confused.
> 
> It goes to line 226 `if tx_op.is_none()`, goes to line 232 `let (tx, state): (DBTx, TxState) = tx_op.unwrap();` and then seems to end.
> 
> Not sure what is happening. Would you have an idea?

Maybe the rollback failed

**Comment by Aries85** [comment]
Would you please have any suggestion on how to debug it, or where to add some log messages?

**Comment by zhuxiujia** [comment]
> Would you please have any suggestion on how to debug it, or where to add some log messages?

try this code to see what error when rollback
```rust
lazy_static! {
   static ref RB:Rbatis=Rbatis::new();
}

#[tokio::main]
async fn main() {
    fast_log::init_log("requests.log", 10000, log::Level::Debug, None, true);

    RB.link("...").await.unwrap();

    let tx_id = rb.begin_tx().await.unwrap();

    let customer = Customer {
        name: String::from("Custom Er"),
        contact_email: String::from("customer@127.0.0.1")
    };

    let result = database::dao::customer_create(&RB, &tx_id , &customer).await;
    println!("{:?}", result);

    RB.rollback(context_id).await.unwrap();

   sleep(Duration::from_sec(3));

}
```

**Comment by Aries85** [comment]
Thank you for the code. This time, the log contains line for rollback, but the data still stays in the table.

Log:
```
2021-04-25 17:37:33.775512349 +02:00 INFO rbatis::plugin::log - [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] Begin
2021-04-25 17:37:33.775744746 +02:00 INFO rbatis::plugin::log - [rbatis] [] Exec  ==> INSERT INTO customers (name, contact_email) VALUES ($1, $2)
                                                                [rbatis] [] Args  ==> ["Custom Er","customer@127.0.0.1"]
2021-04-25 17:37:33.793887043 +02:00 INFO rbatis::plugin::log - [rbatis] [] RowsAffected <== 1
2021-04-25 17:37:33.794358548 +02:00 INFO rbatis::plugin::log - [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] Rollback
```

I have created single-file example:

```
#[macro_use]
extern crate lazy_static;

#[macro_use]
extern crate rbatis;

use rbatis::core::db::DBExecResult;
use rbatis::Error as RbatisError;
use rbatis::rbatis::Rbatis;
use serde::{Deserialize, Serialize};
use tokio::time::sleep;

lazy_static! {
   static ref RB:Rbatis=Rbatis::new();
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Customer {
    pub name: String,
    pub contact_email: String
}

#[tokio::main]
async fn main() {
    fast_log::init_log("requests.log", 10000, log::Level::Debug, None, true);

    // https://docs.rs/postgres/0.15.2/postgres/struct.Connection.html
    RB.link("...").await.unwrap();


    let tx_id = RB.begin_tx().await.unwrap();

    let customer = Customer {
        name: String::from("Custom Er"),
        contact_email: String::from("customer@127.0.0.1")
    };

    let result = customer_create(&RB, &tx_id, &customer).await;

    println!("{:?}", result);

    RB.rollback(&tx_id).await.unwrap();

    sleep(tokio::time::Duration::from_secs(3));

}

#[py_sql(rbatis, "INSERT INTO customers (name, contact_email) VALUES (#{dto.name}, #{dto.contact_email})")]
pub async fn customer_create(rbatis: &Rbatis, transaction_id: &String, dto: &Customer) -> Result<DBExecResult, RbatisError> {}
```

Example Cargo.toml:
```
[package]
name = "rbatis-test"
version = "0.1.0"
authors = ["whoever"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
tokio = { version = "1", features = ["full"] }

# json (required)
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Date time (required)
chrono = { version = "0.4.19", features = ["serde"]}

# logging lib(required)
log = "0.4"
fast_log="1.3"

# BigDecimal lib(optional)
bigdecimal = "0.2"

# rbatis lib(required)
rbatis =  { version = "1.8" }

[dev-dependencies]
pretty_assertions = "0.7.2"
```

Table SQL for PostgreSQL:
```
CREATE TABLE customers
(
    id            serial unique primary key,
    name          text not null,
    contact_email text unique not null
);
```

**Comment by zhuxiujia** [comment]
>  &

I see that the transaction IDs printed in the log are inconsistent and the middle two are empty. This indicates that the execution is not in the same transaction number
```rust
2021-04-25 17:37:33.775512349 +02:00 INFO rbatis::plugin::log - [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] Begin
2021-04-25 17:37:33.775744746 +02:00 INFO rbatis::plugin::log - [rbatis] [] Exec  ==> INSERT INTO customers (name, contact_email) VALUES ($1, $2)
                                                                [rbatis] [] Args  ==> ["Custom Er","customer@127.0.0.1"]
2021-04-25 17:37:33.793887043 +02:00 INFO rbatis::plugin::log - [rbatis] [] RowsAffected <== 1
2021-04-25 17:37:33.794358548 +02:00 INFO rbatis::plugin::log - [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] [rbatis] [tx:c4adbbaa-b108-4969-8868-4e43c1e817fd] Rollback
```

**Comment by Aries85** [comment]
That was it, thank you! :) Now it works like a charm.

Parameter name must match the name expected by `py_sql` macro. 

Is there a list of variable names that `py_sql` accepts along witth their meanings, please?

For future readers with similar problem, here is working code:

```
#[macro_use]
extern crate lazy_static;

#[macro_use]
extern crate rbatis;

use rbatis::core::db::DBExecResult;
use rbatis::Error as RbatisError;
use rbatis::rbatis::Rbatis;
use serde::{Deserialize, Serialize};
use tokio::time::sleep;

lazy_static! {
   static ref RB:Rbatis=Rbatis::new();
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Customer {
    pub name: String,
    pub contact_email: String
}

#[tokio::main]
async fn main() {
    fast_log::init_log("requests.log", 10000, log::Level::Debug, None, true);

    // https://docs.rs/postgres/0.15.2/postgres/struct.Connection.html
    RB.link("...").await.unwrap();


    let tx_id = RB.begin_tx().await.unwrap();

    let customer = Customer {
        name: String::from("Custom Er"),
        contact_email: String::from("customer@127.0.0.1")
    };

    let result = customer_create(&RB, &tx_id, &customer).await;

    println!("{:?}", result);
}

#[py_sql(rbatis, "INSERT INTO customers (name, contact_email) VALUES (#{dto.name}, #{dto.contact_email})")]
pub async fn customer_create(rbatis: &Rbatis, tx_id: &String, dto: &Customer) -> Result<DBExecResult, RbatisError> {}
```

**Comment by zhuxiujia** [comment]
> That was it, thank you! :) Now it works like a charm.
> 
> Parameter name must match the name expected by `py_sql` macro.
> 
> Is there a list of variable names that `py_sql` accepts along witth their meanings, please?
> 
> For future readers with similar problem, here is working code:
> 
> ```
> #[macro_use]
> extern crate lazy_static;
> 
> #[macro_use]
> extern crate rbatis;
> 
> use rbatis::core::db::DBExecResult;
> use rbatis::Error as RbatisError;
> use rbatis::rbatis::Rbatis;
> use serde::{Deserialize, Serialize};
> use tokio::time::sleep;
> 
> lazy_static! {
>    static ref RB:Rbatis=Rbatis::new();
> }
> 
> #[derive(Debug, Deserialize, Serialize)]
> pub struct Customer {
>     pub name: String,
>     pub contact_email: String
> }
> 
> #[tokio::main]
> async fn main() {
>     fast_log::init_log("requests.log", 10000, log::Level::Debug, None, true);
> 
>     // https://docs.rs/postgres/0.15.2/postgres/struct.Connection.html
>     RB.link("...").await.unwrap();
> 
> 
>     let tx_id = RB.begin_tx().await.unwrap();
> 
>     let customer = Customer {
>         name: String::from("Custom Er"),
>         contact_email: String::from("customer@127.0.0.1")
>     };
> 
>     let result = customer_create(&RB, &tx_id, &customer).await;
> 
>     println!("{:?}", result);
> }
> 
> #[py_sql(rbatis, "INSERT INTO customers (name, contact_email) VALUES (#{dto.name}, #{dto.contact_email})")]
> pub async fn customer_create(rbatis: &Rbatis, tx_id: &String, dto: &Customer) -> Result<DBExecResult, RbatisError> {}
> ```

context_id, ctx_id , tx_id It will be correctly recognized by the procedure macro,
you can find  doc  in   our website   of   https://rbatis.github.io/rbatis.io/#/en/?id=mapper-macro
