### ISSUE TITLE
error returned from database: column xxx  is of type bigint but expression is of type text

### ISSUE THREAD

**Issue by xiaojin111** [rbatis/rbatis#97]
当使用None来对数值类型赋值后，插入会出错

**Comment by zhuxiujia** [comment]
> 当使用None来对数值类型赋值后，插入会出错

表字段是否是 支持null呢？

**Comment by xiaojin111** [comment]
> > 当使用None来对数值类型赋值后，插入会出错
> 
> 表字段是否是 支持null呢？

支持

**Comment by zhuxiujia** [comment]
> > > 当使用None来对数值类型赋值后，插入会出错
> > 
> > 
> > 表字段是否是 支持null呢？
> 
> 支持

使用cargo update 更新到最新版本再尝试
