### ISSUE TITLE
请问如何动态修改table name

### ISSUE THREAD

**Issue by ZCKun** [rbatis/rbatis#98]
看了文档没有找到相关内容
谢谢

**Comment by zhuxiujia** [comment]
> 看了文档没有找到相关内容
> 谢谢

可以使用Wrapper的format 功能动态修改表名称

**Comment by simon-fu** [comment]
这样写编译不通过，请教怎么写才能通过呢

    let mut w = rb.new_wrapper();
    let table_name = "table_001";
    let f = |s: &str| table_name.to_string();
    w.formats.insert("table_name".to_string(), f);
