### ISSUE TITLE
#[serde(rename_all="camelCase")]会影响查询结果，该怎么解决？

### ISSUE THREAD

**Issue by node1mei** [rbatis/rbatis#99]
如果一个结构体声明如下：
```
#[crud_enable]
#[derive(Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct SysRole {
    pub id: Option<String>,
    pub name: Option<String>,
    //父id(可空)
    pub parent_id: Option<String>
}
```
同时，数据表中字段为 `parent_id`, 那么查询结果中的 parent_id 为 `None`。如果希望最终输出的 JSON 格式是 camelCase 的，除了再声明一个结构体做转换，请问还有简洁的其他方法吗？

**Comment by zhuxiujia** [comment]
> camelCase

理论上按照DDD分层设计的话，
 #[serde(rename_all = "camelCase")] 应该放在你项目结构里的VO层（展示给前端的数据）结构体头上。
而不是放在数据库模型层上。

然后实现From接口，就可以方便的从 Table 转换到VO 结构体

**Comment by node1mei** [comment]
感谢解答。我理解你的意思。我就是想偷个懒么。

**Comment by zemelLeong** [comment]
可以优化嘛？

**Comment by liniu** [comment]
是否可以优化一下，有时候用确实只是想查个表输出camelCase 格式的json
